### ISSUE TITLE
facing fails while executing a script

### ISSUE THREAD

**Issue by baloan** [KSP-KOS/KOS#1002]
While regression testing my mission toolkit mission to Minmus I encountered this issue:

![facing not found](https://cloud.githubusercontent.com/assets/651799/7594268/bf186824-f8df-11e4-9522-f25f82273c83.PNG)

Original code available at http://ksp.baldev.de/kos/mtkv3/
(won't run because of a) a breaking change in checkvessel.ks and b) renaming to .ks files)

**Comment by ZiwKerman** [comment]
it's not `facing:pitch` but `np:pitch` that is a problem
because `np` is a vector, it does not have a `pitch` suffix if I remember correctly
if you change a previous lines to this it should work:
```
    set np to lookdirup(nd:deltav, ship:facing:topvector). //points to node, keeping roll the same.
    lock steering to np.

    //np is now a Directrion as is facing
    wait until abs(np:pitch - facing:pitch) < 0.15 and abs(np:yaw - facing:yaw) < 0.15.
```

**Comment by ZiwKerman** [comment]
BTW your code helped me a lot when I first started learning kOS, so kudos to you

**Comment by baloan** [comment]
Thanks. Found the solution:
```
set npd to np:direction.
wait until abs(npd:pitch - facing:pitch) < 0.1 and abs(npd:yaw - facing:yaw) < 0.1.
```
Issue may be closed.

**Comment by erendrake** [comment]
@baloan welcome back :) im glad you were able to resolve this issue. if you would like to be more involved in our development discussion and/or the new kslib project. send me an email @ erendrake@gmail.com

**Comment by Dunbaratu** [comment]
> set npd to np:direction.
> wait until abs(npd:pitch - facing:pitch) < 0.1 and abs(npd:yaw - facing:yaw) < 0.1.

You may want to look into the VANG function.  It looks like you're trying to wait until the ship's facing vector is lined up with a desired target vector.  VANG(v1,v2) returns the angle between two vectors.  Using it would allow you to work entirely in the world of vectors only, and let you known when your steering alignment is close.
