### ISSUE TITLE
"Signal lost" when using RT but the vessel is manned.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#1005]
When using kOS with RemoteTech, If the vessel has an astronaut (*) in it, then you shouldn't need an antenna connection to use the kOS terminal, but the way the check is incorrectly implemented now, you do.

The check always incorrectly presumes it's ground control at KSC that has to issue all autopilot commands.

() - by 'astronaut' I mean a kerbal capable of taking the controls.  Tourists don't count as they are disallowed from touching anything in the cockpit.

**Comment by Dunbaratu** [comment]
Is there some sort of generic RT command you can issue to answer the question "are the pilot controls disabled right now?"  Whatever the decision RT is using to allow WASDQE to work without radio delays, we just should use that to also decide if typing commands on the console is allowed.

**Comment by hvacengi** [comment]
I think that RT just added an API method to identify if there is an astronaut available for local control.  I'll take a look and see what options it gives.

The radio delay may be a debatable item.  I think there are 3 schools of thought: 
1. all commands require delay to come from ksc
2. all commands require delay to come from a command center
3. all commands require delay as outlined above, unless a kerbal has local control (possibly limiting it to an engineer)

I personally like the idea of using command centers, but it's not a huge preference.  I could go either way with local control.

**Comment by Andrew-Dunn** [comment]
I think the radio delay should be the shortest possible. If there is a kerbonaut on board, then there should be no delay, otherwise it should use the delay to the nearest command centre or KSC.

It could be interesting if only engineers of a certain level could directly manipulate a kOS system. At the moment engineers are kinda useless.
