### ISSUE TITLE
Update EC usage to be based on actual processing

### ISSUE THREAD

**Issue by hvacengi** [KSP-KOS/KOS#1009]
Now that EC usage is updated using fixed update, it would be nice to also adjust consumption based on actual instructions per update.  Currently consumption is based only the required power of the current volume.  It would be nice to have a hybrid model:
`[Required power] = [volume power per seconds] * [time delta] + [part power per instruction] * [number of instructions]`

Care will be needed with all aspects of balancing the consumption.  We should make sure specifically to balance the volume's requirement against the large time delta's that come with high rates of timewarp (maybe even a timewarp reduction factor) to prevent consumption from ballooning to unreasonable levels.

In the case of Archive access, it currently has a large power draw to account for the need to communicate with Kerbin.  If RemoteTech is installed (which enforces power requirements for antennae) should we reduce or eliminate this penalty?

**Comment by ZiwKerman** [comment]
@Dunbaratu also suggested standby mode, we should try to implement it as well (mode with 1-2 IPU and minimal volume upkeep). Also I like the RT idea, we don't need to penalise more than necessary.

**Comment by hvacengi** [comment]
Hm, an explicit standby mode may be a good thing.  I was going to say that `wait 0.` would result in zero instructions, but that's not true since triggers are executed before and regardless of `wait` (and I think should remain that way, so that if you are waiting for an expensive calculation to be greater than a threshold, that still consumes charge).  If standby gets implemented, it could be explicitly forced for the potential `warpto` command we were discussing on slack.

**Comment by Dunbaratu** [comment]
I agree that it should draw power using micro payments of electric charge per instruction executed.  This idea was being thrown around before, but we had to wait for the move to fixedupdate first or else the out-of-game computer speed would affect the in-game drain.  Now that it's moved to fixedupdate, it's ready to implement it.

When setting the micropayment rate, keep in mind that we ship with a default of 200 IPU, and with default Unity settings, the rate maxes at 25 FixedUpdates per second.  (it can end up being slower than that when the computer is lagging, but not faster than that.  "Fixed" is a misnomer. It's actually more accurate to call it a CappedUpdate.  It's guaranteed not to go FASTER than expected, but t can very easily go SLOWER than expected.  Therefore any solution still needs to pay attention to the actual amount of game universe time passed.

**Comment by Wercho** [comment]
Just a suggestion: If you're going to rework the power drain, it might be nice to make the values configurable in the part module. That way people could tailor things to their liking. It would also allow for working with RT using a MM patch to change the power draw, rather than needing to hardcode something really balanced.
