### ISSUE TITLE
Add a way to get module events as real strings.

### ISSUE THREAD

**Issue by akrasuski1** [KSP-KOS/KOS#1018]
I wanted to make a script that will open a RemoteTech's antenna target selection menu. Unfortunately, the module's action (or event) is changing names from time to time - initially being "no target", but ultimately it could be any vessel or body in the game, so I can't just hardcode the event's name like this: `antenna_module:doevent("no target").` I noticed there is a method in kOS called `:allevents`. However, when applied to this module, it gives the list of things similar to this: `(callable) no target, is KSPEvent`. I doubt such a string is ever useful for kOS developer. I would much prefer if it just returned `no target`, since this way I could do `antenna_module:doevent(antenna_module:allevents[0]).` or whichever index it turns out to be.

**Comment by erendrake** [comment]
@akrasuski1 we recently added 3 new suffixes to module fields

https://github.com/KSP-KOS/KOS/commit/da193705a7506533e96bd5df10eb346a70d7be6a

it will be in the next release

**Comment by akrasuski1** [comment]
oh, ok. I guess you can close the issue then.
