### ISSUE TITLE
Trimming of RCS steering.

### ISSUE THREAD

**Issue by akrasuski1** [KSP-KOS/KOS#1023]
When I try to steer my rocket using RCS controls via kOS, it seems that values below 0.01 are treated as zero. `lock throttle to 0.0001.` seems to work though. Is there a reason for RCS controls not having such delicate control? I wanted to fine tune satelite's period using rcs, but it seems I'll have to revert to, weirdly, more precise main engine.

**Comment by evg-zhabotinsky** [comment]
Didn't look at related kOS code, but I guess it's KSP's problem.

A side note about precision in KSP:

If your spaceship's center of mass differs from some abstract "ship center" (not sure what it exactly is, most likely root part center), *even rotating your ship* (with RCS off) will cause your orbit to fluctuate, usually just a bit, but *quite a lot* on bodies like Gilly or even Mun, if your ship is eccentric enough.

Scott Manley even did a video where he changed his orbit quite a lot by just transferring fuel back and forth (to move center of mass relative to ship's center) and rotating.

**Comment by abenkovskii** [comment]
@evg-zhabotinsky The behaviour @akrasuski1 is talking about isn't a KSP problem. https://github.com/KSP-KOS/KOS/blob/5dc267866fba0876f269cfab2f322996764708eb/src/kOS/Suffixed/FlightControl.cs#L367

**Comment by evg-zhabotinsky** [comment]
Well then...

If user specifies RCS (or other) controls as some complex formula, could (s)he actually mean that (s)he really wants them disabled (being exactly zero)? (I don't mean things like `max(value, 0)` here.)

If not, then checking if controls are **exactly** zero is fine.
You get exactly zero for things like `max(v, z)`, `z * v`, `z / v`, `v - v` and maybe others if `z` is exactly zero.

P.S. I hope the parser is not fancy enough to interpret "0" or "0.0" as some really small value but not exactly zero, or to generate slightly different numbers for the same input string?

**Comment by Dunbaratu** [comment]
Maybe @erendrake can weigh in on why the SETTING_EPSILON is in the code.  I don't know what the original motivation for having it was - maybe he saw a need for some sort of deadzone because something wasn't working right without one?

**Comment by erendrake** [comment]
@Dunbaratu caught me in the middle of responding. this deadzone is there to avoid very small floating point values from locking the steering. i was concerned that people setting throttle based on the result of any complicated equation that they expected to be 0 would have trouble unless they rounded. 

the value for SETTING_EPILSON is easy enough to change. It also doesnt have to be monolithic if we want to have different deadzones for rotation and translation. It was my first best guess :)

**Comment by evg-zhabotinsky** [comment]
Well, as I said, **exactly zero** floating point value exists (at least on x86) and propagates in meaningful ways. So, I think, testing for exact equivalence to zero (instead of this margin) should be fine in this case.

**Comment by Dunbaratu** [comment]
In most cases, floating point exact equality checks to zero work okay, unless you start using some trig functions along the way.  Then you can end up with values that SHOULD be 0.00000000 ending up as 0.0000000001.

But I don't know how I think about this.  On the one hand I don't think you need that sort of deadzone rounding to zero, because people using that kind of trig should know the dangers and do their own deadzoning in user code.  On the other hand,I I think it's probably pretty unrealistic to be able to power a thruster at only 0.01 of its magnitude.  It sort of makes sense to say that in any mechanical process like that you won't be able to get that level of precision.

**Comment by erendrake** [comment]
0.01 is a very aggressive value for this and it should have been much smaller to start. I still believe that it will solve more issues then it causes to have some kind of deadzone.  something like `0.00001`?

**Comment by hvacengi** [comment]
Dead bands are important, especially when dealing with floating point precision.  While zero values do exist, near-zero values do as well, and you could make the case that below a certain point it might as well be zero.  I think this is more important in attitude and translation control than it is with the throttle. Minute changes in orbital parameters may affect what you calculate in relative velocity in a way that causes oscillation.  1% seems like a fairly small increment when we think about it in the real world, but in this kind of code, it restricts the available settings to 101 distinct options.  

I think the those of us building the develop branch should toy with a few values and see what behaves well, maybe start with options of 0.01, 0.0001, and 0.00001.  I'm staring at my Kerbal Engineer readout, and it looks like the semimajor axis is fluctuating by about 1m in 819,972ish, or a little more than 0.000001ish of the overall value.

**Comment by evg-zhabotinsky** [comment]
Well, I agree that extreme precision is quite unrealistic. (And of no use in KSP, with its wobbly orbits etc. :)

But from purely technical point of view, well, If you **mean** zero, you get it. It is extremely unlikely that you mean "turn thrusters off" when you set thrust to some fancy formula that results in near-zero values.

I think it is reasonable there to treat exactly zero as a special value (e.g. like NAN) that means "turn it off".

And anyway, you have CONTROL:NEUTRALIZE to let go of controls!

**Comment by akrasuski1** [comment]
> Real rocket engines hardly ever run below ~80% throttle. They just can't.

I am not experienced in real rockets, but I am talking about RCS thrusters - they surely can allow for precise maneuvering? Or how are ultra-precise satellites positioned otherwise?

Either way, real-life stations need regular thrusts to keep their orbits stable - this is not so funny in KSP, so I would prefer to just make the orbit as precise as possible from the beginning - hence the precision needed.

> something like 0.00001

Yeah, that should be good - as hvacengi experimented, the orbit itself fluctutates at around this value (relatively).

> of no use in KSP, with its wobbly orbits

Disagreed. Orbits are somewhat wobbly, but not nearly as wobbly to make them be the limiting factor - right now the thrust precision is.

**Comment by evg-zhabotinsky** [comment]
So what about CONTROL:NEUTRALIZE?
I re-read the docs and they state (as I understand) that you actually can't just set **one** of controls and leave all others free: you lock all the controls at once and can only free them all with NEUTRALIZE.

And for what on earth would you need to leave just some of controls on manual? And anyway, you can just pass them through in loop if you really need.

Said that, this margin checking looks meaningless to me at the moment and contradicts the documentation.

**Comment by yump** [comment]
I think it would be quite feasible to make a monopropellant RCS thruster that could dial down well below 1/100 of full thrust, if you used a "coarse" valve bypassed with a "fine" valve.

As for rotation with reaction wheels, neglecting KSP's anti-saturation magic, the ability to exert very tiny torques depends on the ability to very accurately ramp up or down the rotation speed of the reaction wheels, which depends on the accuracy of your timebase, which can be [really really good](https://en.wikipedia.org/wiki/Crystal_oven#Comparison_with_other_frequency_standards), even with 1960s technology.

**Comment by akrasuski1** [comment]
> BTW, as code and testing tell me, you can't set engine throttle below 0.01 too. (With raw controls, that is.)

Well, but `lock throttle to 0.00001.` works ;)

**Comment by evg-zhabotinsky** [comment]
For whatever reason, I think my was comment was missed.

Should we be able to control anything manually before NEUTRALIZE after we have used some raw controls?
[Documentation](http://ksp-kos.github.io/KOS_DOC/commands/flight/raw.html) says NO, as I understand it. Even comments in the example make me think so.
*If so, these margin checks are not needed at all.*

`LOCK STEERING TO X.` and `LOCK THROTTLE TO X.` can be treated specially, if removing margins will interfere with them.

**Comment by erendrake** [comment]
@evg-zhabotinsky i say yes, i can think of plenty of reasons I would want kOS to only lock the specific axis that i told it to so. 

As an example of something useful i have seen done that uses this is a docking script that lets kOS control rotation while the user controls translation. 

That being said we dont currently let a script lock the control at `0`. Which might need to be addressed in an enhancement ticket.

**Comment by yump** [comment]
In that case, wouldn't it make sense for the script to copy whichever axes it wasn't using from PILOTROTATION?   That seems better than having a magic range of values near zero that mean to use pilot input instead.

**Comment by evg-zhabotinsky** [comment]
You mean explicitly passing through controls you need by manually copying them in loop?
Sounds interesting. In fact, I have suggested it somewhere above, but then forgot about it.
