### ISSUE TITLE
Add object suffix for orbits.

### ISSUE THREAD

**Issue by akrasuski1** [KSP-KOS/KOS#1024]
I wanted to make a a function taking orbit as a parameter. All went well, until I wanted to know the velocity at particular time. The only way that I am aware of and does not take excessive amount of code, is to use `velocityat` - however this function requires `vessel` argument. Since I do not pass vessel as parameter to my function, I cannot do this.

The solution is to either add `:object` suffix to orbits, which would return the orbiter, or, to solve this particular issue, allow `velocityat` and `positionat` to get orbit arguments.

**Comment by Dunbaratu** [comment]
The following statement:
> however this function requires vessel argument
is false.

You can use *either* a vessel or a body as the argument to velocityat.  At least that's how it's meant to be.  Are you getting some error when trying to pass a Body in to it?

The reason it's not implemented on raw orbit objects is that it's trying to make use of the maneuver nodes, if any are present, in it's prediction.   If it's given a Vessel's orbit object, there's no path from that handle to the vessel to determine if said vessel has a maneuver node in its future.   It cannot detect whether that vessel has a maneuver node on it, and therefore whether the prediction from just looking at the raw orbit alone is going to be false or not.

But if you pass in a Body handle, then it knows there's no way for a body to have a maneuver node, and therefore using the body's raw orbit is a safe assumption to make.

**Comment by akrasuski1** [comment]
> Are you getting some error when trying to pass a Body in to it?

No, I meant to say `orbitable`.

Hmm, but there already is `velocity` suffix for orbits, that returns "current" velocity of orbitting object - *even if it isn't on this orbit yet*. I haven't checked exact behaviour (what is returned - the simulated velocity as though the object was already on that orbit, or actual velocity, even though it is on some other unrelated orbit - I'd assume the first case though), but either way, adding `velocityat` suffix for orbits shouldn't be much worse than that.

I'm now in the process of creating orbital maneuvers library, and it seems weird to pass orbits as arguments to almost every function from this library, except for one, which requires actual `orbitable` parameter.

**Comment by Dunbaratu** [comment]
The reason `velocityat` is on the object and not the orbit is that it's trying to take into account future transitions from encounters or manuever nodes, which the `orbit` object doesn't mention.
