### ISSUE TITLE
Boot files don't work with CONFIG:ARCH

### ISSUE THREAD

**Issue by akrasuski1** [KSP-KOS/KOS#1046]
I play with CONFIG:ARCH set to true at all times. Now I tried to use boot files for the first time, and they don't work for me. As @abenkovskii explained, it is the connection of those two things (boot and CONFIG:ARCH) that cause the issue. <sup><sub>connected issue: erendrake is grumpy :)</sub></sup>

**Comment by hvacengi** [comment]
I'm implementing a fix for this, but wanted to check on something before I PR: traditionally the boot file has been renamed to "boot" on the local disk.  Should we enable support for using the original file name?  It would also open the door to programs being able to set the boot file name, and to future conditional files.  For my purposes, it would clean up the code which currently tests for "boot" on local drives, but reads the bootFile property on the processor when on the archive.
