### ISSUE TITLE
Oops. I forgot to edit one more place when fixing #724

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#1047]
The log command throws an exception but still appends the text to the file:
![screenshot16](https://cloud.githubusercontent.com/assets/11031560/7786997/4b3c7d8a-01fb-11e5-86e3-a7a5830a7852.png)

**Comment by Dunbaratu** [comment]
Again, looking at that screenshot.. how on earth did you get config:audioerr to exist, even though the toggle button for "keyclick" is missing from the terminal window?  Those two things were in the SAME commit.

This change: https://github.com/KSP-KOS/KOS/commit/bdb8fd23f092fffead0e3885a94b4c633f12cc66#diff-cb0bca569b756a5344a5f8e7645fba6aR50

And this change: https://github.com/KSP-KOS/KOS/commit/bdb8fd23f092fffead0e3885a94b4c633f12cc66#diff-3442303abd77e1a399ebcd0ffdff8f1eR597

Are both part of this commit: https://github.com/KSP-KOS/KOS/commit/bdb8fd23f092fffead0e3885a94b4c633f12cc66

**Comment by abenkovskii** [comment]
@Dunbaratu no idea. I just compiled the latest develop version.

**Comment by Dunbaratu** [comment]
Something is wrong with how my commit got merged.  The commit is marked as merged, but the line that the commit claims is present is missing from the current develop.

**Comment by Dunbaratu** [comment]
ancient issue fixed ages ago.
