### ISSUE TITLE
unlock throttle inside trigger does not work

### ISSUE THREAD

**Issue by eozkucur** [KSP-KOS/KOS#1048]
I am using version 0.17.2

The statement "unlock throttle" does not release controls when called inside a when or until block. The following code works as expected.

```
print "Start...".
set thrott to 0.3.
wait 10.
print "taking control.".
lock throttle to thrott.
wait 10.
print "releasing control.".
unlock throttle.
// Pilot controls are enabled.
wait 10.
print "Finish...".
```

However the following equivalent  code does not work as expected.

```
print "Start...".
set finished to false.
set thrott TO 0.3.
set start_time to time:seconds.
when (time:seconds - start_time)>10 then {
    print "taking control.".
    lock throttle to thrott.
    when (time:seconds - start_time)>20 then {
        print "releasing control.".
        unlock throttle.
        // Pilot controls are NOT enabled.
        when (time:seconds - start_time)>30 then {
            set finished to true.
        }
    }
}
wait until finished.
print "Finish...".
```

**Comment by Dunbaratu** [comment]
I've narrowed it down that all it requires is a brace section of *any* kind.  It doesn't have to be a trigger.  This is the simplest case that demonstrates the problem:

This works correctly:
```
lock throttle to 1.0.
wait 2.
unlock throttle.
```
But change it to this, and the unlock does not unlock the throttle:
```
lock throttle to 1.0.
wait 2.
{
  unlock throttle.
}
```
It doesn't matter what the braces are for - as long as there are braces of some sort, for any reason, the problem happens.
