### ISSUE TITLE
Can't unlock throttle inside until

### ISSUE THREAD

**Issue by kendoka15** [KSP-KOS/KOS#1051]
I've tried many ways and I can't ever seem to unlock the throttle from an until.

(Test code: http://pastebin.com/Z5ZfD5x3 )

**Comment by space-is-hard** [comment]
May be related to #1048

**Comment by Dunbaratu** [comment]
Duplicate of #1048 - since it occurs with *any* ``unlock throttle`` that occurs inside a brace section.
