### ISSUE TITLE
KSPAPIExtensions needs update for 1.0.2

### ISSUE THREAD

**Issue by valuial** [KSP-KOS/KOS#1055]
The current KSPAPIExtensions is outdated and causes conflicts with SmartParts, that uses the new dll (as far as I can tell). Replacing the dll in kOS solves the confilict for me.

**Comment by hvacengi** [comment]
We are working on releasing an update that include the most recent version of KSPAIPExtensions (waiting on a couple of other features/fixes to go along with it), so this will be fixed once that comes out.  

Oddly though, Swamp_IG says in his documentation that he went out of his way to prevent old dlls from conflicting with the newer ones.  In fact, that's the very reason he recommends including the dll with every mod.  I wonder if something has changed internal to the api extensions.  What kind of conflicts were you getting?

**Comment by valuial** [comment]
Parts of the right-click-menu of SmartParts were missing.
I've just seen the info in NetKan that KSPAPIExtensions will no longer be handled by ckan but should be supplied by each mod as Swamp_IG intended.

Here is what I get with kOS and SmartParts installed:
![snapshot1](https://cloud.githubusercontent.com/assets/12469889/7961681/55b64eba-0a09-11e5-9ca2-05cb3355cdcb.png)
![snapshot2](https://cloud.githubusercontent.com/assets/12469889/7961683/55b776d2-0a09-11e5-8a53-8a0396bf802f.png)




The menu should look like this (removed kOS):
![snapshot3](https://cloud.githubusercontent.com/assets/12469889/7961684/55bb1aa8-0a09-11e5-9307-fcfe33f79eee.png)

**Comment by valuial** [comment]
Seems to be the same incompatibility issue as with Issue #983 
Closing this as a dupe.

**Comment by hvacengi** [comment]
Still seems odd that it doesn't work, but thank you for the report.  Hopefully we can get the last few things wrapped up and release an update so this isn't a continued issue.
