### ISSUE TITLE
Bug in part:resources list

### ISSUE THREAD

**Issue by mrlyceist** [KSP-KOS/KOS#1062]
List of resources contained in part is formed without closing parenthesis.
It prevents access to suffixes of `:RESOURCES` of such part.
kOS  v.0.17.2, KSP v.1.0.2-Win32.

**Comment by hvacengi** [comment]
Could you be a little more specific and possibly show your code?  I use these suffixes in my transfer fuel script, but they are created from the `:RESOURCES` suffix on `ELEMENT` instead.  The two are not quite the same implementation, so there could be a bug between the two.

**Comment by mrlyceist** [comment]
Unfortunately, it's not about my code. Basicly, I was messing with syntax, trying to write a universal staging logick when I found it.
The thing is the other structures that have a `:RESOURCES` suffix, such as `STAGE` or `ELEMENT` are working fine. Example is on the screenshot. Installation: Vanilla+kOS.
![ksp-screenshot-92](https://cloud.githubusercontent.com/assets/12787278/8039319/537cbb6c-0e22-11e5-80b0-d77f1d58b6b5.png)

**Comment by mrlyceist** [comment]
Sorry for closing issue - I missed the button :-)

**Comment by hvacengi** [comment]
So you just mean that the printed string is wrong, not that it provides any error in the script itself?  It's just formatting then, which *should* be easier to take care of.
