### ISSUE TITLE
Any way to save data from LIST:FILES and not just print it out?

### ISSUE THREAD

**Issue by ergthbeb** [KSP-KOS/KOS#1066]
The LIST: commands are difficult to write into code that creates feedback for the player, because some values are not able to be known beforehand or anticipated correctly.  

I peeked at the code and was wondering it a set of suffixes could be added to listfiles.cs such as LIST:FILES:PRINT and LIST:FILES:GET. 

(For context i want to make my own FILES:LIST type output, but i cannot calculate filespace without knowing what files exist to determine their lengths, or query the Volumes themselves for such info,)

**Comment by tomekpiotrowski** [comment]
I'm not sure I understand your question, but you can already save a list of files to a variable and use it like so:

```
list files in volume_files.

for f in volume_files {
  ...
}
```

**Comment by ergthbeb** [comment]
Thank you for pointing this out for me! I guess I glossed over those two paragraphs in the documentation, and finding an answer this specific through a search engine just wasn't happening.
