### ISSUE TITLE
Steering not working for Stayputnik Mk. 1

### ISSUE THREAD

**Issue by BlueTiger12** [KSP-KOS/KOS#1067]
Found an Issue with Steering a Stayputnik Mk. 1
If you launch a rocket with a Stayputnik as Probecore, it is unable to steer it via kos with sas off.
This is especially an issue when playing career, where it has no sas at the beginning.

Testrocket: Stayputnik->KOS(the grey one)->4 Batteries->FT800->4 AV-R8->LV-T45

System: KSP 1.0.2, 32bit Windows Version(the Game not my OS :D), Stock Install with only KOS added

-------------------------------------------------------------------------------------------------------------------------------
Steps to reproduce:

Build Rocket;
on the Launchpad, open Terminal:
type: "lock steering to heading(180, 90)." it also won't work for "up" or "north" or heading(0, 90)
launch your rocket

-> steering won't work
when you enable sas it will work
disabeling sas again will again prevent steering from working.

Problem in Careermode is, that Stayputnik has no SAS at the beginning, so it is not steerable via KOS

-------------------------------------------------------------------------------------------------------------------------------
Same Setup, but with the octocore instead of the sphere:
steering will work regardless of sas being on or of
but i noticed, that steering with sas on is a lot smoother but overshoots
steering with sas off is precise, but you see very fast oscillations happen on the controlls; is that normal?

**Comment by aidygus** [comment]
I'm pretty sure this because the Staysputnik has no reaction wheels in it.  In the VAB right click the description and it states that there's no force.  Going into GameData/Squad/Parts/Command/probeStackSphere/probeStackSphere.cfg there is no module SAS so I think this is a working as intended.

Add a reaction wheel to the craft and I think you'll find it works

**Comment by BlueTiger12** [comment]
So KOS is unable to use Control Surfaces? Thought it could control them...
Also that doesn't explain, why the Stayputnik is controlable when you turn its sas on, even with no reaction wheels

**Comment by hvacengi** [comment]
Well, technically kOS can control control surfaces, and gimbal.  However, it doesn't know that it can use them, and they aren't accounted for in the lock steering logic.  If you were to try to use the raw controls instead, you should find that you have no problem pitching down.

When you enable SAS, the stock autopilot is used in place of the kOS steering autopilot.  Stock does account for at least gimbal (it might use control surfaces).  This is why turning on SAS makes it work.

We've actually been discussing how to rework the kOS autopilot.  It sounds like we have some theories on how to do a rewrite, which should help with this in the future.  It probably won't be in the next release, unless the release gets pushed back for a while.

**Comment by BlueTiger12** [comment]
Okay tested it and can confirm
Without additional sas module: Stayputnik uncontrollable if sas key is turned off.
With additional sas module: Stayputnik controllable even sas key is turned off
(both meant with the steering command).

Thanks for your support

**Comment by hvacengi** [comment]
I'm hoping that we can at least get the steering code to recognize gimbals, as that would help in most cases.  Stay tuned, maybe you won't need to work around this for very long.

**Comment by BlueTiger12** [comment]
Thanks for your fast repiles :-)

There is one other thing i noticed:
When i used the Stayputnik and the SAS module, steering was very smooth
When i used the OCTOcore without additional sas module the steering was overlapped with very fast oscillations.
Just as a sidenote ;-)

**Comment by Dunbaratu** [comment]
@BlueTiger12 : What do you mean by 'additional sas module'?  Do you mean a torque wheel part?

**Comment by BlueTiger12** [comment]
Yep, sry for the wrong Partname

**Comment by Dunbaratu** [comment]
I think at its core, this issue is really just a repeat of the need to change the LOCK STEERING algorithm to accept torqueless situations.  Stayputniks just happen to trigger that bug because they have no torque wheels.

**Comment by Dunbaratu** [comment]
This seems to be just a duplication of the known cooked steering problem with torque wheel-less craft, which is already being worked on with other issues, so I'll close as a duplicate.

**Comment by BlueTiger12** [comment]
Yes, you are right, i just didn't think of the Stayputnik not having torque wheels.
Thanks for looking into it :-)
