### ISSUE TITLE
A kOS part shouldn't be able to control other vessels directly, but it is.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#1068]
(I thought this bug was already reported ages ago but I read through the issues list and couldn't see it, so I'm reporting it again.)

### To recreate:

Make two airplanes, one with a kOS computer and one without.  Put them within loading range so both vessels' parts are fully loaded at the same time (i.e. have them both parked on the runway, for example).  Give them movable elevator control surfaces so you can easily see when they're being pitched up or down.

Call the vessel with a kOS computer "ship A" and the other one without a kOS computer "ship B".

At the interactive prompt In the kOS terminal for ship A, just type this command:
```
set vessel("ship B"):control:pitch to -1.
```
Then type this:
```
set vessel("ship B"):control:pitch to 1.
```
You can prove that the kOS computer on ship A has the full ability to control ship B by watching ship B's elevator surfaces when you do this.  They respond and move to your commands typed in ship A's terminal, even though ship A has no wiring connecting it to ship B's controls.

### Why is that a bug?

While sending wireless messages between kOS computers so they can coordinate with each other is a neat thing we should support later, it shouldn't just work magically like this.  It should require an antenna connection from source to dest, and it should require some kOS script on the destination vessel to hear the messages the other kOS vessel is sending it and IT moves the controls, not the kOS script on the source vessel.  (i.e later we support some message queue between vessels and let people write their own scripts to decide what to do with the messages).

But in the meantime, this behavior of magically allowing a kOS computer to get direct control of any vessel it's not part of, using the exact same API it uses to control itself, should be considered a bug and disabled.

This immediately raises the question of, in addition to preventing controlling foreign vessels, perhaps preventing querying too much data about them.

Getting the position and velocity of a foreign vessel (and therefore predicting its future position) should be possible just by taking remote readings so that can stay, but things like querying a foreign vessel's internal resources list ("how much charge is left in your batteries, ship B?") shouldn't be possible automatically without even having a connection.  Whether we decide to make that entirely a script-land thing or give it to users automatically as long as its connected can be decided later.  For *now* the fact that you can just get the data magically for a vessel you have no contact with is a bug.

**Comment by erendrake** [comment]
closed with #1182
