### ISSUE TITLE
SHIP:CONTROL cannot utilize engine gimbals prior to first staging event

### ISSUE THREAD

**Issue by space-is-hard** [KSP-KOS/KOS#1073]
**Description**

I encountered this problem while attempting to create a launch script that doesn't rely on the user-defined staging sequence. I have functions that perform all of the usual staging activities for a specific vehicle, including releasing the launch clamps. I found that the script, which utilizes `SHIP:CONTROL` for its PID controller, cannot utilize engine gimbals until I manually hit the spacebar or until the script calls `STAGE`.

**Reproduction steps**

1. Create a simple launch vehicle such as [this one](http://i.imgur.com/GIWVpbs.png). Aerodynamic stability helps to diagnose the problem, so be sure to include static fins.
2. Run [gimbaltest.ks](http://pastebin.com/W11rCdMW) from the launchpad *before* hitting stage.
3. Observe its attempt to pitch down three seconds after liftoff
4. Observe its attempt to pitch down three seconds later, after a script-activated staging event

Expected result: Vehicle should attempt to pitch down utilizing both reaction wheels and engine gimbals.
Actual result: Vehicle first attempts to pitch down utilizing only reaction wheels, and then after the staging event will utilize both reaction wheels and engine gimbals.

Note 1: Vehicle will use aerodynamic control surfaces as expected if they are available.
Note 2: `LOCK STEERING` does not suffer from this issue; only `SHIP:CONTROL`

My first reaction was to check `SHIP:STATUS` before and after the staging event, however it reports `FLYING` each time.

**Comment by space-is-hard** [comment]
Further testing has revealed this to be an issue with the stock game. Manually activating the engine and releasing the clamps via the right-click menus yields the same problem. I simply hadn't encountered this before because nobody launches that way.

**Comment by SirDiazo** [comment]
Just as a FYI to workaround the issue, when you activate the ModuleEngines partModule, you need to find the ModuleGimbal partModule on the same part and activate it as well. There is an action for it now in the stock game that can be used for this.

**Comment by space-is-hard** [comment]
In case anyone encounters this again, this particular issue should be solved by KSP 1.0.5. From the changelog:

>•Activate gimbals when an engine activates, not only when an engine activates from staging the part
