### ISSUE TITLE
Typo in small terminal part config

### ISSUE THREAD

**Issue by epicfacecanada1** [KSP-KOS/KOS#1074]
The  Up X value for the bottom stack node of the terminal part is 1.0 when it should be -1.0.

example:

Original

// --- node definitions ---
// definition format is Position X, Position Y, Position Z, Up X, Up Y, Up Z, connector node size
node_stack_bottom = 0.0, -0.0566, 0.0, 0.0, 1.0, 0.0, 0
node_stack_top = 0.0, 0.0466, 0.0, 0.0, 1.0, 0.0, 0

Edited

// --- node definitions ---
// definition format is Position X, Position Y, Position Z, Up X, Up Y, Up Z, connector node size
node_stack_bottom = 0.0, -0.0566, 0.0, 0.0, -1.0, 0.0, 0
node_stack_top = 0.0, 0.0466, 0.0, 0.0, 1.0, 0.0, 0

without this edit the bottom node of the terminal doesn't attach properly.

**Comment by erendrake** [comment]
@epicfacecanada1 when you say "the terminal part" are you talking about the `KR-2042 b Scriptable Control System`. If so we have a fix in for that part and it will be in the next release
