### ISSUE TITLE
Tourists are able to type at the console.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#1088]
See this user's report:
https://www.reddit.com/r/Kos/comments/3cf37j/flairbug_tourists_can_interact_with_the_terminal/

**Comment by hvacengi** [comment]
Odd, I thought that remote-tech did the heavy lifting for us regarding tourists.  I just went and looked, and this is how the RT api implemented the check:
```
        public static bool HasLocalControl(Guid id)
        {
            var vessel = RTUtil.GetVesselById(id);            
            if (vessel == null) return false;

            RTLog.Verbose("Flight: {0} HasLocalControl: {1}", RTLogLevel.API, id, vessel.HasLocalControl());

            return vessel.HasLocalControl();
        }
```
with the `HasLocalControl` method implemented as an extension method:
```
        public static bool HasLocalControl(this Vessel vessel)
        {
            return vessel.parts.Any(p => p.isControlSource && (p.protoModuleCrew.Any() || !p.FindModulesImplementing<ISignalProcessor>().Any()));
        }
```
We could roll our own solution, but I think what I'll do instead is try to fix the RT implementation and make a PR directly to them.  At that point @erendrake ought to be able to help us push it through to the next release.

**Comment by erendrake** [comment]
I get back into town tonight and would be happy to help with this

**Comment by tomekpiotrowski** [comment]
I was not able to reproduce this issue. I have constructed a simple vessel: command pod + probe + battery + kos processor. The terminal worked fine for a pilot, but did not work for a tourist.

Maybe the OP did not have a probe on his vessel? Then #1171 would explain the behavior he encountered.

**Comment by Dunbaratu** [comment]
Was a bug, but not reproducable anymore after PR #1171, so closing it.
