### ISSUE TITLE
Suffixes do not operate on bodies in lists

### ISSUE THREAD

**Issue by gisikw** [KSP-KOS/KOS#1090]
Many of the functions I'm looking to write would be useful for both celestial bodies and vessels. As such, I'd love to be able to write something like:

```
FUNCTION IS_BODY {
  PARAMETER name.

  LIST BODIES IN allBodies.
  FOR b IN allBodies {
    if b:NAME = name {
      RETURN TRUE.
    }
  }

  RETURN FALSE.
}

// e.g.
IF IS_BODY(foo) {
  RETURN BODY(foo):LONGITUDE.
} ELSE {
  RETURN VESSEL(foo):LONGITUDE.
}
```

Unfortunately, I get an error `CelestialBodies cannot have suffixes`. Referring to a single body (e.g. `BODY('Mun'):NAME`) operates just fine.

**Comment by gisikw** [comment]
If I had to guess, `Body`s when dumped as a list aren't being wrapped as `Orbitable`s?

**Comment by hvacengi** [comment]
From buildlist.cs
```
switch (listType)
            {
                case "bodies":
                    list = ListValue.CreateList(FlightGlobals.fetch.bodies);
                    break;
...
```
Yep, it returns the underlying ksp body object.  We'll have to get that fixed in the next update.

**Comment by gisikw** [comment]
Cheers :-) It looks like for my case, I can invert the logic and `LIST TARGETS` instead (which do support suffixes), but I'll look forward to the update!
