### ISSUE TITLE
LIST:CONTAINS() always false for file names.

### ISSUE THREAD

**Issue by zoombahh** [KSP-KOS/KOS#1095]
when I call `myList:contains()` on a list that was obtained via `LIST FILES IN myList.` it always returns false even when iterating over the elements finds a match.

example:
```
log "hi" to "testfile.txt".

list files in haystack.
local needle is "testfile.txt".

print "looking for '"+needle+" in "+haystack.

print " results in "+haystack:contains(needle).

for f in haystack {
	print "match for '"+f+"' is "+(f=needle).
}
```
![kos_contains_filename](https://cloud.githubusercontent.com/assets/1749138/8638409/ed7476e4-28ba-11e5-977b-188dcf0daff0.png)

On a related note: could we get a way to check if a file exists? listing files and, as a workaround for this ticket, iterating over them seems like a lot of work. (i want to force a rename and MAY have to delete an existing file and to delete it, it has to exist)

Edit: kOS v. 0.17.3.0, the newest version on CKAN as of yesterday.

**Comment by TDW89** [comment]
This is probably becouse `list files in foo.` produces a list of structures of type ![fileinfo](http://ksp-kos.github.io/KOS_DOC/structures/misc/fileinfo.html) so the list does not contain the string `testfile.txt`

One quick solution for you (with regards to deleting potentially non-existent files) is
```
log "" to my_file.ks.
delete my_file.ks.
```

**Comment by zoombahh** [comment]
thats actually a neat idea, thanks.

as a dev I see the issue of having a collection of objects that are implicitly converted to strings for comparison. it still doesent seem very intuitive, but im not sure what i would do / expect to be done about it.

**Comment by hvacengi** [comment]
The suggestion by tdw is how I generally get around this, but now that we have `core:currentvolume` it would be really easy to add a suffix to the volume structure `hasfile` or `fileexists` to be able to check it. I'll add it to my list of things to do.

**Comment by hvacengi** [comment]
Now that we have the associative array structure, I'd like to implement a version of the file list as a string dictionary, that way `haskey` can take serve as the `hasfile` method I mentioned above.

**Comment by crafty-geek** [comment]
@hvacengi getting a Lexicon of a file list (and other structs with a name field) is discussed in #1277, in case you want to chime in.
