### ISSUE TITLE
surface speed being reported wrongly.  change in KSP API it seems.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#1097]
For further information, see this post:

http://forum.kerbalspaceprogram.com/threads/68089-1-0-4-kOS-Scriptable-Autopilot-System-v0-17-3-2015-6-27?p=2080759&viewfull=1#post2080759

**Comment by hvacengi** [comment]
For reference to be implemented when I'm more awake (or by anyone else), here is the referenced KER work around: https://github.com/CYBUTEK/KerbalEngineer/commit/3b44364c6300a93cf15a2a50e00a95550002e3d5

**Comment by erendrake** [comment]
just for discussion, the way that `horizontalSrfSpeed` is calculated is 

    this.horizontalSrfSpeed = this.srfSpeed * Math.Sin(Math.Acos(Math.Abs(Vector3d.Dot(this.obt_velocity.normalized, this.upAxis))));

and it is calculated at the end of the fixed update.

**Comment by Dunbaratu** [comment]
Well no wonder it's fubar'ed in stock.  It''s starting from the orbital velocity vector.

**Comment by Dunbaratu** [comment]
Hey, while we're at it, should we fix the name of the bound variable and the vessel suffix it maps to?

The term "surface speed" implies "scalar size of the thing the mod refers to as the surface velocity" to me, and what the mod calls the "surface velocity" is really the 3-D surface velocity, while the "surface speed" is its 2-D projection, and that seems a clash of terms.

Given that ``surfacespeed`` was broken, it's a good proof nobody is able to use it right now, so it's a good moment to change its name without concern for backward compatibility.

I'm fine with "groundspeed" as a much much more intuitive meaning.

**Comment by erendrake** [comment]
`groundspeed` is the correct term anyway isnt it? https://en.wikipedia.org/wiki/Ground_speed

i am fine with changing it :)

**Comment by Dunbaratu** [comment]
okay I'll push a new commit and update the branch.
