### ISSUE TITLE
dockingport:aquire[force,range,torque] is a misspelling of "Acquire"

### ISSUE THREAD

**Issue by space-is-hard** [KSP-KOS/KOS#1099]
Confirmed misspelled in both game and docs

**Comment by Dunbaratu** [comment]
Is anyone using this yet? - should we ailias both spellings or just fix the spelling and throw away the old spelling?

**Comment by hvacengi** [comment]
I reference it in my docking script, but I'd rather we didn't alias the incorrect spelling.  Maybe the incorrect spelling should throw a deprecation exception for one or two versions, just so people don't think they're crazy when the script claims that the aquire suffix doesn't exist.

There is something funny in the range value anyways, but I haven't figured out what it is.  On one set of docking ports it seems like it's too small, and on another set it seemed to big.  I haven't run a docking mission in a couple of weeks, but I'll make sure to test this out this weekend.
