### ISSUE TITLE
Volume structure is not documented

### ISSUE THREAD

**Issue by hvacengi** [KSP-KOS/KOS#1105]
When I was trying to answer this reddit post: https://www.reddit.com/r/Kos/comments/3drue2/getting_volume_storage_size/  I found that the volume structure doesn't appear to be fully documented on the github pages.  Now that we have easy access to the current volume through `core:currentvolume` it seems prudent to make sure we document the suffixes.  We might also take the the opportunity to add the suffixes `HASFILE` and `GETFILE` to allow a user to determine if the file already exists, as well as to give them access to the `FileInfo` structure without iterating through each file in the `FILES` list.

**Comment by erendrake** [comment]
being able to access the file by name directly would be a great use of an associative array type! good thing i am on the ball and finished making one two months ago and then havent merged it :p  

Sorry, grumpy morning

**Comment by Dunbaratu** [comment]
I';m going through all the old documentation issues and cleaning up some old simple ones.

Because this issue mentions possibly changing it to use associative arrays, I'm going to hold off on documenting it until that PR is merged in.  Whatever I type now might become wrong soon.
