### ISSUE TITLE
velocityat(utime) seems to be a bit off.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#1109]
I noticed this in my script and others reported it too - need to investigate to see if it's true.

**Comment by Dunbaratu** [comment]
As far as I can tell, we're just returning the low level API's idea of the velocity, without "cooking" it at all.

**Comment by hvacengi** [comment]
It could just be inaccuracies in the prediction algorithm that KSP uses.  Given how much the Ap and Pe can bounce at times, it wouldn't be surprising so see both future position or velocity vectors bounce a little bit.  How inaccurate is the velocity vector when you've observed it?

**Comment by Dunbaratu** [comment]
I tried doing circularization burns from it and they're way off.
*as in, find the speed that would be needed to be circular at apoapsis altitude, compare against predicted speed at apopapsis.  The difference is how much deltaV to burn.*

**Comment by space-is-hard** [comment]
>as in, find the speed that would be needed to be circular at apoapsis altitude, compare against predicted speed at apopapsis. The difference is how much deltaV to burn.

Are you doing this and then seeing yourself being short of a circular orbit? Because if so, that could be the result of a non-instantaneous burn and/or gravity drag

**Comment by Dunbaratu** [comment]
re-read my comment.  I was editing it as you replied.

**Comment by space-is-hard** [comment]
That's probably from inefficiencies introduced by a non-instantaneous burn. Is there any way we could do a manual calculation of velocityat() and compare it to what the API returns?

**Comment by Dunbaratu** [comment]
We could get the manual speed by way of knowing the SMA.

**Comment by Dunbaratu** [comment]
comments of github are the wrong place to be having a back and forth conversation.

**Comment by hvacengi** [comment]
I think based on the conversation in slack we decided that `velocityat` was working correctly, am I right?
