### ISSUE TITLE
Comparing numbers with strings.

### ISSUE THREAD

**Issue by TDW89** [KSP-KOS/KOS#1112]
not exactly a bug becouse it is compairing string lengths (I think) but is produces some contradictory looking statements.
```
set num to "b".

print num <> 0. //true
print num < 0 or num > 0. //false

print num >= 0. // true
print num > 0 or num = 0. //false

print num <= 0. //true
print num < 0 or num = 0. //false
```
is there a reason to have it look at string length and number of digits (and only do it when 2 symbols are used) since we dont have string manipulation.

**Comment by Dunbaratu** [comment]
This was a bug, but I believe this was dealt with already in PR #1159 's changes that revamped all string actions.

**Comment by hvacengi** [comment]
I don't think it was covered in #1159, but it will be with #1294.  I specifically added methods to the string calculator which will throw an exception if you try to compare structures that aren't strings.
