### ISSUE TITLE
Trim improvements

### ISSUE THREAD

**Issue by ItMustBeACamel** [KSP-KOS/KOS#1113]
One bug, and one proposal.

The bug: setting trim via the raw controls like "SHIP:CONTROL:PITCHTRIM" does actually do nothing if the craft is currently controlled by the player. This is due to FlightInputManager overwriting the  control state of the craft with its own on every frame.

The proposal: The way kOS currently handles raw controls makes it necessary to neutralize a control input before the player can control it him- or herself again. For normal controls this makes sense, but not for trim. Trim is normally used to maintain a stable state like level flight/ climb/descend. Real world autopilots often pitch a plane by setting the trim, rather then pulling on the yoke. This way the plane does not suddenly drop into a dive after deactivating the flight assistance. So my proposal is to make all pitch related pilot controls settable, like "PILOTMAINTHRUST" already is. That way it is possible to either lock away the trim from the player (PITCHTRIM) or set the trim permanently (PILOTPITCHTRIM).

**Comment by Dunbaratu** [comment]
Closing as 'wontfix' given that the PR it was attached to was closed as "wontfix".  If I'm wrong to do this, re-open it, @erendrake.

**Comment by erendrake** [comment]
Keep it closed, I don't want kOS setting to to the input handler any more often than absolutely necessary
