### ISSUE TITLE
Physics-less parts still report as 0 mass.

### ISSUE THREAD

**Issue by burgled** [KSP-KOS/KOS#1115]
This was the correct thing to do in older versions of KSP but as of 1.0.1 or 1.0(?) it seems that the mass of a physics-less part is added to its parent.

**Comment by Dunbaratu** [comment]
Does the parent part have a larger than normal value when you query it's :MASS?  If so, then there isn't really a problem, but if not then there is.

**Comment by burgled** [comment]
Just tested and it seems that ship:mass is correct but no the individual part masses don't add up to it, the physics-less parts mass doesn't seem to be counted anywhere.

![proof](https://cloud.githubusercontent.com/assets/13560205/8971084/73b01b56-361b-11e5-8bfd-54985dcd0120.png)

**Comment by Dunbaratu** [comment]
Grumble. Well another place where the KSP API isn't really very smart, I guess:  All we're doing is passing that into KSP's own api and returning this:

```
part.mass + part.GetResourceMass() 
```
(That's the dry mass plus the mass of any resources it contains (i.e. fuel).)

So it seems that despite SQUAD's claims that physicslessparts add their mass to the parent part, they clearly don't - at least not in the low level API.  I don't see anywhere where they made a routine to pull together the children's mass to the parent.  I'll have to look later - gotta go.

**Comment by gisikw** [comment]
Just to add a note here: this also breaks `SHIP:WETMASS` and `SHIP:DRYMASS` (was writing a quick delta-v calculator and got really confused)

<img width="1186" alt="screenshot 2015-08-01 23 53 07" src="https://cloud.githubusercontent.com/assets/10201/9024648/83f00b0e-38a8-11e5-8941-1ad2b448fffd.png">
