### ISSUE TITLE
Branch of kOS for user configurable, or 0.0 disk mass multiplier

### ISSUE THREAD

**Issue by Saabstory88** [KSP-KOS/KOS#1121]
Greetings,

I am a Realism Overhaul player who has become very frustrated with the mass multiplier required for kOS disk space. Real spacecraft can have terabytes of storage for a fraction of a kg. I can not successfully recompile kOS with this option. Would it be possible to have a branch made for this? Could even have the mass mult as a KSPField.

**Comment by hvacengi** [comment]
If you are just looking to increase your storage capacity without affecting the mass, you can do that with a module manager patch (stored in a file some where in your GameData folder):
```
@PART[kOSMachine0m]:FOR[kOS]
@MODULE[kOSProcessor]
{
    @diskSpace = 40000
}
```
Set disk space to be whatever you want (you would have to do this for each part).  If you run into an issue with the value being overwritten, add `:FINAL` to the end of the first line.  If you'd like, you can use a similar technique to add kOS processors to any other part (say, for example, every probe core).

**Comment by Dunbaratu** [comment]
Since Realism Overhaul is actually a modpack, rather than just one mod, I presume it has its own ModuleManager patches to alter stock things.  Could this be part of what it does - create ModuleManager alterations to kOS's disk space?

**Comment by Dunbaratu** [comment]
IMO this should be addressed by people who want this using ModuleManager rather than in kOS code.
