### ISSUE TITLE
LOADDISTANCE doesn't do any good without changing PACK distance as well.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#1128]
Each of the load distances also has a pack distance, for example:
```
    PhysicsGlobals.Instance.VesselRangesDefault.orbit.load
    PhysicsGlobals.Instance.VesselRangesDefault.orbit.unload
    PhysicsGlobals.Instance.VesselRangesDefault.orbit.pack
    PhysicsGlobals.Instance.VesselRangesDefault.orbit.unpack
```
In our bound variable LOADDISTANCE, we set both the ```load``` and the ```unload``` distances, but never touch the ```pack``` and ```unpack``` distances.  The effect this has is that you can have vessels loaded (their parts exist) but they are frozen in place as one fixed glued object that refuses to pay attention to any inputs of any sort.

Example where this came up:

Two airplanes parked at the ground at KSC, about 400m apart, one on the runway, the other on the grass to take off next to it.   Both running the same script to take off.  Both of them LOCK THROTTLE TO 1.  But only the currently active vessel actually throttles up.  The other one is not fully "working" even though you can see it.  This is the "loaded but not unpacked" state.

As the currently active vessel gets near the second vessel and starts to pass it by in the midst of its takeoff run, it gets within about 300m of the second vessel, and the second vessel suddenly throttles up and starts moving.   Because it started later, it is slower to get going, and the first vessel soon leaves it behind.  When they get more than 300m apart again, the second vessel's engines magically stop, and the second vessel freezes in place, wheels stuck to the ground, nose partly off the ground as it was in the midst of pulling up for takeoff.  You can see it (parts loaded), and you can even interact with it's kOS terminal, but KSP prevents it from moving.

When you crash the first vessel deliberately, and then switch back to the second one that was frozen in mid-takeoff. suddenly the second one "unsticks" the moment you switch to it, and it finishes taking off.

This evidence seems to point to the idea that:
```
    PhysicsGlobals.Instance.VesselRangesDefault.landed.pack
```
is only 300m, even though I've change the LOADDISTANCE to 15000.

Thus the whole intent behind the LOADDISTANCE setting is rendered moot.  It won't let you actually control a ship that's far away - just LOOK at it and run its terminal window, but any commands that require the vessel to physically move or change don't actually take effect.

Fix: maybe just adjust all 4 (pack,unpack,load,unload) to the same number?  For now?

**Comment by hvacengi** [comment]
Closed with #1179
