### ISSUE TITLE
SASMODE mixed up

### ISSUE THREAD

**Issue by Joachimalaya** [KSP-KOS/KOS#1130]
Using the field SASMODE to use a probe core for attitude control has a bug. Setting SASMODE to "radialout" will activate the mode "Anti-Radial", which is the one pointing inwards. Analogous setting SASMODE to "radialin" will activate the mode "Radial" which is the one point outwards.

How to reproduce:
1. put vessel with probe core capable of radial attitude control and kOS computer in orbit
2. open console and enter:
  i. set sas to true.
  ii. set sasmode to "radialin".
3. vessel will orientate along the marker called "Radial", which is away from the body

observed on Windows 7 64-bit with KSP 1.0.4 32-bit and kOS 0.17.3
additional mod: Remote Tech (had connection to KSC)

**Comment by hvacengi** [comment]
I'm going to blame squad for this one.  I'm could have sworn I tested it, but even in my demo video for the feature it is reversed.  In my defense, squad appears to be reversing the terms internally.  Here is the applicable section of kOS's code:
```
                    case "radialin":
                        SelectAutopilotMode(VesselAutopilot.AutopilotMode.RadialIn);
                        break;
                    case "radialout":
                        SelectAutopilotMode(VesselAutopilot.AutopilotMode.RadialOut);
                        break;
```
As you can see, I I thought I was setting it correctly.  

I'll get a revision pushed that reverses the two, but we'll have to be on the lookout for squad to fix this in a future release.

**Comment by Joachimalaya** [comment]
Well, that is nasty. That means by fixing this you will produce a new bug later.

Do you have a way to track stuff like this? Like a list called 'Issues we expect to be introduced'?

**Comment by hvacengi** [comment]
I have a check list of things I look to see if they've "fixed" on the new versions.  Luckily this one will be pretty easy to check out.
