### ISSUE TITLE
Update quickstart tutorial for 1.0 stock aero and replace stage:liquidfuel stuff

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#1157]
I just noticed that the quickstart tutorial STILL has you trying to go straight up until 10,000, then pitching down to 45 degrees all in one go - there's no way that will work anymore.  I thought this was fixed before, but it doesn't seem to have been.

**Comment by Dunbaratu** [comment]
Also on this issue should be to change the stuff about ``stage:liquidfuel`` for detecting when to stage.  Given how buggy the stock KSP stagevalues are, and how often people keep hitting problems with it, it should probably be swapped for the more reliable ``if maxthrust = 0`` check.

**Comment by hvacengi** [comment]
I'd recommend using `maxthrustat(0)` instead, so that they can use the same logic in a descent stage. There aren't very many cases where max thrust actually decreases other than due reduce performance at higher atmospheric pressures and reduction in thrust due to surface speed for jets, so it is really a fringe case but still a good habit.

**Comment by space-is-hard** [comment]
@Dunbaratu The updated tutorial that I made does rely on `MAXTHRUST` for checking for staging conditions, it's that the tutorial made available to the public [is still the old one](http://ksp-kos.github.io/KOS_DOC/tutorials/quickstart.html#id16).

**Comment by hvacengi** [comment]
Oh yeah... you re-wrote that already... forgot about that!

**Comment by Dunbaratu** [comment]
okay yeah both these issues are fixed already but I can't find the issues that dealt with them before in the github history.

**Comment by Dunbaratu** [comment]
calling it a duplicate even though I can't find the older issue it duplicates - the fix is clearly already present in develop.
