### ISSUE TITLE
Local steering commands still implement RT delay

### ISSUE THREAD

**Issue by Gaiiden** [KSP-KOS/KOS#1163]
```
set done to false.
on AG1 { 
  set ship:control:pitch to 0.5. 
  print "pitching!". 
}. 
on AG2 { 
  set ship:control:pitch to 0. 
  set done to true. 
}. 
until done {}.
```

When using Action Groups Extended to bypass RemoteTech and trigger action groups immediately, the following code prints "Pitching!" as soon as AG1 is triggered but it still takes however long the signal delay is to carry out the command that changes the craft pitch control. RT integration was disabled through the kOS control panel when this script was run. Triggering the second action group ends the program immediately, but it again takes the length of the current signal delay to zero out the pitch control

**Comment by hvacengi** [comment]
Interesting error.  I think that this was working for me properly before, but I haven't tested it with a major delay recently.  We'll get it on the list to research.

**Comment by Gaiiden** [comment]
also I forgot to specify this is with the latest kOS and RT versions

**Comment by hvacengi** [comment]
Did you have the issue with in previous versions of RT, or did it start with the most recent update?

**Comment by Gaiiden** [comment]
I can't say, I only ever tried this recently on the newest versions. A version or few ago RT would allow local steering without signal delay using the flight controls but that was fixed sometime post KSP v1.0

**Comment by Gaiiden** [comment]
Ok so the issue seems to be that I disabled the RT option in the kOS settings. Here is my local control script:

Code:
```
set running to true.
set locked to true.

// exit the program
on AG8 { set running to false. }.

// kill rotation
on AG1 {
  set ship:control:neutralize to true.
  lock steering to ship:facing.
  set locked to true.
  preserve.
}.

// pitch up
on AG2 {
  if locked {
    set locked to false.
    unlock steering.
  }
  set ship:control:pitch to -0.25.
  preserve.
}.

// pitch down
on AG3 {
  if locked {
    set locked to false.
    unlock steering.
  }
  set ship:control:pitch to 0.25.
  preserve.
}.

// roll left
on AG4 {
  if locked {
    set locked to false.
    unlock steering.
  }
  set ship:control:roll to -0.25.
  preserve.
}.

// roll right
on AG5 {
  if locked {
    set locked to false.
    unlock steering.
  }
  set ship:control:roll to 0.25.
  preserve.
}.

// yaw left
on AG6 {
  if locked {
    set locked to false.
    unlock steering.
  }
  set ship:control:yaw to -0.25.
  preserve.
}.

// yaw right
on AG7 {
  if locked {
    set locked to false.
    unlock steering.
  }
  set ship:control:yaw to 0.25.
  preserve.
}.

// initialize
clearscreen.
print "Local control enabled".
lock steering to ship:facing.

// program loop
until not running {
  wait 0.01.
}.

// reset controls
abort off.
unlock steering.
set ship:control:neutralize to true.
print "Local control terminated".
```
Now, when I have the RT option turned *off*, if I run the program and it starts immediately but all ship:control commands I send via action group bypassing RemoteTech via AGX take however long the signal delay is to execute even though all other program commands are immediate. If I turn *on* the RT option then the initial script execution takes however long the signal delay is (which it should, this is proper behavior) and then once the run command has reached the craft and the script is running I have instant ship:control response when I bypass RemoteTech with AGX to trigger the action groups immediately.

So again, RT option off things don't work as they should. RT option on, things all work as expected.

**Comment by Dunbaratu** [comment]
not a bug then?
