### ISSUE TITLE
"Power off" the KOSProcessor isn't saved

### ISSUE THREAD

**Issue by OzoneGrif** [KSP-KOS/KOS#1172]
If I power off, or shutdown a KOSProcessor, it works fine. 
But as soon as I reload my save, or switch vessel, the power is back on.

I checked in the persistence file, and the Power flag is still at "True" instead of "False".

This happens 100% of the time on every processor.

**Comment by hvacengi** [comment]
As near as I can tell, if there is a "power" flag in the save file, it isn't being put there by kOS.  But that doesn't mean it wouldn't be a nice feature to add.  We're going to be messing with persistence when do #1181, this should be easy to add in at the same time.
