### ISSUE TITLE
WHEELSTEERING could not be set to a xxx.0 heading

### ISSUE THREAD

**Issue by weirdculture** [KSP-KOS/KOS#1188]
Hi Guys, 

my first bug report here, took me 3 days to find out the bug.. 

When I try to set the WHEELSTEERING to a heading I have to take a heading which is not ending with a zero.

LOCK WHEELSTEERING to 090.0. <-- doesn't works, wheels are not being set to heading
LOCK WHEELSTEERING to 090.1. <--- works

could reproduce this on Linux and Windows with the actual stable build. 

Best Regards
WeirdCulture

**Comment by Dunbaratu** [comment]
This is identical to #1141.
