### ISSUE TITLE
Make vecdraw:SCALE work only on :VECTOR, not :START

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#1200]
(I've known this was wrong for a while but thought it was too late to fix it because it had been in public use.  But now I think it's impossible to use it anyway the way it is now so nobody *has* been using it.  Users keep giving each other advice of "leave this at 1, don't change it because it messes up" and I suspect nobody is using it at all.  Which makes it okay to change it to something more sane.)

What it does now:  When you change the ``:SCALE`` of a vecdraw, it multiplies the scale by BOTH the ``:START`` and the ``:VEC`` vectors, causing the vector to not only get bigger, as expected, but also to change where the tail is drawn, which isn't expected.

Proper behavior:  Just use ``:SCALE`` on the ``:VEC`` only, not the ``:START`` position.

**Comment by space-is-hard** [comment]
I'm no vector expert, but I've never come across a situation where the current implementation of `:SCALE` has been useful anyways.

+1

**Comment by hvacengi** [comment]
Agreed. As is, I just multiply the vector by my scale factor, and leave the specified scale factor set to 1.  I think the current implementation is only useful if you are trying to visualize how vectors stack together (or instance current velocity plus delta v) at a larger scale.

**Comment by ozin370** [comment]
I highly support this change. When I started using vecdraws and tried to use the scale param to adjust the vector scale, it really confused me and I thought I was doing something wrong.

**Comment by ozin370** [comment]
Actually, come to think of it.. it would be great if scale could be changed into thickness. Depending on circumstances, vecdraws are often too thin or thick compared to the length, sometimes making them a bit useless.

**Comment by Dunbaratu** [comment]
Sort of halfway between bug and enhancement.  Although the current behavior is consistent, it's consistently stupid and useless.  I think it needs fixing.

**Comment by Dunbaratu** [comment]
I like the idea of a width, but not for the scale value because that would mess things up in existing scripts.

**Comment by Dunbaratu** [comment]
Whoa.. there already IS a `:width` suffix, but it's totally undocumented.  I forgot all about it.

**Comment by ozin370** [comment]
Hah! Good to know

**Comment by Dunbaratu** [comment]
My PR above documents :WIDTH, as well as implementing some new rules for how scaling works.  I'm hoping it's entirely compatible with existing scripts, except for the rare exception where someone actually used :SCALE before and a non-origin :START, which I'm thinking is going to be super super rare.

**Comment by Dunbaratu** [comment]
Warning, if you start using `:width` now, before my pull request above becomes public, you'll be using a system that's about to change its interpretation slightly.  I figured it was safe to change how it works given that it wasn't officially promised before (by not being documented).
