### ISSUE TITLE
SHIP:GROUNDSPEED returns NaN instead of zero when parked with brakes - sometimes.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#1208]
Park a plane on the runway, brakes on.

In a terminal, type:
``print ship:groundspeed.``

Use up-arrow and hit return to repeat the command.
agian.
again.
again.
again.

It seems to give a NaN error about a third or so of the time.  The rest of the time it gives a very small magnitude number near zero, as one would expect for a parked plane.

**Comment by Dunbaratu** [comment]
It is because it's running this formula:

            Sqrt( surf speed^2 - vertical speed^2); 

Which can end up doing a sqrt() of a negative number (imaginary number, therefore floating point can't store it, thus a NaN) if vertical speed is larger that surface speed.

In principle that should be literally impossible.  Surface speed is the length of a hypotenuse of a right triangle, and vertical speed is the length of one of its legs.   The leg can't be longer than the hypotenuse, but when the speed gets near zero, this is exactly what the KSP API is returning as the values get small enough to have some error in them.

**Comment by hvacengi** [comment]
You and I have already talked elsewhere about the suggestion of using a vector exclude to help, but I wanted to make sure to mention it in the issue itself.

I recently ran into a similar issue with my quadratic solver script.  When I was debugging the issue, I found that the two numbers were equal to 10 decimal digits.  So I decided to just round anything beyond those digits.  It introduced more floating point error, but I was only using the value to show the estimated time to impact.  Not sure if it would help here to do that because I don't know how big your errors are.

**Comment by Dunbaratu** [comment]
sqrt doesn't need to have an input very far below zero to return NaN - just anything even *slightly* negative does it.  What's happening here is that where the KSP API should be returning two very small numbers one slightly bigger than the other, like so:

A must be > B.  In this instance A = 0.000001, B = 0.0000000997

Instead due to the errors you get doing very tiny angle trig in single-precision floats, you end up getting values like this to come out:

A must be > B.  But In this instance A = 0.000001, B = 0.00000010001, so A < B,.

For most normal applications an error like 0.00000010001 instead of 0.0000000997 would be puny and irrelevant.  But when you're subtracting that number from another similarly tiny number, and MUST ensure that this never goes below zero, then that can make the difference between a result that should be slightly positive, like 0.000000003 ending up slightly negative like -0.00000000001

The problem is that we're getting into the area where the magnitude of the error bars is bigger than the magnitude of the actual values we're trying to measure.  That's why this only happens when parked.

vxcl is probably the safer way, even though it's a bit more computationally expensive.  For the sake of a kos program, that difference in speed is negligible.
