### ISSUE TITLE
The SteeringHelper should use the controller part as reference

### ISSUE THREAD

**Issue by marianoapp** [KSP-KOS/KOS#122]
Related to the changes made in #108, the steering code should use the controller part orientation as reference (change "vessel.transform" for "vessel.ReferenceTransform").

Since we are making this change we could also compile a list of things that should use the controller part as reference, like measuring the distance, bearing, etc.
I'll be editing this issue to add the suggestions we agree on.

**The list**
* Steering code

**Comment by hvacengi** [comment]
Closed via #1118
