### ISSUE TITLE
UNTIL loop not breaking

### ISSUE THREAD

**Issue by adeptinvention** [KSP-KOS/KOS#1232]
Pastebin of entire function: http://pastebin.com/wMtLupeN

I have an UNTIL loop checking target angles against a specific angle such that I launch inside a launch window.  

    UNTIL angleDiff &lt; 0 AND previousAngle &gt; tarAng {
       stuff.
       wait 0.001.
    }

Despite successfully checking if the two conditions are true, the UNTIL loop doesn't break.  I've tried the following too:

    UNTIL FALSE {
        stuff.
        if condition1 {
             if condition2 {
                    BREAK.
             }
         }
        wait 0.001.
    }    

This doesn't break the loop either.

**Comment by Dunbaratu** [comment]
Can you trim off all extraneous things from the example case and just do this:
```
    set a to true.
    set b to true.

    until a and b {
        print "still looping."
        wait 0.001.
    }
```

**Comment by hvacengi** [comment]
I'm having a hard time reproducing this issue, and just noticed on the reddit thread that you said you're using the previous version.  Please report back after you've tried it on the newest version.  We're going to release a patch with some small fixes here today, so you may want to try it after that release.

**Comment by Dunbaratu** [comment]
Not a bug.
Explanation here:  https://www.reddit.com/r/Kos/comments/3rrs8h/until_loop_not_breaking/cwr2w52
