### ISSUE TITLE
change quickstart tutorial to stop teaching people to re-execute LOCK STEERING in a loop.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#1236]
The current quickstart tutorial is teaching people to do this:  Note the way it's re-executing LOCK STEERING each loop iteration even when the expression it's locking things to is the same as it was the last time.

```
UNTIL SHIP:APOAPSIS > 100000 { //Remember, all altitudes will be in meters, not kilometers

    //For the initial ascent, we want our steering to be straight
    //up and rolled due east
    IF SHIP:VELOCITY:SURFACE:MAG < 100 {
        //This sets our steering 90 degrees up and yawed to the compass
        //heading of 90 degrees (east)
        LOCK STEERING TO HEADING(90,90).
    }
    //Once we pass 100m/s, we want to pitch down ten degrees
    } ELSE IF SHIP:VELOCITY:SURFACE:MAG >= 100 AND SHIP:VELOCITY:SURFACE:MAG < 200 {
        LOCK STEERING TO HEADING(90,80).
        PRINT "Pitching to 80 degrees" AT(0,15).
        PRINT ROUND(SHIP:APOAPSIS,0) AT (0,16).
    }.
}.
```
The logic should be slightly re-written to only execute those ``LOCK STEERING`` commands when they change to something new, and not every loop iteration.  It's teaching new users bad practices, and probably misleading them as to how "LOCK" actually works.

**Comment by erendrake** [comment]
Closed by #1341
