### ISSUE TITLE
implement a HASSUFFIX

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#1237]
Akin to the DEFINED, it would be handy to have a HASSUFFIX check for scripts too.  For example:

```
   if p:hassuffix("length") {
        print "p has " + p:length + " things.".
   }
```
This would be part of the "be more type-aware" refactoring I'd like to do, and it was a suggestion from a reddit user, and it's a good one.

**Comment by erendrake** [comment]
We have long talked about some kind of "suffixes" suffix that would give
you more info about a structure. Now that we have the lexicon. Could this
we give the full list of suffixes out and this could just be a `HASKEY` on
that lexicon?

I am not opposed to this at all I am just trying to see if we can finally
expose the descriptions in suffixes ☺

**Comment by Dunbaratu** [comment]
I'm going to mark this as duplicate because I'm about to open an issue that covers this and other things.
