### ISSUE TITLE
Reading files to string

### ISSUE THREAD

**Issue by thexa4** [KSP-KOS/KOS#1238]
KOS currently allows you to write to files but there doesn't seem to be a way to read them back in which would be great for things like preprocessors during launch and as a substitute for user input by giving the user an edit window during program execution.

**Comment by space-is-hard** [comment]
Currently you can read from files in a certain way. If you need to log a string for future use, you can

    LOG "GLOBAL inputString TO " + outputString + "." TO inputLog.ks.

and then later

    RUN inputLog.ks.
    PRINT outputString.

**Comment by erendrake** [comment]
@thexa4 we are hoping to address this before the next major release.

**Comment by Dunbaratu** [comment]
Check this issue again after we've fully tested the changes associated with PR #1269
