### ISSUE TITLE
Boot files do not copy in KSP 1.0.5

### ISSUE THREAD

**Issue by hvacengi** [KSP-KOS/KOS#1240]
It looks like KSP changed the declaration of the Vessel.Situations enum so that references compiled against former versions won't work.  This should just require recompiling with up to date dlls.

I mostly wanted to post here so that anyone looking to report the issue can see that we have already tracked down the issue.

Please close when releasing 0.18.2.

**Comment by tomvanderlee** [comment]
Can confirm, very annoying.

**Comment by tomekpiotrowski** [comment]
We can close this.
