### ISSUE TITLE
Request for information: kOS and RemoteTech

### ISSUE THREAD

**Issue by SirDiazo** [KSP-KOS/KOS#1246]
Alright, I've been working through updates for 1.0.5 and I see RemoteTech has changed how events are handled.

That means I'm going to go back and do a full set of tests to make sure AGX (Action Groups Extended), kOS, and RT all play nice together.

However, I need some clarification on how kOS and RT are supposed to integrate, especially around local/remote control.

When entering commands at the kOS command line, are they handled differently then commands running in a script?

Does kOS always execute in local control? Always in remote (so subject to signal delay)? Or does it switch? If it does switch, how do I tell what mode it is in?

It is probably going to be another week (maybe two) before I have things on my end settled enough to do these tests but I want time for people to think this over so I don't miss anything when I do them.

Note that while I'll be focusing on Actions as that is what AGX deals with, if there are some other tests you'd like to see while I'm in there I have no problem with doing them.

D.

**Comment by hvacengi** [comment]
>When entering commands at the kOS command line, are they handled differently then commands running in a script?

Yes.  The interpreter queues the commands and waits until the signal delay period has expired, then it issues the command the same way it would if RemoteTech is not installed.  If the craft has local control (according to RemoteTech) then the command is issued immediately.  Any subsequent sub-program commands are executed without delay like normal.  There is also no delay before a boot script starts.

>Does kOS always execute in local control? Always in remote (so subject to signal delay)? Or does it switch? If it does switch, how do I tell what mode it is in?

Control itself is always performed without signal delay, as if you had local control of the vessel.  After the initial `run program.` command, everything else is executed without delay.  The rational here is that once the computer has been given a program to run, it doesn't need to wait for every individual instruction to come from KSC.  As long as RemoteTech is installed, and the RT config flag is set to true, kOS will always subscribe to the RemoteTech steering api.

The way I see it, this means two potential places to make sure AGX, RT, and kOS are on the same page: when kOS reads that an actiongroup has been activated by the user and when kOS wants to activate an AGX group.  As implemented, kOS appears to use reflection to call `AGX2VslActivateGroup` and `AGX2VslGroupState` methods for this interaction.  For things to work without changing kOS code, I would expect:
* `AGExtExternal.AGX2VslActivateGroup` would have no delay before the change is executed.
* `AGExtExternal.AGX2VslGroupState` would return the state taking into account delay if applicable.

That should produce the following behavior:
```
// assume the ship has a 5 minute RT delay
// user activates ag12 via ui
wait until ag12. // waits 5 minutes.
set ag13 to true. // actions from ag13 should be executed without delay
print ag13. // reading ag13 should return true without delay
// user activates ag14 via ui
wait 10. // wait less than the delay duration
print ag14. // should return the initial value (false).
wait 5 * 60. // wait 5 minute delay
print ag14.  // now that delay is done, return the new value.
```

@tomekpiotrowski should probably weigh in on this too, he has been doing a lot to improve the support of RemoteTech.  And I think @ZiwKerman originally wrote the AGX support.

**Comment by SirDiazo** [comment]
It sounds like we are on the same page then. When kOS issues a command to activate an action group it has already considered RT's signal delay and AGX should just go ahead and activate the action without worrying about delaying it.

`AGExtExternal.AGX2VslActivateGroup` activates a group immediately. It does not check for RT's signal delay or if the vessel is in control, it assumes that kOS has already checked all that. This is what is currently used based on your comment.

Another method `AGExtExternal.AGX2VslActivateGroupDelayCheck` exists where AGX does the checking to make sure a connection exists and will delay the action by whatever the current signal delay is. kOS does not currently use this, but it does exist if it would make your end of things easier.

`AGExtExternal.AGX2VslGroupState` simply returns the current state of the action group. I'm not sure what you mean by having it take delay into account, it simply returns the state of the action group as visible on screen in the 3D game space.

**Comment by hvacengi** [comment]
>`AGExtExternal.AGX2VslGroupState` simply returns the current state of the action group. I'm not sure what you mean by having it take delay into account, it simply returns the state of the action group as visible on screen in the 3D game space.

That's what I meant.  I just intended to say that it should not return the new value immediately after pressing the button on your UI.

**Comment by tomekpiotrowski** [comment]
I think we can close this. The OP can continue the discussion if he wants to, but this is not a real issue.

**Comment by SirDiazo** [comment]
Done.

This was supposed to be a short-term issue only open for a week so I could log my testing results and any issues that needed addressing.

As real life has gotten in the way this testing has not happened yet and there is no actual issue in here.
