### ISSUE TITLE
Let's talk about function calls and program calls and propose a solution.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#125]
Right now all of the following facts about kOS scripts are true:

1 - You can't do a premature exit from a subprogram.  If you check for a condition that would make you want to cause a premature exit, you have to protect the rest of the code from that point downward inside one long if-check in order to skip around it to the bottom of the program file instead of saying "quit here".  If the exception occurred inside something like a loop or another if-check, then the need to skip around everything after that can lead to several extra levels of indenting just to handle the lack of an "exit" command.  

2 - You can't return a value when a subprogram is called, other than by putting it into a global variable.

3 - There are no local variables.  Not local to a program, not local to a file, etc.  This means that when writing a utility routine meant to be called from more than one place, you have to know what variables all the programs calling it are going to be using and not clobber them.  That's a hindrance to writing re-usable script code.

4 - There is a one-to-one mapping between program file and "function call".  If you want to call a "function" you do it by running an entire program file because that's the only place where you have the ability to pass arguments.

I think that as far as kOS script syntax goes, this is currently the biggest barrier to the language right now.

And I have the impression that all those things I mentioned in the list are really in essence the "same" issue:  calling routines from other routines is messy.

I was about to work on adding an "exit" to kOS but then stopped myself because I realized that if it returns an exit code, then it may as well return a value instead, and then if it returns a value and programs are really being called like functions, then maybe it really should be just a "return" statement, and maybe functions should exist first and then...... and then I stopped because I decided the roadmap for all these things is inexorably intertwined.  They have to be addressed as a set, with one coherent 'map' of what the final end product of this work would look like.  If I just pick something and start implementing it, then I'm stepping on a lot of other people's work, so this needs an agreed consensus first.

**So, Questions: (using letters instead of numbers to distinguish from the list above).**

(**Question A**) *What do we want as the relationship between script files and function calls?*  Currently it is effectively 1-to-1.  You pass arguments to a subprogram.  Do we want that changed to being able to define multiple functions in the same script file?

(**Question B**) *If the answer to (A) is "multiple functions allowed per file", then what namespace nesting rule would you propose?**  Is a simple global function namespace sufficient (i.e. a function called 'foo' in 'file1' and a different function called 'foo' in 'file2' would therefore not be possible - either the second instance of foo would be an error or it would replace the previous function foo.).

(**Question C**) *If the answer to (A) is "multiple functions allowed per file", then are those functions callable by other program files or just local to that program?*  (If they're callable by other program files, the way you'd do that is to first RUN MYPROGRAMWITHFUNCTIONS once first to make the computer load them for the other programs to use, given that kOS is supposed to be able to run the scripts directly without the user issuing a separate compile step, that means you can't do "linking" ahead of time to get the functions into the main program - you have to have the main program call the subprogram to get the subprogram's functions loaded.)  If you answer that they should be local to the program only, then what do you propose as the way to make the current subprogram syntax return a value from a subprogram call?.

If the answer to (A) is "one function only per file", so it is similar to how it works now, then the design is a bit more restricted, but a bit simpler to implement.

(**Question D**) *At what level should local variables exist?*  Should there be both local-to-function, and local-to-program? (if the answer to (A) is "one func per file" then this is simpler.)  

(**Question E**) *Do we want recursion to work correctly?*  Keep in mind recursion might be be something as direct and obvious as a function calling itself, but it could also happen quite indirectly from a function running a subprogram that runs a function that runs a subprogram that in turn calls the function that started this all.  Supporting a thing like that smoothly would have to mean local variables and passed parameters ending up in some type of stack structure..

You don't have to answer those bullet-point per bullet-point.  I just wanted to get written down the issues I was thinking about and how they interrelate, and ask other people's opinions on this.

I think that for stacked local variables and stacked parameters, (question E) the implementation that would probably be closest to what the code does now and thus the simplest to implement would be to, instead of putting local vars on the same stack as the execution stack uses, we instead take the global variable dictionary and make a separate stack of THEM - a stack of dictionaries - in which the bottom of that stack *is* the global variable namespace dictionary, the next dictionary above that on the stack is the namespace of the first function call, the next dictionary above that on the stack is the namespace of the next nested function call, and so on.  Then we alter the opcodes that store/retrieve values from variables so that when looking for a variable name they walk the stack of dictionaries from top to bottom, asking each one "do you have a variable called this?", thus finding the "innermost" variable with that name.  This would mimic the local namespace rules of most languages, where the variables of any level "more global than" the current level are accessible.

**Comment by abenkovskii** [comment]
@Dunbaratu 
> That's not how languages work.

Python works like this. Well... in fact it works a bit more complex: variables from scope where a function was declared are accessible too.
@marianoapp 
> At first we should require the functions to be fully qualified, for example "file1.foo()".

[Namespaces are one honking great idea -- let's do more of those!](https://www.python.org/dev/peps/pep-0020/)
Why we ended up not implementing this?
P.S.
Why this issue is still open?
