### ISSUE TITLE
LOCK ignores @lazyglobal off.

### ISSUE THREAD

**Issue by chippydip** [KSP-KOS/KOS#1263]
I mis-typed `lock THOTTLE` and couldn't figure out why my rocket wasn't turning on. This script has `@lazyglobal off.` at the top, so this should have been flagged as a compile-time error.

**Comment by Dunbaratu** [comment]
Locks are not variables.  They are a shorthand way to express a function.  Thus the `lock THOTTLE` statement *is* a declaration.  Otherwise all your scripts that use `lock foo` would fail if that was the first mention of `foo` and you had `@lazyglobal off.`

**Comment by chippydip** [comment]
If locks aren't variables, I don't know what is. They are identifiers which can have their values changed. That's pretty much the definition of a variable. The fact that their values happen to be functions shouldn't have any bearing on that.

Semantics aside, I understand that the implementation under the hood is very different for locked variables vs normal variables, but from a language user's standpoint I expect this to work:

    global foo is 0.
    lock foo to bar.

and this to fail with an error if `@lazyglobal off.` is specified:

    lock foo to bar. // first mention of 'foo'

Furthermore, the docs explicitly say that this is how locks are supposed to work:

"If the variable name used does not exist in local scope, then LOCK will create it as a global variable, unless @NOLAZYGLOBAL is set to off, in which case it will be an error."

(Assuming that @NOLAZYGLOBAL really means @lazyglobal off).

**Comment by Dunbaratu** [comment]
Then you are correct that there's an error.
But the error is in the docs (and in the initial language design that made these functions called "locks" look like variables, but that mis-design isn't my fault and predates me).

`lock foo to bar.` is identical in semantics to `function foo { return bar. }`. 

The ugly part is in trying to make `lock foo` throw an error when there doesn't happen to already be an identically named variable foo in a way that doesn't also throw an error when you do `function foo`.

**Comment by chippydip** [comment]
Well, I suppose a `@lazylock off.` directive could be added.

Honestly, though, the leaky abstraction that is locks has caused enough problems for me that I've decided as a general rule to just avoid locking anything but THROTTLE and STEERING, so I'd be happy with a solution that would throw and error if I tried to lock anything else.

**Comment by erendrake** [comment]
Closed by #1341
