### ISSUE TITLE
RCS display vectors are strange when RCS is off.

### ISSUE THREAD

**Issue by erendrake** [KSP-KOS/KOS#1279]
![No redraw](https://dl.dropboxusercontent.com/u/525229/Kerbal/kOS/rcs-vec.gif)

it looks like these are stale values that dont get cleared out. The issue could be solved by simply hiding vectors that are shown by `STEERINGMANAGER:SHOWRCSVECTORS` while RCS is turned off.

EDIT: I just realized that cropping the video destroyed the context that RCS is off the whole time. and the issue only appears when i come out of timewarp and start slewing to a new position. If you turn on RCS all of the yellow and pink vectors snap into place

**Comment by hvacengi** [comment]
I must have not set the vectors to clear when RCS gets turned off, so they just remain static (you'll notice they don't appear to turn away from the universal axes).  Should be easy enough to fix, just need to replicate some code from the engine section.  I'll also make sure that it works properly if you disable a single thruster.
