### ISSUE TITLE
(bug) ship:velocity vector type issue

### ISSUE THREAD

**Issue by baloan** [KSP-KOS/KOS#128]
KSP 0.23.5 with kOS 0.12.2p1
Vector cross works for some arguments. I found a case where it breaks. I issued the commands from a ship in 79km orbit around Kerbin. Actually location shouldn't make a difference for vector cross product.
![vcrs broken](https://cloud.githubusercontent.com/assets/651799/3139982/7f62b196-e8fd-11e3-9734-dcd5e68af814.PNG)

**Comment by erendrake** [comment]
ship and bodies are reconciled now
