### ISSUE TITLE
Reduce volume of error beep

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#1282]
In watching several peoples' youtube vids I've come to the conclusion that the error beep appears to be much louder than any of the other sounds the KSP game seems to be emitting.  I suspect that by calling Unity's Play() function directly, we are in fact bypassing all the KSP game's volume slider settings and just emitting at max volume no matter what.  This will need further experimentation to see.

**Comment by hvacengi** [comment]
I can confirm that it bypasses the game's volume setting.  I have my sounds turned all the way down, and the error beep still plays at full volume.  It usually isn't a problem for me, because I leave the system muted most of the time as well.

**Comment by Dunbaratu** [comment]
This should have auto-closed with PR #1287 but didn't.
