### ISSUE TITLE
Feature request: Clock mode suffex

### ISSUE THREAD

**Issue by TDW89** [KSP-KOS/KOS#1296]
A means for a script to determine if a day is 6 hours or 24 hours.

**Comment by space-is-hard** [comment]
`BODY("Kerbin"):ROTATIONPERIOD` should give you day length in seconds

**Comment by TDW89** [comment]
not quite what i meant. The day night period of a body is easy enough to work out. But if you want the user of a script to enter a time in the future then knowing whether the user expects 1 day to be 1 day/night cycle of kerbin (6 hour clock format) or 4 day/night cycles (24 hours) would be useful.

Real scale aside changing the clock mode in the main settings menu does not affect the rotation period of kerbin.

also on a side note `body:rotationperiod` does not give the exact length of a kerbin day. It gives the time taken for a full rotation of the body without taking into account the progression around it's parent body.
eg. for kerbin it is just under the 6hour day, for the mun (which is tidally locked) it is exactly the same as its `orbit:period` instead of `0`/`inf` which it would be it it was the time taken to rotate the same point back to facing the parent body. (not sure i did the best job of explaining that).
