### ISSUE TITLE
update or rewrite the links to kslib page of the docs

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#1299]
This page:
http://ksp-kos.github.io/KOS_DOC/library.html

Has hardcoded links into the kslib docs.  That's not good futureproofing, as kslib is re-arrangable and things can change.  Also it only mentions a few of the things there, and one of them is the now obsolete ``pid_lib.ks``.

Maybe it should say less and just point directly to kslib?

**Comment by hvacengi** [comment]
Close via #1341
