### ISSUE TITLE
Bound Variables docs don't mention kuniverse

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#1301]
the bound variables page has a section like so:

> System Variables
> 
> This section is about variables that describe the things that are slightly outside the simulated universe of the game and are more about the game’s user interface or the kOS mod itself. They represent things that slightly “break the fourth wall” and let your script access something entirely outside the in-character experience.

This section makes no mention of ``kuniverse`` at all, and in fact the entire bound variables page never mentions it.

**Comment by hvacengi** [comment]
Close via #1341
