### ISSUE TITLE
Make a new 4th generation low-mass computer part (was: Support Tweakscale)

### ISSUE THREAD

**Issue by dcrockwell** [KSP-KOS/KOS#1303]
I'm making drones in the game, but the smallest computer part I can use weighs 80kg

If I could use tweakscale, I could make the computer smaller to fit the drone.

Alternately, create a very small controller unit for miniature drones that weights only a few grams.

**Comment by Dunbaratu** [comment]
> the smallest computer part I can use weighs 80kg

The radial mount computer is 30kg  (called "Compomax Radial Tubeless").

**Comment by dcrockwell** [comment]
Ideally, I'd like one that is less than 1kg.

As it is, the CPU is the heaviest component on the drone I'm building, and my hopes to create a mini drone are not possible.

**Comment by Dunbaratu** [comment]
You can change the mass of parts with ModuleManager, or by editing the .cfg files that kOS ships with under kOS/Parts/.

We might make a 4th model for higher up the tech tree that' is lightweight, but in the meantime you can just change the ``mass = `` line in the configs.  (It's in megagrams, so 0.03 means 30 kg, for example.)

**Comment by TDW89** [comment]
I believe tweakscale support is handled at the tweakscale side of things, although they probably rely on other mod creators and 3rd parties to submit module manager files to them.

Stick this file in the tweakscale patches folder. (name it kOS_TweakScale.cfg)
```
@PART[kOSMachine0m] // Small Inline kOS core
{
    %MODULE[TweakScale]
    {
        type = stack
        defaultScale = 0.625
    }
}

@PART[kOSMachine1m] // Medium Inline kOS core
{
    %MODULE[TweakScale]
    {
        type = stack
        defaultScale = 1.25
    }
}

@PART[kOSMachineRad] // Radialy attached kOS core
{
    %MODULE[TweakScale]
    {
        type = free
    }
}
```

**Comment by pellinor0** [comment]
TweakScale can scale any kspField inside a partModule, it just needs the configs to tell it what to do. To scale values of the KOS module you can copy from ScaleExponents.cfg in the TweakScale folder. These patches can go anywhere inside Gamedata. 

I have my doubts how well scalable processors fit into the concept of KOS, but you can always write your own custom patches.

**Comment by dcrockwell** [comment]
> I have my doubts how well scalable processors fit into the concept of KOS, but you can always write your own custom patches.

To be honest, kOS has evolved a lot past the Apollo mission simulation it originally provided. I don't see/want kOS to be a "vintage space program computer". I want it to be a "kerbal-esque programming language" and I figure since I'm making miniature quadcopters; so are the kerbals.

**Comment by dcrockwell** [comment]
> You can change the mass of parts with ModuleManager, or by editing the .cfg files that kOS ships with under kOS/Parts/.

Awesome. I'm not familiar with modding KSP yet, so this is really cool to discover!

> We might make a 4th model for higher up the tech tree that' is lightweight

Sweet. Perhaps I could create a mod specifically for this so that you don't have to maintain miniaturization.

**Comment by Dunbaratu** [comment]
I wonder how hard it would be to detect if a computer core is on the "outside" of the craft versus stored inside something like the science bay.  One of the reasons computer parts on spacecraft are clunky is for radiation hardening.  It might be kind of neat to make a high-tier model that is tiny and compact but throws an exception and wipes memory the moment you expose it to the sun in vacuum without any other parts shading it.  The lower tier models would have their own shielding from the fact that they're big and heavy old tech.  The miniaturized model would either only work in atmosphere or would require that you build something around it.

**Comment by dcrockwell** [comment]
> throws an exception and wipes memory the moment you expose it to the sun in vacuum without any other parts shading it

Super cool idea.

**Comment by Dunbaratu** [comment]
By the way, it may take some time to make a fourth computer model.  Art assets are our weakest point, with just one member of the team capable of doing that sort of work. 

In the meantime, you can use the ModuleManager mod to add the kOS functionality to any other part, turning them effectively into kOS computers themselves,  Some people have done this with some of the computerized remote probe cores.  I can't offer advice on how to do it (or a guarantee that it will work properly) because ModuleManager's syntax is not something I've ever bothered trying to understand.

**Comment by dcrockwell** [comment]
A friend of mine or myself could make the art asset depending on how it's specified. Let me know if you'd like to open a topic on that.

**Comment by Dunbaratu** [comment]
Assigned to @pgodd, the  one who's already started doing some work on the new 3d model for it.

**Comment by pgodd** [comment]
I have the part working really well now.
I'm still struggling with one aspect. 
I want to tie power consumption to the intensity of the lights.
Right now the power consumption is an item in the part.cfg file, I have done a day of research and can't figure a way to alter the power consumption other than changing this value.
It's coded into the stock light module, and there doesn't seem to be a way to change it in flight.
This part could be ready tomorrow if I can get some help with this.

**Comment by pgodd** [comment]
using System;
using UnityEngine;
using KSP.IO;

namespace kOS.LightColor
{
    class kOSLiteModule : PartModule
        
    {

        [KSPField(isPersistant = true, guiName = "Required Power for Lights", guiActive = true)]
        public float resourceAmount ;

        [KSPField(isPersistant = true, guiActive = true, guiName = "Light R")]
        [UI_FloatRange(maxValue = 1, minValue = 0, scene = UI_Scene.Flight, stepIncrement = 0.01f)]
        protected float red = 1;
        
        [KSPField(isPersistant = true, guiActive = true, guiName = "Light G")]
        [UI_FloatRange(maxValue = 1, minValue = 0, scene = UI_Scene.Flight, stepIncrement = 0.01f)]
        protected float green = 1;
        
        [KSPField(isPersistant = true, guiActive = true, guiName = "Light B")]
        [UI_FloatRange(maxValue = 1, minValue = 0, scene = UI_Scene.Flight, stepIncrement = 0.01f)]
        protected float blue = 1;


       

        public void Update()
        {
            resourceAmount = ((red + green + blue)/10);
           

            if (HighLogic.LoadedSceneIsEditor)
            {
                red = part.FindModelComponents<Light>()[0].color.r;
                green = part.FindModelComponents<Light>()[0].color.g;
                blue = part.FindModelComponents<Light>()[0].color.b;
            }


            else
            {
                setColor();
            }
        }
        
        public void setColor()
        {
            float electricCharge = 0;
            float electricMax = 0;
            var myVessel = FlightGlobals.ActiveVessel;
            foreach (Part p in myVessel.parts)
            {
                if (p.Resources.Contains("ElectricCharge"))
                {
                    foreach (PartResource pr in p.Resources)
                    {
                        if (pr.resourceName.Equals("ElectricCharge") && (pr.flowState))
                        {
                            electricCharge += (float)pr.amount;
                            electricMax += (float)pr.maxAmount;
                            break;
                        }
                    }
                }
            }
            
            var EnergyRemaining = (electricCharge / electricMax) * 100;

            if (EnergyRemaining < 0.5f) {
                foreach (Light lgt in part.FindModelComponents<Light>())
                    lgt.color = new Color (0, 0, 0);
                
                foreach (Renderer emi in part.FindModelComponents<Renderer>())
                    emi.material.SetColor ("_EmissiveColor", new Color (0, 0, 0, 0));
            }
            else {
                foreach (Light lgt in part.FindModelComponents<Light>())
                    lgt.color = new Color (red, green, blue);
            
                foreach (Renderer emi in part.FindModelComponents<Renderer>())
                    emi.material.SetColor ("_EmissiveColor", new Color (red, green, blue, 1));
            }
        }
        }
    }
