### ISSUE TITLE
Analog inputs via control stick?

### ISSUE THREAD

**Issue by dcrockwell** [KSP-KOS/KOS#1310]
This may be a big stretch, but since I'm building quadcopters in game, it seems like it would be super cool to hook up an XBox controller and feed it's analog inputs into kOS to be used as a PID controller's setpoint.

I'm just throwing this out there because then creating drivable cars, multicopters, helicopters, etc. with controller support would be possible via infernal robotics, etc.

**Comment by TDW89** [comment]
ksp supports a 6 dof device.
It may be possible to use a program to remap the xbox controller to appear to be a 6 dof device and then you can detect `ship:control:pilot...` as your set-points. If you use the rcs translation axies then with rcs off the ship will not be affected by the inputs, or if the steering is locked you can use the rotation axies too.

**Comment by dcrockwell** [comment]
@TDW89 Awesome! This is superb. I think this can be closed :)

**Comment by Dunbaratu** [comment]
Basically if you open the main stock game settings screen (the main menu one you see on the "munscape" opening menu screen, not the one that appears during flight, which is missing most of the settings and is only showing you a subset of them), you can go to the controls tab and map your controller's axes to which KSP thing they are meant to control.  once you do that you can have kOS read KSP's idea of where that control axis is set, as TDW89 describes above.
