### ISSUE TITLE
vessel:UNPACKED not documented

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#1324]
The UNPACKED suffix for vessel doesn't seem to be in the sphinx docs.

**Comment by Dunbaratu** [comment]
This matters because we're presenting this as the solution to the boot order problem.  Wait until ship:unpacked = true.

**Comment by hvacengi** [comment]
Odd, I just opened that source file and I distinctly remember editing that section when I added the suffix.  I must have failed to commit the change, and now it's lost.  I can get that added.
