### ISSUE TITLE
boot script loading fails when not starting on archive.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#1325]
Once again I tried using the boot feature that never works.   I think it's because I'm running without START_ON_ARCHIVE set to true.  I'm using the default of starting on volume 1.  Are any of the people testing booting doing that?

I have this in my archive:  `boot_std_launch.ks`.

The contents of boot_std_launch.ks is this:
```
wait until ship:unpacked.
print "Unpacked. Now loading launch software.".
copy launch.ks from 0.
copy launch_lib.ks from 0.
run launch.
```

Nothing ever happens when I launch, and I get this message in the output_log:
```
kOS: Boot file "boot_std_launch.ks" is missing, skipping boot script
```
Which is false.  It's there in the archive.

It's coming from this line in the mod, CPU.cs, line 116:
```
else if (shared.VolumeMgr.CurrentVolume.GetByName(filename) == null) { SafeHouse.Logger.Log(string.Format("Boot file \"{0}\" is missing, skipping boot script", filename)); }
```
It's looking on CurrentVolume.  CurrentVolume is 1, not archive.  It's present on the archive, but it's not looking there, and never copies it from the archive to the local volume.

**Comment by hvacengi** [comment]
"Starting on the archive" should make it work if the file is not successfully copied, however the file should betting copied to the local hard drive during `InitObjects` on the kOSProcessor class.  Starting on line 302:
```
            // initialize harddisk
            if (HardDisk == null)
            {
                HardDisk = new Harddisk(Mathf.Min(diskSpace, PROCESSOR_HARD_CAP));

                if (!String.IsNullOrEmpty(Tag))
                {
                    HardDisk.Name = Tag;
                }

                // populate it with the boot file, but only if using a new disk and in PRELAUNCH situation:
                if (vessel.situation == Vessel.Situations.PRELAUNCH && bootFile != "None" && !SafeHouse.Config.StartOnArchive)
                {
                    var bootProgramFile = archive.GetByName(bootFile);
                    if (bootProgramFile != null)
                    {
                        // Copy to HardDisk as "boot".
                        var boot = new ProgramFile(bootProgramFile) { Filename = bootFile };
                        HardDisk.Add(boot);
                    }
                }
            }
            shared.VolumeMgr.Add(HardDisk);
```
Do you do anything different to your directory?  It shouldn't be a link issue, my copy uses a symbolic directory link to reference a folder in my DropBox directory.  I would expect that for some reason your instance is having an issue with `archive.GetByName`.  If you copy the file to the local hard drive and then `reboot.` does the boot script execute?

**Comment by Dunbaratu** [comment]
When it has been manually copied and I reboot it does run it.

It is specifically failing to perform the copy on scene load to the launchpad.  If you can't make the failure happen on your installation I could sprinkle some debug writelines into `InitObjects` and look at the log.

For me this problem has been consistent ever since the boot feature has been added.  It has *never* worked, ever.  And I'm not doing anything fancy with my folder setup - It's a plain ordinary vanilla filesystem setup.

I wonder if there's a timing issue where it's possible for `InitObjects` to be running at a time when status is not PRELAUNCH.  If it's run when not PRELAUNCH, there is no other place where the copy would happen instead.

**Comment by hvacengi** [comment]
Do you mean that you're launching by clicking on the launch pad instead of going through the VAB?  I have not tried that specific scenario myself, I've only tried it from the VAB.

It is possible that the InitObjects is being called too early, though it seems like it would be a more widespread issue in that instance.  We call that method from inside `OnStart`.  Do we know if `OnStart occurs before or after `OnLoad`?

**Comment by Dunbaratu** [comment]
It's irrelevant whether I start from the VAB or not.  It's the same either way.

**Comment by Dunbaratu** [comment]
It's because a DLL mismatch caused the enum check to fail.  Basically PRELAUNCH didn't equal PRELAUNCH, because the DLL was using a different int value for the enum from what our code used, due to the DLL mismatch.  It was in my installation only.
