### ISSUE TITLE
Q reading doesn't match kPa

### ISSUE THREAD

**Issue by Gaiiden** [KSP-KOS/KOS#1326]
Here is what I get when I print out `ship:Q` under the latest kOS and FAR in 1.0.5

![untitled](https://cloud.githubusercontent.com/assets/7699577/12004375/3e72f8f6-ab22-11e5-9d80-a0b569ce37f6.png)

The kOS screen refreshes once a second so the value is behind that's not the issue - the issue is what's up with the decimal placing?

**Comment by Dunbaratu** [comment]
I just had a read through the code and `Q` is being returned in units of ATM's not kPa's.  The documentation is basically lying.  I think it *should* be kPa's and the docs are right and the code is wrong.

**Comment by Dunbaratu** [comment]
How many scripts are alive out there that are using `Q` and expecting it to be ATM's?  Because I don't want complaining by users who's scripts broke when we fix this.

**Comment by Dunbaratu** [comment]
Okay after slack discussion, we're keeping it as ATM's and changing the documentation to match.  If you want to get it in kPA, you can multiply it by `constant:AtmToKpa`.

**Comment by Gaiiden** [comment]
Whoops forgot to keep tabs on this while traveling. Sounds good, especially since it's a fix that doesn't need a new code release
