### ISSUE TITLE
Can't add maneuver node after undock

### ISSUE THREAD

**Issue by pellinor0** [KSP-KOS/KOS#1327]
I have two vessels: 
A: the active vessel
B: a space station

My script docks them, and then undocks again. Afterwards, A is the active vessel and has the KOS processor on board, but the following command

add NODE( TIME:SECONDS+30, 0,0,-50 ).

fails with an error "A KSP limitation makes it impossible to access the maneuver nodes of this vessel at this time (perhaps it's not the active vessel?)". 

Maybe after undocking some reference ends up pointing to the wrong vessel? It might be important that the station has higher priority, so the merged vessel was named "B".

**Comment by Dunbaratu** [comment]
Whomever fixes this, check to see if it's being caused by the same underlying problem as #1321

**Comment by hvacengi** [comment]
While testing #1321 I decided to test this out too.  I had a similar situation, larger station which retained focus after undocking, forcing me to "switch" to "A".  Adding the maneuver node did not fail during my testing.  Could you please confirm the following steps to reproduce:
- Vessel "A" is the ship which docks to the station, and performs maneuvers
- Vessel "B" is the space station, and for the purposes of this test it does not perform maneuvers
- Vessel "B" is larger than "A" such that it is the higher priority vessel.
- Dock "A" to "B".  Merged craft is named "B" automatically.
- Wait a short bit.
- Undock "A" from "B", "B" remains in focus.
- Switch focus to "A" using `[` or `]` keys, making it the active vessel.
- Type `add node(time:seconds + 30, 0, 0, -50).` into the terminal and press `Enter`.

I did test this using the latest "develop" build, so there is a chance that we somehow fixed it, but the "node" system doesn't appear to have been modified recently.

The only other thing that I wonder about, is that you did not mention switching vessel focus.  @pellinor0 please let me know if "A" is automatically the focused vessel when you undock.

**Comment by pellinor0** [comment]
I did not switch focus, instead the script calls "control from here" on A's docking port. This makes A end up in focus when undocking the ports. 

Will do a retest later today.

**Comment by pellinor0** [comment]
Seems like I can't get this thing reproduced again. Should have kept that exact version of the scripts and craft files. I touched many codelines in the meantime but the docking/undocking sequence should be exactly as before...

So I'll close this for now and promise better documentation if I see the issue again. Sorry for the inconvenience!

**Comment by hvacengi** [comment]
No need to apologize. Thanks for testing again to try and reproduce, and for reporting back!
