### ISSUE TITLE
Serialization chokes on num/string equivalent keys

### ISSUE THREAD

**Issue by gisikw** [KSP-KOS/KOS#1342]
When lexicons are created, they treat `"0"` and `0` as distinct keys. However, after being written out and returned back, the latter clobbers the former.

```
set l to lexicon().
set l["0"] to "foo".
set l[0] to "bar".
print l:dump.
LEXICON of 2 items:
[0]= foo
[0]= bar
writejson(l, "lex.json").
print readjson("lex.json").
LEXICON of 1 items:
[0]= bar
print readjson("lex.json"):dump.
LEXICON of 1 items:
[0]= bar
```

**Comment by tomekpiotrowski** [comment]
This is expected behavior, JSON does not handle non-sting keys. Lexicon docs specifically mention this: `Please note however that non-string keys will not be properly serialized/deserialized.` Maybe I should be more specific.

**Comment by tomekpiotrowski** [comment]
Ok, I will update the docs and provide a more detailed description of what works and what does not.

**Comment by gisikw** [comment]
Ah. Would it perhaps be appropriate to cast numeric keys to string, however, for consistency? Especially with `dump` no longer showing quotes to distinguish between key types?

Thus changing this behavior:
```
set l to lexicon().
set l["0"] to "foo".
set l[0] to "bar".
print l:dump.
// LEXICON of 2 items:
// [0]= foo
// [0]= bar
```

To this:
```
set l to lexicon().
set l["0"] to "foo".
set l[0] to "bar".
print l:dump.
// LEXICON of 2 items:
// [0]= bar
```

**Comment by gisikw** [comment]
Sorry if I'm making the issue for nothing. I just came across this when I discovered that `dump` removed quotes from the output after yesterday's merges, and figured it was worth checking to see if this broke anything. I didn't think to review any docs updates.

**Comment by tomekpiotrowski** [comment]
That's a valid point. I was thinking about this when implementing serialization. The issue at the time was that JSON does not handle non-string keys, but maybe some other fancy `Formatter` that we add in the future would. Now that I'm thinking about it the chance of that happening is slim and it does create the inconsistency that you've pointed out.

**Comment by gisikw** [comment]
Yeah, honestly, I wouldn't object to removing support for any non-string lex keys. If people really want an Object-to-Object map, they can wrap that in a list/lex structure of their own. Lexes are new enough that it's not likely to break much right now.

**Comment by Dunbaratu** [comment]
Gaaah. no, no, no.  Don't remove support for non-string key lexes.  It's so very useful.

This has GOT to be fixable, and the time to fix it is before we expose serialization to the public.  Once we do expose it, then we start hitting backward compatibility concerns if we change the format of the output files people have already started making so they can't read in the files they already wrote out.

Can't we store lexes as lists of named pairs, like so?
```
(LEXICON header here so we know this is not an actual array object despite looking like one)
"lex_data" : [
  { "key" : 0, "value" : 10 },
  { "key" : "0", "value" : 20 }
]
```
Putting the keys in as terminal data fields like that allows them to be more different kinds of object.  The serialization looks like an array of key/val pairs, and we turn that into the lexicon on re-reading it.

If you are concerned about space, you can just turn it into a flat array of size 2x the array, where even numbered items are the key and odd numbered items are their values:
```
(LEXICON header here so we know this is not an actual array object despite looking like one)
"lex_data" : [
  0, 10, "0", 20
]
```
As long as the deserialization can read that and go "this isn't really an array of 4 things. The header tells me so, but I'll let JSON read it in like an array of 4 things at first, then I'll transform that array into a lex", it seems like it would work and be far more universally generic.

**Comment by Dunbaratu** [comment]
To be honest I hadn't noticed the doc change that said non-string lex keys wouldn't be supported.  I'd have raised this back then if I had.

**Comment by gisikw** [comment]
That solution makes sense to me too :) My concern is just that _if_ `writejson` succeeds, then `readjson` should deep-equal what was persisted. The problem here is that the failure case is silent.

**Comment by Dunbaratu** [comment]
Of the two things above, I kind of prefer the second.  It's compact and simple.  array[0], [2], [4], etc are the keys and array[1], [3], [5], etc are their values.
