### ISSUE TITLE
Can we have something like HASTARGET, as calling TARGET when there isn't one results in a crash

### ISSUE THREAD

**Issue by ElWanderer** [KSP-KOS/KOS#1350]
Similar to the long-standing request (though a quick search didn't find an open issue) to have a way of telling if it is safe to use NEXTNODE. 
Discussion of this on reddit: https://www.reddit.com/r/Kos/comments/3zgtd2/help_how_can_you_tell_if_there_is_a_target_set/

**Comment by hvacengi** [comment]
I will work on getting this pulled together, hopefully before the next update.
