### ISSUE TITLE
Can we have object conversion, eg integer to string?

### ISSUE THREAD

**Issue by benetherington** [KSP-KOS/KOS#1351]
This would be handy for "print to" functions that want to call :length on an integer, and would make dealing with #1342 easier no matter the resolution.

Alternatively/additionally, a suffix that returns the type of object would be handy.

**Comment by hvacengi** [comment]
While there is no direct method right now, you can convert a value to a string simply by adding it to an empty string.  Below is a helper function that I use:
```
function SafePrintAt {
	parameter message, col, row.
	local limit is terminal:width - col - 1.
	set message to "" + message.
	if (message:length > limit) {
		print message:substring(0, limit) at (col, row).
	}
	else {
		print message:padright(limit) at (col, row).
	}
}
```

A type system is in the works, but we needed to get a few things cleaned up under the hood before it could be exposed.  Types won't make the next release but they should be soon, possibly the following release.

**Comment by benetherington** [comment]
Good workaround, thank you!

**Comment by Dunbaratu** [comment]
We now have both string to integer (use an integer in string context and it becomes a string, i.e: ``"val is: " + num``.) and integer to string (``str.ToScalar()``).  I think this should be closed now.
