### ISSUE TITLE
Rescaled text/terminal window

### ISSUE THREAD

**Issue by ozin370** [KSP-KOS/KOS#1356]
I suppose this is a suggestion for much further down the line post KSP 1.1 patch, but I think it would be nice to be able to scale up the font size, or just scale up the whole terminal window itself, making the text easier to read on screenshots, youtube videos and streams. When I record in 1440p+ the font looks pretty small, and 720p playback on youtube is basically unreadable.

**Comment by erendrake** [comment]
What is your channel? i dont know if i have seen your videos!

**Comment by erendrake** [comment]
I think this would be a great feature. like you said it will surely not happen before ksp 1.1 drops

**Comment by ozin370** [comment]
https://www.youtube.com/user/Ozin370/videos

Just some videos from my quadcopter drone stuff. The latest two are in 1440p for reference.

**Comment by hvacengi** [comment]
It looks like we may have the ability to use an actual "font" for the text in Unity 5, in which case this would not be difficult to implement.  I'd be worried about scaling artifacts using the current image based system.  The same change may allow an expanded character set to be used as well.

**Comment by Dunbaratu** [comment]
There's a lot I want to do to the terminal after Unity5.  This is one of the things.  Just so you know, our plans are to first release a "just make it work at all" version of kOS for KSP 1.1, and then the second version after that would be for "actually take advantage of new things".
