### ISSUE TITLE
change request: ship:control:* vs. user inputs

### ISSUE THREAD

**Issue by MrOnak** [KSP-KOS/KOS#137]
I've mentioned this in the forums but I thought I'd add it here as well to keep things in one place for you guys.

When a script uses any of the ship:control:* commands to steer a craft, ALL ship:control: axis are blocked from user input. I.e. when a script uses ship:control:pitch exclusively (like my autopilot) the user is unable to adjust throttle, roll or yaw as well.

Naturally that makes the use of ship:control:* very limited to full-guidance solutions. 

Not knowing the kOS code behind it - or in fact the reason for locking the user out, but I'm sure there is one - I see two ways around this:
- FIFO. Script and user both have equal authority over the controls, inputs are handled by KSP in sequence. This should be rather straight forward to do but TBH I'm not sure how useful this is as user and script would fight over the controls IF they perform inputs on the same axis.
- an explicit permission system. Script commands that can lock authority per axis to either the user or the script, exclusively. Something like "set ship:control:throttle:blocked to true". This would still allow user input for all non-blocked axis (and prevents the script to control it) but gives exclusive access to throttle to the user.

The permission system is much safer in use but requires a more programming for both you and the kOS scripts.

**Comment by erendrake** [comment]
this has been resolved with the new pilot controls. thanks everyone for the discussion :)
