### ISSUE TITLE
Allow LEXICON() to accept an initializer list like LIST(), STACK(), and QUEUE() can.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#1381]
We can do ``set L to list(1,2,3,4).``

We should have a similar ability for lexicons.  Right now we only let people construct empty ones that they then have to fill one item at a time.

Two possible syntaces are:

1 - Flattened list of pairs.  i.e. value0 is the key of value1, value2 is the key of value3, etc.  Like so:

```
set L to LEXICON("a", "ant", "b", "bear", "c", "cat").
```
Resulting in `L["a"] = "ant"`, `L["b"] = "bear"`, and `L["c"] = "cat"`.

2 -  If we added the ability to pass in a list of pairs to populate it like this:
```
set rawlist to LIST().
rawlist.add to LIST("a","ant").
rawlist.add to LIST("b","bear").
rawlist.add to LIST("c","cat").
set L to LEXICON( rawlist ).
```
Then we'd sort of automatically get a way to do that all in one go, but it would be a bit more wordy:
``set L to LEXICON(  list( list("a", "ant"), list("b", "bear"), list("c", "cat"))).``

(I noticed this in passing when I was running through all the constructor functions in Suffixed.cs for an unrelated refactor, but as this is outside the remit of that refactor I'm just recording it in an issue and moving on.)

**Comment by Dunbaratu** [comment]
We could also do a thing halfway between 1 and 2.  Still a flattened list, but it's a list you pass in as an actual ListValue, like so:

Let's call it option 1.5:
```
set L to LEXICON( LIST( "a", "ant", "b", "bear", "c", "cat") ).
```

**Comment by TDW89** [comment]
Not sure if this comes under the same enhancement but expanding it to include `list:add` & `stack / queue:push` might be useful. At the moment
```
list:add(1, 2, 3).
stack:push(4, 5, 6).
queue:push(7, 8, 9).
```
are not possible.
