### ISSUE TITLE
Fix all occurrences of bogus data types in documentation

### ISSUE THREAD

**Issue by tomekpiotrowski** [KSP-KOS/KOS#1412]
Because proper encapsulation types did not exist the docs often use things like `scalar`, `boolean`, `Boolean`, `scalar (metric tons)` to specify the type of a suffix parameter or a suffix return type. Now that we have proper user space types we should point to them.

As @hvacengi has pointed out we will probably want to take care of it after #1408 is done ;)

**Comment by hvacengi** [comment]
I suppose it depends on what we end up with as the type names.  I think this will be related to the discussion in #1408.  But if the decision is that `ScalarValue` reports it's type to the user as `"scalar"`, then those references may (heavy on the *may*) be OK.  Either way, we need to walk it and make sure.    The references should be consistent for sure.

**Comment by Dunbaratu** [comment]
I'm going to examine the possibility of scripting this edit with some clever regex search/replace scripts.

**Comment by hvacengi** [comment]
Closed via #1493
