### ISSUE TITLE
KAL 9000 too early in tech tree

### ISSUE THREAD

**Issue by gisikw** [KSP-KOS/KOS#1430]
At the moment, the KAL 9000 part is under "Precision Engineering" (160-tier), with the KR-2042 b. Since this is the "god" unit, it should probably go in a later tier (the CompoMax is under "Unmanned Tech", 300-tier).

If we truly want this to be an endgame part, "Experimental Electronics" (final 1000-tier) makes the most sense. Otherwise, "Automation" (500-tier) might be appropriate as well.

Personally, my vote would be to throw it in the 1000-tier, since it really is the core to end all cores.

**Comment by hvacengi** [comment]
Closed via #1431
