### ISSUE TITLE
Minor glitch with the lights on the kOS parts

### ISSUE THREAD

**Issue by MrOnak** [KSP-KOS/KOS#144]
The light on the computer core parts starts in the ON state, contrary to the light switch ("U" key) on the ship. That causes the core to always be on when the ships lights are off and the comp being off when the ships light are on.

Not sure if that's intended behaviour.

**Comment by erendrake** [comment]
There is a lot work work i would like to do on that part to give scripters access to the light

**Comment by hvacengi** [comment]
I believe this has been fixed as part of the change to the kOSLightModule (PR #1402)
