### ISSUE TITLE
Add a possibility to serialize/deserialize stuff without using files

### ISSUE THREAD

**Issue by tomekpiotrowski** [KSP-KOS/KOS#1441]
Currently the only way to use serialization is to use `writejson` and `readjson`. It is not possible for users to obtain the json string other than reading the file back using `open(file):readall:string`.

We could add a universal `tojson` suffix to all serializable structures and a method to deserialize stuff directly from a string.

**Comment by Dunbaratu** [comment]
Not a bad idea.

**Comment by luckielordie** [comment]
Anyone mind If I take a stab at this? I'm looking for something fun to do.

**Comment by tomekpiotrowski** [comment]
Sure, go ahead, but I would suggest to wait until #1414 gets merged, because this is the PR that adds suffixes to all structures. After that you could easily add a `TOJSON` suffix to all `SerializableStructure`s.

A quick look at `FunctionWriteJson` and `FunctionReadJson` should be enough to understand how to use `SerializationMgr` (the class that handles serialization and deserialization of structures).

**Comment by luckielordie** [comment]
Cool, I'll keep an eye out and cast an eye over that stuff tonight hopefully.

**Comment by Dunbaratu** [comment]
It may be better to make the new method that returns a string have primary importance and make the existing method that works on a file piggypack its work on top of the string method.  (i.e. have it call the string method, and take the result and dump it to the file, and visa versa).

**Comment by tomekpiotrowski** [comment]
Closing as this was implemented years ago.
