### ISSUE TITLE
Error when logging variable.

### ISSUE THREAD

**Issue by shuttle128** [KSP-KOS/KOS#1453]
Any time I use the LOG command in a script I get the following error:

```
Can't append to file: not enough space or access forbidden
________________________________________________
                 VERBOSE DESCRIPTION
Can't append to file: not enough space or access forbidden
________________________________________________
At tune on 1, line 35
                          LOG logline TO throttle_log.
                                         ^
```
The code snippet in question is from the following portion of script:
```
LOCK logline TO (TIME:SECONDS - start_time)
        + " " + P
        + " " + maxtwr.

UNTIL SHIP:ALTITUDE > 30000 {
    SET dt TO TIME:SECONDS - t0.
    IF dt > 0 {
        SET thrott TO MIN(1,MAX(0,thrott + dthrott)).
        SET t0 TO TIME:SECONDS.
        LOG logline TO throttle_log.
    }
    WAIT 0.001.
}
```
I am running KSP v1.05.1028 with kOS v 0.18.2 and a few other mods installed by CKAN with no conflicts. Computer is Windows 7 64-bit. My saves and GameData folders are hooked into Dropbox and I have installed KSP through Steam to my secondary hard drive.

**Comment by hvacengi** [comment]
If you're trying to write while on the archive and the folder is saved in dropbox, that's probably your issue.  I have the same setup on my computers, and I run into issues with access violations occasionally.  Try the code again turning off drop box (I mean fully exit, don't just pause syncing) and see what happens then.  It is particularly picky if you just created or deleted the file, but can be pretty picky either way.

If turning off dropbox doesn't help, let us know.  It's most likely an issue with directory permissions or file access permissions, but it certainly could be something else.

**Comment by shuttle128** [comment]
It seems that I was not running the script off of the archive. The tutorial I was following ran off of the ship drive then copied the log onto the archive. Running the script from archive and removing the COPY command fixed the issue. Thanks for the quick help.

**Comment by hvacengi** [comment]
My guess is you ran out of disk space on the kOS local drive then.  You could probably fix the issue by increasing the capacity using the tweakables in the VAB, or by selecting another processor part.
