### ISSUE TITLE
SHIP is missing several Orbital properties. (Possible documentation issue)

### ISSUE THREAD

**Issue by surge9000** [KSP-KOS/KOS#1467]
This might go deeper, (as in related to basic object inheritance in the underlying code) or it's just a documentation error, but the following are undefined:
SHIP:HASORBIT
SHIP:HASOBT
SHIP:HASBODY

The following similar values DO work:
SHIP:OBT
SHIP:ORBIT
SHIP:BODY
As SHIP is a Vessel, and therefore also an Orbitable, all of these should work according to the docs.

Tested on kOS versions 0.17.3 (where SHIP:ORBIT did not work either)
and 0.18.2. Note: I doubt it matters, but KSP version was 1.0.4. I don't use 1.0.5 due to a game breaking bug.

**Comment by hvacengi** [comment]
It looks like these suffixes were removed in February of 2015 during the upgrade to suffix logic.  This was literally four days after the suffixes were initially added (both in C# and in the documentation).  I think this was maybe a conflict that got missed in a merge or rebase.  @erendrake and @Dunbaratu were the two authors of involved, and the applicable commits are 34046b4 and cab7c01

**Comment by Dunbaratu** [comment]
It must be that it got lost in the merge.  It probably made a merge conflict and the "wrong" side of the conflict got picked as the side to keep.
