### ISSUE TITLE
PANELS ON affects some things that aren't solar panels

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#1469]
I had a vessel that had radiator panels and a crew ladder, and solar panels on it.

When I do a `PANELS ON.` command, it toggles more than just the panels.  It also extends the radiator panels and the ladder.

**Comment by AlchemistCH** [comment]
In case of radiators it's a good question, if they should be on the same action group with the solar panels or if they deserve a separate one. Both options sound rather reasonable.

... and ladders may deserve a separate action group as well
