### ISSUE TITLE
Quaternion() function documentation error

### ISSUE THREAD

**Issue by jmmerchant** [KSP-KOS/KOS#1473]
The description of the arguments to the Quaternion() function in the [documentation](http://ksp-kos.github.io/KOS_DOC/math/direction.html) is currently this:

> A Direction can also be created out of a Quaternion tuple, indicated with the Q() function, as shown below where x, y, and z are a Vector to rotate around, and rot is how many degrees to rotate: SET myDir TO Q( x, y, z, rot ).

This is incorrect.  What is described in this block of text is an Euler axis angle rotation, also referred to as a simple rotation.  Quaternions are a completely different beast.  One can encode the rotation of a certain angle about an axis in a quaternion, but not like this; see [here](https://en.wikipedia.org/wiki/Rotation_formalisms_in_three_dimensions#Quaternions).

According to [this](http://docs.unity3d.com/462/Documentation/ScriptReference/Quaternion-ctor.html), the arguments to the Unity 4 constructor for Quaternion are the four elements of the quaternion without modification (x, y, z, w); here (x, y, z) is most definitely not the axis and w is definitely not the angle of rotation.  If users expect this to be so, it could cause confusion when results are not as expected.  Please update the documentation for this function accordingly.

**Comment by Dunbaratu** [comment]
True - that documentation is very old, and I'm not even comfortable that the Q() constructor is even present at all, if we can't document it with anything other than just "go read this thing you won't understand unless you already understood it to begin with."
