### ISSUE TITLE
Switch to nearby vessel.

### ISSUE THREAD

**Issue by Kerbalnut** [KSP-KOS/KOS#1476]
When root part is changed on a (long, narrow, wobbly) vessel closer to the center of mass for more stable ascent with cooked flight controls according to [the kOS documentation](https://ksp-kos.github.io/KOS_DOC/commands/flight/cooked.html#advantages-disadvantages) after staging, the focus stays on the dumped stage instead of the payload, for every `STAGE.` operation that is performed further from the vessel's root part. (requiring player to use either `[` or `]` to re-focus on payload)

Using `KUniverse:ACTIVEVESSEL` in this state will only re-focus on the dumped stage because both 'vessels' after separation still have the same name. 
Eg. running `SET KUniverse:ACTIVEVESSEL TO VESSEL().` command while dumped stage is focused does nothing, while if run while payload is focused, focus changes back to the dumped stage.

Changing name of the vessel changes the names on both separated stages within render distance of each other, and same behavior occurs.

Ascent with modified root part crafts like this is stable and completely automated except for having to change focus back to payload before next ignition. Any way to re-create `[` or `]` functionality in kOS?

**Comment by hvacengi** [comment]
You should be able to do this after staging:
```
if kuniverse:activevessel <> core:vessel { kuniverse:forceactivevessel(core:vessel). }
```
You would need to use `forceactivevessel` if the ship is under acceleration or in the atmosphere.  Give that a try and let us know if it suits your purpose.

http://ksp-kos.github.io/KOS_DOC/structures/core.html#attribute:CORE:VESSEL
http://ksp-kos.github.io/KOS_DOC/structures/misc/kuniverse.html#method:KUNIVERSE:FORCEACTIVE

**Comment by Kerbalnut** [comment]
`SET KUniverse:ACTIVEVESSEL TO SHIP. ` and
`SET KUniverse:ACTIVEVESSEL TO CORE:VESSEL. ` both work perfect when out of atmo but

`SET KUniverse:FORCEACTIVE() TO SHIP. `
`SET KUniverse:FORCEACTIVE() TO CORE:VESSEL. `
`SET KUniverse:FORCEACTIVEVESSEL() TO SHIP. `
`SET KUniverse:FORCEACTIVEVESSEL() TO CORE:VESSEL. `
are the only ones I could get to execute without error but even when out of atmo I couldn't get them to work.

Sorry for late reply

**Comment by hvacengi** [comment]
I just found a bug in the documentation, it is incorrectly labeled as `forceactive`, it should be `forcesetactivevessel`.  The correct syntax is apparently `kuniverse:forcesetactivevessel(tgtvessel).`.  I'll be working to update the documentation and to get a more intuitive alias for the command.
