### ISSUE TITLE
No way to tell if TARGET is set.

### ISSUE THREAD

**Issue by surge9000** [KSP-KOS/KOS#1483]
if (defined TARGET) returns 1, even if its not set. Any access to unset TARGET causes script error.

Workaround: You can clobber an already set target, and then expect the user to reset it, but it's not an elegant solution. e.g.:
```
set TARGET to BODY("Sun").
```
and later...
```
if (TARGET <> BODY("Sun")) {
// code that relies on a valid target here
}
```

**Comment by Dunbaratu** [comment]
I'm going to close this as moot because the change to fix this is already in the development branch.  It will appear in the next public release.

https://github.com/KSP-KOS/KOS/pull/1368
