### ISSUE TITLE
edit doc/source/chages.rst to match 0.19.0 changelog

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#1485]
Once every other document PR is merged for 0.19.0, we need a changes.rst edit that contains a heading for each new feature and a link below pointing at the part of the docs where the new thing is.

This is like the changelog, except it doesn't mention bug fixes, or extremely small one-liner changes to fix incorrect docs.  It only mentions things that are new entries in the documentation, that have a place we can point to.  It also allows for a slightly longer sentence describing each thing, rather than a short terse statement as needed by the changelog list.

**Comment by hvacengi** [comment]
Closed via #1493
