### ISSUE TITLE
Future feature idea: letting the user preset global CPU and volume names in the VAB's tweakables.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#150]
Right now you can only name a Volume once the code is running, and to do that you have to start off using an arbitrary numbering system you don't control to reference which Volume you meant.  And it's a numbering system that varies depending on which CPU is doing the running of the code.

If you have 3 CPU's (each with a Volume) on the vessel, then:

CPU A will number volumes this way:

* Volume 1 is CPU A's volume (me).
* Volume 2 is CPU B's volume.
* Volume 3 is CPU C's volume.

CPU B will number volumes this way:

* Volume 1 is CPU B's volume. (me)
* Volume 2 is CPU A's volume.
* Volume 3 is CPU C's volume.

CPU C will number volumes this way:

* Volume 1 is CPU C's volume. (me).
* Volume 2 is CPU A's volume.
* Volume 3 is CPU B's volume.

To make it easier to write multi-CPU and multi-Volume code that can refer to things more globally, would it be possible to let the user pick the volume and CPU identities via tweakables in the VAB?  I realize tweakables don't let you write strings, so you can't give them any arbitrary text labels, but you could give them text labels like "VOL1", "VOL2", VOL3", etc, where the number part of the string 1,2,3 is the value of the selectable tweakable slider widget.

**Comment by erendrake** [comment]
the only part of this that isnt in now would be aliasing the volume that comes in the kOSProcessor to its kosTag name. that seems pretty reasonable :)

**Comment by abarbe-** [comment]
Think this is implemented now, according to https://ksp-kos.github.io/KOS_DOC/changes.html#volumes-and-processors-integration

**Comment by hvacengi** [comment]
Closed by #1195
