### ISSUE TITLE
Setting number fields is broken with new encapsulation

### ISSUE THREAD

**Issue by hvacengi** [KSP-KOS/KOS#1503]
With our new encapsulation, setting a KSPField of type `float` is broken.  I apparently have the `ToSingle` part of the `IConvertible` implementation throw an exception instead of creating a float.  I will submit a PR shortly to include with tonight's release.

**Comment by Dunbaratu** [comment]
Good catch.  I guess this also means we need to figure out some better test scripts.  Things like PartModules can't be tested in kOS.Safe but we should still think of a test craft with a few part modules on it (and some IR parts on it) and a script that does nothing more than prove they're working by turning things on and off via partmodule interfaces (lights, moving a big lever arm, etc.).

**Comment by hvacengi** [comment]
That's actually how I caught it.  I decided my Duna script should test the color changing effects of the new `kOSLightModule`, only to be greeted with an error mentioning a type that I thought we had hidden.

It's a one line fix, assuming that my test works correctly.
