### ISSUE TITLE
(bug) setnode results in deltav: V(NaN,NaN,NaN)

### ISSUE THREAD

**Issue by baloan** [KSP-KOS/KOS#151]
KSP 0.23.5 with kOS 0.12p1
When running a mission I encountered the issue mentioned in the title. A subsequent manual call to ```aponode(15000).``` creates the node without issue. Enclosed find a screenshot:
![setnode-nan](https://cloud.githubusercontent.com/assets/651799/3332392/e837a9a4-f7e6-11e3-9d6d-c9daa3af9e98.PNG)

How to reproduce:
1. load scriptset, craft and savegame file from http://ud.baldev.de/ksp/kos/issue-151/.
a)  .txt scripts to ```Plugins/PluginData/Archive```
b)  .sfs files to ```saves/default```
c)  .craft files to ```saves/default/Ships/VAB```
2. start KSP, resume default
3. select Tracking Station.
4. select vessel "Landed at Minmus"
5. Press "9" to open kOS terminal, then
```
run prep.
run kamc4.
```

6. watch and enjoy. After leaving the Minmus SOI the script calls ```aponode(15000)``` for a correction burn. This is where the setnode fails.

I've just tried to reproduce after a KSP restart and it worked this time. Maybe it is only a problem when the whole mission runs in one piece (including getting to Minmus). The whole mission can be started using the kamc3 script.
Recording available http://youtu.be/8uRO1GsPrGM. Issue happens at 20:40.

**Comment by erendrake** [comment]
@baloan we are running up on 0.17 release and i want to look at this issue. would you mind seeing if it is still an issue?

**Comment by Dunbaratu** [comment]
I'd like to classify this as "waaaay to old, and too hard to reproduce, wonfix".

If the OP can't narrow it down to a more quick way to trigger the problem, It's too time consuming to try to address it.  and besides, it refers to a version prior to 0.17.

**Comment by hvacengi** [comment]
Is there a chance that the issue is that the node didn't get added for some reason?  I want to say that I remember seeing a comment about that somewhere else (though a search for NaN on github issues doesn't show anything).

**Comment by erendrake** [comment]
@baloan Thank you very much for your bug report. i am sorry that we were unable to fix your problem. If you run into this again in a repeatable fashion please let us know
