### ISSUE TITLE
Steering doesn't try to steer for small control values

### ISSUE THREAD

**Issue by hvacengi** [KSP-KOS/KOS#1512]
The EPSILON value on SteeringManager prevents it from actuating controls for values smaller than 0.0001.  In some instances, this is not enough to properly control the roll.  I will be lowering the value of EPSILON to 1e-16, which has worked in these conditions in my tests.

**Comment by Dunbaratu** [comment]
Doubles only have precision up to 15 and a half-ish signficant decimal places.  (52 binary places).
So I'm not sure what the point is of even *having* an epsilon cutoff at all if it's going to be that small.

**Comment by Dunbaratu** [comment]
Well, I suppose you can still *have* smaller numbers than 1e-16 - they just stop being precise at that point.

**Comment by hvacengi** [comment]
They continue to be precise.  You still get 15 significant digits, it's just that they are to a power.  So while 1e-16 has little precision when compared to the number 1, it is actually more precise when compared to the number 0.  I think the smallest double greater than zero is 2e−1074, which leaves us a very large number of values still smaller than 1e-16.  I can remove it entirely, but I think that we will want to tune it further with my future revisions to steering.

**Comment by Dunbaratu** [comment]
True enough.  Okay let's leave it in the logic just in case we want to change the number later.   I suspect that even if values that small can be stored near zero, they're still the result of math performed on larger numbers so the calculation is limited by the precision of those bigger starting numbers that were input into the formula.)
