### ISSUE TITLE
kOSProcessor Action: Toggle Power, TRUE/FALSE not working as expected

### ISSUE THREAD

**Issue by troyfawkes** [KSP-KOS/KOS#1514]
Hey guys,

Currently there's no way (that I can see) to figure out if a CPU has its power on or off, or to select whether you want it on or off. You just get the ability to toggle it, which means you need a completely different method of tracking whether power is on or off.

kOSProcessor provides these fields, actions and events that are relevant:

- kos average power: no difference between powered on and powered off, which is probably a bug anyway. If this value was accurate (0 for powered off, >0 for powered on), I could live with it.
- (event) toggle power: doesn't say if it's toggling on or off. The format is DOEVENT("toggle power")
- (action) toggle power: doesn't say if it's toggling on or off. The format is DOACTION("toggle power", true/false). Right now it doesn't matter if you put true or false, it just toggles the power.

The ideal solution is to get DOACTION("toggle power",true) to turn the power on, and DOACTION("toggle power",false) to turn the power off (which I think was intended).

**Comment by TDW89** [comment]
@troyfawkes Is [this](http://ksp-kos.github.io/KOS_DOC/structures/vessels/kosprocessor.html) what you are after?
Specifically the `:MODE`, `:ACTIVATE` and `:DEACTIVATE`suffixes

**Comment by troyfawkes** [comment]
Ah, yeah that's it. Sorry I didn't realize it wasn't equivalent to other modules. That'll do the trick!
