### ISSUE TITLE
v0.19.2 release edits.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#1529]
- [x] CHANGELOG.md
- [x] doc/source/changes.rst
- [ ] version numbers in:
  - [x] doc/source/conf.py
  - [x] Resources/GameData/kOS/kOS.version
  - [x] src/kOS.Safe.Test/Properties/AssemblyInfo.cs
  - [x] src/kOS.Safe/Properties/AssemblyInfo.cs
  - [x] src/kOS/Properties/AssemblyInfo.cs

**Comment by hvacengi** [comment]
Now why didn't I think of an actual task list for this when I did the release?
