### ISSUE TITLE
"Deploying command" message doesn't obey terminal height setting.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#1531]
This may have been this way for a long time for all I know.  When you perform an interactive command at the terminal window, and RemoteTech is installed, you get a message at the bottom like so:

```
--------------------------------------------------
Deploying command.                       0:01:12
```

However, this message  doesn't actually appear at the bottom if you've resized your terminal to something bigger than the default.  Instead it appears in the same hardcoded position regardless of terminal height, as shown in this screen capture:

![screenshot114](https://cloud.githubusercontent.com/assets/5216848/13616305/f77c19c6-e53e-11e5-9504-02bcf33d5109.png)

**Comment by hvacengi** [comment]
While we're at it, we should review our error messages and the like.  I believe the verbose message horizontal lines don't properly respect the width either (even though the text message flows to the full width).  Maybe we should create some internal alignment helpers?

**Comment by Dunbaratu** [comment]
I'm thinking I'd actually rather the delay timer happened wherever the terminal happens to be when the command happens, so you see a log of the delays in the scrollback buffer:
```
print "hello".
<Signal Delay 1:31 ||||||||||||||||||||||||||||||||||||||||| 0:00>
hello
print ship:liquidfuel.
<Signal Delay 1:31 ||||||||||||||||||||||||||||||||||||||||| 0:00>
83
print eta:periapsis.
<Signal Delay 1:32 ||||||||||||||||||||||||||||||||||||||||| 0:00>
391
```

**Comment by hvacengi** [comment]
This issue was duplicated in #1860 and fixed (in a different way than mentioned here) in #2076.  Closing the issue accordingly.
