### ISSUE TITLE
IR part control of other vessels.

### ISSUE THREAD

**Issue by TDW89** [KSP-KOS/KOS#1540]
If you store the `IRServo` structure while it is part of your vessel (haven't found a way of accessing it when it's not yet), then you can continue to control it after undocking / decoupling. despite the core and the IR part now being on separate vessels.

**Comment by ZiwKerman** [comment]
Is it on 0.21.4 version of IR or you use the pre-release 0.21.5 (from here https://github.com/MagicSmokeIndustries/InfernalRobotics/releases/tag/0.21.5-pre)?

**Comment by TDW89** [comment]
It was on 0.21.4 but i have just tried it with 0.21.5 and it still lets you control it then too.

**Comment by ZiwKerman** [comment]
If you save a pointer to PartModule instead of the Servo doesn't it allow you do the same?

**Comment by TDW89** [comment]
Nope if you save a partmodule belonging to another vessel (or get it by querying that vessels partmodules after separating) you can get info from it but you cant set, do actions or do events.

**Comment by hvacengi** [comment]
The applicable part of the code I added was:
```
        public void ThrowIfNotCPUVessel()
        {
            if (this.Part.vessel.id != shared.Vessel.id)
                throw new KOSWrongCPUVesselException();
        }
```
I haven't looked into how we handle the IR api at all, but so long as the servo still has a handle to it's part, we should be able to use the same technique.  If IR holds a handle to the kOS `PartValue`, it can execute this method directly.
