### ISSUE TITLE
Add an eta:transition like variable which takes manouvre-nodes in account

### ISSUE THREAD

**Issue by riemervdzee** [KSP-KOS/KOS#1546]
When I set a manouvre node which will put the vessel on an escape orbit, I am not able to get the ETA of the transition via kOS (while able seeing it on the map overview). Perhaps we can add an ETA:transition which takes this in account? Another option would perhaps be to add this information to the Orbit structure, besides nextpatch something like nextpatchETA.

I'm currently familiarizing with kOS codebase and perhaps can help implementing it if someone tells what is the preferred API point.

**Comment by riemervdzee** [comment]
Rationale behind the request:

All orbitable's in KSP are reduced to a 2-body problem. Therefore most common equations don't apply any more and it becomes more important to know under which SOI a vessel is under at a given flight-plan to make more accurate adjustments.
At the moment I am trying to write a ks script which creates a manoeuvre point from the Mun to Kerbin where I wish to have the most efficient burn possible with a given periapsis around Kerbin. The current calculations require this SOI ETA.

**Comment by dewiniaid** [comment]
Worth noting that -- as a workaround until 1.0.0 -- you can get a maneuver node's orbit and solve this by calculating where in the orbit the altitude equals the body's SOI radius.
