### ISSUE TITLE
Integer overflow

### ISSUE THREAD

**Issue by pellinor0** [KSP-KOS/KOS#1553]
in kOS 0.19.2 I'm getting the following multiplication overflow that did not happen in 0.18.x: 
```
print 60000 * 60000.
-694967296
print 60000.0 * 60000.0.
-694967296
print 60000 * 60000.1.
3600006000
```
Obviously kOS decides to treat both values as integers and does not check if the result fits in the type. By changing one value I can force it to do the whole calculation with float values, and get the correct result.

**Comment by Dunbaratu** [comment]
Actually I suspect the reason for the difference is that in the last example the number ends in .1, rather than .0.  It got made into an integer when it was a round number.

At any rate it should be fixed because numbers that large can happen due to how often "radius squared" comes up in orbital formulas.

**Comment by pellinor0** [comment]
Yes, that's what I meant by forcing floats. And you are totally right on the formula that broke:
`local g is Body:Mu/(Body:Radius*Body:Radius).`

**Comment by johnwhall** [comment]
Is there any workaround that doesn't require modifying every arithmetic operation in our .ks files?

**Comment by hvacengi** [comment]
I'm working on an optimization to scalar math anyways.  I'll check the impact of doing all math as floating point math and see if it's a major performance hit.  I suspect that detecting times where floating point math will be as costly as doing the floating point math itself.  In some old tests, it didn't look like floating point math was a big deal.

**Comment by Dunbaratu** [comment]
@pellinor0 : as a temporary workaround until a release with the fix of this comes out, if you actually use the expoentiation operator instead of multiplication, it's implemented to always use doubles for that, and it should avoid the problem.

i.e. doing `r^2` instead of `r * r`.
