### ISSUE TITLE
Optional Telnet Server for  KoS Terminal

### ISSUE THREAD

**Issue by IronGremlin** [KSP-KOS/KOS#157]
It would be awesome to telnet into a KoS terminal from another computer over your network.

The 'killer application' of this feature would be for using KoS in conjunction with KSP 'LARP' set-ups, see also the mod "Go At Throttle Up."

I propose allowing the pilot to flag a particular part as 'active' via a right-click context menu option (ideally this should be 'action group'-able) as a solution to potential 'multiple CPUs one vessel' conflicts - This also fits really nicely with the GATU style game play, where use of KoS  scripts would require two way communication between mission control and the pilot.

Ideally said telnet server should be configurable via plain text files, allowing user/pass authentication, port number specification, and the ability to outright disable the telnet server altogether. Also, perhaps obviously, the server should default to 'inactive' on any part until the player activates it.

**Comment by Dunbaratu** [comment]
I've been working on this for 2 weeks and realized just now that I forgot to assign it to myself.

**Comment by erendrake** [comment]
@Dunbaratu you also forgot to close it now that you are done :)
