### ISSUE TITLE
[KSP1.1] Cannot stage in mapview

### ISSUE THREAD

**Issue by hvacengi** [KSP-KOS/KOS#1575]
This seems to be a new limitation from KSP itself.  If you attempt to stage from inside of the map view, the KSP function that manages the `stage:ready` state will fail to complete, and you will be unable to stage either manually with the spacebar or from the script using `stage`.  I need to look for the proper channel to report this to squad, as the official bug tracker claims that we shouldn't report mod bugs.

**Comment by Dunbaratu** [comment]
Out of curiosity, if you temporarily remove the ready check, will it let you stage if you unconditionally try without checking?  That would narrow down the problem to only being with the check and not the staging operation itself.

**Comment by hvacengi** [comment]
@erendrake tried that the other night and it just played the audio click.

The KSP Staging logic internally checks `StageManager.CanSeparate` and will not stage if it is false.  In fact, if you watch the little stage LED in the lower left hand corner, you'll see it continually blinking a code because the "stage cool down" loop never finishes iterating.  The only time that `StageManager.CanSeparate` is set to true is at the end of the cool down loop.

**Comment by Dunbaratu** [comment]
Well if squad refuses to fix it because autopilots are a mod-only feature, I suppose we could force the game back into flight camera view, then do the stage, then move back to map view.

**Comment by hvacengi** [comment]
Or we can simply throw an error telling the user that they can only stage on flight view.  I'd rather not do either of those two options.

I'm in the middle of making a bug report to squad, and Chris is gonna see if he can move it up the depth chart.

**Comment by hvacengi** [comment]
Today I was able to test this feature on the most recent Squad build (1196) and staging appears to be fixed.  You can see the bug here: http://bugs.kerbalspaceprogram.com/issues/7916
