### ISSUE TITLE
[KSP1.1] Clicking focus into GUI terminal causes map view to start rotating the camera.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#1579]
KSP 1.1 looks like it has some kind of "screen saver" or some such mode on the map view, in which if you click the focus outside the main game window into something else (say a browser, or text editor), then KSP's map mode camera will start to slowly do a 360 degree cinematic sweep rotation around your vessel icon.

The bug is that this is also happening when switching focus into the *in-game* KOS GUI terminal.  This makes it very hard to look at something on the map view while typing a command, as the act of trying to type the command will make the map view start rotating.

I saw this happen in Windows, playing in Windowed mode (not fullscreen).  I do not know if it would also happen in fullscreen.

**Comment by hvacengi** [comment]
The only way that I can replicate this is by using timewarp while in mapview.  If using timewarp, the camera spins with the ship's rotation about the body (causing all stars to rotate in the camera's filed of vision).  When not in timewarp, I do not see any difference in the rotation.

This camera behavior for timewarp/mapview existed in KSPv1.0.5 for sure, possibly in other previous versions as well.

**Comment by hvacengi** [comment]
Interesting, I had left mapview up with timewarp disabled while I typed that response, when I went back to KSP and de-focused the terminal the ship "jumped".  It looks like it is not actually dependent on timewarp, it's just that timewarp made it obvious.

Are you seeing the rotation without timewarp @Dunbaratu?

**Comment by hvacengi** [comment]
Just replicated it in 1.1 by engaging timewarp and then opening KSPedia.  It must be tied to the window management.

**Comment by Dunbaratu** [comment]
Maybe I had timewarp on and didn't notice?
I'll try it again later today and see.

**Comment by Dunbaratu** [comment]
Confirmed that it only happens in time-warp, not in 1x mode.  I must not have noticed before.
Although, I now think it's a bug in Stock rather than a screen saver of some sort.  The reason being that it changes depending on how MUCH time warp you have.  If you're at 100x time warp, you see the rotation.  If you're at 5x time warp, the rotation is very very slow and you have to look carefully to see it.  It seems the rotation of the view is tied to how fast the ship position in its orbit is changing, which implies it's a bug about how the camera updates, rather than a deliberate screen saver feature.

At any rate, I'll close this issue as not a real problem.

**Comment by Dunbaratu** [comment]
Tagged as "won't fix" because it's entirely SQUAD's fault and we are powerless to  stop it.

**Comment by hvacengi** [comment]
You should submit a bug on squad's bug tracker.  It should be able to be taken seriously since it can be reproduced in stock using the KSPedia window.
