### ISSUE TITLE
Documentation errors/suggestions

### ISSUE THREAD

**Issue by Gaiiden** [KSP-KOS/KOS#1586]
404 error
http://ksp-kos.github.io/KOS_DOC/general/CPU_hardware.html#FROZEN
for the link to frozen update nature of the kOS computer when reading TIME in this section:
http://ksp-kos.github.io/KOS_DOC/bindings.html#time-structure

**Comment by Gaiiden** [comment]
Spelling error (actually this is pretty funny :p)
https://ksp-kos.github.io/KOS_DOC/language/syntax.html#general-rules

Under Identifiers being similar:
>My_Variable  my_varible  MY_VARAIBLE

**Comment by Gaiiden** [comment]
https://ksp-kos.github.io/KOS_DOC/general/career_limits.html#the-rules-being-enforced
Formatting for the example code at bottom of the section

**Comment by Gaiiden** [comment]
I think a paragraph about nesting triggers should be included: http://www.reddit.com/r/Kos/comments/3znxg7/first_orbital_launch_script/cyo5pqk

**Comment by Gaiiden** [comment]
https://ksp-kos.github.io/KOS_DOC/language/user_functions.html#declare-function
In the similar examples, throw a period at the end of one

**Comment by Gaiiden** [comment]
Should be noted in 
https://ksp-kos.github.io/KOS_DOC/math/basic.html
That there's also the arithmetic operator e? Or us that a different e?
 https://ksp-kos.github.io/KOS_DOC/language/syntax.html#general-rules

**Comment by hvacengi** [comment]
>I think a paragraph about nesting triggers should be included:
We already have an entire section discussing nested triggers:
http://ksp-kos.github.io/KOS_DOC/tutorials/designpatterns.html#minimize-trigger-conditions

**Comment by Gaiiden** [comment]
ah, well then a link to that then I think would be appropriate

**Comment by Gaiiden** [comment]
the section for EDIT makes no mention of the fact that if you try to edit a file that isn't there kOS will create it for you on the current volume, and that if you use the command `EDIT test.` then it will create a file called "edit" not "edit.ks"
http://ksp-kos.github.io/KOS_DOC/commands/files.html#edit-program

**Comment by Gaiiden** [comment]
example for the http://ksp-kos.github.io/KOS_DOC/structures/collections/lexicon.html#attribute:LEXICON:DUMP is formatted wrong

**Comment by Gaiiden** [comment]
https://ksp-kos.github.io/KOS_DOC/structures/vessels/node.html is missing HASNODE

**Comment by hvacengi** [comment]
http://ksp-kos.github.io/KOS_DOC/structures/orbits/orbit.html#attribute:ORBIT:VELOCITY

`orbit:velocity` is listed as a vector when it is actually `OrbitableVelocity`

(Adding here, cause I don't want to make a new issue)

**Comment by GER-Space** [comment]
http://ksp-kos.github.io/KOS_DOC/structures/collections/list.html

:LENGTH is shown in the example, but not in the structure overview.

**Comment by GER-Space** [comment]
http://ksp-kos.github.io/KOS_DOC/addons/OrbitalScience.html

in the first example there is a suffix :isrerunnable used. right is :rerunnable

**Comment by hvacengi** [comment]
Length is a suffix of `Enumerable`, so you have to click the link in "All suffixes of Enumerable"

**Comment by GER-Space** [comment]
oh, sorry. Then I must have been really tired, when I checked last time :-(
