### ISSUE TITLE
In-game program editor ignores keys 'E','S', and 'R' until certain click sequence

### ISSUE THREAD

**Issue by tjayh913** [KSP-KOS/KOS#1593]
KSP version: v1.0.5.0
kOS version: 0.19.3
Operation System: Ubuntu 14.04

Replication:
(0.1. Started KSP
0.2. Started a new sandbox mode
0.3. Launched Mk1 command pod with KAL9000 attached
The above steps appear unnecessary to replicate.
1. Open the in-game terminal window for KAL9000
2. Run "edit test."
3. Click on the text part of editor to edit.
4. Attempt to type "ersqERSQ" (chose q as a random non-bugged letter).
BUG: Only "qQ" appears on screen.
5. Double click on ground outside any windows.
6. Click back to text input.
7. Attempt typing those characters again.
Now the box should work as expected until the editor is reopened, at which point the clicking solution almost always restores it.

**Comment by tomekpiotrowski** [comment]
This is a known issue in KSP < 1.1, see #1071. AFAIK it should be gone in KSP 1.1, but I haven't tested it myself.
