### ISSUE TITLE
ANGULARVEL and ANGULARMOMENTUM are wrong

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#161]
These Suffixes on Vessel and on Body:

:ANGULARVEL
:ANGULARMOMENTUM

Are both wrong.  They are being returned as Directions, rather than as the data types they should be.

ANGULARVEL should be a vector: the direction tells you the axis of rotation and the magnitude tells you the rotational speed.  When just a Direction is returned it loses the speed information.

ANGULARMOMENTUM should be a scalar or a vector, but definitely not a Direction.

**Comment by erendrake** [comment]
@Dunbaratu i think this is done?

**Comment by Dunbaratu** [comment]
done
