### ISSUE TITLE
Terminal font scale suggestion

### ISSUE THREAD

**Issue by ozin370** [KSP-KOS/KOS#1619]
I think it would be great if it was possible to scale the terminal's font size through the program running on it (similar to how you can set it's dimensions currently).

**Comment by hvacengi** [comment]
I think I'm confused, are you looking for a single parameter to change the font's scale or do you want the ability to change the font scale for only a section of text?

**Comment by hvacengi** [comment]
I'm going to reference the documentation for setting character width and height here: http://ksp-kos.github.io/KOS_DOC/structures/misc/terminal.html#attribute:TERMINAL:CHARWIDTH and close the issue.  If you're looking for something more than what's supported currently, feel free to re-open and clarify.
