### ISSUE TITLE
KOS only accepts scripts encoded as ANSI and UNIX line edning

### ISSUE THREAD

**Issue by adamkoncz** [KSP-KOS/KOS#1627]
Currently when I try to copy a script to the vessel I get EOF exceptions unless the encoding is ANSI and line endings are set to UNIX.

**Comment by hvacengi** [comment]
Can you please give us some additional information?  We'll need the output_log.txt file to track down the error itself, and a copy of a failing script to test.  Even though we can find it in the log file, it might also be good to tell us what operating system you use, what version of KSP you have, and what version of kOS you are using.

I just looked at my own scripts, and they run without issues with UTF-8 encoding and a mixture of unix (`\n`) and Windows (`\r\n`) line endings.  But we did make a change to how volumes are handled in a recent release, so it it certainly possible that something got broken for a fringe case.

**Comment by adamkoncz** [comment]
Seems the same exact script is working now. KSP got updated to 1.1.1 last night maybe that fixed it. 
I guess you can close this now.
Anyway thank you for the quick response.

**Comment by hvacengi** [comment]
Thanks for the bug report, even if it got closed.  I'm not sure how KSP 1.1.1 could have much of an effect for this, but I'm glad it's working for you now.
