### ISSUE TITLE
Unable to set target via kOS.

### ISSUE THREAD

**Issue by VFB1210** [KSP-KOS/KOS#1634]
When trying to set a target using kOS, using `set target to "vesselname"`, no target can be set, and a prompt from KSP (not kOS) is displayed in the upper center of the screen reading "Target selection locked." Targets can be set normally in KSP, and once set by hand, kOS functions normally.

Example, using a stock Velociteze with a KAL9000 unit, trying to target a probe titled "KSC Runway 09" using `set target to "KSC Runway 09"` resulted in the "Target selection locked" message. However, manually selecting "KSC Runway 09" as the target, and then using `print target` correctly resulted in SHIP("KSC Runway 09"). Additionally, once the target is set by hand, all properties of the target can be accessed by kOS; the issue appears to lie solely with setting the target within kOS itself.

**Comment by hvacengi** [comment]
I looked into it briefly, it looks like KSP is internally looking for an input lock, and then displays the "Target selection locked." message if it is locked.  But according to the debug menu, there is no lock in effect, so I'm confused how the message is in effect.  I'll continue to dig in to it.

**Comment by VFB1210** [comment]
I made a short video detailing the bug, just in case it would be any help. (Though you seem to have recreated the bug without issue.) [Link.](https://youtu.be/f-gwerJKLnc)

**Comment by hvacengi** [comment]
Found the root of the issue.  It is indeed that setting the target is now subject to input locks.  It appears that the big issue is that our terminal window locks out "all" input.  So we just have to make sure we don't lock out the "target" input.  The down side is that we don't have any control over who else locks the "target" input, so I'm seeing potential for a number of emails/IRC messages/forum posts to ask other modders to exclude the "target" input with their own locks.
