### ISSUE TITLE
Verbose description dividers don't line up

### ISSUE THREAD

**Issue by hvacengi** [KSP-KOS/KOS#1638]
Using the default terminal dimensions, the horizontal line dividers don't align properly for verbose errors.  It also looks like there are some new line characters missing.  A screenshot is located at the bottom of this post.

Maybe we should consider creating a helper class that is terminal aware and dynamically pads lines with the correct characters.  Or maybe there is a unicode character that represents a horizontal line that fills the line?  I seem to recall there being "reserved" characters that can be used for application specific functions, perhaps we could use that here.

![verbose description](https://cloud.githubusercontent.com/assets/2975036/15045783/7aea5d3e-12aa-11e6-873a-abeb862dc42a.png)

**Comment by Dunbaratu** [comment]
The actual error is the lack of a line break.

This:
```
Undefined Nariable Name 'tset'. _______________________________
```
Is supposed to have drawn the underscores on the next line like so:
```
Undefined Nariable Name 'tset'. 
_______________________________
```

**Comment by dewiniaid** [comment]
Could this be related to the fact that PRINT CHAR(13) (or 9, or 10) doesn't output the corresponding control codes either?

**Comment by hvacengi** [comment]
No, there was no new line character being added to the message text (as fixed in the linked pull request).  Attempts to print `\r` and `\n` on their own should always result in a single new line because the screen buffer trims these characters from the end of the string to print.  (I think that `print "".` results in a new line, that's what kOS ends up seeing as the string).  The inability to print a horizontal tab is because kOS simply does not display invisible characters and does not support the concept of "tab".

**Comment by dewiniaid** [comment]
In my experience (IIRC, I'm at work and can't test), `PRINT "Line 1" +
CHAR(13) + "Line 2".` (or similar) does not yield a newline -- though it is
present if written to a file via other means.  But it's an unrelated issue,
so should probably have its own ticket.

**Comment by hvacengi** [comment]
I know from personal experience that:
```
print "Line 1
Line2".
```
with the new line in the original string would in fact print a new line in the middle.  `char(13)` is `\r`, which is discarded as unprintable.  Using `char(10)` should provide `\n` instead, which will give you a new line.  Because of the multiple operating systems that kOS spans, we ignore `\r` and only handle `\n` (windows line endings are `\r\n` while unix is just `\n`)
