### ISSUE TITLE
clarification: ship:prograde:vector and the like

### ISSUE THREAD

**Issue by ghost** [KSP-KOS/KOS#164]
I'm quite confused about these vectors:

```
ship:prograde:vector
ship:retrograde:vector
ship:facing:vector
```

All of them return V(0, 0, 0) no matter where in orbit I am and no matter what the "parent" property - an R() - actually is. Is that on purpose? If so, is there an intuitive way to make these vectors usable with VecDraw()?

I understand ship to be an instance of VESSEL, that's correct right? I keep bumping into "oh yeah, right" moments because many of VESSELs properties are directions from "active vessel" to VESSEL, which in the case of SHIP doesn't make sense. (bearing, heading, ...)

**Comment by kjl2875** [comment]
It can help you.
[LINK](https://www.reddit.com/r/Kos/comments/4mkqn9/vector_heading/)
