### ISSUE TITLE
ship:orbit:meananomalyatepoch is always wrong

### ISSUE THREAD

**Issue by zentarul** [KSP-KOS/KOS#1641]
I was testing some scripts that stopped working since I switched to 1.1 and discovered that the reported mean anomaly at epoch, which is supposed to be the current mean anomaly, is always wrong. It can easily be tested with by printing it repeatadly and observing that it goes around 360 in less than a minute.

**Comment by hvacengi** [comment]
Hm, if you look at this line: https://github.com/KSP-KOS/KOS/blob/develop/src/kOS/Suffixed/OrbitInfo.cs#L50 you'll see that we are converting from radians to degrees... twice!  Taking out the extra conversion seems to have fixed the problem.

I was going to make a comment about "there's no guarantee that the epoch is the current time" but looking over how KSP handles it, it looks like it almost always is guaranteed now.  The only time it isn't, is when landed or splashed with timewarp enabled.  But there is always a chance that in the future KSP will change how this is calculated.
