### ISSUE TITLE
Feature request: Mission control CPU

### ISSUE THREAD

**Issue by dewiniaid** [KSP-KOS/KOS#1646]
(Supporting #1645, though it might have other uses)

Would it be possible to have a permanent "Mission Control" CPU?  It would have no volume of its own (runs off the archive), as well as no "ship", " body", etc. parameters.  (Alternatively, ship is a virtual single part vessel located at KSC).

This CPU could react to events such as scene changes, loading a quicksave, or a telnet client being connected/disconnected.  Depending on how it is implemented, it might also serve as an alternative to boot.ks -- rather than a probe automatically executing a script to download firmware, mission control uploads a script to the probe.

**Comment by tomekpiotrowski** [comment]
This is a good idea and was already proposed here: #1366 :)
