### ISSUE TITLE
obt:meananomalyatepoch is unusable without a way to get the orbit's epoch.

### ISSUE THREAD

**Issue by dewiniaid** [KSP-KOS/KOS#1665]
I originally had assumed that `orb:meananomalyatepoch` is based on what the mean anomaly was at time=0.  However, some testing quickly revealed that to be untrue and it seemed to be based on the current time instead.

It turns out that neither of these are true:
- Outside of warp, it's (at least very close) to the mean anomaly at the current time.  (Presumably because this is the epoch time).
- On rails, it seems to be the time that warp was entered/the vessel was put on rails.

This makes sense, since this is precisely the value that'd be needed in a save; mean anomaly corresponds to MNA in savegames but there's also an EPH ("Epoch") parameter.

That said, there doesn't appear to be any way to get the current epoch that meananomalyatepoch is referring to which renders the suffix unreliable at best, useless at worst.

_current_ mean anomaly thus requires

```
degrees = 180/pi
eccentric_anomaly = arccos((ecc+cos(trueanomaly))/(1+ecc*cos(trueanomaly)))
mean_anomaly = degrees * (eccentric_anomaly/degrees - ecc*sin(eccentric_anomaly))
```

**Comment by hvacengi** [comment]
Honestly, we had previously made a conscious decision to leave mean anomaly as an exercise for the user.  At the time, we assumed that the epoch did not move as much as it appears to.  We have discussed adding an epoch suffix on the orbit structure numerous times, it simply has not been very high on the priority list.  It probably should get bumped though, as without a definition for epoch you are correct the value of `meananomalyatepoch` is useless.

**Comment by Dunbaratu** [comment]
handled by PR #2047
