### ISSUE TITLE
kOS skips a second 'STAGE' command

### ISSUE THREAD

**Issue by Euphemios** [KSP-KOS/KOS#1674]
For some reason the second stage command in this code is skipped. I believe it to be a bug.
        
      `  NOTIFY("Launching"). 
	     STAGE. 
	     WAIT 0.5. PRINT "Stage: " + STAGE:NUMBER AT(0,13).
	     NOTIFY("Releasing launch clamps"). 
	     STAGE. PRINT "Stage: " + STAGE:NUMBER AT(0, 14).
	     SET launched TO TRUE.`

**Comment by hvacengi** [comment]
This is not a bug with kOS but rather a limitation of KSP itself.  If you want to stage in succession like that, you should use
```
wait until stage:ready.
```
instead of waiting for a set period of time.

I was sure it was documented somewhere, but a quick search didn't turn it up.  I'll look closer tonight.

**Comment by Euphemios** [comment]
Ah, thanks. Its mostly to allow for KW rocketry engines to start up first though so do you know how long it takes for the stage to get ready?

**Comment by Dunbaratu** [comment]
Yeah, basically what @hvacengi is talking about is that the stock game itself enforces a cooldown time for staging.  You can see this effect if you fly manually and just try to hit the spacebar super fast over and over multiple times per second.  If the stage isn't ready, the spacebar just makes a "click" sound and doesn't do anything.

**Comment by hvacengi** [comment]
If we don't have it documented though, we really need to add it.  I'll reopen this issue if I can't find documentation tonight.

**Comment by Euphemios** [comment]
Would you prefer it if I changed the issue title and desciption to having no documentation @hvacengi ?

**Comment by hvacengi** [comment]
Found it: http://ksp-kos.github.io/KOS_DOC/structures/vessels/stage.html#attribute:STAGE:READY

It isn't **super** clear, but it is at least _somewhere_.  I'll leave it closed.
