### ISSUE TITLE
Documentation for PR1657

### ISSUE THREAD

**Issue by hvacengi** [KSP-KOS/KOS#1677]
I'm creating a new issue to break out the documentation changes for #1657.  It should mostly be deleting old references to the limitation of file names being restricted to bare word file names.  We probably want to add examples for using it with the new file system.  All of the example scripts should be updated to use string literals as well, so that we can start weening users off of using bare words.

**Comment by teleksterling** [comment]
I'd suggest the docs also make it clear what happens when there is a bare word filename / variable name conflict - which I assume is to evaluate the variable.
