### ISSUE TITLE
Auto-migrate boot scripts

### ISSUE THREAD

**Issue by hvacengi** [KSP-KOS/KOS#1678]
When the Scripts directory was moved into the global "ships" directory and the extension was changed from .txt to .ks, we included a small utility that would automatically move existing scripts and change the file extensions.  Now that boot files are located in a separate folder, we should offer to move and strip the "boot" prefix.

_When implementing, the file "boot.ks" should not be renamed, it should just be moved._

**Comment by dewiniaid** [comment]
Would it make more sense to allow both old-style and new-style boot scripts to exist, deprecating the old style with a plan to remove it in the next major release or two?

I say this only because of the potential havoc this may raise if someone is directly running a boot script from another script -- or they have their entire script folder under source control...

**Comment by hvacengi** [comment]
I think that I've reached something of a compromise position after reviewing comments to PR #1686.  I don't think that we will be supporting selection of boot files from locations other than the boot directory in the editor, but they will still be valid from within scripts.  I've updated the code so that vessels already in flight will still use the existing root location as defined by the boot script currently.

Existing craft files will be a little smarter.  They will look to see if the existing saved file is located in the archive root.  If it doesn't find the file there, it will look for a file by the same name within the boot directory.  If it still doesn't find it, and if the file name starts with "boot" or "boot_" it will strip the prefix off and look again.  If you are using a file that doesn't exist in the boot directory, selecting another file **and** saving the craft file will prevent you from selecting that file again with that same craft.

I sympathize with the issue of running boot scripts from another script.  This is a breaking change in that regard, and it will be a pain.  But given the large all encompassing nature of this release, and how many changes we have to file name and path handling, I feel like simply forcing the change is the correct choice.

With regard to the source control, it should be able to recognize a file as being moved if it has the same name.  We should be able to make renaming the files optional, so that you can select "yes move my files and rename", "yes move my files but don't rename", and "no, I'll deal with it myself".

**Comment by hvacengi** [comment]
I'm also adding a note here to revise the documentation to address the boot file change, since it's a decent change that users need to have a clear understanding of.
