### ISSUE TITLE
Can't get the position or parent vessel of a part.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#169]
If TARGET is referring to a Part rather than a Vessel, then you can't get TARGET:POSITION because PART doesn't have :POSITION and you can't get to the parent vessel from a PART object to get the vessel's position either.

(This is what I'm discovering as I try the test case of "try to make a simple docking operation".  The inability to find the position of the targeted part is a hindrance.)

In much the same way that making BODY and VESSEL use similar suffixes with similar meaning is necessary because they can both be the result of TARGET, it's useful for a PART to also either:
A: Have similar suffixes to vessel where possible (i.e. POSITION and VELOCITY)
or
B: Have a means for the script to query types (a common request) so it can branch code based on "if TARGET is a Part do this code else if it's a Vessel do this other code..."

At the moment trying to dock by rightclicking a docking port and saying "Set as Target" can't really work.

**Comment by hvacengi** [comment]
Between the addition of the `SHIP` suffix on the part, and the introduction of kOS type information, this should be able to be closed.  

kOS types: PR #1414 

I can't find where the suffix was added, so I'm just linking the line (which will surely break in the future): https://github.com/KSP-KOS/KOS/blob/develop/src/kOS/Suffixed/Part/PartValue.cs#L45
