### ISSUE TITLE
unchar() seems to be broken

### ISSUE THREAD

**Issue by sshilovsky** [KSP-KOS/KOS#1692]
kos 0.20.1. log follows.

    PRINT UNCHAR("A").
    Failed to set scalar value.  Passed type Char, expected Double or Int
    __________________________________________
               VERBOSE DESCRIPTION
    Failed to set scalar value.  Passed type Char, expected Double or Int_________
    _________________________________
    __________________________________________
    At interpreter history, line 24
    PRINT UNCHAR("A").
                 ^

**Comment by dewiniaid** [comment]
I thought I opened an issue for this myself but apparently not.  I can confirm I've experienced the same issue.

This also means there is currently no means of case-sensitive string comparisons save for maybe some hackery involving a case-sensitive Lexicon.  (Add both strings to new case-sensitive Lexicon, then check its length)

**Comment by Dunbaratu** [comment]
I confirmed that this is still happening in our latest develop build.

I'm guessing this will be a simple one-line fix.  Let me look at it.
