### ISSUE TITLE
v1.0.0 Replace changelog urls with the real site just before real release.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#1702]
The current changelog is pointing to the temp location: http://hvacengi.github.io/KOS/ for all the documentation links.

When we publish v1.0.0 for real (and not just a pre-release) these should all be search/replaced with: http://ksp-kos.github.io/KOS_DOC/

**Comment by hvacengi** [comment]
Fixed as part of the release of v1.0.0: https://github.com/KSP-KOS/KOS/tree/v1.0.0
