### ISSUE TITLE
Boot script selection UI doesn't show unless there are at least two boot files

### ISSUE THREAD

**Issue by bfrobin446** [KSP-KOS/KOS#1705]
The current code sets the boot script selector to be visible if the number of script files in `Ships/Script/boot` is greater than 1. If I have exactly one script file in `boot`, I'm unable to select it because the UI doesn't show in the VAB.

Pull request #1704 changes the comparison from "greater than 1" to "greater than or equal to 1", which has restored the expected behavior for me.

**Comment by bfrobin446** [comment]
Exact reproduction steps on KSP 1.1.3 and kOS 1.0.0-pre-1:

Have exactly one .ks file in `Ships/Script/boot`.

    $ ls -FR Ships/Script
    boot/
    
    Ships/Script/boot:
    dartA.ks   dartB.txt  dartC.txt

Start a clean sandbox save. Go into the VAB and place a CX-4181 SCS as the root part. Right-click the processor. The option to set the boot file doesn't appear.

Delete the kOS processor, leaving the VAB empty. Give a second file in the boot folder the .ks extension.

     $ ls -F Ships/Script/boot
     dartA.ks   dartB.ks   dartC.txt

Place a new kOS processor as the root part. Now that there are two .ks files to choose from, right-click the processor, and the option to choose a boot file is available.

**Comment by bfrobin446** [comment]
Confirmed that I'm getting the fix in a fresh build from `develop`. Closing.

**Comment by hvacengi** [comment]
Adding a reference to #1704 which fixed this issue.
