### ISSUE TITLE
Typo in the documentation about communication?

### ISSUE THREAD

**Issue by Efratror** [KSP-KOS/KOS#1709]
In the pre-release doc [LINK](http://hvacengi.github.io/KOS/commands/communication.html) about the newly added communication function there is this line :

> kOS will automatically add 3 values to every message that is sent: Message:SENTAT, Message:RECEIVEDAT and Message:SENDER

shoudn't Message:SENTAT be Message:SENDAT?

Later on I saw the same suffix in the doc.
Haven't had the time to test if it's just a typo or if the suffix is really named :SENTAT

**Comment by bfrobin446** [comment]
`SENTAT` is correct: https://github.com/KSP-KOS/KOS/blob/1ea7ae9243e03e51ac189379ae5adf351d0854ba/src/kOS/Communication/MessageStructure.cs#L43

It refers to the time when the message was *sent*, just like `RECEIVEDAT` is the time when the message was *received*.

**Comment by Efratror** [comment]
My bad, English isn't my first language. I had my accounts wrong thought that the past simple of send was just send.
