### ISSUE TITLE
Some solution dependencies are missing from the list in CONTRIBUTING.md

### ISSUE THREAD

**Issue by jboecker** [KSP-KOS/KOS#1715]
The list at the end of CONTRIBUTING.md is missing some assemblies. After copying three more files (`Assembly-CSharp-firstpass.dll`, `KSPUtil.dll`, `UnityEngine.UI.dll`), I could successfully build the solution.

I'll send a pull request once I have verified that this build actually works in KSP.

**Comment by jboecker** [comment]
Created pull request #1717.

**Comment by Dunbaratu** [comment]
good catch  thanks for noticing it.
