### ISSUE TITLE
Broken arity checks for anonymous functions

### ISSUE THREAD

**Issue by gisikw** [KSP-KOS/KOS#1725]
Anonymous function arguments are encountering param check errors. Issue can also be replicated in some named-delegate situations as well, which may constitute a regression from the previous version.

## Failing Case $1
```
function test {
  parameter name, body.
  body().
}

test("some behavior", {
  print "the behavior works".
}).
```

```
Number of arguments passed in didn't match the number of DECLARE PARAMETERs.
 Too few arguments were passed to body
__________________________________________
           VERBOSE DESCRIPTION
Number of arguments passed in didn't match the number of DECLARE PARAMETERs.
 Too few arguments were passed to body
The number of arguments being passed into a function or program call is not corr
ect.
__________________________________________
__________________________________________
At Archive:/anon_test.ks, line 3
  body().
      ^
Called from Archive:/anon_test.ks, line 9
}).
```

## Also Failing Variants
$2
```
function test {
  parameter name, body.
  body:call().
}

test("some behavior", {
  print "the behavior works".
}).
```
*^ Note: unlike the first example, this does print "the behavior works" before throwing the same error message*

$3
```
function test {
  parameter name, body.
  body().
}

function test_body {
  print "the behavior works".
}

test("some behavior", test_body@).
```
*^ This should be valid syntax for pre-1.0 kOS*

## Passing Variant

```
function test {
  parameter name, body.
  body:call().
}

function test_body {
  print "the behavior works".
}

test("some behavior", test_body@).
```

I did try adding parameters to the anonymous function, to see if maybe matching arity would fix stuff, but as far as I can tell, it doesn't seem to make any difference.

**Comment by gisikw** [comment]
Sorry, should mention this is on the RC, and should probably also tag @Dunbaratu

**Comment by gisikw** [comment]
Update: managed to get develop compiling via mono (my Windows machine is dead at the moment). The errors are the same on develop, but $2 works with Dunbaratu's #1723 PR applied. That is to say, once that's merged, it looks like behavior is as expected for `delegate:call()`. Both cases where the delegate is invoked merely via parens remain borked.

**Comment by Dunbaratu** [comment]
I'm very confused by this part of your description of the broken variants:  Your $3 variant is listed as one of the things under the "broken variants" section, and despite that it looks identical to the one just after that which you've labelled as the working variant.  I looked back and forth between $3 variant and "passing variant" and literally can't find any difference in what you've typed.

**Comment by Dunbaratu** [comment]
Note.  `body()` is the name of a built-in function (hmm - we should see if we can throw an error when you make an identifier that matches a built-in).

I changed the name of the function to something else and there's still a problem here, but it throws exception at a different instruction in the program.

**Comment by gisikw** [comment]
Oh, heh, I forgot about that. Though yeah, still encountered the issue with non-bound names.

**Comment by Dunbaratu** [comment]
I think once you rename the ``body`` to something else (I just picked ``body_``) AND use the PR #1723 then all 3 of your problem cases above passes, and the issue goes away.

Can you verify if this is true, and if so close the issue?

**Comment by gisikw** [comment]
Sure thing, lemme verify quick!

**Comment by gisikw** [comment]
Yep, all those cases are working with that PR! However, even user-bound name collisions will cause an issue (that is, it's not respecting nearest-scope). Example:

```
{
  function block {
    parameter foo.
    // Force a param check collision
  }

  function test {
    parameter name, block.
    block().
  }

  test("Behavior", {
    print "The block works".
  }).
}
```

This'd be a big issue with people using any libs, and I know that nearest-scope had been working under older versions of kOS. Let me know if I should close this issue and open a new one, or if this should be considered the same problem.

**Comment by gisikw** [comment]
Actually, yeah, this isn't an arity problem anymore. I'll go ahead and close this and open a new issue.
