### ISSUE TITLE
RemoteTech is breaking the steering manager on vessel-switch, without a scene reload

### ISSUE THREAD

**Issue by GER-Space** [KSP-KOS/KOS#1731]
Hi,

I have ha rocket with sevreal smaller sattelites on it. The mothership launches the sats, waits a few seconds and then it switches to the released sat via KUniverse:ACTIVEVESSEL(my_sat).

After that the new Sat has no control with the seeting-manager. 

[output_log.txt](https://github.com/KSP-KOS/KOS/files/367173/output_log.txt)
[KSP-log.txt](https://github.com/KSP-KOS/KOS/files/367174/KSP-log.txt)

**Comment by Dunbaratu** [comment]
I have sometimes had problems with kOS refusing to rotate the ship until I reload the scene, or the script turns on the throttle which seems to "wake up" the problem and allow it to start steering (of course this makes the planned burn be waay off since it the script was unable to start rotating to align with the right direction until it was already starting to burn).

This makes me wonder if the problem is in how RemoteTech is locking out the controls.  Allegedly kOS is suposed to be asserting that it has the right to override RT's control lockout, but we had problems with that system before and maybe something just changed in how that works?

Paging @hvacengi about this.  GER-Space, do you have an easily reproducable example of the problem?  Every time I had it it was in a situation where it was hard to reproduce exactly.

**Comment by GER-Space** [comment]
I could provide you a savegame. The only Mods needed are KOS, RemoteTech and procedual fairings. It is 100% reproducable and does not fix it.

**Comment by GER-Space** [comment]
Here are the scripts and the savegame. When you load the last quicksave you can switch to the Vessel "Mun  Carrier 1" 
The bootscript (carrier.ks) will launch a sat (which boots sat.ks) and switch to the new sat a few seconds later. The new Sat will not alling itself to the next node, also manual steering is possible. 
[saves.zip](https://github.com/KSP-KOS/KOS/files/367511/saves.zip)

**Comment by hvacengi** [comment]
@GER-Space Could you try doing this on a build of the current develop branch?  We now support Remote Tech's ability to be disabled, which means that it can be tested without RT interfering with the controls.

I should have time tomorrow to look at this and see what's going on (maybe even tonight) but I've got a busy couple of days at work so I'll be a little detached from kOS.

I just had a thought while thinking about the issue that @Dunbaratu saw where he needed to use the bracket keys to switch back and forth between vessels to make it work, and that locking the throttle "woke up" the steering update: I wonder if there is an issue with RT and the "Sanctioned Pilot" handlers when changing active vessel.  In which case, it might be a fix on RT's end, or it might be as simple as updating the event handlers whenever the active vessel changes.  The one difference between how steering and throttle register for RT updates is that throttle does it every time it gets enabled, while steering only registers once when the `KOSVesselModule` is created.

**Comment by GER-Space** [comment]
Testing results with the build from todays sources. 

RT disabled --> ALL good.
RT enabled & config:RT =true.   --> Steering Manager not working, but I can steer the sat with my keys, as long I have antenna connection 

RT enabled & config:RT =false.  --> Ok this is really strage. Steering Manager is working, as long I have an antenna connection. Controls by Keys behaves the same, which is ok.  

I think the problem is, that I switch to a sat, wich is in the Physics bubble and which is allready loaded or freshly created by releasing it.

**Comment by hvacengi** [comment]
>RT enabled & config:RT =false. --> Ok this is really strage. Steering Manager is working, as long I have an antenna connection. Controls by Keys behaves the same, which is ok.

That's because kOS is essentially the same as local control if you disable the config flag.

Looks like I'll have to figure out how to smooth over the control of multiple vessels using RT.

**Comment by GER-Space** [comment]
would it be possible to have a addons:rt:registersteering suffix? This might be easier to implement.
