### ISSUE TITLE
list files in foo only list the file/directories in the main directory

### ISSUE THREAD

**Issue by Efratror** [KSP-KOS/KOS#1735]
If you have a volume set up like this
> 0:/Develop/foo1,ks
> 0:/Release/foo1.ks

and you want to list the files in the develop directory like so:
`cd ("0:/Develop/").`
`list files in foo.`
`print foo.`

the output is a list of the archive volume:
> List of 2 items:
>[0] = "Develop"
>[1] = "Release"

Don't know if you prefer if I add this to #1729? But for now i made a new issue.

**Comment by Dunbaratu** [comment]
I'd definitely call this a bug because "list blarg" and "list blarg in foo" are supposed to conceptually always be the same list - one just goes to the terminal and the other into a variable.  And "list blarg" to the terminal *does* obey the current working directory, so "list blarg in foo" should as well.

**Comment by Efratror** [comment]
Maybe if found the problem, correct me if i'm wrong but for `list files in foo.` you use this [file](https://github.com/KSP-KOS/KOS/blob/14c50e4d6ec477ade56a14bae200dac8ef2e1854/src/kOS/Function/BuildList.cs), there line 43 says:
>list = ListValue.CreateList(shared.VolumeMgr.CurrentVolume.ListAsLexicon().Values.ToList());

And in this [file](https://github.com/KSP-KOS/KOS/blob/14c50e4d6ec477ade56a14bae200dac8ef2e1854/src/kOS/Function/PrintList.cs) is used,  from line 84 up to line 109 U state the code for construction the `list files.` function in that segment you use code like:
>list.Title = shared.VolumeMgr.CurrentDirectory.Path.ToString();

So you use CurrentVolume which I presume is the Volume you are working on for  `list files in foo.` and you use CurrentDirectory which i guess is the current path for `list files.`. 

I think if you change `list=ListValue.CreateList(shared.VolumeMgr.CurrentVolume.ListAsLexicon().Values.ToList());` to `list = ListValue.CreateList(shared.VolumeMgr.CurrentDirectory.ListAsLexicon().Values.ToList());` the bug is fixed

**Comment by Efratror** [comment]
Thought i fixed it, but when i tried to build the KOS solution to test the things i changed the solution doesn't want to build because of the many errors it produces and the error's where thrown in parts I didn't even looked at, so what's the problem with that?

**Comment by hvacengi** [comment]
You probably just had an issue with dependencies.  What program were you using to compile?  Did you place 5 dlls inside of the Resources folder?  I've occasionally seen it where you needed to manually compile `kOS.Safe` before compiling `kOS` even though it should do so automatically.  I'll download your PR and test compiling locally.

**Comment by hvacengi** [comment]
@Efratror I just tested your PR and it appears to work fine.  If you "restore" that branch one more time I will merge (I'm not sure what happens if I merge when the source branch is deleted...)

**Comment by Efratror** [comment]
branch and pr are restored. I use visual studio 2015 to compile, which 5 dlls and Resources folder are you talking about?

**Comment by hvacengi** [comment]
I'm going from memory as I'm on my phone now, but I think they are: Assembly-CSharp, Assembly-CSharp-firstpass, KSPUtil, UnityEngine, and UnityEngine I all from within KSP's KSP_Data/Managed or KSP_x64_Data/Managed folders.

**Comment by Efratror** [comment]
Thank you very much those where indeed the missing reference's. Solution is building like charm now.

**Comment by hvacengi** [comment]
Closed via #1737
