### ISSUE TITLE
Can't COMPILE to a different volume than source file

### ISSUE THREAD

**Issue by bfrobin446** [KSP-KOS/KOS#1741]
On kOS 1.0.0-pre1, when I execute `compile "0:/sidewinder.ks" to "1:/sidewinder.ksm".`, the output file sidewinder.ksm is created on the Archive instead of on volume 1 like I expected.

**Comment by hvacengi** [comment]
Well, I found the issue.  In the load function we only read the `Volume` information once, and use the same volume that reads the file to save the file.  I'm sure it's left over from before we even supported paths, and that it just didn't get updated at the same time.  Should be a quick fix.
