### ISSUE TITLE
latest SteeringManager commit is not good

### ISSUE THREAD

**Issue by GER-Space** [KSP-KOS/KOS#1752]
the following commit https://github.com/KSP-KOS/KOS/commit/f197c32f01b24ee5fe974905316f95395ffeb1a4 for the y-z Roll Swap is currently breaking my launches. 

When I tested a launch the roll lever on the left down corner was going nuts (flickering left-richt) and my rockets (I tested a few) where flying spirals. 

Reverting the above commit repaired the steering manager for me.

They are all normally build (no offcenter or rotated root-parts)

**Comment by Dunbaratu** [comment]
@hvacengi : I just tested with the stock craft "AreoEuquus" (stock plus a kOS "CompoMax Radial Tubeless" computer attached to the side of the capsule). and my old launch script behaved exactly as it did before _AT FIRST_.  But then when it hit the upper parts of the atmosphere (where the fins no longer help all that much) the yaw control indicator started deflecting back and forth across the intended steering point, with bigger and bigger deflection each time, until it was see-sawing back and forth in arcs as big as 180 degrees.  (then it ran out of battery power from all that use of torque wheels and my test concluded, but that was enough to prove something is wrong).

That didn't used to happen before.

When I accepted the PR, I only performed a few limited tests in some situations, and assumed you'd done a full suite of launch scenarios.  But it seems something pretty basic got missed somewhere.

**Comment by hvacengi** [comment]
I'll test tonight and should be able trace down the issue.  I swear I did a strong set of testing, but must have missed something.

**Comment by hvacengi** [comment]
@GER-Space Can you try building the pull request I just submitted and see if it fixes your observed issues?

**Comment by GER-Space** [comment]
@hvacengi  I have no idea how to apply a pull request to my local branch, but revering to two, in the pull request mentioned, commits fixed the launches for me.
