### ISSUE TITLE
diskSpaceMassFactor 1000x too large?

### ISSUE THREAD

**Issue by cfe316** [KSP-KOS/KOS#1755]
In the documentation it is listed that diskSpaceMassFactor is set so that 4096bytes ~ 0.02kg. I believe the factor is more like 4096byes ~ 0.02 tons. When turning up the storage of the Compomax Radial Tubeless my ship's mass increased by 0.88 tons.
(Is this meant to model rope memory? :D )
This link suggests that the mass setting is in megagrams, not kilograms:
https://github.com/KSP-KOS/KOS/issues/1303

Additionally here is are two screenshots. I'm running 1.1.3 on Mac 10.9.5 with the kOS-v1.0.0-pre-1 (https://github.com/KSP-KOS/KOS/commit/7cbf846b862f7a2e0e38319289a48c3e3c14e323).

![withlittlemass](https://cloud.githubusercontent.com/assets/9857723/17075429/08e0123e-5061-11e6-9950-503b5bf82893.png)
![withlotsofmass](https://cloud.githubusercontent.com/assets/9857723/17075430/08e2851e-5061-11e6-8c26-dfe934a873ad.png)

**Comment by Dunbaratu** [comment]
I'm not entirely happy with the entire disk size game balance, period, but figured there wasn't much point in addressing it until other systems were in place.  Now that those other systems are in place, maybe we can come back to it and balance the weights a bit better.
