### ISSUE TITLE
Part Highlight not visible after part tree alterations

### ISSUE THREAD

**Issue by TDW89** [KSP-KOS/KOS#1783]
[ksp v1.1.3] [kos v1.0]
Tested with KerbalX (with KAL9000)

sorry for the long test script but because of the visual nature I went for user feedback at each step.

```
clearscreen.
set ag10 to false.
set foo to ship:rootpart.
set bar to highlight( foo, blue ).
print "The pod is highlighted blue. " + bar:enabled. 
print "press 0 for next step".

wait until ag10.
set ag10 to false.
sas on.
lock throttle to 1.
stage.
print "Highlighting still enabled. " + bar:enabled.
print "press 0 for next step.".

wait until ag10.
set ag10 to false.
                              //This is where it starts to go wrong
stage.
print "Highlight:enabled is now reporting " +bar:enabled.

//if this reported false i would assume it was a design choice to prevent having hard to remove
//highlights on detached parts.
//The highlight however has disappeared for me (will test different graphics settings in a bit)

print "Press 0 for next step.".
wait until ag10.
set ag10 to false.

set bar:enabled to true.
print "Highlight is now back. " +bar:enabled.
print "press 0 to end.".

wait until ag10.
set ag10 to false.
```

For me the highlight is disappearing as soon as the launch clamps are detached. It also happens with any other staging that fires decouplers. I will install bdArmory later and see if shooting parts off the vessel causes the same issue.
Will fiddle found with the graphics setting a bit too to see if that changes anything.

**Comment by hvacengi** [comment]
I had actually noticed in the past that there is also an issue with the highlight getting disabled when you switch active vessels using the `[` and `]` keys.  Oddly, in that instance the highlight only disappears if you are highlighting a part on the cpu vessel.  In my docking script I highlight both docking ports (the one on the ship and the one on the station) and noticed that changing the active vessel to the station caused the ship's port to loose it's highlight.  I never reported it cause it was a very minor issue, but it's probably related to this use case.  I'll try to dig in to the code as some point in the near future and see how kOS manages the highlight.  @erendrake might have some ideas as I think he implemented the system to begin with.

**Comment by Dunbaratu** [comment]
I looked at this a bit when this issue first appeared but didn't say anything because I didn't find an answer.  It seems that all our code does is rely on KSP's own highlighting code and *it* seems to have some logic to turn the highlighting off in some cases.  This may be one of those cases where the base game has assumptions that only one craft ever matters - the active vessel - and it messes us up.
