### ISSUE TITLE
Laser Distance Measurer: a test case for getting data about parts' info displays.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#179]
One of the things we wanted to do in the future is generically be able to read any of the display fields on any of the rightclick menus of any part.

Another thing people have been asking for is some sort of line-of-sight altimeter that's like the radar altimeter except that it can give distances along other directions than just straight down.

With @erendrake away for a bit and thus kOS relatively frozen for a few days I decided to give it a go and try to make a brand new part mod that does this lazer distance measurer, using the underlying Unity RayCast ability. 

Here's what it looks like:

![screenshot63](https://cloud.githubusercontent.com/assets/5216848/3467927/82144bf8-0297-11e4-8ceb-da6c757c9ada.png)

And the distance is ray-cast from the part in question, from its orientation, as demonstrated in this screenshot:
![screenshot64](https://cloud.githubusercontent.com/assets/5216848/3468017/ac6e81b0-0298-11e4-9a6b-a5351ecd6b62.png)

I intend this to be a separate tiny KSP Mod (the plugin code right now is just one 200 line class file for the PartModule, and I don't see it needing to get much more complex than that.)  I'm making it a separate mod for two reasons:

1. Because maybe other people with similar autopilot ideas might find it useful to have a part like this too (like mechjeb or Jebnix).

2. Because it would make a good use case for getting kOS to be able to read the data from any part, that once that's working it would really help make kOS more useful.

When I get the github project for it up I'll post a link to it here, but right now I don't trust myself as I'm sleeeeepy.

One I do get it up, I'd welcome the help of anyone with 3D modelling artwork experience to make the part's texture and mesh look better.  What I have there now is a placeholder.  I don't have a 3D modelling program installed so I made it by just slapping a few quick Unity primitive objects together to get the idea so I could get to the part where I write the code.

**Comment by cherrydev** [comment]
Unless I misunderstand, this is implemented in 0.15

**Comment by Dunbaratu** [comment]
Yes, this can be closed.  LaserDist has its own problems but the stuff about how to integrate with kOS is done.
