### ISSUE TITLE
No way to detect if warp is really ended.

### ISSUE THREAD

**Issue by surge9000** [KSP-KOS/KOS#1790]
WAIT UNTIL WARP = 0. will detect when the game's warp factor has been commanded to 0, but it is not useful for determining when the warp has actually finished. The game takes a while (sometimes minutes of game time for long warps) to actually stop warping.

This is pretty important because many things like :MEANANOMALYATEPOCH, positionat(), velocityat() etc, are completely wrong during warps, not to mention doing a normal WAIT <seconds> that is shorter than the time the game takes to stop warping will not wait at all.

I've been working on a workaround, but I haven't found one yet, unfortunately.

**Comment by TDW89** [comment]
does `wait until ship:loaded` work? That will only help with on rails time warp but I'm assuming its the time taken to come down from high "rails" warp that's causing an issue for you.

**Comment by surge9000** [comment]
WAIT UNTIL WARP = 0 and SHIP:UNPACKED.
does, so there is a workaround.  (Was writing this when I see you commented :)

I noticed that the global SESSIONTIME could have been used if it worked as documented, but it seems to give the time since the vessel was set active, not the time since it was on rails.

**Comment by hvacengi** [comment]
Using `ship:unpacked` is the best answer currently.  The only issue with that is it doesn't work with physics warp.  For physics warp you'd need to check the time delta manually to see when it comes back to "normal".  It may be possible to expose the actual fractional rate itself, which ramps over time as you come out of warp.  But at that point we really should look at exposing a new structure for managing warping, because flooding the global variable list with warp related variables is probably not the best idea.

Technically `meananomalyatepoch` is not wrong during warps, because epoch does not change while warping.  We need to expose the value of epoch on the orbit to make that number useful (#1665).  My recommendation remains to not presume that the mean anomaly at epoch is equal to the current mean anomaly, because it is possible that KSP changes the behavior in the future.

I'm more curious about you comment that `positionat()` and `velocityat()` don't work.  How do they fail, and what are the "etc" features that don't work correctly?  I have some scripts that perform calculations during time warp in an effort to keep the orbits more stable and had not noticed any issues, but I don't do it all that often.  We need to fix any thing that breaks under timewarp.

**Comment by Dunbaratu** [comment]
I think I remember seeing cases where epoch does change upon coming back OUT of warp, though, as part of the act of going from on-rails to not-on-rails it seems to re-create the state vectors (pos, velocity) out of the Kepler parameters, and then once it's in full physics mode, it calculates the Kepler parameters out of the state vectors.  In circular orbits, that causes a loss of information that gets re-made.  (Maybe this is also related to why ships sometimes "jump" to new positions up to a hundred meters off when you time warp and then come out of time warp.)

**Comment by surge9000** [comment]
You both seem to be very confused about what mean anomaly means. It *is* accurate during 1x warp, as is true anomaly, and pretty much all the other orbital things KSP exports; and you have regurgitated faithfully in the OBT structure (good job).

But, for example; I saw a bug report about mean anomaly being > 360, which annoyed me... mean anomaly is the angle from perigee the craft *would* be at if it was in a circular orbit with the same semimajor axis as the current (elliptical) orbit, and given the real time that has passed since perigee. (it's essentially the only thing the famous Keplers Law states; all the mathematical gibberish we have to do to calculate anything useful is superfluous; and generally why most KSP users become terrified when you mention elliptical orbits :).

It's therefore physically nonsense for it to be anything other than 0 -> 360. Sadly, some bits of kOS report a range of -180 -> 180 which is also nonsense, although workaroundable, and depending on the equations you use, mathematically possible.

During warp these values are halted (temporarily, and probably only for rails), and thus are meaningless; which is why I was looking for a solution to this. They are recalculated properly once real time begins again.

But back to this bug... I would be comfortable if the documentation simply pointed out that WARP = 0 AND SHIP:UNPACKED was a way to determine if warping has stopped in the section about warpto().
A better solution would be to make WARP match the real current warp (at least 1 physics tick later) when read, but thats obviously too difficult.

I notice also that this was not a problem until a recent update of KSP when they implemented 'predictive warp' that gradually slows down as it gets nearer to the warp endpoint. It was introduced in 1.0.3, or 1.1.2,. I cant remember, but previously warp would just stop immediately, which tended to screw up carefully planned intersections and so on, so they made it more gentle. Good for squad, but now you have to fix your thing.

**Comment by hvacengi** [comment]
I like the idea of mentioning `ship:unpacked` in the documentation for `warp` as one of our note call out boxes to help other users find the information more easily.  I'll tag it with the documentation label.

I don't have my historical KSP copies on the computer that I'm on right now, but I am pretty sure that this has been an issue for a while.  I have script history dating back to December 2015 where I added the unpack wait code.

If I may draw your attention back to an earlier question though, could you clarify how other functions are broken during time warp?

I don't want to continue to side track the conversation defining the term, but I wanted to defend at least a portion of my position.  Feel free to ignore the below commentary, it will be the last that I post regarding the definition.

>You both seem to be very confused about what mean anomaly means. ...

I am not confused; we are describing two different concept.  Yours is a correct definition of mean anomaly.  Mean anomaly **at epoch** on the other hand is a value that defines the relationship between the orbit and a "real" time.  The epoch anchors the orbit in time.  When I first looked into this I expected epoch to be `universal time = 0`, but KSP assigns the epoch an arbitrary value that may or may not be equal to the current time depending on situation.  If you have the current time and the current true anomaly, mean anomaly at epoch doesn't really provide additional information as they both provide the "real" time reference point.  Which brings us back to issue where we don't directly expose KSP's value for epoch on the orbit, with which you could easily calculate current mean anomaly using the mean motion of the orbit (or you could just calculate it based on current true anomaly and eccentricity).

I presume that you're referring to #1669 regarding the 360° clamping.  You'll notice that I didn't say we would implement it.  I personally prefer our current method where we clamp the value from 0° to 360°.  It leaves it up to the user how they want to treat the value, as they can clamp it however they like.  The value is not very difficult to calculate for either [elliptical](http://www.braeunig.us/space/orbmech.htm#position) or [hyperbolic](http://www.braeunig.us/space/orbmech.htm#hyperbolic) orbits.

**Comment by surge9000** [comment]
Feel free to add your own positionat(). vecdraw()  etc. in the appropriate place and notice that they are ridiculous.
```
// demonstrates delay between WARP = 0 and actual warp end.
set sl to terminal:height -10.
clearscreen.
set oldtime to TIME.

function printdata {
	print "WARP = " +WARP at(2,sl).
	if oldtime = TIME print "No physics.   " at(2,sl+1).
	else print "Yes physics.    " at(2,sl+1).
	print "Unpacked: " +SHIP:UNPACKED +"   " at(2,sl+2).
	print "Loaded: " +SHIP:LOADED +"   " at(2,sl+3).
	set oldtime to TIME.
	wait 0.1.
}

warpto(TIME:SECONDS +5000).
until WARP = 0 and SHIP:UNPACKED {
	if WARP = 0 and not (defined Tdelay) 
		set Tdelay to TIME:SECONDS.
	printdata().
}
printdata().
print "Delay was " +round(TIME:SECONDS -Tdelay,2).
```

**Comment by surge9000** [comment]
Also, for orbital mechanics...
```
clearscreen.
clearvecdraws().

function eccan {
// returns eccentric anomaly for trueanomaly t
	parameter t.
	local _e to OBT:ECCENTRICITY.
	local i1 to sqrt((1 -_e) /(1 +_e)).
	return arctan(i1 *tan(t/2)) *2.
}

function tofperigee {
//	if hasnode {
//		set nd to nextnode.
//		remove nd.	
//	}
//	set nd to node(TIME:SECONDS +ETA:PERIAPSIS, 0,0,0).
//	add nd.

	local _e to OBT:ECCENTRICITY.
	local n to sqrt(BODY:MU /OBT:SEMIMAJORAXIS^3)
		*CONSTANT:RadToDeg.
print "n = " +round(n, 4) +", _e = " +round(_e, 4) +"  " at(2,23).


	local i1 to cos(OBT:TRUEANOMALY).
	local Eo to arccos((_e  +i1) /(1 +_e *i1)).
	local Mo to Eo -_e *sin(Eo).
print "OBT " at (2,24).
print "Mo: " +round(OBT:MEANANOMALYATEPOCH, 4) +"   " at(25,24).
print "braeu Eo: " +round(Eo, 4) +"  " at(2,25). 
print "Mo: " +round(Mo,4) +"  " at(25,25).

	local Eo to eccan(OBT:TRUEANOMALY).
	local Mo to Eo -_e *sin(Eo) *CONSTANT:RadtoDeg.
	set Mo to mod(Mo +360, 360).
print "OMfES Eo: " +round(Eo, 4) +"  " at(2,26).
print "Mo: " +round(Mo,4) +"   " at(25,26).

	
	set fast to (OBT:MEANANOMALYATEPOCH /360) *OBT:PERIOD.
print "Tp (OBT) = " +time2str(fast) +"   " at (2,28).
//print "Error (OBT) = " +round(nd:eta -fast, 1) +"s  " at(2,29).

	set braunig to Mo /n.
print "Tp (braunig) = " +time2str(braunig) +"   " at (2,30).
//print "Error (braunig) = " +round(nd:eta -braunig, 1) +"s  " at(2,31).

	set OMfES to (360-Mo)/360 *OBT:PERIOD.
print "Tp (OMfES) = " +time2str(OMfES) +"   " at (2,32).
//print "Error (OMfES) = " +round(nd:eta -OMfES, 1) +"s  " at(2,33).

	return OMfES.
}

function tofang {
// calculates time to rotate angle a around orbit from now.
	parameter a.
	local ecc to OBT:ECCENTRICITY.

	local Eo to eccan(OBT:TRUEANOMALY).
	local Et to eccan(OBT:TRUEANOMALY +a).

	// not sure what the RadtoDeg is for, ecc is a ratio
	// and everything else is in degrees
	local Mo to Eo -ecc *sin(Eo) *CONSTANT:RadtoDeg.
	local Mt to Et -ecc *sin(Et) *CONSTANT:RadtoDeg.

	return (Mt -Mo)/360 *OBT:PERIOD.
}


function time2str {
	parameter _s. // time in seconds
	local m to mod(floor(_s/60), 60).
	local h to mod(floor(_s/60/60), 6).
	local d to floor(_s/60/60/6).
	return d +"d "
		+abs(h) +":" 
		+abs(m) +":"
		+abs(round(mod(_s, 60), 1)).
}

function drawstuff {
	clearvecdraws().

	set VRtgt to -BODY:POSITION +TARGET:POSITION.
	set VRship to -BODY:POSITION +SHIP:POSITION.
	// get angle to next -csending node
	set Ntgt to vcrs(TARGET:OBT:VELOCITY:ORBIT, VRtgt):normalized.
	set Nship to vcrs(OBT:VELOCITY:ORBIT, VRship):normalized.
	set Vnode to vcrs(Nship, Ntgt).
	vecdraw(BODY:POSITION, 
		Vnode:normalized *(SHIP:ALTITUDE +BODY:RADIUS), 
		red, "Node vector", 1, TRUE).
	set Vtest to vcrs(Vnode, VRship).
	set Anode to vang(VRship, Vnode).
	if Vtest:y < 0 set Anode to 180 -Anode.

	if hasnode {
		set nd to nextnode.
		remove nd.	
	}
	set nd to node(TIME:SECONDS +tofang(Anode), 0,0,0).
	add nd.
	
	print "angle to node: " +round(Anode,1) at(2,10).
	set tnode to tofang(anode).
	print "time to node: " +time2str(tnode) at (2,12).
	
	print "true anomaly (OBT): " +round(OBT:TRUEANOMALY, 2) at(2,15).
	set i1 to cos(OBT:TRUEANOMALY).
	set ecc to OBT:ECCENTRICITY.
	set Eo to arccos((ecc  +i1) /(1 +ecc *i1)).
	print "ecc anomaly: (braunig)" +round(Eo, 2) at(2,16).
	set Eo to arctan(sqrt((1-ecc)/(1+ecc)) *tan(OBT:TRUEANOMALY/2)) *2.
	print "ecc anomaly (OMfES): " +round(Eo, 2) at(2,17).
	set Mo to Eo -ecc *sin(Eo) *CONSTANT:RadtoDeg.
	print "mean anomaly (OMfES/braunig): " +round(Mo, 2) at(2,18).
	print "mean anomaly (OBT): " +round(OBT:MEANANOMALYATEPOCH, 2) at(2,19).
	
	print "time since perigee: " +time2str(tofperigee) at(2,21).



}

until False {
	drawstuff().	
	wait 1.
}
```

**Comment by Dunbaratu** [comment]
> Mean anomaly at epoch on the other hand is a value that defines the relationship between the orbit and a "real" time. The epoch anchors the orbit in time. When I first looked into this I expected epoch to be universal time = 0, but KSP assigns the epoch an arbitrary value that may or may not be equal to the current time depending on situation

And that is the behaviour that seems to change when you come off of time warp and back to 1x warp.  I've found that this is one of the events that tends to reset the epoch of the orbit.  It changes the meaning of "MeanAnomalyAtEpoch" because it changes when "At Epoch" is.

**Comment by Dunbaratu** [comment]
Let's not derail the topic any further with this other utterly unrelated issue.  It doesn't matter why someone needs to know when the time warp really has successfully become zero.  There's multiple reasons that would be a necessary thing to know because there's so many things that are locked out from working properly until then (regardless of whether or not the OP understands orbital parameters, there's still plenty of other things where it does matter).

The core problem is that the value we're returning for the current warp appears to be the user interface's *requested warp level* as  opposed to the actual *current* warp level.  While the "UNPACKED" check is a good way to find out if we're at warp = 0, it doesn't solve the problem for other destination warp values.  (i.e. what about "I want to warp at 1000x, let me know when I've finally reached 1000x for real." and other similar cases where it's not looking for 1x specifically but just any time warp amount it takes time to achieve?")

Can we find something in the KSP API that tells us the current warp amount that was used in THIS physics tick?  i.e. if you go from 100x to 1000x you will often see on the user interface screen that it very quickly displays values like 259x, then 401x, then 614x, then 850x, then finally 1000x, or something along those lines.  It would be nice if we could find a way to expose those values like 259, 401, etc that it was hitting along the way to its target timewarp speed.

**Comment by hvacengi** [comment]
The `TimeWarp` class has the following values available for us:

* `CurrentRate` - `(double)`: represents the current fraction of normal time.  This value is linearly interpolated as timewarp engages and disengages.  After the interpolation finishes it's essentially the multiplier (100x = `100.0`).
* `fixedDeltaTime` - `(double)`: the current value for s/tick.  Usually 0.02 when not warping, it returns `Time.fixedDeltaTime * CurrentRate` when warp is enabled
* `CurrentRateIndex` - `(int)`: this is the value we read for the value of `warp` currently.  It's the integer value used to determine `CurrentRate`

If we want to expose more than we already do, I think it should be on a structure `TimeWarp` accessible from `kuniverse:timewarp`.  The existing `warp` and `warpmode` functionality would be moved into the structure, but those variables would remain in place pointing to the `timewarp` structure's implementation.  That keeps backwards compatibility in good shape while still allowing us to expand the functionality pretty reasonably.
