### ISSUE TITLE
ScienceData sciencevalue and transmitvalue not working in sandbox mode

### ISSUE THREAD

**Issue by Patrykz94** [KSP-KOS/KOS#1795]
Yes, I know, it's sandbox mode, but I guess I'm not the only person who tests their spacecraft and scripts in a sandbox test save. When trying to get the "transmitvalue" or "sciencevalue" I expected it to return 0 but it gave me an error instead: "Object reference not set to an instance of an object". The "title" and "dataamount" suffixes work fine. Tested it in a carear mode and everything works well so I guess this is because of sandbox.

**Comment by hvacengi** [comment]
This should be fairly simple to fix.  There should be a game setting to check and see if science is enabled.
