### ISSUE TITLE
Tertiary operator ("?")  (with short-circuit logic) to protect against infinity in a single expression.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#18]
The change for #14 broke the ability to store infinity in a variable.

Now if there is going to be a chance that there might be a divide by zero anywhere in an expression, that has to be checked for ahead of time, rather than allowing it to return infinity.  As soon as any math expression or sub-expression returns infinity, the script dies.

That means things like this:
`set var to x / y.`

If there's a chance Y might be zero, have to be turned into this instead:

```
set var to bigNum.
if y > 0 or y < 0 { 
  set var to x / y.
}.
```

(I'd use if/else instead for that if there was an 'else'.)

This makes writing lock expressions currently a bit of a pain because there's no mechanism currently to protect a lock expression with an "if" like you can with a 'set'.  The value of a lock must be written out as a single expression, which you must assume could be executed at any random time not directly under your control (because flybywire might execute it even if you don't).

So what I'm talking about is the ability to do this:

lock var to x /y, unless y happens to be zero at this instant, in which case lock it to bigNum instead.

With a 'set' command, you can control when the check happens as shown above.

But since a lock has to all be one expression, the technique used for the set isn't quite right.

If something like C's trinary operator "?" was implemented, then you could protect lock expressions like this:

```
lock var to ( (y = 0) ? bigNum : x /y)
```

Obviously the syntax there isn't quite right for kosscript's terms.  Perhaps something like:

```
lock var to CHECK y = 0 TRUEVAL bigNum FALSEVAL x/y .
```

might look a bit more 'kosscript'-like.

As it stands, the only way to protect the expression is to lie about the contents of 'y' and pretend it's something like 0.000001 whenever it's really 0.0, which if you're using it elsewhere besides this lock expression, could be messy.

That's what I'm doing for now in my script to deal with this new change.  When the air pressure is really 0, I'm pretending it's 0.000001 just to keep the script from barfing out.

**Comment by Dunbaratu** [comment]
This seems a bit silly to be doing when we don't even have short-circuiting for normal boolean and/or yet.  It would be weird and hard to write user documentation explaining it if we had a '?' operator that *does* short-circuit, when normal boolean operations don't.

I figure we come back to this after vanilla ``and`` and ``or`` do short-circuiting.

**Comment by crafty-geek** [comment]
Nudge: Vanilla AND and OR now short-circuit

**Comment by firda-cze** [comment]
`SET var TO a IF cond ELSE b.`

this is python-style ternary ;)
`ifTrueExper IF cond ELSE ifFalseExpr`
