### ISSUE TITLE
Timespan doesn't seem to use the right number of days per year for Kerbin

### ISSUE THREAD

**Issue by ElWanderer** [KSP-KOS/KOS#1800]
I have a stock v1.1.3 install, aside from kOS (v1). The stock game clock is set to 6-hour days, so I am expecting game years to be 426 days long.

I noticed that the MET timestamps I logged out didn't match what KSP was displaying a few years into a mission. The disparity in days/years could be explained by the TIME:CALENDAR, TIME:DAY and TIME:YEAR using Earth's year length rather than Kerbin's. I thought I ought to check the KUNIVERSE:DAYSPERHOUR setting before raising this as an issue, then promptly forgot about it until tonight. Now I've checked, and the hours per day setting is definitely 6.

Screenshot showing that kOS and KSP disagree on the UT year and day:
![koscalendar](https://cloud.githubusercontent.com/assets/16566715/18181838/29d023d2-7085-11e6-9672-814ea0b51df2.png)

Looking in Timespan.cs it seems the lengths of both Kerbin and Earth years are calculated using/assuming a 365-day year:

```
    private const int DAYS_IN_YEAR = 365;

    private const int SECONDS_IN_KERBIN_YEAR = SECONDS_IN_KERBIN_DAY * DAYS_IN_YEAR;

    private const int SECONDS_IN_EARTH_YEAR = SECONDS_IN_EARTH_DAY * DAYS_IN_YEAR;
```

**Comment by hvacengi** [comment]
Huh, I had no idea that the game year was that long.  I wonder if we can find this value some where in the game settings rather than hard coding it.

**Comment by Efratror** [comment]
The kerbin year is it's oribital period (2556.6 hours =  426,08 days) for futher info see the wiki http://wiki.kerbalspaceprogram.com/wiki/Time

**Comment by ElWanderer** [comment]
I'd not realised the orbital period wasn't a round number of days (works out at 426 d 0 h 32 m 24.6 s according to the wiki) - does anyone know if KSP models a 32-minute 427th 'day' or if the years are 426d precisely with the location of "day 1" point slowly moving each year?

**Comment by ElWanderer** [comment]
From playing around with the terminal, it looks like MET is calculated based on one Kerbin year = 426 days = 426 * 6 * 60 * 60 seconds.

MET is displaying T+ 2y, 83d, 00:40:00 (give or take a few seconds)

    PRINT ROUND(MISSIONTIME).
    20198402

    // calculate based on one year = 426.08 Kerbin days
    PRINT (((426.08 * 2) + 83) * (6*60*60)) + (40*60).
    20201856

    // calculate based on one year = 426 Kerbin days
    PRINT (((426 * 2) + 83) * (6*60*60)) + (40*60).
    20198400
