### ISSUE TITLE
Sphinx building doesn't handle new sphinx and python versions

### ISSUE THREAD

**Issue by jacktose** [KSP-KOS/KOS#1825]
Using `sphinx-build` with python 3 spits the following error:

```
Exception occurred:
  File "C:\path\to\repo\KOS\doc\ksdomain.py", line 263, in get_objects
    for (typ, name), docname in self.data['objects'].iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```

That's because `iteritems()` was renamed to `items()` in python 3.
---

Using sphinx version 1.4.0 or above spits tons of errors like these:

```
C:\path\to\repo\KOS\doc\source\addons\IR.rst:None: WARNING: 4 column based index found. It might be a bug of extensions you use: [('single', 'IRAddon [struct]', 'structure:IRADDON', '')]
C:\path\to\repo\KOS\doc\source\addons\IR.rst:None: WARNING: 4 column based index found. It might be a bug of extensions you use: [('single', 'IRAddon:AVAILABLE', 'attribute:IRADDON:AVAILABLE', '')]
C:\path\to\repo\KOS\doc\source\addons\IR.rst:None: WARNING: 4 column based index found. It might be a bug of extensions you use: [('single', 'IRAddon:GROUPS', 'attribute:IRADDON:GROUPS', '')]
...
```

A quick googling shows that's a common issue after upgrading to sphinx 1.4.0+. [This post](https://github.com/sphinx-doc/sphinx/issues/2673#issuecomment-226076269) describes it succinctly. It can be easily avoided [as shown here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=827622#10).
---

In fact, both issues can be easily avoided by a conditional check in `ksdomain.py`.

I have submitted such a change in [PR 1826](https://github.com/KSP-KOS/KOS/pull/1826).

**Comment by jacktose** [comment]
https://github.com/KSP-KOS/KOS/issues/1834 referenced this issue, but didn't merge https://github.com/KSP-KOS/KOS/pull/1826, or anything else dealing with this issue.

I have replicated the above errors after updating to the latest develop branch, so I suggest reopening this issue and merging https://github.com/KSP-KOS/KOS/pull/1826.

**Comment by Dunbaratu** [comment]
I merged the PR into develop just now.  Can you confirm that it fixed the problem?

**Comment by jacktose** [comment]
Updated to develop and built (Python 3.5.2 and Sphinx 1.4.8). Neither Python or Sphinx was an issue. The errors are gone. So yep, fixed. Thanks!
