### ISSUE TITLE
kOS Terminal unable to be opened

### ISSUE THREAD

**Issue by TheVinicombe** [KSP-KOS/KOS#1828]
I am running the latest KSP with Flight engineer and yesterday I downloaded and added kOS. 
The parts are available to me, I've added them to the ship and clicked 'open terminal' after launching.
But I have never been able to get the terminal to open!
I've seen in videos what the terminal looks like and I can see how mine is different:
![image](https://cloud.githubusercontent.com/assets/22512928/18940209/b382c8be-8638-11e6-9efc-c3fd785c0847.png)
Can you suggest what I'm doing wrong, what I should try to get it to work?

**Comment by TDW89** [comment]
This is usually a symptom of an incorrect instillation of KOS. I would recommend you check the that the folder structure is correct it should be `[ksp directory]\GameData\KOS`.
Beyond that deleting the KOS folder, (if you are on steam) running steams "verify integrity of game cache" then re-downloading KOS and installing it again should eliminate / reduce the possibility that something is missing in the base game or that your original download of KOS was corrupted.

If none of that works your ksp log files will probably be needed to work out whats going wrong.

**Comment by Dunbaratu** [comment]
This looks like it's throwing an exception halfway through the process of "painting" the kOS window right where it tries to draw that icon, and thus doesn't finish drawing the rest of the panel.  The most likely cause would be a mangled installation of kOS that's missing some files or has them in the wrong place or somehow got them corrupted.  I suppose it's possible for there to be some other reason it throws an exception there, but that seems the most likely reason.  If it still persists after wiping out the installation and re-downloadig it and re-installing it, then post the error log file here and we can have a look at what the actual exception is.

**Comment by TheVinicombe** [comment]
Hi fellas
I verified the cache integrity, it returned 9 bad things, but I don't think that that was the problem (thanks for that suggestion though).
Then I removed and reinstalled kOS and realised that I had been extracting it incorrectly. It had been structured as:
[ksp directory]\GameData\GameData\KOS
It's now structured as it should be and it seems to be working :)
              Cheers fellas
![image](https://cloud.githubusercontent.com/assets/22512928/18982515/630037fa-8719-11e6-9f87-118d5b7b452d.png)
