### ISSUE TITLE
Timespan appears to have no 'constructor' function.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#183]
In going through all the documents trying to explain things better, I've discovered that the Timespan doesn't seem to have the same sorts of constructor function everything else has.

In other words, I can tell people "You can make a maneuver node with SET X TO NODE(a,b,c,d)" and "You can make a Vector with SET VEC TO V(a,b,c)" and so on…

but I can't say "You can make a Time with SET T to …..uh… to…………….."

It seems the only variable of type Timespan that exists in the entire kOS system is the current-time bound to the identifier TIME.

Which is weird because the Timespan class has lots of work done to enable the arithmetic operators to add two Timespans' together, or subtract them…. but…the only way they'll ever be used is when it's Timespan + double or Timespan + integer, because Timespan + Timespan presumes there's two different timespans in users' variables.

I think there should exist functions that return Timespans, like:
- SET T TO DATETIME( year, day, hour, minute, second).
- SET T2 TO TIME + T.

**Comment by erendrake** [comment]
sweet, lets do it!

**Comment by hvacengi** [comment]
Now that we have the ability to have variable argument counts, we could create 2 constructors: `datetime(year, day, hour, minute, second)` (as @Dunbaratu listed above) and `datetime(totalseconds)`.  That gives an easy way to do both epoch and to create a timespan object based on `datetime(time:seconds + x)` (not that I'm sure what good that last scenario does for us, but it would be a valid use).

**Comment by dewiniaid** [comment]
Worth noting that something like this exists as 
 Styling with Markdown is supported
Comment
a workaround:

```
GLOBAL K_EPOCH IS TIME-TIME.  //Timespan 0.

// ....

LOCAL t IS K_EPOCH+60.  // One minute from epoch.
```

I agree that the workaround shouldn't be needed though.

**Comment by Dunbaratu** [comment]
Already have this constructor - old issue didn't get closed.
