### ISSUE TITLE
`global` doesn't work for functions as mentioned in the documentation

### ISSUE THREAD

**Issue by SchwarzChristian** [KSP-KOS/KOS#1831]
The [documentation](http://ksp-kos.github.io/KOS_DOC/language/variables.html#explicit-scoping-keywords) says "The DECLARE, FUNCTION, and LOCK commands can be given explicit GLOBAL or LOCAL keywords to define their intended scoping level[.]", but if i try
```
{
  global function hello {
    print "Hello, World!".
  }.
}

hello().
```

kOS says
```
run test.
Program ended.
  global function hello {
    print "Hello, World!".
  ^
line 2, col 3: 'GLOBAL' command found in a function declaration. It only works in a variable declaration.
At interpreter, line 18
run test.
    ^
```
`local` works fine.

Seems like an error in the documantation, but having global functions would be nice ;)

**Comment by Dunbaratu** [comment]
The documentation should be fixed.  But having global functions already is possible.  Just not by declaring global scope from inside local scope.
If you want to do that, you can assign a local function delgate to a global name:
```
{
  function aaa { print "aaa". }
  global bbb is aaa@.
}
bbb().
```

**Comment by SchwarzChristian** [comment]
Sure, or for short, you can declare the function as a delegate directly.
`global hello is { print "World!". }.`

A global function would certainly be more descriptive, but the workaround is ok.

Btw., thanks for the great mod!

**Comment by Dunbaratu** [comment]
Well, the other question that immediately comes up is ... if you wanted the function to be global why not just declare it outside the scoping braces and then you don't need to mess with delegates.

**Comment by SchwarzChristian** [comment]
Encapsulation. I have a library that needs local state and i don't want to publish it. But to access the local state from the libraries functions, they need to be in the same scope.
