### ISSUE TITLE
Procedural simple sound system

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#1832]
(What I'd like to see is a feature that will work similarly to the old Commodore 64 SID chip and similar systems).

For making it so users can implement their own sounds emitting from scripts, it has been suggested that they be able to drop their own WAV or MP3 files into the archive and we play them like we play our own internal sounds.  The problem I have with this suggestion is that such files are big, and the disk size is limited.  We'd have to either abandon the idea of old-school disk size limits, or break the 4th wall again by having access to those files live "outside" the normal system.

I'd like to try implementing a means for people to make simple computery sounds from their scripts by letting them say things like "I'd like a sawtooth wave, for 0.5 seconds at volume 0.2 please...".

It may be possible to improve upon the system with attack/sustain/decay envelopes, and so on later, but even just getting a simple "make it beep at the frequency you say so" would be enough of a start to let people start adding that to their user interfaces for things.

**Comment by JCariveau** [comment]
I've only barely looked at it, but hooking MIDI would be my recommendation, saw an example for (older) vb.net that claimed `Sound(Waveform, Frequency, Duration)` would be easy at that point... Not sure how that translates Mono/Multi Platform, as the example shows hooking a system .dll (unmanaged?)

Also, most C64 music (SIDPlayer) is listed as MIDI files.

**Comment by Dunbaratu** [comment]
This didn't auto-close when #1859 was merged.  Closing it manually.
