### ISSUE TITLE
Support for KSP 1.2

### ISSUE THREAD

**Issue by hvacengi** [KSP-KOS/KOS#1835]
Simple placeholder issue for compiling against KSP 1.2 and making necessary modifications to build.

Notable TODO notes following my first push:
- [x] TransferManager.cs https://github.com/hvacengi/KOS/blob/experimentals/src/kOS/Execution/TransferManager.cs#L53
- [ ] ActiveResourceValue.cs https://github.com/hvacengi/KOS/blob/experimentals/src/kOS/Suffixed/ActiveResourceValue.cs#L30
- [ ] ScienceDataValue.cs https://github.com/hvacengi/KOS/blob/experimentals/src/kOS/Suffixed/ScienceDataValue.cs#L39
- [x] Utils.cs https://github.com/hvacengi/KOS/blob/experimentals/src/kOS/Utilities/Utils.cs#L317
- [x] VesselUtils.cs https://github.com/hvacengi/KOS/blob/experimentals/src/kOS/Utilities/VesselUtils.cs#L13

**Comment by hvacengi** [comment]
Notable TODO notes following my first commit:
- [ ] TransferManager.cs https://github.com/hvacengi/KOS/blob/experimentals/src/kOS/Execution/TransferManager.cs#L53
- [ ] ActiveResourceValue.cs https://github.com/hvacengi/KOS/blob/experimentals/src/kOS/Suffixed/ActiveResourceValue.cs#L30
- [ ] ScienceDataValue.cs https://github.com/hvacengi/KOS/blob/experimentals/src/kOS/Suffixed/ScienceDataValue.cs#L39
- [ ] Utils.cs https://github.com/hvacengi/KOS/blob/experimentals/src/kOS/Utilities/Utils.cs#L317
- [ ] VesselUtils.cs https://github.com/hvacengi/KOS/blob/experimentals/src/kOS/Utilities/VesselUtils.cs#L13

**Comment by Dunbaratu** [comment]
Are you saying these are TODO's for yourself before you remove the "not ready" tag?

**Comment by hvacengi** [comment]
No, I'm making a separate list of todos so that I can remove the not ready label, and remove the link that would close this issue when the PR is merged.

I don't want to do a pre-release without the code merged, but I don't want to merge without making sure we know that there are things to re-visit.  I'm running a test now, but will be pushing a commit that will let me check a few of these off the list.

**Comment by Dunbaratu** [comment]
Ah so it would be okay for me to merge this with the above TODO's still unresolved.  That's good.  I was hoping to get to this tonight.
