### ISSUE TITLE
VesselSensors.cs is pulling data from active vessel NOT CPU Vessel

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#184]
As I was trying to finish documenting everything I noticed that VesselSensors.cs is pulling data from the FlightGlobals and NOT from the actual sensors in question.  It checks for if the right sensor exists, but then takes data from FlightGlobals.

What this means is that if the CPU Vessel (i.e. Shared.Vessel) is not the same as the Active vessel, then the CPU running this code will be taking readings from the wrong Vessel.

**Comment by erendrake** [comment]
This appears to be fixed
