### ISSUE TITLE
"Stage:ResourcesLex["LiquidFuel"]:Amount" and "Stage:LiquidFuel" return different values.

### ISSUE THREAD

**Issue by zamadatix** [KSP-KOS/KOS#1840]
I noted this problem in [this Reddit post](https://www.reddit.com/r/Kos/comments/55lgr7/problems_with_stageresources/) but figured I should make an official bug report for tracking.

Under certain conditions outlined below (mainly referencing [this general craft design](http://i.imgur.com/bcqD5p5.png) "Stage:ResourcesLex["LiquidFuel"]:Amount" will return a different value than "Stage:LiquidFuel". This difference is equal to the additional liquid fuel in the (yet un-reached) final stage. Remote Tech is used which may slightly changed the steps required to reproduce.
- An antenna MUST be attached anywhere below the bottom (secondary) Remote Guidance Unit.
- An antenna MUST be attached above the top (main) Remote Guidaince Unit.
- There MUST NOT be a decoupler between the antenna and the Remote Guidance Unit

Other interesting tidbits:
- Any other logical antenna arrangement DOES NOT cause the values to differ.
- Adding a decoupler above the top Remote Guidance Unit and attaching the upper antenna to that DOES fix the value difference.
- Moving the part the antenna is attached to +/- a stage without adding a decoupler DOES NOT change the behavior.

The following was captured while landed at the launchpad with nothing changing inbetween lines:

```
print Stage:ResourcesLex["LiquidFuel"]:Amount.
900
print Stage:LiquidFuel.
720
print Stage:ResourcesLex["LiquidFuel"]:Amount.
900
print Stage:LiquidFuel.
720
```

I can provide a copy of the craft file and any additional information that may be needed as requested.

**Comment by hvacengi** [comment]
This one still baffles me.  An antenna _shouldn't_ have any bearing on the fuel calculation... but I've seen stranger things.  There was a previous report that using the radial mount MechJeb part as a probe core mounted in a very specific configuration did the same thing.

All of the fuel logic is getting revised with KSP 1.2.  When we post a pre-release for testing purposes, can you try to replicate this with that version as well?

**Comment by zamadatix** [comment]
Would be glad to test it out in 1.2 when the pre-release is posted.

**Comment by hvacengi** [comment]
In theory PR #1893 should fix this issue too.  But if it isn't fixed after release, please feel free to open this back up.
