### ISSUE TITLE
files not executing properly

### ISSUE THREAD

**Issue by KingHandspider** [KSP-KOS/KOS#1854]
I've installed kOS correctly, and everything is working properly, except files. Commands by themselves (etc. set throttle to 0.75.) work fine outside of the files. When I execute a file, the first line gets executed and then the program ends. I have ensured that the syntax is correct (to the best of my knowledge).
Notable things:
MacBook Air
OS X El Capitan 10.11.3
KSP latest version of 1.2
most current version of kOS
Ship was loaded on the launch pad
Ship was a Kerbal X with the 1.25m SCS under the parachute
Mods installed were: kOS, Surface Lights, Airplanes plus
Searched the log (Player.log, not KSP.log) for exceptions ("  at"), found none.
File was saved in archive volume.

**Comment by hvacengi** [comment]
We will also need the file you were attempting to run in order to try and reproduce the issue.

**Comment by KingHandspider** [comment]
[kerbxr.txt](https://github.com/KSP-KOS/KOS/files/548142/kerbxr.txt)
(note that I converted a copy of the original to a .txt file so i could upload it)
it is in the standard location (KSP > ships > script)

**Comment by hvacengi** [comment]
You're program is ending after line 2 and unlocking the controls.  See here: http://ksp-kos.github.io/KOS_DOC/commands/flight/cooked.html#unlocking-controls  If you modify your file to do something else on line 2, you will find that a print statement works just fine.

>When the program ends, these automatically unlock as well, which means that to control a craft you must make sure the program doesn’t end. The moment it ends it lets go of the controls.

You must "wait" in some way to prevent the program from ending.  Something like `wait 10.` will just give 10 seconds before reverting controls.  You could instead do an until loop to wait:

```
sas on.
lock throttle to 0.8.
until (altitude > 1000) {
    // do something
    wait 0.
}
```

Please read our [quick start guide ](http://ksp-kos.github.io/KOS_DOC/tutorials/quickstart.html) for pretty decent introduction to how to make controls work.

**Comment by KingHandspider** [comment]
thank you again
