### ISSUE TITLE
Signal delay progress bar ignores terminal resize - draws in the wrong spot.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#1860]
This has always annoyed me a little and I think I saw the cause of it.

In RemoteTechInterpreter.cs (which is about to become renamed to ConnectivityInterpreter.cs as part of PR #1850 , which will probably be merged in before this issue is resolved, so look for it there), we have these lines:

```
        private void CreateProgressBarSubBuffer()
        {
            progressBarSubBuffer = new SubBuffer();
            progressBarSubBuffer.SetSize(3, ColumnCount);
            progressBarSubBuffer.Fixed = true;
            progressBarSubBuffer.PositionRow = RowCount - progressBarSubBuffer.RowCount;
            AddSubBuffer(progressBarSubBuffer);

            var separator = new string('-', progressBarSubBuffer.ColumnCount);
            progressBarSubBuffer.Buffer[0].ArrayCopyFrom(separator.ToCharArray(), 0, 0);
        }
```
These measurements like RowCount and ColumnCount are only queried when the Interpreter was first constructed, and then they get stuck that way for the life of the interpreter.  If you stretch or shrink the window, then all the progress bars being drawn for signal delay get messed up because it never reassigns these values for `progressBarSubBuffer` to match the new size.

**Comment by hvacengi** [comment]
Sounds like we need to hook an update in the resize handler, like where we round the size to "whole" character widths.

I might be able to make the changes as part of the pending PR... but it's already really big.  So, we'll save that for the full release.
