### ISSUE TITLE
Note To Self:  Fiddle with terminal brightness a bit before next release.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#1864]
I've been meaning to fix this for a while and keep forgetting to - it's probably just a tiny one or two line change too.

The current default brightness on the slider is too dim for the terminal.  This is probably because I put it at the halfway point of a linear scale when perception of brightness is actually a non-linear phenomenon.  But at any rate the default brightness is kind of dim and everyone always adjusts it up as the first thing they do on loading it.

Also, let's try to make the default brightness a persisting slider in the preferences panel.

**Comment by hvacengi** [comment]
That should be pretty easy to add to the "difficulty" settings, unless you want to keep it a global value.
