### ISSUE TITLE
Log/writeln can't write when file is open for reading

### ISSUE THREAD

**Issue by gisikw** [KSP-KOS/KOS#1866]
Was playing around with an idea for exporting data from a craft into a live dashboard, ideally through writing to file. However, if a file is open for reading, kOS crashes on write.

*Unix env:* `tail -f Ships/Script/test.log` (echo new lines as they're written)
*kOS:* `open("0:/test.log"):writeln("Test").`

*Result:* Sharing violation on path %GAMEDIR%/Ships/Script/test.log

Not sure how solvable this is, and I'm sure it's low-priority, but I believe it's the only way to get data *out* from kOS, aside from trying to write some scraper around a telnet connection.

**Comment by Dunbaratu** [comment]
Whether or not more than one process can open the same file at the same time is one of the areas where Windows differs from Unix.  Windows still shows its roots in having previously been a rather simple single-user OS in the fact that it presumes *allowing* multiple processes  to open the same file simultaneously is the exception.  On the other hand, Unix presumes the opposite, that *preventing* it should be the exception and the OS should just assume it's operating in an environment with many users needing to look at the same file at the same time that some part of the system is still writing to (i.e. this is precisely the `tail -f` scenario you're trying to do here).

That being said, both Windows and Unix *do* support doing it either way (lock the file when its open for writing, or don't).  The difference is in just which of the two you get *by default* versus which of the two you have to add some additional bit of code to change the default (where you have to go look up "now how the heck do that again?")

**Comment by gisikw** [comment]
@Dunbaratu It looks like in this case, it's a default preference on the part of C#, but one that can be explicitly overridden. Threw up a PR that seems to fix the issue. :)

**Comment by Dunbaratu** [comment]
True, but the attitude prevalent in Windows is *why* it became the default in C# to prevent simultaneous access unless otherwise specified.  Lots of processes running at the same time looking at each others' files is normal systems operation in Unix.  It would make Unix sysadmin scripting more painful if every program did this locking by default except the few where people chose to make an exception.
