### ISSUE TITLE
Suspect code in src/kOS/Screen/KOSToolbarWindow.cs

### ISSUE THREAD

**Issue by WazWaz** [KSP-KOS/KOS#1875]
```
            GameEvents.onGUIApplicationLauncherReady.Add(AddButton);
            GameEvents.onGUIApplicationLauncherReady.Add(RemoveButton);
```

This does not look correct. Should the second line instead be using onGUIApplicationLauncher**Unreadifying**? I suspect it happens to work because the adds are done in reverse order (so RemoveButton is called, then AddButton).

**Comment by hvacengi** [comment]
This is one of those things that I just don't know how it works right now.  The best I can come up with is that `Add` might do something like
```
delegateValue = Delegate.Combine(newDelegate, delegateValue);
```
such that the newest delegate added is the first called.  In which case `RemoveButton` would be called before `AddButton`.

I tried commenting the line for `RemoveButton` and saw no adverse affects.  I'll try using `onGUIApplicationLauncherUnreadifying` tonight and try to figure out the implications of each.
