### ISSUE TITLE
Leaking kOSTermWindow objects badly

### ISSUE THREAD

**Issue by WazWaz** [KSP-KOS/KOS#1880]
I noticed using Kerbal Object Inspector that even time a craft is reverted, loaded, etc., 2 more objects named "kOSTermWindow" get created.

The cause for two seems to be that InitObjects() is called in both OnStart and in OnLoad.

The cause for them not being deleted is that InitObjects() calls DontDestroyOnLoad() of the object.

Some basic testing showed that everything still seems to work fine if the call to InitObjects from OnLoad and the DontDestroyOnLoad are removed.

**Comment by hvacengi** [comment]
I have a local optimization branch where I'm trying to address this, and many other memory issues.  The editor widow also needs this modification.

Im also addressing multiple exceptions thrown due to AGX missing and an error reverting to the editor.

**Comment by WazWaz** [comment]
I confirm this appears fixed now in develop.

**Comment by hvacengi** [comment]
Um... it shouldn't be fixed yet.  I haven't even made a pull request yet for my optimization branch.  But I am working on getting it ready to at least show the world, even if it doesn't make the next release (it probably won't, but maybe it gets reviewed quickly

**Comment by WazWaz** [comment]
Ugh, never mind, I'm an idiot, I forgot that I commented out those InitObjects() calls DontDestroyOnLoad() calls in my local files because it was bogging my system down so much while testing. I really hope your changes do get in!
