### ISSUE TITLE
Trajectories impact position not available even if I checked first that it is.

### ISSUE THREAD

**Issue by luovahulluus** [KSP-KOS/KOS#1899]
![screenshot0](https://cloud.githubusercontent.com/assets/7191086/21096958/e69a9f3a-c06a-11e6-9df7-44b79d6a07ca.png)
I have this line in the script:
	if ADDONS:TR:HASIMPACT PRINT ADDONS:TR:IMPACTPOS at(0,14).
Still, sometimes I get the impact position not available error, but only occasionally. I have a script for a high speed mun rover that frequently checks where the rover is going to land, so I have plenty of occasions where this could happen.

**Comment by hvacengi** [comment]
Can you provide a save file with a vessel ready with the script, or the script itself?  And maybe a log file from your crash?  It could be that you're experiencing some kind of race condition where trajectories is for some reason not yet finished with it's calculation.  I'd recommend ensuring that the calls to `hasimpact` and `impactpos` occur in the same physics tick by putting them as close as possible to your loop's `wait` condition (so you work with as small of a instruction count as possible) and increasing your IPU to 2000 (so it takes more instructions before it rolls over to the next physics tick).

**Comment by luovahulluus** [comment]
[impactpos_bug_rename_to_sfs.pdf](https://github.com/KSP-KOS/KOS/files/647275/impactpos_bug_rename_to_sfs.pdf)
It's a save file, but I didn't have winzip installed so just rename it to .sfs :) I couldn't upload it without renaming.
The script is in the craft. Just run p.ks and you can use z key to get up to 40m/s quicker. You'll get the bug eventually, I hope. I don't know where to find a log file from the crash.

**Comment by luovahulluus** [comment]
[impactpos_bug_rename_to_sfs.pdf](https://github.com/KSP-KOS/KOS/files/647275/impactpos_bug_rename_to_sfs.pdf)
It's a save file, but I didn't have winzip installed so just rename it to .sfs :) I couldn't upload it without renaming.
The script is in the craft. Just run p.ks and you can use z key to get up to 40m/s quicker. You'll get the bug eventually, I hope. I don't know where to find a log file from the crash.

**Comment by luovahulluus** [comment]
It helped to put `wait 0.` in front of the `if ADDONS:TR:HASIMPACT`.

**Comment by Dunbaratu** [comment]
I'm going to close this as too old to really work with (there's been a new trajectories update merged into develop.)  If the problem still exists after the next release, feel free to re-open this.
