### ISSUE TITLE
log spill

### ISSUE THREAD

**Issue by sebseb7** [KSP-KOS/KOS#1904]
seeing this the KSP unity player logfile: (1.2.1osx+1.0.2)

is this a known bug, or is more investigation useful?

> Timing0 threw during FixedUpdate: System.NullReferenceException: Object reference not set to an instance of an object
>   at kOS.Module.kOSVesselModule.cacheControllable () [0x00000] in <filename unknown>:0
>   at (wrapper delegate-invoke) Callback:invoke_void__this__ ()
>   at (wrapper delegate-invoke) Callback:invoke_void__this__ ()
>   at Timing0.FixedUpdate () [0x00000] in <filename unknown>:0
> 
> (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

**Comment by hvacengi** [comment]
That's part of the work around to make kOS work when "require signal for control" is selected, which locks out kOS control by default.  I've been using that work around for a pretty long time and haven't seen this error pop up.  Can you post the complete log?  The surrounding messages may help figure out when the error is being thrown, and if it occurs repeatedly it may be an issue.  More than likely, if it isn't being thrown continuously during flight it can be safely ignored.

Looking at the code, there's really only one place where the null ref could happen, in the property chain to get the CommNet settings.  If we can't narrow down the source of the issue, I may just add some null checking there to be safe.

**Comment by sebseb7** [comment]
[LOG 19:50:21.116] kOS: Saving and removing 0 pointers
[ERR 19:50:21.260] Timing0 threw during FixedUpdate: System.NullReferenceException: Object reference not set to an instance of an object
  at kOS.Module.kOSVesselModule.cacheControllable () [0x00000] in <filename unknown>:0
  at (wrapper delegate-invoke) Callback:invoke_void__this__ ()
  at (wrapper delegate-invoke) Callback:invoke_void__this__ ()
  at (wrapper delegate-invoke) Callback:invoke_void__this__ ()
  at (wrapper delegate-invoke) Callback:invoke_void__this__ ()
  at Timing0.FixedUpdate () [0x00000] in <filename unknown>:0

[LOG 19:50:21.263] kOS: FlightControl Binding

**Comment by hvacengi** [comment]
We'll need more of the log than just a few lines. Can you please post the complete log file?
