### ISSUE TITLE
SKID module is broken.

### ISSUE THREAD

**Issue by Efratror** [KSP-KOS/KOS#1910]
I tried to use the Sound/Kerbal Interface Device(SKID) but it won't let me use the structure voice. So if I want to `SET V0 To GetVoice(0).` it give's the "Undefined Variable Name 'getvoice' " error.

**Comment by hvacengi** [comment]
Are you sure you're using the most recent version of kOS?  I cannot reproduce the issue locally, but functions are loaded dynamically at run time so it's possible for an error to prevent fully reading all of the built in functions.  Can you please post an error log?  If there is an error loading functions you should have a message in the log file, and you should find other functions that are not loaded either.

**Comment by Efratror** [comment]
Hmm the version of kOS that's the problem, you guys released two new versions without me noticing. Thought that the sound module was build way way back but it's brand new. So I will update kOS.
