### ISSUE TITLE
Ship cannot communicate with itself with CommnetConnectivityManager

### ISSUE THREAD

**Issue by jberkman** [KSP-KOS/KOS#1911]
kOS 1.0.3, KSP 1.2.2, ship has a cpu core and non-relay antenna, on the runway at KSC:

```
print ship:connection:isConnected.
False
```

**Comment by hvacengi** [comment]
Odd.  I obviously must not have tried this when I was testing the implementation.  It's strange that KSP itself doesn't recognize that the origin and destination are the same vessel.  This should be an easy item to fix by adding a `vessel1 == vessel2 ||` to the path finding logic.
