### ISSUE TITLE
printat function is not documented

### ISSUE THREAD

**Issue by Tricky1702** [KSP-KOS/KOS#1920]
The keywords **print** and **at** are documented but the function **printat** that combines the 2 is not.

**Comment by Dunbaratu** [comment]
This is deliberate.  There's lots of syntax options that are backed by builtin functions under the hood.  If we document printat() then we'd also have to document load(), run(), etc, which have reasons not to expose them publicly.

**Comment by Dunbaratu** [comment]
Thanks for the feedback, but we have lots of open issues and need to manage them better, so I'm closing this right away so we don't forget about it for months and months and let it linger.
