### ISSUE TITLE
Cannot set target when window is out of focus

### ISSUE THREAD

**Issue by hvacengi** [KSP-KOS/KOS#1931]
This is a bit of a follow up to #1634.  One of the "features" of KSP's input locking is that it also locks out some features when the KSP window is not in focus, specifically target setting.  Until recently I thought this was a limitation we would simply need to live with.  As it turns out however Squad added an optional parameter to the `SetVesselTarget` method allowing us to specify if it should obey the input locking.  So if we modify our call to it (VesselUtils.cs, line 159) to pass `true` for that parameter, we should be able to eliminate this limitation.

**Comment by Dunbaratu** [comment]
Just a note on re-creating this problem as I try to test the fix.  It seems the problem (pre-fix) only manifests when you click the terminal window and then click outside the KSP window entirely (i.e. you have to run KSP in windowed, not full-screen to be able to test this).  If you focus the terminal but stay within the game window when you do so, the original bug doesn't seem to happen.)

It took me a few tries to figure that out, as I wanted to recreate the problem first before I looked at the solution.
