### ISSUE TITLE
"open terminal" event should work as a toggle

### ISSUE THREAD

**Issue by pellinor0** [KSP-KOS/KOS#1936]
I'd like to to close the terminal window from a script. The use case is the following:
* first a boot file does its things and if it runs into errors I want to see them (so I fire the event there)
* if the script thinks there is nothing more to do, it shuts down the core. So I end up with an inactive terminal that I can only close by hand. 

A straightforward solution would be to have the button act as a toggle, like "toggle power" already does.

**Comment by ozin370** [comment]
This would break some of my scripts. Better to have an action "open terminal" become available when the terminal is closed and vice-versa with a "close terminal" action when it is open.

**Comment by hvacengi** [comment]
Is there a reason that you can't just call the "Close Terminal" action to close it?  I use the following functions in my own scripts:
```

function CloseTerminal {
	core:doaction("Close Terminal", true).
}
function OpenTerminal {
	core:doaction("Open Terminal", true).
}
```
I use these functions in many of my scripts and both work without issue.

You could also call the "Toggle Power" action
```
core:doaction("Toggle Terminal", true).
```
But relying on "toggle" ignores the fact that the terminal can be opened or closed by the user without the script knowing.

Does this solve your problem?

**Comment by pellinor0** [comment]
Ah, interesting. Yes this solves my issue. 

I rarely use action groups and usually those are identical to the available action buttons. So I forgot to double check if there are additional actions available. 

Now that I think of it, it also makes sense that a close event is missing because the user already has a close button at the terminal window. So I'll close the issue.
