### ISSUE TITLE
Incorrect true anomaly?

### ISSUE THREAD

**Issue by MorpheusFT** [KSP-KOS/KOS#1957]
I had 2 craft in circular orbits, at the time 180 degrees apart.

print(ship:orbit:trueanomaly)     gave about 275
print(targetVessel:orbit:trueanomaly) gave about 251

The values did change with time, but the difference in degrees was not even close to 180.

Am I missing something or does :trueanomaly give incorrect values?

**Comment by hvacengi** [comment]
True anomaly is not a universal measurement.  It is defined as the angle between your current position in the orbit and the periapsis.  So the only way to "sync" the true anomaly is to have the same longitude of ascending node and argument of periapsis (the two orbital parameters that determine where in the universe your periapsis is located).

**Comment by MorpheusFT** [comment]
Ah, in that case my mistake. Forget I said anything.
