### ISSUE TITLE
Support underscores in numbers

### ISSUE THREAD

**Issue by fizker** [KSP-KOS/KOS#1978]
When writing big numbers (which, because KSP counts distance in meters, happens quite often), putting in underscores to group digits would greatly increase readability. This would be a great alternative to scientific notation, as I find numbers with less than 10 digits harder to read with scientific notation compared to the full number.

The rules for a valid number would be:

- Whatever consists of a valid number today
- An underscore must be surrounded by digits
- There are no limits to the number of digits between underscores. This avoids cultural issues (The [Indian numbering system](https://en.wikipedia.org/wiki/Indian_numbering_system) groups digits differently that the western system)

This would not change the meaning of the number, only how a human or kerbal would read the number.

Both Swift and C# 7 have the same feature.

Some examples:

| Name                | Raw      | Scientific | With underscores (western) | With underscores (indian) |
| ------------------- | -------- | ---------- | -------------------------- | ------------------------- |
| Kerbin Atmos        |    70000 |        7e4 |                     70_000 |                    70_000 |
| Kerbin spacestation |   150000 |       15e4 |                    150_000 |                  1_50_000 |
| Mun orbit           | 12000000 |       12e6 |                 12_000_000 |               1_20_00_000 |

**Comment by Dunbaratu** [comment]
I have never heard of this convention used in any programming language before, but I guess it doesn't really break anything to add it.

**Comment by hvacengi** [comment]
I guess the question is whether or not this format is supported in the version of C# used by KSP/Unity.  If all we need to do is modify the regular expression used to recognize numbers, it shouldn't be an issue.  Even if it isn't supported by our version of C#, it should just be a matter of calling `Replace("_", "")` before passing it to the parse method.

**Comment by Dunbaratu** [comment]
A;though this isn't really on the path for Milestone 1.1.0, The alteration of the parser regex for multinational identifiers *is*, and this is like right next to it in the code so I may as well implement this while my fingers are in there.
