### ISSUE TITLE
Surface sample from a command seat is available before any facility upgrades.

### ISSUE THREAD

**Issue by sshilovsky** [KSP-KOS/KOS#1985]
In career mode facilities are required to be upgraded in order to collect surface samples, which is not respected by kOS.

### How to reproduce:

In a craft with Command Seat manned by a kerbal:

    set kerbal to ship:partsnamed("kerbalEVA")[0].
    print kerbal:allmodules.
        LIST of 15 items:
        [0] = "KerbalEVA"
        [1] = "ModuleScienceExperiment" // <- these are of interest
        [2] = "ModuleScienceExperiment" // <- these are of interest
        [3] = "ModuleScienceContainer"
        ...
    print kerbal:getmodulebyindex(1). // <- checking first
        ModuleScienceExperiment, containing:
        LIST of 2 items:
        [0] = "(callable) deploy, is KSPAction"
        [1] = "(callable) discard sample, is KSPAction" // <- surface sample
    print kerbal:getmodulebyindex(2). // <- checking second
        ModuleScienceExperiment, containing:
        LIST of 3 items:
        [0] = "(callable) eva report, is KSPEvent" // <- not surface sample
        [1] = "(callable) eva report, is KSPAction"
        [2] = "(callable) discard report, is KSPAction"
    
    set sample to kerbal:getmodulebyindex(1). // <- surface sample
    sample:deploy.
    print sample:data[0]:dataamount.
        21 // <- oops!

**Comment by Dunbaratu** [comment]
Have you verified that this only exists because of kOS?  (i.e. can you perform the same thing manually by using the rightclick menu on the kerbal in the seat?)

It would be very strange if kOS is allowing this but the manual game controls aren't.  The check kOS performs to see whether or not to expose a KSPEvent *is* to check its visibility on the rightclick menu.  It would be weird if the game is reporting to kOS that the button is present on the panel if it's actually not.

**Comment by sshilovsky** [comment]
Yeah, surface sample is unavailable from the context menu.

**Comment by Dunbaratu** [comment]
Milestone moved to v1.1.1 because the PR associated with this was moved to v1.1.1 (see PR #1993 for the explanation why).

**Comment by hvacengi** [comment]
As commented on in the PR that attempted to fix this ( #1993 ), we cannot find a way to satisfy all 3 conditions, most specifically the inability to prevent the dialog box from being displayed requiring manual confirmation.  As such, we're going to mark this as "won't fix" for now, and will look into revisiting it in future versions of KSP.

**Comment by Dunbaratu** [comment]
Milestone cleared because this is in "wontfix" status.
