### ISSUE TITLE
Kerbalism Support

### ISSUE THREAD

**Issue by eberkain** [KSP-KOS/KOS#1989]
Kerbalism has its own comm network system that is an alternative to stock or remote tech.   Could we get another connectivity manager of kOS that would support it?

**Comment by SirMortimer** [comment]
Kerbalisms own comm network implementation has been removed for a couple of releases now.

I think this issue can be closed.

**Comment by Dunbaratu** [comment]
I don't use Kerbalism so I didn't know about this.  It makes sense though, come to think of it, given that Kerbalism never wanted to have signal delay it would make sense for it to just use the stock CommNet once that started existing.
