### ISSUE TITLE
Key clicker stopped working.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#1996]
It's not that important, but something I did recently seems to have made the keyclicker fail to make sound.  Since it's probably caused by one of the recent milestone 1.1.0 changes, fixing it should be in 1.1.0 as well.

It probably is related to when I moved a few things around in the AssetManager.  I'll investigate later to find out what.

**Comment by Dunbaratu** [comment]
Okay I examined it and it turns out the game *IS* playing the sound - as far as the code is concerned.  (i.e. I traced it and it *does* get to the ``source.Play();`` call, and the source *is* the key clicker sound... And there was no complaint about the wav file not loading, and the volume is maxxed..... so.... No clue.)

**Comment by hvacengi** [comment]
I'll try it with the debugger and see if I can make sure the wave form is actually loading properly.  Maybe that will help track down the issue.

**Comment by Dunbaratu** [comment]
I also noticed that the audio error beep sound is silent too in the same way.  They both work through the same system and play the same way so it's probably the same bug, whatever it is.

**Comment by Dunbaratu** [comment]
Changing assignment to @hvacengi because he said in Slack he had found a solution and was going to make a PR for it.

**Comment by hvacengi** [comment]
Thanks for doing that, since I just finished making the modification in my code and was wondering if we had an issue for it.  PR will be inbound soon.
