### ISSUE TITLE
ORBIT:VELOCITY doc page inconsistency

### ISSUE THREAD

**Issue by pand5461** [KSP-KOS/KOS#2018]
Current doc page says that Orbit:VELOCITY suffix return type is Vector while it's actually OrbitableVelocity.

**Comment by hvacengi** [comment]
This was fixed in PR #2015 and is temporarily rendered at http://hvacengi.github.io/KOS/structures/orbits/orbit.html#attribute:ORBIT:VELOCITY while v1.0.90 is in pre-release prior to v1.1.0.
