### ISSUE TITLE
user-specifiable throttle behavior on program death

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#202]
When you LOCK THROTTLE during a program and then the program dies either though error of through normal exit, kOS restores the throttle to it's previous setting, which in 0.24 is typically now 50% instead of 0%, unless the user manually throttled down first before running a launch program.  Because of the goal of letting people run auto-boot programs on launches, telling the user to _manually_ bring the throttle down to 0 before launching programs isn't really a workable answer.  With an auto-boot script, there is literally no way for a program to put the throttle at 0% on program exit.  You must have manual control, and use manual control to set it to 0% before launching, which means the auto-boot script cannot perform the launch itself.  The user must use the command line to manually RUN something in order for the window of opportunity to manually bring the throttle to 0 beforehand to exist.

There are times when having the software set the throttle to 0 on program death is right.  There's times when it's not.  I suggest adding an "exit state" setter - where the code can run a command that says up front "Upon exit, leave the controls as follows....", and then whenever kOS aborts the program prematurely because of an exception or it terminates the program nicely because it finishes, the last thing it does is set the controls to the state the code said, rather than to whatever they were set to before the program was run.

**Comment by Blacksilver42** [comment]
This page came up first in a google search, instead of #207, so here's what to do:

`SET PILOTMAINTHROTTLE TO 0.`
