### ISSUE TITLE
GUI Slider docs claim ONCHANGE takes a string.  It takes any object.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#2023]
The docs for GUI Slider claim ONCHANGE is a delegate taking a string.  Actually it takes whatever the slider's value happens to be, which is probably a Scalar.  This is probably a cut and paste error in the docs.

**Comment by hvacengi** [comment]
Yeah, it's on me.  I double checked with the popup window, but didn't do so with the slider.  I'm not really sure why I did that.
