### ISSUE TITLE
Compatibility with KSP 1.3

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#2039]
Now that it's a full release and not pre-release, let's have an issue to handle the changes needed to make things work with KSP 1.3.

The remit of this issue is just making things work, not about using any new features or enhancements or anything like that.

**Comment by Atllan** [comment]
Yeah, that would be quit nice. I`ve just started playing. And i understood that it is difficult to do accurate maneuver, for example - reaching geostationary orbit right over operational center, without scripts. So please, change version)
