### ISSUE TITLE
Script loses control after reloading saved game

### ISSUE THREAD

**Issue by valery-labuzhsky** [KSP-KOS/KOS#2051]
My scenario is following:
0. I have vessel with 2 processor in it. It is saved just before separation.
1. Game is loaded
2. Vessel is separated
3. Each subvessel can control itself
4. The same game is loaded again
5. Vessel is separated
6. Some (both or none) of subvessels lose control

It seems to be random if subvessel looses control or not.
My (enhanced) logs are following:
[LOG 11:47:45.670] kOS: FlightControlManager.AddTo ce754e80-f6dc-4221-8144-c49ddd9c4270
[LOG 11:47:45.777] kOS: FlightControlManager.AddTo ce754e80-f6dc-4221-8144-c49ddd9c4270
[LOG 11:47:49.687] kOS: FlightControl Binding
[LOG 11:47:49.687] kOS: FlightControl Bound
[LOG 11:47:57.226] kOS: kOS.Binding.FlightControlManager:Update(currentVessel = null)!
[LOG 11:47:57.226] kOS: kOS.Binding.FlightControlManager:Update(currentVessel = Shared.Vessel)!
[LOG 11:47:57.254] kOS: FlightControl Binding
[LOG 11:47:57.254] kOS: FlightControl Bound
[LOG 11:48:06.275] kOS: kOS.Binding.FlightControlManager:Dispose()!
[LOG 11:48:06.275] kOS: kOS.Binding.FlightControlManager:Dispose: currentVessel: null
[LOG 11:48:06.279] kOS: kOS.Binding.FlightControlManager:Dispose()!
[LOG 11:48:06.279] kOS: kOS.Binding.FlightControlManager:Dispose: currentVessel: null
[LOG 11:48:08.712] kOS: FlightControlManager.AddTo ce754e80-f6dc-4221-8144-c49ddd9c4270
[LOG 11:48:08.717] kOS: FlightControlManager.AddTo ce754e80-f6dc-4221-8144-c49ddd9c4270
[LOG 11:48:19.905] kOS: kOS.Binding.FlightControlManager:Update(currentVessel = null)!
[LOG 11:48:19.905] kOS: kOS.Binding.FlightControlManager:Update(currentVessel = Shared.Vessel)!

Here I see that:
1. Two FlightControlManagers were created and set currentVessel
2. One of them detected that root part is changed and reset currentVessel
3. But when Dispose was executed both currentVessel are null
4. Thus in new load FlightControls think they are binded and not trying to bind again

Why currentVessel is null is complete mistery for me. I tried to replace currentVessel with property and log any value sets, but didn't catch the nulls. It seems to be some dark C# magic.

`set ship:control:neutralize to true.` helps

**Comment by hvacengi** [comment]
This probably has something to do with how KSP handles loading quick saves and the life cycle of vessel modules.  I've run into a similar issue where the steering manager is null if you revert to launch after having docked with a station in orbit (so the opposite scenario as yours, since two vessels become one and then you revert instead of one vessel becoming two before loading).  I can take a look at it one evening this week and see if I can get it fixed.  It probably means we just need to add a few more status checking fields.
