### ISSUE TITLE
Unity on Linux bug makes RETURN keypress get ignored in kOS.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#206]
(This bug was found after some back and forth posts with a user on the forums performing some debug tests for me.  I do not have a Linux platform to test this on myself.)

The correct ascii character for the carriage return, or "control-M" or "RETURN KEY" is 0x0d.  This means that when padded out into a 16 bit unicode character, it is supposed to be 0x000d.  This is not supposed to be OS-dependant.  That IS the return character in ascii and unicode cross-platform standards.

But the Linux build of Unity that KSP is using has a bug in regards to this.  It is returning a unicode character of 0xff0d for RETURN instead of the correct 0x000d.  Unity on Windows returns 0x000d as expected.  (I haven't tested on mac).

This bug makes kOS fail to detect the RETURN key properly in the terminal window, thus rendering the entire kOS mod utterly useless to Linux users since without RETURN, you can't execute any command, not even run a program.  (That's why I'd classify this as a serious severity bug.  It's one very tiny thing that's blocking an entire platform.)

Similar behavior seems to be happening for other control-characters like tab, which should be 0x0008 but is coming out as 0xff08 on Linux.  The problem seems to be that Unity on Linux is padding out the keypress's unicode character high byte with 1 bits instead of 0 bits in the case of control characters.  (Oddly, the printable ascii characters, like "A", are being padded correctly with zeros.)

Because KSP is unlikely to release a public patch just to update the Unity engine underneath, even if Unity itself fixes the bug we'll still be stuck with it for several months until the next KSP update at least, so we'll need to implement a workaround now if we want to have any Linux users.

(Yes, I know the usual argument about how small a sliver of the marketplace Linux constitutes "so let's not write special code to support it", but lets not forget that the filter "people who are interested in kOS" tends to select in favor of the more technical end of the userbase, making the Linux sliver of the pie a bit larger than it would be in a normal random sampling of users.)

**Comment by Xasin** [comment]
Hey!
I've recently tested out kOS on my KSP, and it seems like this bug is still (or again) affecting linux users. 
(At least I would assume this, as I am running 64-Bit linux and KSP, 1.0.2, kOS directly downloaded via CKAN.)

Is there any way I could fix this myself?
