### ISSUE TITLE
Vessel:isdead throws error if the vessel has docked

### ISSUE THREAD

**Issue by ozin370** [KSP-KOS/KOS#2068]
An "object reference not set to an instance.." error happens if `vessel:isdead` is used where the vessel has recently docked (in my case, during the last/current physics tick).

I have also had trouble with getting an updated `dockingport:state`, it reads as "aquiring" when it really just docked (again, in the very last physics tick). A few lines down the program will throw an error if I try to use `vessel:velocity`, stating the same error as above.

In general I'm just having trouble detecting if the target vessel has just docked to something..

**Comment by hvacengi** [comment]
This is due to us now listening to the `OnVesselDestroy` event and setting `Vessel` to `null`.  The fix should be a simple one line modification to the suffix definition in `VesselTarget`:

```
AddSuffix("ISDEAD", new NoArgsSuffix<BooleanValue>(() => (Vessel == null || Vessel.state == Vessel.State.DEAD)));
```
