### ISSUE TITLE
Mod compatibility (Module Manager(2.2.0))

### ISSUE THREAD

**Issue by TDW89** [KSP-KOS/KOS#207]
Not sure who to bother with this issue so have reported it on both repositories.
When using the following .cfg

@PART[probeCoreSphere]
{
MODULE
{
    name = kOSProcessor
    diskSpace = 512
}
}

I can launch the craft as normal, open the terminal and everything works fine and as it should. However, if i revert to launch the part does not load properly. It doesn't become active, the throttle doesn't jump up to 50% and the physics is not loaded so no 'pop' out of the ground. (I have left it for half an hour and it still didn't load so not a just need to wait a bit longer issue.)

If you then press Esc you get the game paused menu and the buttons activate as you mouse over them but they don't do anything. To exit you have to Alt + Tab out of the game.

For me this has tested at 100% repeat-ability on both 32 and 64 bit versions of the game.
The KOS parts don't cause this and using Module Manager to edit parts in other ways doesn't cause the bug.

Other than these 2 mods ksp is a clean copy of 0.24.2.

**Comment by Blacksilver42** [comment]
(Typo'd the number; did not mean to reference this. Sorry)
