### ISSUE TITLE
(bug) path = path doesn't return true under some cases 

### ISSUE THREAD

**Issue by nuggreat** [KSP-KOS/KOS#2085]
found this unexpected behavior when using paths as the key value in lexicons for a file/directory manipulation script i am working on and it looks like the same paths will return false when compared with "="  if they don't come the same initial construction, I am using the TOSTRING suffix as a workaround

```
LOCAL pathA IS PATH("1:/").
LOCAL pathB IS PATH("1:/").
LOCAL pathC IS pathA.
PRINT pathA = pathA.  //should be true and is true
PRINT pathB = pathB.  //should be true and is true
PRINT pathA = pathC.  //should be true and is true
PRINT pathA = pathB.  //should be true and is false
PRINT pathB = pathC.  //should be true and is false
PRINT pathA <>pathB.  //should be false and is true
PRINT pathA:TOSTRING = pathB:TOSTRING.  //workaround that should be true and is true
//lexicon example
LOCAL pathLex IS LEX(pathA,TRUE).
PRINT pathLex[pathA].  //should be true and is true
PRINT pathLex[pathB].  //should be true and will crash the script
```

**Comment by hvacengi** [comment]
Odd.  Both functions should return a `GlobalPath` value, which does override `Equals`, so maybe one of the components we test in there is instance checking instead of content/value checking.

**Comment by Dunbaratu** [comment]
Note to self:  Pay special attention to this case when fixing this:
```
LOCAL pathLex IS LEX(pathA,TRUE).
PRINT pathLex[pathA].  //should be true and is true
PRINT pathLex[pathB].  //should be true and will crash the script
```
Because that is handled in C# with the hashcode override system and NOT the Equals override.  (This is the reason for the common warning the compiler will give when you override equality but don't override hashcode making.  That failure makes associative arrays still treat equal keys as different keys.

**Comment by hvacengi** [comment]
Are path's immutable?  So that they cannot change?  If not, they technically should all have the same hash which forces a dictionary to compare `Equals` (it compares `Equals` if more than one object is in the same "hash bin" iirc.

**Comment by Dunbaratu** [comment]
Why? So they're mutable?  What does that break?  Mutabilty would mean this happens:
```
set thePath to path("0:/").
set theLex to lex(thePath, "value").
print theLex[thePath].
value
set thePath to path("1:/").
print theLex[thePath].
[[ error results because thePath now refers to a different value.]]
```
That's not a bug.  That's correct behaviour.  Compare with using any other variable as a key:
```
set theFloat to 0.123.
set theLex to lex(theFloat, "value").
print theLex[theFloat].
value
set theFloat to 0.333.
print theLex[theFloat].
[[ error results because theFloat now refers to a different value.]]
```
