### ISSUE TITLE
(bug) onRadioChange is not working

### ISSUE THREAD

**Issue by nuggreat** [KSP-KOS/KOS#2086]
the onRadioChange callback seems to be broken as far as I can tell unless i am using it incorrectly.  I have 2 workarounds but they cause odd things to happen when used.

The first workaround  uses ONTOGGLE will cause the onRaidoChange callback to fire when ever the radio button the ONTOGGLE is on is pressed this also only works if sing 2 radio buttons.

The second workaround uses on ONCLICK and will fire for the button pressed and the button that was previously on doesn't effect onRadioChange at all

```
CLEARGUIS().
LOCAL done IS FALSE.

LOCAL interface IS GUI(100).
  LOCAL radioBox IS interface:ADDHBOX.
    LOCAL rbA IS radioBox:ADDRADIOBUTTON("A",TRUE).
    LOCAL rbB IS radioBox:ADDRADIOBUTTON("B",FALSE).
//    LOCAL rbC IS radioBox:ADDRADIOBUTTON("C",FALSE).
 
SET radioBox:onRadioChange TO { PARAMETER B.  PRINT "Documentation: You selected:  " + B:text. }. //copied from documentation

//NOTE use only one type of workaround at a time
SET rbA:ONTOGGLE TO workaround_1@.  //first workaround only works for 2 buttons and will some times cause onRadioChange to fire use A,B only

//SET rbA:ONCLICK TO workaround_onclickA@.  //second workaround causes double fireing when changing from one button to another
//SET rbB:ONCLICK TO workaround_onclickB@.  //second workaround fires for prevous button and new button
//SET rbC:ONCLICK TO workaround_onclickC@.  //second workaround

LOCAL doneButton IS interface:ADDBUTTON("Exit").
SET doneButton:ONCLICK TO { SET done TO TRUE. }.

interface:SHOW.
WAIT UNTIL done.
interface:DISPOSE.

FUNCTION workaround_1 {
  PARAMETER junk.  //parameter needed for ONTOGGLE but not used by function
  IF radioBox:RADIOVALUE = "A" { PRINT "Workaround_1 : You selected:  A". }
  IF radioBox:RADIOVALUE = "B" { PRINT "Workaround_1 : You selected:  B". }
}

FUNCTION workaround_onclickA {
  IF radioBox:RADIOVALUE = "A" { PRINT "Workaround_A : You selected:  A". }
  IF radioBox:RADIOVALUE = "B" { PRINT "Workaround_A : You selected:  B". }
  IF radioBox:RADIOVALUE = "C" { PRINT "Workaround_A : You selected:  C". }
}

FUNCTION workaround_onclickB {
  IF radioBox:RADIOVALUE = "A" { PRINT "Workaround_B : You selected:  A". }
  IF radioBox:RADIOVALUE = "B" { PRINT "Workaround_B : You selected:  B". }
  IF radioBox:RADIOVALUE = "C" { PRINT "Workaround_B : You selected:  C". }
}

FUNCTION workaround_onclickC {
  IF radioBox:RADIOVALUE = "A" { PRINT "Workaround_C : You selected:  A". }
  IF radioBox:RADIOVALUE = "B" { PRINT "Workaround_C : You selected:  B". }
  IF radioBox:RADIOVALUE = "C" { PRINT "Workaround_C : You selected:  C". }
}
```

**Comment by Dunbaratu** [comment]
You spend a lot of time describing the workaround but no time describing the bug.  What is it about onradiochange that isn't working?  Does it appear to never fire at all?  Does it fire but do the wrong thing?

**Comment by nuggreat** [comment]
never fired at all

**Comment by Dunbaratu** [comment]
The problem was that the test to see whether or not OnRadioChange should be called was  buried inside the test to see whether or not OnToggle should be called.  If the conditions weren't right to cause OnToggle, then it also would never check for OnRadioChange.

It just so happened that in my tests I had been trying to test every callback - so I had them all enabled to see which fires when, which meant it never tested the case where OnRadioChange was defined but OnToggle was not.

There will be a small Pull Request coming shortly.
