### ISSUE TITLE
No syntax colouring for BBEdit

### ISSUE THREAD

**Issue by MaraRinn** [KSP-KOS/KOS#2094]
It would be nice to have kOS support for the best programmer's editor :rocket:

**Comment by MaraRinn** [comment]
derp. wrong repository.

**Comment by hvacengi** [comment]
This should be a request to the editor tools repository instead, as that's where we maintain various editor packages.  Also, if you could point us in the right direction for how to implement it, that would make it far more likely to support.

https://github.com/KSP-KOS/EditorTools
