### ISSUE TITLE
Liquid engines do not work without a kerbonaut or remote control.

### ISSUE THREAD

**Issue by andrewdalecramer** [KSP-KOS/KOS#2099]
I'm running career and using ~~cows~~ tourists as a money maker. I'm low on the tech tree and so I've used automation to make the whole thing run. Trick is: no pilots, no remote controls.

I've found that liquid engines do not work. To reproduce:

  * create a ship with a kOS cpu, a fuel tank and an appropriate engine
  * load on a boot program which has the commands: `wait 2. stage.`
  * watch as nothing happens

I've currently got my kerbals running through it by using flea SRBs with specific amounts of solid fuel.

**Comment by hvacengi** [comment]
Can you upload your save and craft files so that we can test?  By itself, loosing remote connection should not prevent control of the craft.

Do you have a probe core on your craft?  It is a requirement that you have some kind of valid control source, either a probe core or a crewed command pod.

**Comment by Dunbaratu** [comment]
@hvacengi 
Liquid engines use the throttle.
Solid boosters do not.
Could this just be an instance of the the throttle lockout problem we saw once before?

**Comment by hvacengi** [comment]
It's very possible.  
I guess I should have thought to also ask: does the throttle display on the navball move when you adjust throttle?

Throttle-able engines have a funny implementation under the hood, where they don't update the engine's throttle reading to match the user setting if it doesn't detect "control" available on the vessel (either by a lack of control part, or if there is no signal and the "require signal" difficulty setting is enabled).  That's also why you can't use a liquid fuel engine in place of a sepertron.

So, the issue could be related to the other cooked steering race condition issues, or it could be related to the work around for "require signal", or it could just be a lack of valid control part (if for example there is only a command pod installed, and it has a tourist in it).

**Comment by andrewdalecramer** [comment]
The navball throttle updates the correctly.

**Comment by hvacengi** [comment]
Revisiting this issue after our most recent release: if the navball throttle updates correctly, that implies the issue is internal to KSP not to kOS.  The UI updates based on the same information that kOS uses to set the controls, so we know that kOS is correctly setting the value, it's just that KSP is not responding to the value.  I would guess that you don't have a probe core or a manned control module installed on the vessel.  If neither of those are the issue, please upload save and craft files along with a log file so we can see what is happening.

**Comment by andrewdalecramer** [comment]
Yeah, appears to be the case. I guess you can close the ticket in that case.
