### ISSUE TITLE
AGX no longer recognized

### ISSUE THREAD

**Issue by madlemur** [KSP-KOS/KOS#2118]
Caveat: @SirDiazo hasn't officially updated AGExt to KSP 1.3 yet (although there are reports of it not working on KSP 1.2.2) But I've tried with AGExt recompiled to work with 1.3 (which it does), but kOS won't recognize it at all. not via ADDONS:AGX:AVAILABLE, not via AG11-AG250. I did some cursory poking at the code, but I'm not familiar enough with KSP/Unity internals to suss out the problem. It looks ok(?) to me compared to addons that are working, so I'm just not sure what's up.

KSP: 1.3
kOS: 1.1.2
AGX: 2.2

**Comment by hvacengi** [comment]
Honestly, until AGExt is officially updated it will be hard for us to provide official support.  We might be able to look into it with the backported release for KSP 1.2.  Looking at the AGExt code that is on github, it doesn't look like anything should be broken.  So I would be curious to find out what (if any) changes you had to make to compile against KSP 1.3.  I would also like to see the log file output from KSP to see if it shows any errors when loading/initializing.  It looks like everything on the kOS side catches errors, in which case the log might not show anything at all.

I will try to look into this if you can let me know at least what you had to do to compile for KSP 1.3.

**Comment by KSAMissionCtrl** [comment]
This worked fine in KSP v1.2.2 with kOS v1.0.3, I was using AG11 in my script no problems and AGExt is working without any issues for me in KSP v1.2.2. Came here to also report AGExt support is broken now with kOS v1.1.3.1 under KSP v1.2.2

**Comment by hvacengi** [comment]
Can you post a log file to help us try to track down the issue?

**Comment by KSAMissionCtrl** [comment]
Sure. I loaded the game went right into the VAB and took a ship to the pad that had an AG11 trigger setup in its boot script. It error'd out on load and I task-killed it. Log file is here - http://www.blade-edge.com/misc/output_log_kos-agx.zip

If there is some other way you want me to throw the error, let me know

**Comment by kananesgi** [comment]
Has there been any movement on this issue? I brought it up on the KSP forum to linuxgurugamer (who is now maintaining AGExt until Daizo comes back), and his thought was that kOS had been compiled against the wrong version of AGExt. LGG has updated AGX to 1.3.1 now.

https://forum.kerbalspaceprogram.com/index.php?/topic/167269-131-action-groups-reextended-250-action-groups-in-flight-editing/&tab=comments#comment-3236606

Log file of the test session (with only kOS and AGExt installed): https://pastebin.com/VF0dsvK9
Image of the kOS terminal associated with the above log: https://ibb.co/iZ3cUb

**Comment by hvacengi** [comment]
No, we haven't made further progress looking in to the issue.  According to the source code, we should still work with AGX.  I will have to do step debugging to figure out if it's the assembly that can't be found, or if there is an issue with the type look up, or something else entirely.  Our system entirely uses reflection and isn't built against a specific version.  So long as the external API methods remain the same and keep the same signature we shouldn't have an issue.  It might be an issue with our assembly checking method.

I'll try to keep it on my list to work on, but I don't know that I can commit to a time frame.

**Comment by hvacengi** [comment]
I take it back.  I decided it would be faster to try a quick compile fix and ask you to see if it works.  Can you download this zip and see if AGX works for you? https://www.dropbox.com/s/ruw4a3lwooec10f/kOS-AGX-Test.zip?dl=0

**Comment by kananesgi** [comment]
It works! Just loaded up the same instance as my test session above with the same craft, and typing in the terminal, "print ag20." returns a false now (was undefined variable before), and "ag20 on." activates the antenna just as it should.
