### ISSUE TITLE
No access to KOS Terminal on a manned craft without connection to KSC using RemoteTech

### ISSUE THREAD

**Issue by dergnom** [KSP-KOS/KOS#2127]
When using KOS with RemoteTech connectivity Manager the terminal is inaccessible when there is no connection to KSC or another control station even on manned vessels. In this case the Message "Signal lost.  Waiting to re-acquire signal." is displayed at the bottom of the KOS terminal sreen and no further input is possible.

When using the CommNet connectivity manager, access to the KOS terminal on manned craft is possible, even though no connection to KSC / control station is availlable.

I think the  reason for the different behaviour between  RemoteTech connectivity manager and CommNet connectivity manager lies in the implementation of the "HasConnectionToControl" Method of the connectivity managers. This method is used by the "UpdateDeployment" Method of the ConnectivityInterpreter class to determine wether it should be allowed to type into the KOS Terminal

```
private void UpdateDeployment(double deltaTime)
{
            if (!ConnectivityManager.HasConnectionToControl(Shared.Vessel))
            {
                if (!signalLossWarning)
                {
                    DrawStatus("Signal lost.  Waiting to re-acquire signal.");
                    progressBarSubBuffer.Enabled = true;
                    signalLossWarning = true;
                }
            }
```

Within the "HasConnectionToControl" Method of the CommNet connectivity manager (in file: src\kOS\Screen\CommNetConnectivityManager.cs) having control is determined by either having a connection to KSC / ground station or by the presence of crew (vessel.CurrentControlLevel >= Vessel.ControlLevel.PARTIAL_MANNED):

```
public bool HasConnectionToControl(Vessel vessel)
{
            if (!IsEnabled)
                return true;

            // IsConnected is only set to true on the active vessel, so we have to manually
            // call the FindHome method to evaluate the home connection.

            // WARNING: In stock this will only work for vessels with a relay antenna installed.
            // This is a limitation put in place to improve performance in the stock game, and
            // there isn't a very good way around it.
            if (!vessel.isActiveVessel)
            {
                var net = CommNetNetwork.Instance.CommNet;
                tempPath = new CommPath();
                net.FindClosestControlSource(vessel.Connection.Comm, tempPath);
                return tempPath.signalStrength > 0 || vessel.CurrentControlLevel >= Vessel.ControlLevel.PARTIAL_MANNED;
            }
            return vessel.Connection.IsConnected || vessel.CurrentControlLevel >= Vessel.ControlLevel.PARTIAL_MANNED;
}
```

Within the RemoteTech connectivity manager (in file: src\kOS\AddOns\RemoteTech\RemoteTechConnectivityManager.cs) you need a vessel with a RemoteTech SPU and a working connection for this method to return true. There is no additional check for crew:

```
public bool HasConnectionToControl(Vessel vessel)
{
            if (!RemoteTechHook.IsAvailable(vessel.id))
                return false; // default to no connection if the vessel isn't configured for RT.
            return RemoteTechHook.Instance.HasAnyConnection(vessel.id);
}
```

Changing the last line to 

```
return RemoteTechHook.Instance.HasAnyConnection(vessel.id)  || vessel.CurrentControlLevel >= Vessel.ControlLevel.PARTIAL_MANNED;
```

fixed my problem. I still require a RemoteTech SPU on the vessel (due to:  if (!RemoteTechHook.IsAvailable(vessel.id)) return false;) but I think this is the design intend of KOS/ RemoteTech connectivity manager.

Sofar I did not run into additional problems that might be caused by this change. Since the check for crew is also included in the CommNet connectivity manager I think this addition might be a working solution.

Remark:
-The files quoted are from the current master branch, downloaded yesterday (october 3rd).
-I found a file called RemoteTechInterpreter.cs in the src\kOS\AddOns\RemoteTech2 folder. This file also includes a UpdateDeployment Method. In this Method the check for crew was included. However, this file is no longer part of the solution.

**Comment by hvacengi** [comment]
Thanks for doing all of this leg work to find the issue.  It has helped me to find the part that had confused me.  If you look a few lines above `HasConnectionToControl` you'll find:
```
        public double GetDelayToControl(Vessel vessel)
        {
            if (!RemoteTechHook.IsAvailable(vessel.id))
                return -1; // default to no connection if the vessel isn't configured for RT.
            return RemoteTechUtility.GetInputWaitTime(vessel);
        }
```
Which calls a method from inside `RemoteTechUtility`:
```
        public static double GetInputWaitTime(Vessel vessel)
        {
            if (RemoteTechHook.Instance.HasLocalControl(vessel.id)) return 0d;
            else return GetTotalWaitTime(vessel);
        }

        public static bool HasConnectionOrControl(Vessel vessel) // this method isn't called
        {
            return RemoteTechHook.Instance.HasAnyConnection(vessel.id) || RemoteTechHook.Instance.HasLocalControl(vessel.id);
        }
```
You'll notice the second method `HasConnectionOrControl` actually does what we want for checking local control, but it isn't used in `RemoteTechConnectivityManager`.  If you have time, could you test by modifying RemoteTechConnectivityManager.cs as follows:
```
        public bool HasConnectionToControl(Vessel vessel)
        {
            if (!RemoteTechHook.IsAvailable(vessel.id))
                return false; // default to no connection if the vessel isn't configured for RT.
            RemoteTechHook.Instance.HasAnyConnection(vessel.id) || RemoteTechHook.Instance.HasLocalControl(vessel.id);
        }
```
I will be able to install and test myself later today after I get home from work.

I'm going to propose that we remove the utility method class because the connectivity managers essentially wrap these utility methods under the new model.  It also centralizes the code so we don't run into and issue like this in the future where we have the logic implemented correctly in one place but then don't use that correct implementation.  At the same time, we need to remove the old RemoteTech2 folder and contents.

**Comment by dergnom** [comment]
Using the implementation you proposed
```
public bool HasConnectionToControl(Vessel vessel)
        {
            if (!RemoteTechHook.IsAvailable(vessel.id))
                return false; // default to no connection if the vessel isn't configured for RT.
            RemoteTechHook.Instance.HasAnyConnection(vessel.id) || RemoteTechHook.Instance.HasLocalControl(vessel.id);
        }
```
also works!

**Comment by hvacengi** [comment]
As you can see above, I've submitted a PR including the proposed changes and some file clean up.  This should be fixed in the next release.

**Comment by dergnom** [comment]
Thanks!
Looking forward to the next release :-)
