### ISSUE TITLE
Bug from "EOF"

### ISSUE THREAD

**Issue by zDarKLordZ** [KSP-KOS/KOS#2160]
When i enter any command in the console, it says "Unexcepted token 'EOF found. Excepted EOI, please help.

**Comment by zDarKLordZ** [comment]
![image](https://user-images.githubusercontent.com/22128470/32321758-7f7a1b02-bfc2-11e7-97b9-f81fb804856a.png)

**Comment by hvacengi** [comment]
You're missing the period at the end of the command. Try using this instead:
```
print "hello world".
```

**Comment by Dunbaratu** [comment]
In general when you see "unexpected token ____ found", it means the previous thing wasn't finished yet and it wasn't expecting to start the next thing yet.  In this case it was the missing period, but in the general case just remember "unexpected token ____" usually means "previous thing wasn't completed right".
