### ISSUE TITLE
readjson doesn't work

### ISSUE THREAD

**Issue by mrantmet** [KSP-KOS/KOS#2164]
Hello,

code:
SET LEX TO RADJSON("1:/config.json").
error:
Method not found: 'Default constructor not found.. .ctor() of kOS.Sufficed.BodyTarget'.

KSP versions: 1.2.2, 1.3.1
KOS version: 1.1.3.2
Reproducible on clean just installed game with 100% chance.

BR,
mantmet

**Comment by mrantmet** [comment]
looks like a duplicate of #2105

**Comment by Dunbaratu** [comment]
Thanks for doing the research to find the duplicate.  It makes our lives easier for organizing the issues.
I'll close this and you can make further comments on the duplicate bug, or watch for progress there.
