### ISSUE TITLE
Impact time from Trajectories mod

### ISSUE THREAD

**Issue by Patrykz94** [KSP-KOS/KOS#2176]
I see that the Trajectories mod API has a function that returns the impact time called `getEndTime()`. Could you add a new suffix for the TRAddon that would return the impact time?

https://github.com/neuoy/KSPTrajectories/blob/master/Plugin/API.cs#L21

**Comment by Dunbaratu** [comment]
I assume this issue is out of date with the recent trajectories merge.  If it's still a problem after that, feel free to make a new issue with it.
