### ISSUE TITLE
Casting error on compiled files for develop

### ISSUE THREAD

**Issue by hvacengi** [KSP-KOS/KOS#2193]
When testing the current develop branch for our next release I ran into an issue with a casting error that I traced down to this line in Opcode.cs:
```
        public override void PopulateFromMLFields(List<object> fields)
        {
            // Expect fields in the same order as the [MLField] properties of this class:
            if (fields == null || fields.Count<1)
                throw new Exception(String.Format("Saved field in ML file for {0} seems to be missing.  Version mismatch?", Name));
            Identifier = (string)fields[0]; // <<-- casting error
        }
```
https://github.com/KSP-KOS/KOS/blob/develop/src/kOS.Safe/Compilation/Opcode.cs#L515

It looks like the field being returned is typed as `StringValue` which cannot be cast to `string` without first unboxing it (the silly C# issue with using structs as classes).  I recomend switching to use `Convert.ToString` or a more robust error checking system to ensure the type is correct.

**Comment by Dunbaratu** [comment]
Should this be for the current release milestone?

**Comment by hvacengi** [comment]
Yes, it caused errors in compiled code only after using the new label association for some opcodes.  Specifically it was introduced somehow with the most recent PR related to that.

Sorry that I didn't make that part of the issue clear.
