### ISSUE TITLE
QUICKSAVETO and QUICKSAVE differ in functionality

### ISSUE THREAD

**Issue by KSAMissionCtrl** [KSP-KOS/KOS#2195]
Not sure if this is a bug or poor documentation but I was getting kOS script runtime errors when trying to use `kuniverse:quicksaveto` immediately after exiting the atmosphere (almost - trigger was set to 70100km so a bit of a delay). It was driving me nuts why this wasn't working all of the sudden because it had before. After some futzing around and using `kuniverse:canquicksave` to wait until the save was possible I found the command only executed after the rocket engine stopped firing. I guess that makes sense, but I did another launch and found I was able to use both F5 and Alt+F5 keys in the atmosphere with the engines burning no problem. Furthermore, when I used just `kuniverse:quicksave` right at the border of space with the engines still running the game made a quicksave no problem.

So yea, not sure if a bug or the docs need to be updated to include more information about how `quicksaveto` should be properly used.

Oh and so this wasn't a problem before because my previous rockets all burned out before reaching space.

**Comment by hvacengi** [comment]
That's interesting.  If I recall correctly I modeled our implementation to match the logic KSP used.  I could be wrong though.

Are you saying that the command does nothing when the rockets are firing, or does it throw an exception?  Does `canquicksave` correctly tell you when it is safe to quicksave (i.e. return false when the engine is firing and true when it is not firing)?

**Comment by KSAMissionCtrl** [comment]
the command throws a runtime error saying saving is not possible, but checking for a valid situation works. Here is the code I'm using now to ensure I save at space no matter what, with an additional save if engines are still running while at space

    when ship:altitude >= 70000 then { 
      if kuniverse:canquicksave {
        // works if the engines are not thrusting
        kuniverse:quicksaveto(ship:name).
      } else {
        // works under any circumstances
        kuniverse:quicksave.
        // wait for the engines to stop thrusting then saveto
        when kuniverse:canquicksave then {
          kuniverse:quicksaveto(ship:name).
        }
      }
    }

**Comment by JonnyOThan** [comment]
QUICKSAVETO incorrectly tests FlightGlobals.ClearToSave() which will not return clear if in atmosphere or while the engine is firing etc.  But the stock game would normally allow you to quicksave in this situation.

https://github.com/KSP-KOS/KOS/blob/e3921571bcd523b4fd6970fd3ff328f119e19da6/src/kOS/Suffixed/KUniverseValue.cs#L209
