### ISSUE TITLE
GEOCOORDINATES:TERRAINHEIGHT is unaware of oceans

### ISSUE THREAD

**Issue by pand5461** [KSP-KOS/KOS#2221]
When GEOCOORDINATES:TERRAINHEIGHT is called, it returns the elevation of solid ground at certain geoposition. It does not care whether this solid ground is under water, so on Kerbin it returns negative values over all oceans.
This causes difficulties for landing script because there is no way to get real elevation of the terrain at the predicted touchdown point.
On the other hand, alt:radar accounts for water but can only be called for the point directly under the ship.
It would be good to have a water-aware version of TERRAINHEIGHT as well.

**Comment by Dunbaratu** [comment]
Water isn't terrain.  This is not a bug.  If the height is negative then you know it's under the water line and can act accordingly.  There are cases where bodies don't have water and you need that info about craters below the zero altitude point.

**Comment by pand5461** [comment]
I am sorry for persistence. A portable way to check whether a body has ocean, then?
