### ISSUE TITLE
ETA:Apoapsis crashes the kOS script if on an escape trajectory

### ISSUE THREAD

**Issue by zakukai** [KSP-KOS/KOS#2229]
From the documentation of ETA:apoapsis:

"Seconds until SHIP hits its apoapsis. If the ship is on an escape trajectory (hyperbolic orbit) such that you will never reach apoapsis, it will return zero."

In practice it seems in this case ETA:apoapsis actually returns infinity (which seems reasonable) but attempts to use the value in almost any context cause an error which crashes the script.

**Comment by ThunderousEcho** [comment]
working on this
