### ISSUE TITLE
VT100 Telnet Support Doesn't Work

### ISSUE THREAD

**Issue by chippydip** [KSP-KOS/KOS#2231]
...and probably never has: https://github.com/KSP-KOS/KOS/blob/develop/src/kOS/UserIO/TerminalUnicodeMapper.cs#L63

`"VT100".Substring(0, 4) -> "VT10"` so the equals check will never pass. Even if it did pass it would end up setting the term type to XTERM anyway.

**Comment by Dunbaratu** [comment]
Good catch.
