### ISSUE TITLE
VolumeDirectory:LIST() return type doesn't match documentation

### ISSUE THREAD

**Issue by PKduck** [KSP-KOS/KOS#2235]
[The documentation page](http://ksp-kos.github.io/KOS_DOC/structures/volumes_and_files/volumedirectory.html#method:VOLUMEDIRECTORY:LIST) says method LIST of structure VolumeDirectory returns a LIST of VolumeFile or VolumeDirectory. In game testing on KSP 1.3.1 with kOS 1.1.5.0 with `print open("1:/"):list().` indicates the method returns a LEXICON.

# Steps to reproduce
1. Build a new vessel in KSP with a kOS Processor and launch it.
2. Run `print open("1:/"):list().` in the in game kOS terminal.

# Expected output
`LIST of 0 items:`

# Actual output
`LEXICON of 0 items:`

**Comment by Dunbaratu** [comment]
The documentation is out of date.  It *used to* return a List.  We'll fix the docs.
