### ISSUE TITLE
weird

### ISSUE THREAD

**Issue by shmurphy09** [KSP-KOS/KOS#2250]
for some reason windows defender things its a virus and deletes it instantly

**Comment by firda-cze** [comment]
Blame Microsoft. I have seen many false positives from their shitty wannabe antivirus.

**Comment by shmurphy09** [comment]
Lol thanks for replying

**Comment by shmurphy09** [comment]
Its up to date
Its just junk
Ill have to turn it off or somthin

**Comment by firda-cze** [comment]
Try some other free antivirus instead, maybe avast

**Comment by Dunbaratu** [comment]
@shmurphy09 - Out of curiousity, what does it claim the virus actually?  It seems most likely that it's a bogus false positive, but hey, it can't hurt to check.  There's always the nonzero chance that when the ZIP file got created on one of the dev's machines that their ZIP program is compromised and is putting something "extra" in there.

**Comment by shmurphy09** [comment]
It says trojan somthing

I dont really think
Kos
Is a virus tho lol

On Mar 21, 2018 1:36 AM, "Steven Mading" <notifications@github.com> wrote:

@shmurphy09 <https://github.com/shmurphy09> - Out of curiousity, what does
it claim the virus actually? It seems most likely that it's a bogus false
positive, but hey, it can't hurt to check. There's always the nonzero
chance that when the ZIP file got created on one of the dev's machines that
their ZIP program is compromised and is putting something "extra" in there.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/KSP-KOS/KOS/issues/2250#issuecomment-374838121>, or mute
the thread
