### ISSUE TITLE
positionAt used with nextNode:eta is broken (+1 and -1 works)

### ISSUE THREAD

**Issue by firda-cze** [KSP-KOS/KOS#2252]
```
set vd1 to vecDraw(v(0,0,0), v(0,0,0), white, "pos-1", 1, true).
set vd1:vecUpdater to {return positionAt(ship,time:seconds+nextNode:eta-1).}.
set vd2 to vecDraw(v(0,0,0), v(0,0,0), red, "!pos!", 1, true).
set vd2:vecUpdater to {return positionAt(ship,time:seconds+nextNode:eta).}.
set vd3 to vecDraw(v(0,0,0), v(0,0,0), green, "pos+1", 1, true).
set vd3:vecUpdater to {return positionAt(ship,time:seconds+nextNode:eta+1).}.
terminal:input:getChar().
clearVecDraws().
```

White and green points near the node, but red is totally broken (90° with insane magnitude, tested on transfer from Kerbin to Mun).

![obrazek](https://user-images.githubusercontent.com/11376520/37787968-86b2426c-2e00-11e8-9700-4de965ce0b8a.png)

**Comment by Dunbaratu** [comment]
I have no idea what the rules are that KSP uses for the patch's start and end times.  They could be inclusive ranges on both ends `[start..end]`, or they could be inclusive on the start and open on the end `[start,end)`, or inclusive on the end but open on the start `(start, end]`, or open on both ends `(start, end)`.  The answer to that question would decide whether to use `<`,  or `<=` on the two endpoints of the range.  At least these are `double` timestamps, making an exact equality match seem unlikely. 

There are places where the lack of API documentation really hurts the ability to know what's right when modding.  SQUAD releases docs that often don't contain descriptions but just state the types, which the C# IDEs can already tell you anyway.

**Comment by Dunbaratu** [comment]
@firda-cze what is your manuever node?  I can't reproduce the bug - what kind of manuever node did you make?

**Comment by firda-cze** [comment]
@Dunbaratu I have noted that it is **transfer from Kerbin to Mun**, that may be important as it changes SOI and that can have different patches. The node is **few seconds/minutes in the future** with small prograde burn, nothing else makes sense as it is transfer orbit, there is no next or previous orbit, but SOI change. Will try to test that more later this day.

As for the ranges, the question is: **are they sorted**? They most probably include both ends, because they are just formulas, some orbit properties, the transition has to be smooth. So:
1. Safest way would be to change the condition to `while (!(orbitPatch.StartUT <= desiredUT && desiredUT < orbitPatch.EndUT))`. That should not break anything and will solve the `StartUt == desiredUT` problem. Doubles are likely to be same if you construct them from the same values (`nextNode:eta`+now is `patch.StartUT`, exactly).
2. More reasonable way would be to change it to `while (desiredUT < orbitPatch.StartUT)` which assumes they are sorted (ordered by `StartUT`). Could break if not ordered.

This is definitely not the first time I encountered this. My node execution script uses `lookDirUp(dv, positionAt(ship,at)-body:position)` - that should work, right? But it sometimes rolls the ship upside down.

**Comment by Dunbaratu** [comment]
> ``while (!(orbitPatch.StartUT <= desiredUT && desiredUT < orbitPatch.EndUT))``

I would prefer that definition, as it is how ranges in programming languages usually work (include the start point, do not include the end point).  Right at the moment of the transition between the two, the two orbit patches *should* be returning the same answer anyway so it doesn't matter which one is picked as long as one of the two is picked and it's not skipping over both of them like it is now.

**Comment by firda-cze** [comment]
It is really about ordered or not, you find first that satisfy `desired >= start` and you have the one if you know that `patch[i].start <= patch[i+1].start` for every `i`. It even prevents the error because `desired > start` should work as well, because the intervals are inclusive. But if you want me to create PR, I will use the safer version, because I am not sure they are really ordered (that would be sane, but you know). Looks like decided.
