### ISSUE TITLE
Trajectories wrapper doesn't work with 2.0.0

### ISSUE THREAD

**Issue by gegy1000** [KSP-KOS/KOS#2254]
In 2.0.0, the Trajectories API changed the casing of their methods:
https://github.com/neuoy/KSPTrajectories/blob/master/Plugin/API.cs#L45

KOS still searches for the old names, but should be checking for the new ones.
I propose KOS gets the ability to search for more than one method name to maintain compatibility with a range of addon versions.

**Comment by Dunbaratu** [comment]
This was addressed by PR #2220.  That PR didn't have the reference at the top to cause github auto-close this issue.  Closing it manually.
