### ISSUE TITLE
Target of inactive ship lost (after switching)

### ISSUE THREAD

**Issue by firda-cze** [KSP-KOS/KOS#2257]
If I `lock steering to target:position` (or `target:position-ship:position` or even `target:position-kUniverse:activeVessel:position`) on one vessel and then switch to the other then the first one, now inactive, starts to steer to different direction. What is the correct way to do this, that works in all the cases (when active and also when inactive)?

**Comment by hvacengi** [comment]
The target variable is only supported on the active vessel.  If you want to use the target vessel as selected when you start the script, you'll need to store the value of target in another variable:
```
set steerTowards to target.
lock steering to steerTowards:position.
wait until [some condition].  // during this wait, you can change the active vessel
```
It's a limitation of KSP itself, and frankly I thought it would throw an error on the inactive processor (I thought we checked for the active vessel before returning `target`).

**Comment by firda-cze** [comment]
That explains a lot. I have the code protected by `hasTarget`, didn't expect it to return false when the ship clearly had a target. I am also surprised you say it is limitation of KSP itself - it clearly remembers it, so, it should be somewhere. I will look into this later, will try to find a way to dig it from KSP API or maybe just preserve the last known value when the ship was active. Not a perfect solution (won't work if you unload the ship) but good enough for most cases.

**Comment by firda-cze** [comment]
How about `Vessel.targetObject`? Same type (`ITargetable`) as `FlightGlobals.fetch.VesselTarget` currently used (in `MissionSettings`), public field, looks like it.
