### ISSUE TITLE
Non-English letters lost on reading from archive

### ISSUE THREAD

**Issue by AlchemistCH** [KSP-KOS/KOS#2265]
Basically, the picture says it all:
![koserror](https://user-images.githubusercontent.com/15855182/38425491-ad524af8-39bc-11e8-976d-0dc25af80f40.png)
I can type Russian into console and it works. But in a script from archive it turns into question marks. And opening the file in editor interface (or copying it to local volume) doesn't change the situation

the messages the script is trying to display are:
print "Система Аварийного Спасения активирована".
print "ДУ САС отсутствует!".

Windows 7
KSP 1.4.2
kOS 1.1.5.2

**Comment by firda-cze** [comment]
Did you save the file as UTF8?

I can try Czech Language, our ***Příliš žluťoučký kůň úpěl ďábelské ódy*** should be equally good test.
I expect it to work if saving the file as UTF8 and having problems with CP1252 or whatever is the default code-page now.

**Comment by AlchemistCH** [comment]
![kosbug2](https://user-images.githubusercontent.com/15855182/38752669-bc108b2e-3f64-11e8-8266-e11acfd37f72.png)

That's the problem. I've been using Windows7 Notepad for .ks file editing and here are the observations:
* By default it was using ANSI - kOS functions with that OK, but Russian letters are lost.
* I can select UTF-8 and kOS reads the symbols properly, but it finds an extra symbol at the start of the file and refuses to parse the script (see picture)
* If I use kOS editor then and remove the extra symbol, it works properly... until I edit the file with Notepad again

**Comment by Dunbaratu** [comment]
I suspect Windows Notepad is inserting what is called a BOM at the start of the file:

http://www.unicode.org/faq/utf_bom.html#BOM

On most text editors that can save to UTF-8 the BOM is optional and can be left off, but I remember hearing something about how you can't force Notepad to leave the BOM off.   (That when you tell Notepad to save UTF-8 it will always have a BOM whether you like it or not.)

For the long term, I guess kOS should be made to accept and understand the BOM.  But in the meantime, try using a different editor than Notepad, one that will allow you to save UTF-8 without a BOM character.

The reason we don't like the BOM is that to support it properly means not just throwing it away, but also obeying it and complicating the load/save code.  It is supposed to help define when the order of the high and low bytes is swapped in the character codes that take more than 1 byte to express.

**Comment by Dunbaratu** [comment]
The cheap way to deal with it might be to just change the definition of 'whitespace' in the grammar to include not only space, tab, return, and newline, but also BOM.

**Comment by Dunbaratu** [comment]
@AlchemistCH can you verify if using a different text editor to save UTF-8 other than notepad works?
If it does then I'd like to close this issue and instead open a new one that just says "make kOS tolerate UTF-8 files with the BOM in them".

**Comment by AlchemistCH** [comment]
@Dunbaratu Yes, tried saving it in Notepad++ and it works properly.

However, for some reason Notepad++ displays that file (but not other script files!) with quadruple amount of line breaks (everything else including kOS file editor displays it without that effect even after being saved in Notepad++)

Anyway the joke's on me for not properly checking the encoding in the first place. Got too used to kOS just working with script files edited with default settings

**Comment by Dunbaratu** [comment]
(I'm reading old open issues.)
Rather than keep this issue open for the secondary problem that kOS can't read the BOM, I'd rather make a new one for the "BOM" problem with a better title.
