### ISSUE TITLE
Do not make list#x deprecated it works for OOP

### ISSUE THREAD

**Issue by robot-aquila** [KSP-KOS/KOS#2288]
Hello

Not sure this discussion is not appeared in the past.
I looked through issues but found nothing similar.
Sorry if is duplicate.

I noticed that list#x marked as deprecated here
http://ksp-kos.github.io/KOS_DOC/structures/collections/list.html?highlight=deprecated
Accidently I found that # works also for lexicons.
And voila - we get good OOP syntax out of box right now.

```
function kob_atm_ascent_new {
    declare local parameter myMaxQ.
    local obj is lexicon().

    // class attributes
    set obj#q_lim to myMaxQ.
    set obj#q_cur to 0.
    set obj#q_factory to 0.
    ... more attributes

    // class methods
    set obj#update to kob_atm_ascent_update@:bind(obj).
    set obj#test to kob_atm_ascent_test@:bind(obj).
}

function kob_atm_ascent_test{
    declare local parameter obj, mult.
    return obj#q_cur * mult.
}

// Update variables according to ship current state
// Param1: object
function kob_atm_ascent_update {
    declare local parameter obj.
    obj#q_factor to obj#q_cur * 12345.
}
```
class usage example somewhere in code
````
    local ascent is kob_atm_ascent_new(15).	
    until ship:altitude < 60 {
        ascent#update().
        print round(ascent#q_cur, 2) + at ( 0,  1).
        ...
    }
````
That looks exciting to me.
It is absolutely true OOP like in other scripting languages.
Just don't depreciate it.

Thanks for excellent mod.

**Comment by robot-aquila** [comment]
Please don't close the issue. I have something more to tell about kOS OOP. But I have to prepare some good examples. And yes, speaking in advance I faced some troubles when using # for that purposes. I've got KSP crashed few times in complex formulas with #.

**Comment by Dunbaratu** [comment]
Show me an example case where ``obj#key`` couldn't be replaced with the proper syntax of ``obj["key"]``.  Pretending Lexicons are classes instead of being associative arrays doesn't seem like a good idea.  The only reason ``obj#key`` works the way you're using it is because of a *misfeature* that the key isn't being de-referenced properly so it only works on source code literals as indexes which is why I replaced it with a proper system in the newer ``[...]`` syntax.  Once upon a time in the language we inherited from the previous kOS incarnation, that syntax was all that existed and it wasn't usable because of it.  (i.e. you couldn't do ``myList#i``, for a variable ``i``, you had to do ``myList#0`` and ``myList#1`` and ``myList#2`` and so on with hardcoded indeces.

**Comment by robot-aquila** [comment]
I currently writing KUnit - the unit testing framework for kerboscript. It is almost done. I just need to cover all classes by self tests. It is completely OOP. I achieved a lot of OOP things:

strong incapsulation
inheritance
polymorphism
private, protected and public members
protected and public methods overriding
calling parent

The unit testing framework we can get is essentially powerful. It could support most features similar to stronges existing frameworks: classical state-driven and behaviour-driven testsing whith mocks

Those things works well. Let me show you few examples.
```
// Base class of unit test

runoncepath("kunit/class/KUnitObject").
runoncepath("kunit/class/KUnitResultBuilder").

// Constructor.
// Return: Unit test instance.
function KUnitTest {
	declare local parameter
        testName,           // Name of test.
        reporter,           // Instance of test result reporter. Reporter will
                            // receive all results including self-test failures
                            // of unit test. Reporter must be a sub class of
                            // KUnitReporter class.
        className is list(),
        protected is lexicon().
    className:add("KUnitTest").

	local public is KUnitObject(className, protected).
	local private is lexicon().

    set private#reporter to reporter.
    set private#testName to testName.
	set private#shuffleTestCases to true.
    set private#resultBuilder to KUnitResultBuilder().
    set private#isRunning to false.

	// Map: case name -> test function. Also it is used to check that test
	// case with such name isn't added yet.
	set private#testCases to lexicon().

	// We must ensure all test may run in order as they were registered. Yes,
	// public is a "smell" of tests. And to avoid any issues with it there is
	// shuffleCases option. This list still keeps possibility to run test
	// cases in predictable order if needed.       
	set private#testCasesList to list().

    // Protected methods.
    
	// See method description for details.
	// Those are just prototypes to avoid checking before call.
	set protected#setUpTest to KUnitTest_setUpTest@.
	set protected#tearDownTest to KUnitTest_tearDownTest@.
	set protected#setUp to KUnitTest_setUp@.
	set protected#tearDown to KUnitTest_tearDown@.

    // Public methods:

    set public#getTestName to KUnitTest_getTestName@:bind(public, private).
    set public#shuffleTestCases to KUnitTest_shuffleTestCases@:bind(public, private).
	set public#addCase to KUnitTest_addCase@:bind(public, private).
	set public#addCasesByNamePattern to KUnitTest_addCasesByNamePattern@:bind(public, private).
	set public#close to KUnitTest_close@:bind(public, private).
	set public#run to KUnitTest_run@:bind(public, protected, private).
	set public#fail to KUnitTest_fail@:bind(public, private).
	set public#assertThat to KUnitTest_assertThat@:bind(public, private).
	set public#assertTrue to KUnitTest_assertTrue@:bind(public, private).
	set public#assertFalse to KUnitTest_assertFalse@:bind(public, private).
	set public#assertEquals to KUnitTest_assertEquals@:bind(public, private).
	set public#assertListEquals to KUnitTest_assertListEquals@:bind(public, private).
	
	// Private methods:
	set private#reportError to KUnitTest_reportError@:bind(public, private).
	
	return public.
}


// Override this method to do something before all test cases executed.
// Return: should return true if ok, false on error
function KUnitTest_setUpTest {

    return true.
}


// Override this method to do cleanup after all test cases executed.
function KUnitTest_tearDownTest {

}


// Override this method to do something before each test case executed.
// Return: should return true if ok, false on error
function KUnitTest_setUp {

    return true.
}


// Override this method to do cleanup after each test case executed.
function KUnitTest_tearDown {

}


// Get test name.
function KUnitTest_getTestName {
    declare local parameter public, private.
    return private#testName.
}


// Shuffle test cases before start unit test.
// This helps detect bad tests when test cases depend on each other.
// Param1: true to enable shuffling, false - to disable
function KUnitTest_shuffleTestCases {
    declare local parameter public, private, shuffle.
    set private#shuffleTestCases to shuffle.
}


// Register test case.
// Param1: test case name
// Param2: test case function
function KUnitTest_addCase {
	declare local parameter public, private, testCaseName, testCaseFunction.
	if private#isRunning {
        return private#reportError("Unable to register new cases while running").
	}
	if private#testCases:haskey(testCaseName) {
	   return private#reportError("Test case already registered: " + testCaseName).
	}
	set private#testCases[testCaseName] to testCaseFunction.
	private#testCasesList:add(testCaseName).
}


function KUnitTest_addCasesByNamePattern {
    declare local parameter public, private, namePattern.
    for methodName in public:keys {
        if methodName:matchespattern(namePattern) {
            public#addCase(methodName, public[methodName]).
        }
    }
}


function KUnitTest_close {
    declare local parameter public, private.
    set private#testCases to lexicon().
    set private#testCasesList to list().
}


// Execute registered test cases. 
function KUnitTest_run {
	declare local parameter public, protected, private,
	   includeNamePattern is "". // test case selection pattern (optional)
	   
    local reporter is private#reporter.
    local resultBuilder is private#resultBuilder.

	// TODO: add shuffle of test cases
	
    resultBuilder#setTestName(private#testName).
    resultBuilder#setTestCaseName("").
    if not protected#setUpTest() {
        private#reportError("Test setup failed").
        protected#tearDownTest().
        return.
    }
    
    local result is resultBuilder#buildSuccess().
    reporter#notifyOfTestStart(result).

    set private#isRunning to true.    
    for testCaseName in private#testCasesList {
        resultBuilder#setTestCaseName(testCaseName).
        if not protected#setUp() {
            private#reportError("Test case setup failed").
            protected#tearDown().
        } else {
            set result to resultBuilder#buildSuccess().
            reporter#notifyOfTestCaseStart(result).
            local testCaseFunction is private#testCases[testCaseName].
            testCaseFunction().
            protected#tearDown().
            reporter#notifyOfTestCaseEnd(result). // can use the same result
        }        
    }
    set private#isRunning to false.
        
    resultBuilder#setTestCaseName("").
    protected#tearDownTest().
    set result to resultBuilder#buildSuccess().
    reporter#notifyOfTestEnd(result).
    resultBuilder#setTestName("").
}


function KUnitTest_fail {
    declare local parameter public, private, msg is "".
    local reporter is private#reporter.
    local builder is private#resultBuilder.
    local result is builder#buildFailure(msg).
    reporter#notifyOfAssertionResult(result).
}

function KUnitTest_assertThat {
	declare local parameter public, private, assertFunction, msg is "Conditional requirement is not met".
    local reporter is private#reporter.
    local builder is private#resultBuilder.
    local result is builder#buildSuccess().
    local ret is assertFunction().
	if not ret {
        set result to builder#buildFailure(msg).
	}
	reporter#notifyOfAssertionResult(result).
    return ret.
}


function KUnitTest_assertTrue {
	declare local parameter public, private, actual, msg is "Expected true".
	return public#assertThat({ return actual = true. }, msg).
}

function KUnitTest_assertFalse {
    declare local parameter public, private, actual, msg is "Expected false".
    return public#assertThat({ return actual = false. }, msg).
}

function KUnitTest_assertEquals {
    declare local parameter public, private, expected, actual, msg is "Value equality expectation".
    local reporter is private#reporter.
    local builder is private#resultBuilder.
    local result is builder#buildSuccess().
    local ret is true.
    if actual = expected {
        set ret to true.
    } else {
        set result to builder#buildExpectationFailure(msg, "Values are not equal", expected, actual).
        set ret to false.
    }
    reporter#notifyOfAssertionResult(result).
    return ret.
}

function KUnitTest_assertListEquals {
    declare local parameter public, private, expected, actual, msg is "List equality expectation".
    local reporter is private#reporter.
    local builder is private#resultBuilder.
    local result is builder#buildSuccess().
    local ret is true.
    if actual = expected {
        set ret to true.
    } else if actual:length <> expected:length {
        set result to builder#buildExpectationFailure(msg,
            "Number of elements", expected:length, actual:length).
        set ret to false.
    } else {
        local break is false.
        from { local i is 0. }
            until i >= expected:length or break = true
            step { set i to i + 1. }
            do
        {
            if actual[i] <> expected[i] {
                set result to builder#buildExpectationFailure(msg,
                    "element #" + i + " mismatch", expected[i], actual[i]).
                set ret to false.
                set break to true.
            }
        }
    }
    reporter#notifyOfAssertionResult(result).
    return ret.
}

// Private methods.

// Private.
// Errors are not test failures!
// Error mean something is going wrong with test process.
// For example - bad implementation of the unit test which causes error.
function KUnitTest_reportError {
	declare local parameter public, private, msg.
	local reporter is private#reporter.
	local builder is private#resultBuilder.
	local result is builder#buildError(msg).
	reporter#notifyOfError(result).
}
```
and its subclass
```
function KUnitTestTest {
	declare local parameter reporter is KUnitReporter().
	local public is KUnitTest("KUnitTestTest", reporter).
	local private is lexicon().

    set public#testFail to KUnitTestTest_testFail@:bind(public, private).
    set public#testAssetEquals to KUnitTestTest_testAssertEquals@:bind(public, private).
    
    set public#testRun to KUnitTestTest_testRun@:bind(public, private).
    set public#testRun_ShouldSkipAllTestCases_IfSetUpTestFailed to KUnitTestTest_testRun_ShouldSkipAllTestCases_IfSetUpTestFailed@:bind(public, private).
    set public#testRun_ShouldSkipTestCase_IfSetUpFailed to KUnitTestTest_testRun_ShouldSkipTestCase_IfSetUpFailed@:bind(public, private).

    public#addCasesByNamePattern("^test").
    
	return public.
}

function KUnitTesttest_testFail {
    declare local parameter public, private.
    local reporterMock is KUnitReporter().
    //set reporterMock#
    public#fail("Not yet implemented").

}

function KUnitTestTest_testAssertEquals {
    declare local parameter public, private.
    public#fail("Not yet implemented").
}

function KUnitTestTest_testRun {
	declare local parameter public, private.

	// Given
	local actual is list().
	local reporter is KUnitReporter().
	local service is KUnitTest("test1", reporter).
	service#shuffleTestCases(false).
	set service#setUpTest to { actual:add("setUpTest"). return true. }.
	set service#tearDownTest to { actual:add("tearDownTest"). return true. }.
	set service#setUp to { actual:add("setUp"). return true. }.
	set service#tearDown to { actual:add("tearDown"). return true. }.
	set service#testCase1 to { actual:add("testCase1"). }.
	set service#testCase2 to { actual:add("testCase2"). }.
	service#addCase("testCase1", service#testCase1).
	service#addCase("testCase2", service#testCase2).

	// When
	service#run().

	// Then
	local expected is list().
	expected:add("setUpTest").
	expected:add("setUp").
	expected:add("testCase1").
	expected:add("tearDown").
	expected:add("setUp").
	expected:add("testCase2").
	expected:add("tearDown").
	expected:add("tearDownTest").

    // Example assertions
	if not public#assertListEquals(expected, actual, "Unexpected call sequence") { return. }.
}

function KUnitTestTest_testRun_ShouldSkipAllTestCases_IfSetUpTestFailed {
    declare local parameter public, private.

}

function KUnitTesttest_testRun_ShouldSkipTestCase_IfSetUpFailed {
    declare local parameter public, private.
    public#fail("Not yet implemented").
}
```

You see there is a lot code. Using object#["member"] could be used of course. But it looks pretty weird., more symbols -> more errors. The only thing which will scare me to use kOS OOP is weird syntax with object["member"]. Intuitively it looks not like an object member reference.

So, if we can proceed discussing about pretty looking OOP in couls I happy to help practivally. For example I could write lot tests to cover all potentially problem cases. I faced with crashes while using OOP. But as I can see most of them is not directly related to object#member syntax. If the code written well (without syntaxt errors, all keys are exists) then it causes no problems. Most cases. So there is something to work around and I ready to help with it.

I used TDD and I need OOP. I have many ideas what to implement and I know how to implement. Well-looking OOP opens a lot of possibilities. I know kOS a long time. I remember it did not had even functions. Avery time I played with kOS a bit and gone away because it was too weak to build complex software. Now it almost ready for strong and complex programming. There is only one decision needed - yours.

**Comment by Dunbaratu** [comment]
> So, if we can proceed discussing about pretty looking OOP I happy to help practivally. 

Good.  So lets talk about that *instead of* insisting on keeping the ``#`` syntax around forever and ever.  For now, you've come up with a great ad-hoc way to layer a form of OOP on top of kOS, but as a desire to type fewer characters, you've resurrected an old syntax that visually doesn't make any sense to use for strings and only really works on strings by accident.  (Using on integers is why the old syntax used the ``#`` symbol, as in "number 1, number 2, etc..."  working on string literals came later *accidentally* because it hadn't been deleted when it was deprecated, which happened prior to Lexicons existing).  The point of a github issue is to ask for changes to kOS, not to ask for stagnation of it.

The correct way to try to do this is to alter kOS to support the ``:`` syntax on user classes, if you're talking about 'pretty looking OOP'.  And to make user classes as a first class citizen rather than layering them on top of Lexicons.

I guess my argument is this, of these three options:

1 - OOP supported by kerboscript itself.   (It would probably use the ``:`` member syntax)
2 - OOP layered on top of kerboscript by use of Lexicon using ["member"] syntax.
3 - OOP layered on top of kerobscirpt by use of Lexicon using #member syntax.

There's a wide gap in quality between 1 and 2, while there's very little gap between 2 and 3.  If you're talking about pretty looking OOP, then you are talking about *neither* 2 *nor* 3.  You're talking about 1, in which case the need to preserve the ``#`` syntax forever and ever and ever isn't there.  If you're talking about accepting *either* 2 *or* 3, then I don't see the difference between those two as a sufficient difference to un-deprecate the old syntax.  Not when the new syntax can do, literally, a superset of everything the old one can.

**Comment by robot-aquila** [comment]
You're right. Possible I got started from a bad point.

To keep it clear the only issue matters to me - to get kOS OOP asap. I know that is long-time and complex issue. That does not matter to me what exact syntax it will support. Let me focus on advantages and disadvantages of what I found in current KOS regarding OOP regardless of member calling syntax.

The approach suggested by me is pretty good. It's close to javascript or similar languages. It allows developer free to use it at his own style.

The good points: we can achive everything what are called OOP. There are a lot points to talk of: what they are and how they are may be achieved. I propose to discuss them separately at the right appropriate moment.

The bad points (I placed them in priority from most critical to less or insignificant):

1) Visibility specificators. You see we have to use three specificators for three scopes: private, protected and public. It make a mess when declaring prototypes and defining method bodies. When you make refactoring you have to double check both are consistent to each other. I'm not sure how to solve it in easy way without builtin visibilite rules.

3) Type Checking/Reflection API. I simulated this in such manner:
```
function KUnitObject {
    declare local parameter
        className is list(),
        protected is lexicon().
    className:add("KUnitObject").
        
    local public is lexicon().
    local private is lexicon().
    
    set private#className to className.
    set private#refID to KUnitObject_NEXT_REF_ID().
    
    set public#getClassName to KUnitObject_getClassName@:bind(private).
    set public#getRefID to KUnitObject_getRefID@:bind(private).
    set public#isSameClassWith to KUnitObject_isSameClassWith@:bind(public, protected, private).
    set public#isA to KUnitObject_isA@:bind(public, protected, private).
...
function KUnitObject_getClassName {
    declare local parameter private.
    return private#className[0].
}

function KUnitObject_isSameClassWith {
    declare local parameter public, protected, private,
        other.  // Value to test. It must be at least lexicon or
                // runtime error will occur.
        
    if not KUnitObject_isObject(other) {
        return false.
    }
    if object#getClassName() = this#getClassName() {
        return true.
    }
    return false.
}
```
I'm happy with this but type checking in weak typed language is important. If this may be achieved by language it would be perfect. Something like isa(instance) & isclass(instance) functions would be great.

3) It is weak typed. As for me - weak typing is an evil. It is more critical for OOP because we're talking of interfaces. Interface is a contract requirement. But many languages are ok with it and I cannot ask for that feature for ingame language. KOS is pretty enough as is. In case if there is no any realistic possibilities to discuss this issue.

So, the possible shortest and easiest way to get OOP is to make some kind of lexicon for classes with right member referencing syntax. With this we can start coding OOP in KOS. The next KOS versions may add new features for that basis but legacy coded classes should keep working.

The ideal way I see is adding : as member reference with possibility to derive built-in classes like list, file entry, etc. If so, then core KOS developers can focus on really significant features like closures, binding, calling issues, syntax/error checking etc. Everything else can be done by community in a form of some kind system library. And if there is some good core function in the system lib appeared it may be converted as builtin function any time later.

**Comment by robot-aquila** [comment]
Few more words on this:
 
you've resurrected an old syntax that visually doesn't make any sense to use for strings and only really works on strings by accident

If you remember a naming conventions for most known languages you can see - we do not need more for member calling. I don't know languages which allow starting names with numbers. The most significant problem is that in combination with lexicon:case() approach described above does not work.

**Comment by robot-aquila** [comment]
Isn't hot issue, correct? :)

OK. There is it [KUnit - Unit Testing framework for kerboscript](https://github.com/robot-aquila/kunit)

That would be nice if you play with it to get better overview of what approach I specifically suggest. Although 98% of code is well tested, those tests were run literally thousand times and I reproduced them on two hosts there is still a chance to get it broken somewhere, some cases, sometimes...

I'm ready to go ahead this approach with all its problems. This is a chance and it's time to get fun instead of pain. There are lot ideas waiting (years) for implementation. Now we can deal with design of any complexity.

I'm a developer myself and I know what is software development. Therefore I have not the slightest desire to force ahead KOS OOP issue. This is one reason why I againt propose you to keep this syntax or better to propagate this as official feature. Of course you're the boss here and you're free to make any decision. But when you will do it please think one more time what is best for KOS and its community. We can and should use this approach to open path for complex software in KOS asap.

**Comment by madlemur** [comment]
As a bull in a china shop... I just can't see the actual bona-fide benefit to keeping an unintended side-effect of a deprecated syntax alive when there is a perfectly good, if vaguely more verbose (3 extra characters) way of expressing the exact same thing. There is a reason for the term Syntactic Sugar. I would much, _much_ rather time be spent on getting proper OO support for kOS. Or even marginal OO support. :)

**Comment by griderd** [comment]
I've been working on a general-purpose OOP framework for kOS myself, along with a bunch of other fun stuff attached to it. I don't run under the assumption, however, that x#y will always work, so I've been using the clunkier x["y"] syntax. It's ugly but it works.

Having real OOP would be awesome though.

**Comment by robot-aquila** [comment]
if you would like to stop getting pain of language and start getting fun of programming spaceships just get a look on krpc

**Comment by griderd** [comment]
@robot-aquila  - I typically use both. The problem with krpc is latency. It's difficult, if not impossible, to use krpc for high-speed or high-precision operations because it operates over a network connection instead of natively in the game. Therefore, krpc is great for remote control/telemetry where delay is not important, but I wouldn't use it to control a precision burn or automatically dock a vehicle.
