### ISSUE TITLE
Error/Exception handling (try..catch)

### ISSUE THREAD

**Issue by firda-cze** [KSP-KOS/KOS#2295]
That NaN/Infinity problem (which is understandable) and "Node does not exist" and whatever error that sometimes happen asynchronously (you cannot even rely on `hasNode` to fetch `nextNode` because you could get interrupted by IPU which can break even `if hasNode return nextNode:deltaV`) ... are quite annoying and there is no good measure as far as I know. My control GUI sometimes crashes for really ridiculous reasons and there is no way to reset/reboot. Am I wrong?

TRY..CATCH is the modern way of handling these things and you may think that kOS is old-style, but it is not - SUFFIXES are MODERN, old CPUs knew nothing about names, they knew addresses and HardFault (Access Violation) INTERRUPT and that was the only way to notice that you have accessed something wrong / non-existent and you could (and can e.g. in ARM) set some global variables (in `.noinit` section) to give some hint to reboot (if you are not able to repair / unwind which is the modern way that can be implemented even on very old HW).

The only alternative I can see is:
1. Every suffix / function has to return something, even if that would mean NaN/null or special Error class. 2. KSP API would have to be protected and some global `errno` storing last error (like "Sorry, but we won't pass NaN/Inf to KSP API").

But I think that implementing TRY..ERROR (as that sounds more like kOS than try..catch ... maybe ON ERROR) would be easier. No need to `catch(type)`, it could be implemented by global variable (`if lastError:isType("NoNodeError")`), but why not.

I would look into this myself, but I already have three pending PRs and this would probably be huge (well that try..error can be tested outside of KSP and I could improve my tester, but I would probably rewrite CPU.cs and related things a lot).

**Comment by lucaelin** [comment]
related to #1794
