### ISSUE TITLE
Weird scoping behaviour for parameters of the same name as functions

### ISSUE THREAD

**Issue by nummersyv** [KSP-KOS/KOS#2308]
The following script outputs `1`, whereas I believe it should return `2`:
```
function f {
    return 1.
}

function g {
    parameter f.
    return f.
}

print g(2).
```

The issue seems to be that the function `f` is called without parentheses, as described [here](https://ksp-kos.github.io/KOS/language/user_functions.html?highlight=function#calling-a-function-without-parentheses-please-don-t). As stated in the link, calling functions without parentheses only work for functions defined in the same file, so what happens if we declare `f` and `g` in separate files?

**f_decl.ks**
```
function f {
    return 1.
}
```

**g_decl.ks**
```
function g {
    parameter f.
    return f.
}

print g(2).
```

```
> run f_decl.
> run g_decl.
2
```

Conclusion: The issue is definitely something to do with the fact that "[omitting parentheses only works in the same file](https://ksp-kos.github.io/KOS/language/user_functions.html?highlight=function#omitting-parentheses-only-works-in-the-same-file)", but shouldn't the scoping rules ensure that `parameter f` in function `g` takes precedence over globally declared functions?

**Comment by Dunbaratu** [comment]
(Just doing a bit of housekeeping here.)
This bug, and bug #2318 are the same bug.
