### ISSUE TITLE
LIST.ADD not working

### ISSUE THREAD

**Issue by SlavDimov** [KSP-KOS/KOS#2311]
Hello, i'm trying to implement the quicksort algorithm in KOS

`
@LAZYGLOBAL OFF.

function QUICKSORT {
    declare local parameter X.
    
    if X:length = 1 or X:length = 0 {
        return X.
    }

    declare local PIVOT is X[0].
    declare local I is 0.
    declare local TEMP is 0.
    
    from {declare local J is 0.} until J >= (X:length - 1) step {set J to J + 1.} do {
        if X[J + 1] < PIVOT {
            set TEMP to X[J + 1].
            set X[J + 1] to X[I + 1].
            set X[I + 1] to TEMP.
            set I to I + 1.
        }
        
        set TEMP to X[0].
        set X[0] to X[I].
        set X[I] to TEMP.

        
        declare local FIRST_PART to QUICKSORT(X:sublist(0, I)).
        declare local SECOND_PART to QUICKSORT(X:sublist((I + 1), X:length)).
        
        FIRST_PART.ADD(X[I]).
        FIRST_PART.ADD(SECOND_PART).
        return FIRST_PART.
    }
}
`

`
This should work but for some reason I get this:

Undefined Variable Name 'first_part.add'.
__________________________________________
           VERBOSE DESCRIPTION
Undefined Variable Name 'first_part.add'.
__________________________________________
__________________________________________
At 0:/lib/sorting.ks, line 30
        FIRST_PART.ADD(X[I]).
                         ^
...

`

I'm I being blind or is this really a bug?

I'm using KOS latest version from CKAN, running KSP 1.2.2 with RO & RP-0

**Comment by Dunbaratu** [comment]
Kerboscript separates members using Colons, not Dots.
Try ``first_part:add`` rather than ``first_part.add``

**Comment by SlavDimov** [comment]
OMG I feel so stupid now. This is what I get from writing scripts at 2 AM in the morning LOL.

`
@LAZYGLOBAL OFF.

function QUICKSORT {
    declare local parameter X.
    declare local parameter COMPARE.
    
    if X:length = 1 or X:length = 0 {
        return X.
    }

    declare local PIVOT is X[0].
    declare local I is 0.
    declare local TEMP is 0.
    
    from {declare local J is 0.} until J >= (X:length - 1) step {set J to J + 1.} do {
        if COMPARE(X[J + 1], PIVOT) {
            set TEMP to X[J + 1].
            set X[J + 1] to X[I + 1].
            set X[I + 1] to TEMP.
            set I to I + 1.
        }
    }

    set TEMP to X[0].
    set X[0] to X[I].
    set X[I] to TEMP.

    declare local FIRST_PART to QUICKSORT(X:sublist(0, I), COMPARE).
    declare local SECOND_PART to QUICKSORT(X:sublist((I + 1), X:length), COMPARE).
    
    FIRST_PART:add(X[I]).
    LIST_MERGE(FIRST_PART, SECOND_PART).
    return FIRST_PART.
}

local function LIST_MERGE {
    declare local parameter X.
    declare local parameter Y.

    for ITEM in Y {
        X:add(ITEM).
    } 
    return X.
}

declare local a to list(3,1,2,4, -2 ,6).

PRINT QUICKSORT(a, {
    declare local parameter aa,b.
    return aa < b.
}).
`

this works now.

Just one last question:
Is there a way to merge the 2 LISTS without having to define my own function ( LIST_MERGE)?
using :ADD(<LIST>) adds the list as an item to the other list...
