### ISSUE TITLE
kOS didn't work with IR_v3.0.0_beta3_p7

### ISSUE THREAD

**Issue by Lookerksy** [KSP-KOS/KOS#2316]
I find the kOS_v.1.1.5.0_for_KSP_1.3.1 didn't work with InfernalRobotics_3.0.0_beta3_p7_for_KSP_1.3.1.
When I check ADDONS:IR:AVAILABLE, the result is FALSE.
And I can't control IR parts by ADDONS:IR structure.

![kos didn t work with ir](https://user-images.githubusercontent.com/21987795/44001969-fa8980aa-9e6d-11e8-9921-29e16dd4fb0e.jpg)

Maybe the reason is IR has updated. It's module name and part-menu has changed.
Have you the plan to repair this problem in next kOS version?
Thnaks.

**Comment by Dunbaratu** [comment]
@Lookerksy :
Has Infernal Robotics changed it's Assembly name in the DLL?  We're expecting a name of "InfernalRobotics".
Also, does your output log show any lines during the loading process that contain the string "[IR Wrapper]"?  Those are some messages that print out when it finds Infernal Robotics but fails to find certain parts of it (if the IR API changed and a method or class we're used to using no longer exists or has a new name you might get some diagnostic messages about that in the log.).


(( Unrelated note to self:  I just saw that there's a typo in these messages.  One of them prints in the error message that it failed to find "InvernalRobotics.dll" which makes it look like it's searching for the wrong name.  It's searching for the right name, "InfernalRobotics.dll" - but the error message itself spells it wrong when reporting it.))

**Comment by Lookerksy** [comment]
@Dunbaratu 
I find "InfernalRobotics_v3.dll" in IR folder.
And I find module name "ModuleIRServo_v3" in Part:Modules.
I didn't find string "[IR Wrapper]" in KSP.log.
![qq 20180813021208](https://user-images.githubusercontent.com/21987795/44005004-9e2c226e-9e9e-11e8-8915-620f88a31af0.jpg)
