### ISSUE TITLE
GUI: Can drag a window from outside the box (vertically) if box was shrunk

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#2321]
1 - Make a GUI(N) where N is a fixed integer for the width.
2 - Fill the contents with a VerticalBox that contains several items, so the GUI window will decide on a height based on that content.
3 - Remove some of the contents inside the VerticalBox so the GUI window will now shrink in the Y direction, to a shorter window.
4 - The area of the screen where a mouse drag causes the GUI window to move does not shrink during step 3 above.  Instead the window can now be dragged by clicking and dragging in the background of the screen, with the pointer in the area *just south of* the window.  This is the area that *used to be* inside the window because of the content in step 2 above, but is now outside of the window border because of the shrinking in step 3 above.

It seems like the drag rectangle doesn't shrink when the content shrinks.

I have no idea how to begin looking into this, but I wanted the problem recorded for completeness in case someone with better knowledge about Unity IMGUI wants to take a look.

**Comment by ozin370** [comment]
This looks like the same as issue #2184 . There is a simple script for quick testing of this bug in that issue
