### ISSUE TITLE
Direction multiplication incorrect?

### ISSUE THREAD

**Issue by surge9000** [KSP-KOS/KOS#2326]
While attempting to create something that would point solar panels on a ship at the sun during long trips, I got horrendously confused by 'directions', and did a test.

I made some pictures to demonstrate, but github does not like them. In any case, check the result of, for example:
lock steering to R(90,0,0) *UP.
lock steering to R(0,90,0) *UP.
lock steering to R(0,0,90) *UP.
I chose 90° for a reason - it's easy to see 1/4 angles. The only one of these in my tests that was actually 90° to *anything* (UP, raw coordinate system, original ship orientation) was R(0,90,0) *UP. The rest ended up rotated in at least 2 dimensions by what looked like somewhere between 45° and 20° relative to all other axes I did vecdraws for and could think of.

After watching a video on this 15 bazillion times (https://www.youtube.com/watch?v=7byYiZZBBVc), I noted that he has the same problem if you look closely: he types a vecdraw for R(30,0,0) *UP, and claims its rotated by the X axis, but its rotated by the Y axis and one (possibly 2) other axis slightly as well. This may be explained by the raw system moving as he talks, but after the above tests, I start to doubt it.

This all stems from what I ended up with to point solar panels at the sun. After previous irrelevant code that finds a panel and gives it a name of 'sp' (solar panel):

lock steering to SHIP:facing:inverse *sp:rotation *SUN:position.

Seems logical, right? We have the suns position, and we want to point at it, but rotated by the panels orientation (sp:rotation) relative to the ships orientation (SHIP:facing:inverse). But all it does is point in a random direction - similar to the above tests.

The only thing I could find that sort of works is this:

lock steering to rotatefromto(sp:rotation:vector, SHIP:facing:vector) *lookdirup(SUN:position, UP:vector):vector.

which sort of points the panel vaguely at the sun, but constantly rotates around it. I just sort of stumbled upon this after randomly poking it. I have no idea how or why it almost works, since the rotatefromto() should be a constant, and it is not - both vectors are in the raw system, and do not ever move relative to each other. lookdirup() seems unnecessary too, but without it, it just randomly spins all over the place.

It's worth noting that one might think "Aha, this is similar to the docking problem, I'll just go look at that code", but it is not because in those cases, one sets 'control from here' for the port, and then the steering directions are automagically aligned in the same coordinate system as the target. This isn't the case for random parts like solar panels where you have to 'subtract' the part's rotation from the steering directions.

Also, what is (Dir1 - Dir2) supposed to do? This is undocumented, but comes up with another seemingly random rotation.

**Comment by pand5461** [comment]
Dir1 +/ - Dir2 adds or subtracts them component-wise. Better not to use that operation, except for Dir + R(0,0,additional_roll).
Are you sure you're not confusing extrinsic and intrinsic rotations? Applied right-to-left, they are extrinsic rotations, i.e. `((R(90,0,0)*R(0,0,90)):vector` is V(0,-1,0), not V(1,0,0).

**Comment by surge9000** [comment]
That is exactly why i did things like SHIP:rotation before the panel rotation before the sun vector. It's counter intuitive, but I'm well aware of it.

I suggest you actually try the tests mentioned above.

**Comment by surge9000** [comment]
Aha, I was told by the video to place the rotations before the thing youre trying to align with. I notice UP *R(90,0,0) results in an obvious 90° rotation.
I will play around with it some more and if I can get the solar panels to align, I'll close this. A few quick tries with swapping the terms still resulted in seemingly random directions.

**Comment by surge9000** [comment]
Ok, I think I got it to work, but I still don't fully understand it. Most of the problems stem from rotating a vector resulting in nonsense because vectors are usually in a different coordinate system to directions (ship vs raw).
I still don't understand why we need *two* :inverses though:

lock steering to lookdirup(SUN:position, UP:vector) *R(0,0,<required rotation>) *(SHIP:facing:inverse *sp:rotation):inverse.

It is also wasteful to require the lookdirup(), since the *R(...) takes care of the remaining axis of freedom already - it's only needed to get the sun's vector into raw relative coordinate system.
I still consider this a bug, since this confusing and computationally wasteful way appears to be the only way to do it, but I will close this for now. If a developer wishes to fix it, they can reopen it.

I also recommend better documentation on this, but that also, can be for another day.
