### ISSUE TITLE
Null reference when throttling.

### ISSUE THREAD

**Issue by SilverWingedSeraph** [KSP-KOS/KOS#233]
A cruise control script:

    declare mode. 
    set mode to 0.
    until surfacespeed = 0 {
    wait 0.5.
    if  altitude < 10000 { //Mode 1 - "low" altitude
    if mode <> 1 {print "Switching to Low Altitude Mode". set mode to 1.}.
    print "Speed:" + surfacespeed.
    if surfacespeed > 250 {print "Before Throttling". set throttle to (throttle - 0.05). print "After Throttling".}.
    if surfacespeed < 200 {print "Before Throttling". set throttle to (throttle + 0.05). print "After Throttling".}.
    print "After Throttling Block".
    }. //Mode 1 end
    }. //Loop end`

Whenever the speed is outside the tolerable range, the script should try to throttle. Instead:

    Speed: 308.9...
    Before Throttling.
    Object reference not set to an instance of an object

And the script exits.

EDIT: Fixed by using a variable T and locking the throttle to that. So basically, you can't do math on the THROTTLE variable.

**Comment by erendrake** [comment]
@SilverWingedSeraph you can now get the SHIP:CONTROL:PILOTMAINTHROTTLE and SHIP:CONTROL:THROTTLE. That will show you the throttle that the "user" has set and the autopilot throttle respectively

**Comment by SilverWingedSeraph** [comment]
That's an excellent solution, thank you.
