### ISSUE TITLE
Debug code is unreachable by design

### ISSUE THREAD

**Issue by mathuin** [KSP-KOS/KOS#2343]
There are several pieces of debug code in the repository of the style:

    const bool DEBUG_WALK = false;

    if (DEBUG_WALK) SafeHouse.Logger.Log("BodyOrbitsBody(" + a.name + "," + b.name + ")");

The compiler generates "unreachable code" warnings for this code.  This warning is mentioned in at least one place in the repository as being deliberate.  

It may be better to intentionally disable the "unreachable code" warning for code of this type.  The preprocessor has a pragma to disable specific warnings around particular pieces of code.  Minimizing "false warnings" will make it easier to recognize "true warnings".

Generating a PR to address this issue was trivial.

**Comment by MaraRinn** [comment]
https://stackoverflow.com/questions/3167637/how-can-i-easily-exclude-certain-lines-of-code-from-a-compile

I will check if [Conditional(“Debug”)] works for this purpose tonight-ish.

**Comment by mathuin** [comment]
I think the [Conditional("Debug")] idea is a good one, but I'm not sure it applies here since the cases I was looking at were 'printf'-style output embedded in particular methods that would be individually enabled in case of debugging that particular method.  I think #ifdef may be cleaner since that's what the if statements are effectively doing.  The other option is to simply remove the debugging code if it's no longer needed, but then folks will just have to put it back if the methods in question are insufficiently robust.

Thank you for looking into this, and I look forward to seeing your results!
