### ISSUE TITLE
kOS reading UTF-8 can't handle a file with a BOM in it.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#2345]
(This is something that was raised by issue #2265.)

kOS can read UTF-8 files on the archive (volume 0), but not when they are preceded by a BOM (Byte Order Mark) marker.  kOS ignores the BOM and fails to realize it doesn't count as char data.  Thus it's offset by one byte when rest of the bytes are read, making it mangle unicode characters above 127.

BOM is a short byte sequence optionally inserted at the front of a UTF_8, UTF-16, or UTF-32 file that tells the reader whether the file is encoded as UTF-8, UTF-16, or UTF-32.  It also specifies in UTF-16 whether the bytes are encoded in big-endian or little-endian order, which isn't even relevant information in UTF-8.  In UTF-8 the only purpose of the BOM is to identify the file as definitely being UTF-8.  Most editors that save UTF-8 don't even use the BOM mark.

The fix of telling users "Find your text editor settings about the BOM and tell it not to include it" is what we do for now.  But it is hypothetically possible to make kOS recognize the BOM when present and just skip past it as long as it says the file is UTF-8.

What is the BOM? -> https://en.wikipedia.org/wiki/Byte_order_mark

**Comment by acattaneo88** [comment]
I've implemented a quick fix here: [https://github.com/KSP-KOS/KOS/pull/2353](https://github.com/KSP-KOS/KOS/pull/2353)
