### ISSUE TITLE
Telnet Server Won't Take Input

### ISSUE THREAD

**Issue by Nybbler98** [KSP-KOS/KOS#2367]
Hey I really wanted to get this going so I could write a script that mimics a flight computer and have a friend fly missions on my computer. The telnet server is a really good idea but I can't get it working, **I can connect to the serve**r (It shows both in KSP and in the Client) but I **can't type any input** into the server. It shows the CPU selection menu and just has a blinking cursor at the bottom, when I type nothing shows up, **none of the key shortcuts or buttons work in the telnet window**. I tried both Microsoft Telnet and Putty, same issue on both. **I think the server isn't listening at the right time**. Everything seems to work fine up until I type something.

**Comment by Dunbaratu** [comment]
That's going to be hard to diagnose without seeing it.

But one thing I can say is don't use Microsoft Telnet.  It only speaks a rather limited subset of the telnet protocol. It doesn't negotiate properly into char-at-a-time mode, which the kOS telnet server needs.  Putty should work though.

Is Putty using VT100 or Xterm as its terminal type?  Only those two are supported.  That could be part of a problem, depending.

Other than that it may need a more complex logging.  If you can't make it work let me know and I'll see if I can give you a special version of the DLL that has a ton of debug log stuff spamming out that describes the protocol handshaking in detail.

**Comment by Nybbler98** [comment]
I think I found the issue, when the game is not in focus the terminal (putty) doesn't display key inputs but they still appear to be in the buffer, when you change focus to the game then the key presses appear in the terminal.
This won't really be an issue for my friend controlling it unless I change focus away from the game, which could still be a big problem. 

In [this ](https://i.imgur.com/nXXefQy.png) image putty is in focus and I've just typed "stage" into it, as you see nothing is displayed.

In [this ](https://i.imgur.com/umJdUea.png) image I have changed focus back onto the game and the word appears. 

In [this ](https://i.imgur.com/ckuYPAO.png) one I tab back out to putty and push enter, again nothing appears to happen.

And [finally ](https://i.imgur.com/lqVQCI3.png) when I tab back into the game, the key input is executed.

Since it didn't work in both microsoft telnet and putty I don't think this is a program incompatibility issue.
I think the telnet server in the mod is being paused when the game is not in focus (along with the game), if that's the case nothing can really be done about this unless someone can help me make sure KSP doesn't pause on focus change.

Any ideas?

**Comment by Nybbler98** [comment]
**Problem solved!**

This issue only exists when "Simulate in Background" is unchecked. 
I remembered that weird option. 

So for the record this issue only exists when the "Simulate in Background" option under Game / System settings is unchecked, my best guess is the game pauses when out of focus which in tern froze the telnet client.

**Comment by Dunbaratu** [comment]
Thanks for figuring this one out.  That would have taken forever for me to work out if I didn't know you had that option turned on.  It had forgotten that that option even exists.

I'm going to re-open this issue because the documentation about the kOS telnet server should mention this, and changing the docs is still an "issue" even if it's not a "bug".

**Comment by Dunbaratu** [comment]
Change - I'm not just going to add it to the user docs.  I'm also going to see if I can actually enforce it in the mod somehow, where attempting to turn on the telnet server while "simulate in background" is off will give the user some kind of message explaining the problem, and then refuse to actually start telnet.

**Comment by Nybbler98** [comment]
Nice work man, thanks for your speedy response.
