### ISSUE TITLE
Trajectories detection not working?

### ISSUE THREAD

**Issue by LouisB3** [KSP-KOS/KOS#2379]
Looks like kOS does not consider Trajectories to be available even when installed. I am running KSP (Windows) 1.5.1, kOS 1.1.5, Trajectories 2.2.1. 

I see that these versions of kOS and Trajectories are not officially supported for KSP 1.5.1, but they seem to otherwise work so I thought this would be worth reporting.

**Comment by PiezPiedPy** [comment]
see PR #2220

**Comment by LouisB3** [comment]
Thanks, I used your dev version of kOS and everything appears to be working correctly after a few minutes of testing. I possibly should have been able to find this myself, but it's a bit hard to sort through the timeline of various discussion threads and mod versions.
