### ISSUE TITLE
(Discussion) Standard Library Source Locations?

### ISSUE THREAD

**Issue by jonnyboyC** [KSP-KOS/KOS#2381]
If there is a better place to ask these sorts of questions please let me know and close this issue.

I've been trying to pin down where all the globally accessible KOS functions and structures that are located in this repo. Poking around I'm suspecting the the Binding and Function folder in KOS and KOS.safe contain the globally accessable entities.

[kos binding](https://github.com/KSP-KOS/KOS/tree/develop/src/kOS/Binding), [kos function](https://github.com/KSP-KOS/KOS/tree/develop/src/kOS/Function), [kos safe function](https://github.com/KSP-KOS/KOS/tree/develop/src/kOS.Safe).

I've been working on a kos language server over [here](https://github.com/jonnyboyC/kos-language-server). At this stage highlighting and parsing works and I'm attempting to add more semantic information. I've got some basics like detecting unused variables and goto definition for user functions in a single file. 

Right now I don't have any information to indicate calling "abs(-10)"  or "ship:heading" is fine because they're already defined in KOS. I've found this [doc page](https://ksp-kos.github.io/KOS/bindings.html?highlight=vessel) but I'd prefer having a script to scrape the repo so I know it's up to date with the release.

**Comment by Dunbaratu** [comment]
You keep using this weird term, "language server".  You don't define it here, nor do you define it on the github project you link to.  From the context of reading through that project I'm going to guess it is some kind of site that an IDE or text editor can use in lieu of a config file, to get the info about how do things like syntax highlighting and tab completion.  Is this right?  It might be a feature unique to VSCode, which I don't use.

In the past I often thought it would be handy for kOS to spit out a file with all the info a text editor needs for these things, which works by actually reading the kOS classes via Reflection and spit out the info.  That way it could give the grammar (already in the TinyPG file) and also the names of all the builtins (which requires reading at runtime), and the names of the suffixes (which again, requires reading at runtime).  This is why the suffixes have a field for "description" which was never actually used.  It was so it could be hypothetically possible to spit that description out when doing such a thing.

**Comment by jonnyboyC** [comment]
Here the a wikipedia article on the [language server protocol](https://en.wikipedia.org/wiki/Language_Server_Protocol), here is an article specifically about implementing [lsp for vscode ](https://code.visualstudio.com/docs/extensions/example-language-server). 

The main pull would be the majority of the editor support is actually located on a local server that the editor spins up in the backgrounds. The editors then acts as a client of the server. When you use a shortcut to go to definition, or when the editors gives you a diagnostic that a variable doesn't exist, that activity that is actually handled by the server in the background. With this setup you would only need to write a client for each editor you want to support but reuse the same server. As of now I've only written a vscode client. If I continue on with the project I'll probably eventually make the server and vscode client separate projects so I or others could more easily add or updated various clients.

Back on topic, so just so I'm following, the suggestion you have would be to build some sort of dumping class that could be turned on maybe via some config. Then we could use reflection to get the runtime information about all the loaded functions and whatnot and maybe dump this out to file somewhere. I would say I'd be interested in possibly implementing such a feature. I obviously have my own goals for the use case, if I were to put something like this together would certain outputs be useful for this projects, maybe those .rst doc files?
