### ISSUE TITLE
kOS holds references to dead parts: need ISDEAD suffix on part?

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#2383]
```
set all_parts to ship:parts.
print "Before stage, This script has references to " + all_parts:length + " parts.".
stage.
```
Now all_parts has references to all the ship parts that *used* to be on the vessel, even though part of the vessel detached with ``stage.``.  That's fine for now, but as the stage falls out of load distance and gets removed, the main KSP game will want to orphan those parts and it can't because the kOS ``PartValue``s still have references to them.  So instead the game marks them as dead and starts to remove their Unity objects.

But the script has no way to query "is this part dead?"  it can do it with vessels, using Vessel:ISDEAD, but not with parts.

**Comment by lucaelin** [comment]
related to #2225

**Comment by Dunbaratu** [comment]
ah - not just related - it's the same issue.

**Comment by Dunbaratu** [comment]
hmm.  I think this might bring about another issue though...  I'll write up a new one.
