### ISSUE TITLE
RCS dead zone 

### ISSUE THREAD

**Issue by nuggreat** [KSP-KOS/KOS#2426]
In some random googling I was doing I found a reference in the documentation on the KSP API to a rcsDeadZone that might kOS might be able to change to remove the current 5% cut off on the translation i have no clue if it will do anything or not but it might let kOS remove that limit.

https://kerbalspaceprogram.com/api/class_flight_input_handler.html

**Comment by Dunbaratu** [comment]
Sadly the value of rcsDeadZone is 0.001f, while the actual cutoff is happening at 0.05f, so whatever that rcsDeadZone value is for, it's not this.
git

**Comment by Dunbaratu** [comment]
I'm going to close this issue, not as "solved" but as "won't fix" because essentially we are helpless to fix it when it's coming from the base KSP system.
