### ISSUE TITLE
Listing sensors in code includes non-sensor parts

### ISSUE THREAD

**Issue by mathuin** [KSP-KOS/KOS#2427]
```
function hasThermometer {
  local HasT is false.
  list sensors in senselist.
  for s in senselist {
    if s:type = "TEMP" { set HasT to True. }
  }
  return HasT.
}

print hasThermometer().
```

What I expected was for this script to return `True` or `False` as it did in v1.1.5.2.

What I saw in v1.1.6.1 was an error `GET Suffix 'TYPE' not found on object PART(Mark2Cockpit,uid=691240960)`.  Replacing the `s:type` line with `print s.` showed that all parts on the vessel were included in `senselist`, not just those considered "sensors".

**Comment by Dunbaratu** [comment]
Looking at it by eyeball (I'm not in a position to compile to test right now), It looks like it got broken in commit 9758b0a which was part of PR #2256.

Specifically, in this "diff" from file "src/kOS/Suffixed/Part/SensorValue.cs" :

This code:
```
                foreach (PartModule module in part.Modules)
                {
                    var sensor = module as ModuleEnviroSensor;
                    if (sensor == null) continue;
                    toReturn.Add(new SensorValue(part, sensor, sharedObj));
                }
```
Effect: Adds a part to the list if it contains a ModuleEnviroSensor (which is derived from PartModule).

That was replaced by this code:
```
                if(part.Modules.Contains<PartModule>())
                    toReturn.Add(vessel[part]);
```
Effect: Adds the part to the list if it contains ANY kind of PartModule, whether it's a ModuleEnviroSensor or not.  All parts will contain *some* kind of PartModule, so all parts get added to the list.

**Comment by Dunbaratu** [comment]
I read through the commit and it looks like only "list sensors" had that mistake.  Many of the other "list" types were edited similarly in that commit, but it looks like all the other ones seemed to correctly mention a specific kind of PartModule rather than just generically all part modules like the sensor one did.
