### ISSUE TITLE
boot script not loading on scence transition (START_ON_ARCHIVE=true)

### ISSUE THREAD

**Issue by Defaultldentity** [KSP-KOS/KOS#2437]
core:bootfilename is set to "/boot/something.ks" by default. When I launch the ship, it works fine, but if I go to the tracking station and then load the ship back, neither "0:/boot/something.ks" nor "1:/boot/something.ks" is started (I tried to create the latter manually as it was absent).

With START_ON_ARCHIVE=false everything is all right.

KSP 1.6.1 kOS 1.1.6.2

**Comment by Dunbaratu** [comment]
There is an old submitted PR about this from a person who was a toxic personality to work with so I had put it off a long time.  (Also, for quite a long portion of that time, I was operating under the misconception that another person on the kOS dev team was working on that PR, so I thought I didn't have to.)

I'm in the middle of testing what that person proposed as a fix.

But in the meantime, can you tell me, are you using remote tech?  It could be relevant as Remote Tech takes a lot longer to find the connection to home after a scene switch than the stock comms net does.  The stock comms system finds the connection within 1 tick, while RT can sometimes take as much as a full second before it has all the bounce paths loaded in to find the connection.

**Comment by Dunbaratu** [comment]
@Defaultldentity Can you give an exact set of circumstances that caused it?  I'm having trouble making the problem happen with this test. (I believe you - I just need a test case that actually makes the bug happen so I can watch as it happens and diagnose things and I'm having trouble making it happen.)

Here's what I've been trying to far that doesn't make the bug happen:

SET CONFIG:ARCH to true.

The file "0:/testboot.ks" is this:
```
print "__PROOF THAT TESTBOOT IS RUNNING__".
```

Then: set core:bootfilename to "/testboot.ks".

Then reboot - It prints the message "__PROOF THAT TESTBOOT IS RUNNING__" on launchpad, and  when I go to tracking station and then back to lauchpad, and when the ship is "set orbit cheated' into orbit of moon.

It may require a specific set of circumstances to trigger the problem.  Is your ship really big so it takes time for the game to load it in?  What connectivity manager for kOS have you picked when you started the game (Permit All, CommNet, or Remote Tech), and do you have Remote Tech installed?

**Comment by Defaultldentity** [comment]
Hi, sorry for long silence.

> Then reboot

Reboot works for me too, the issue happens when I go to Space Center/Tracking station, and back to the ship: the boot script is not started. Typing reboot in console, or switching kOS module off/on again makes the script start again.

The ship is quite small (20 low-tech parts or so), connectivity manager is CommNet, no Remotetech installed

My steps to reproduce:

1. have START_ON_ARCHIVE=true

2. create new ship, add probe core and kOS module, set kOS module's boot script to /boot/something.ks in the editor:

```
core:doevent("open terminal").
print "something.ks".
wait until false.
```

3. Launch. See the script running.

4. Go to KSC (don't recover the ship).

5. Go to tracking station and choose the ship. The script won't be run automatically.

**Comment by Defaultldentity** [comment]
I can't reproduce it right now though. Let me experiment a little.

**Comment by Defaultldentity** [comment]
Sorry, I think I can't find a way to reproduce it again. True, it might had required a specific set of circumstances. I've switched to start_on_archive=false since then, and have changed a couple mods, and have refactored the whole kscript quite a lot.

I guess I'm closing this issue for now. Although could you link me to an issue/pull request of the similar problem you are talking about above?

> There is an old proposed fix about this
