### ISSUE TITLE
Fix CPU.OnLoad() and CPU.OnSave()

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#245]
These two methods have some obsolete code that attempts to restore the state of the computer for going on and off rails, but it doesn't work for some of the modern changes in later versions of kOS.  investigate why and fix it.

Perhaps it would be best for all Classes in kOS to have the capacity to implement an interface we make up, call it "IKOSPersistable" or something like that, that requires the class to implement its own OnLoad() and OnSaveI().  Then, much like our main PartModule's Update() calls out to all the IUpdateObservers, we could have our main PartModule's OnLoad() and OnSave() call out to all the IKOSPersistables.  What that would do is put the persistence logic in the classes themselves instead of being handled by a "foreign" class that arrogantly pretends to know their internals when it doesn't.

It would make it easier for a programmer to remember "Oh I changed this thing about this class, I'd better also edit its persistence methods to accommodate this important new piece of data."  Right now, to remember that requires knowing about how an entirely different class manipulates it.  (i.e. the code for how to reload a program context isn't inside ProgramContext.  It's inside our PartModule (KOSProcessor.cs).  That's what I'd like to see change.)

**Comment by hvacengi** [comment]
We didn't really fix this, but I'm going to close it as variable loading has been abandoned for the time being.  I'm going to close this issue refering to PR #1111.
