### ISSUE TITLE
Getting number of arguments error despite supplying correct number of arguments.

### ISSUE THREAD

**Issue by adsasson** [KSP-KOS/KOS#2451]
Not sure if this is related to the #2349 refactor, but the following script in version 1.1.6.3 results in the 'Number of arguments passed in didn't match the number of DECLARE PARAMETERS. Called with not enough arguments.' error.

orbitProgram.ks:
```
copypath("0:launch.ks","1:").
copypath("0:orbitLib.ks","1:").
copypath("0:shipStats","1:").
RUNONCEPATH("0:launch.ks","1:").
RUNONCEPATH("0:orbitLib.ks","1:").
RUNONCEPATH("0:shipStats","1:").

PARAMETER inputHeading,
          inputApoapsis,
          inputPeriapsis,
          inputScaleHeight TO 100000,
          inputGoalTWR TO 2,
          inputStaging TO TRUE,
          inputUseNode TOTRUE.



launchProgram(inputHeading,inputApoapsis,inputScaleHeight,inputGoalTWR,inputStaging).

orbitalInsertion(inputHeading,inputApoapsis,inputPeriapsis,inputStaging,inputUseNode).
```

Called with RUNPATH("orbitProgram",90,200000,20000). or with run orbitProgram(90,200000,20000). results in same error.

**Comment by adsasson** [comment]
One additional piece of information: if the empty parameters are supplied with default parameters and the script is called without parameters, it runs fine. If it is supplied with default parameters, and called with different parameters, the default values overwrite the input arguments.

**Comment by Dunbaratu** [comment]
@adsasson I've tried to recreate this problem a few times after reading this issue, with an example of my own, and I can't make the problem happen.

Can you provide the rest of the files needed to make this happen?
Specifically, I mean these programs:
``launch.ks``
``orbitLib.ks``
``shipStats``
``orbitProgram.ks``

It's possible there is something specific happening in just those programs that is needed to make it happen.  I may need to try it with the full scripts and then try to narrow it down to what they're doing that other scripts aren't.

If I can't get it to happen when I'm looking then I won't be able to debug anything about it.

**Comment by adsasson** [comment]
It's useful to know that it may not be a problem with the parameterization. The other files are long, and have their own dependencies. I had considered that there was a scope problem and that their might be naming collisions, but renaming variables hasn't seemed to help. I want to try a couple of things first.  I will try putting all the separate files in one large file, then break them out one by one to see if I can further isolate the problem. Please keep this issue open for now, and I will update with what I find.

**Comment by adsasson** [comment]
Ok, I've narrowed down the behavior. It's interesting, and I've included the smallest system that recreates the behavior. Basically, I had each script running the bootfile at start to load what were essentially file system behaviors, since they didn't always seem to be accessible after start, despite the bootfile (obviously) running on ship load. When I comment out the line to run the bootfile, (in demoLaunchProgram) the script takes parameters again.

### bootfile:
```
@LAZYGLOBAL OFF.

GLOBAL bootFile IS SHIP:MODULESNAMED("kosprocessor")[0]:BOOTFILENAME.
GLOBAL verbose IS FALSE.

CORE:DOEVENT("open terminal").
copypath("0:demoOrbitprogram.ks","1:").
```
### demoOrbitprogram.ks:
```
@LAZYGLOBAL OFF.
RUNONCEPATH(bootfile).

copypath("0:demoLaunchProgram.ks","1:").
RUNONCEPATH("demoLaunchProgram.ks").

PARAMETER inputHeading,
          inputApoapsis,
          inputPeriapsis,
          inputScaleHeight IS 100000,
          inputGoalTWR IS 2,
          inputStaging TO TRUE,
          inputUseNode IS TRUE.

performLaunch(inputHeading,inputApoapsis,inputScaleHeight,inputGoalTWR,inputStaging).
```
### demoLaunchProgram.ks:
```
@LAZYGLOBAL OFF.
RUNONCEPATH(bootfile).
FUNCTION performLaunch {
  PARAMETER a,b,c,d,f.
  PRINT a + " " + b + " " + c + " " + d + " " + f.
}
```

**Comment by Dunbaratu** [comment]
I was able to recreate the problem with this.

You can also make the problem go away by doing this instead of commenting out the RUNONCEPATH:
Leave the RUNONCEPATH there, but move the parameters up higher in demoOrbitprogram like so:

```
@LAZYGLOBAL OFF.
RUNONCEPATH(bootfile).

PARAMETER inputHeading,
          inputApoapsis,
          inputPeriapsis,
          inputScaleHeight IS 100000,
          inputGoalTWR IS 2,
          inputStaging TO TRUE,
          inputUseNode IS TRUE.

copypath("0:demoLaunchProgram.ks","1:").
RUNONCEPATH("demoLaunchProgram.ks").

// The parameters used to be here:
// PARAMETER inputHeading,
//           inputApoapsis,
//           inputPeriapsis,
//           inputScaleHeight IS 100000,
//           inputGoalTWR IS 2,
//           inputStaging TO TRUE,
//           inputUseNode IS TRUE.

performLaunch(inputHeading,inputApoapsis,inputScaleHeight,inputGoalTWR,inputStaging).
```

**Comment by adsasson** [comment]
Ok, thanks for the workaround.

**Comment by Dunbaratu** [comment]
I trimmed the example down to this minimal case, without the boot logic, without everything that isn't directly the problem itself:
```
// The contents of file "test2451_prog1.ks":
run test2451_prog2.

PARAMETER a,
          b,
          c is "default".

prog2_func(a,b,c).
```
```
// The contents of file: "test2451_prog2.ks":
FUNCTION prog2_func {
  parameter p2_a,
            p2_b,
            p2_c.
  print "prog2_func args were: ".
  print "p2_a = " + p2_a.
  print "p2_b = " + p2_b.
  print "p2_c = " + p2_c.
}
```
Just put both files on the archive, don't bother booting anything, and just do:
```
switch to 0.
run test2451_prog1.
```
And that is minimally enough to trigger the problem.

**Comment by Dunbaratu** [comment]
A more minimal example that triggers it:

#### test2451_prog.ks:
```
run once test2451_prog3.
run test2451_prog2.

PARAMETER a,
          b,
          c is "default".

prog2_func(a,b,c).
--

#### test2451_prog2ks
```
run once test2451_prog3.

FUNCTION prog2_func {
  parameter p2_a, p2_b, p2_c.

  print "prog2_func args were: ".
  print "p2_a = " + p2_a.
  print "p2_b = " + p2_b.
  print "p2_c = " + p2_c.
}
```

#### test2451_prog3:
```
print "Proof prog3 is running when you see this.".
```
```

**Comment by Dunbaratu** [comment]
Okay, so it seems that when RUN ONCE detects that the program was already compiled, it ends up skipping over the bit where the program's args get consumed.

This test example shows it:
Version 1 - using RUN without the ONCE keyword:
```
//prog2.ks
print "Proof prog2 is getting executed.".
```

```
//prog1.ks
run prog2.
run prog2.
run prog2.
run prog2.

// Deliberate div by zero crash to show a stack dump in the log:
set x to 1/0.
```

When you do that, the stack in the dump is like this:
```
kOS: Argument Stack dump:
Argument Stack: count = 2
001 SP-> _KOSArgMarker_ (type: KOSArgMarkerType)

000      0 (type: Int32)
```

But change those 4 run statements to RUN ONCE statements like so, and you get this output:
```
run once prog2.
run once prog2.
run once prog2.
run once prog2.
```

```
kOS: Argument Stack dump:
Argument Stack: count = 5
004 SP-> _KOSArgMarker_ (type: KOSArgMarkerType)

003      _KOSArgMarker_ (type: KOSArgMarkerType)

002      _KOSArgMarker_ (type: KOSArgMarkerType)

001      _KOSArgMarker_ (type: KOSArgMarkerType)

000      0 (type: Int32)
```

Proving that RUN ONCE is leaving stuff behind on the stack when the execution is skipped.

Note, this does NOT leave your args behind if you did something like this:
```
run once prog_with_args(10,20).
run once prog_with_args(10,20).
run once prog_with_args(10,20).
print 1/0 // deliberate crash for logging.
```
(If you do that, then all the extra 10's and 20's on the stack DO in fact get popped off.  It's only the extra _KOSArgMarker that is left behind).

In my testing I believe leaving the arg behind is what causes the bug in this issue's original post.
