### ISSUE TITLE
Engine suffixes not working properly on multi-mode engine

### ISSUE THREAD

**Issue by JennyDracos** [KSP-KOS/KOS#2452]
Among the recent failures: calling engine:mode on a Rapier throws an error for 'trying to call mode on a single-mode engine', and calling ignition on a live Rapier in closed-cycle mode returns false.

**Comment by Dunbaratu** [comment]
Similarly, the PART (not engine module) also has the same kind of confusion about whether or not it should have multi-mode suffixes on it.
e.g.
``print ship:parts[4]:suffixnames`` shows that part 4 (a R.A.P.I.E.R engine) has the suffix ``AUTOSWITCH`` on it.  But attempting to do ``print ship:parts[4]:autoswitch.`` gives the error message that this isn't a multi-mode engine and thus that suffix is invalid.  (If it's not a multi-mode engine, that suffix shouldn't be on it.  At least that's how it used to work.)
