### ISSUE TITLE
Is there a way to go from seconds scalar to a TimeSpan?

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#2475]
Looking through the code, I don't think there is a direct way.

We have the ability to ADD or SUBTRACT seconds from a ``TimeSpan``, but the only way to construct a ``TimeSpan`` appears to be to get the "now" time with ``TIME``.  You can't get an arbitrary timespan of some other time.

Proposal: A TimeSpan constructor function that allows a user to pass in a number of seconds, and it will make a new TimeSpan that many seconds from game epoch.

i.e. ``set oneHourTimespan to TIME(60*60).``

We could just change the existing TIME bound variable and turn it into instead a builtin function call that can tolerate zero or one arguments.  If given zero arguments, it behaves as before, and gets the now time.  If given an argument, it takes that to be the number of seconds to construct from.

**Comment by teleksterling** [comment]
So then will `TIME + 60*60` give the same result as `TIME + TIME(60*60)`?
I assume the old syntax will be kept for compatibility.
