### ISSUE TITLE
"panels off" and "toggle panels" result in continuous log spam

### ISSUE THREAD

**Issue by plonk75** [KSP-KOS/KOS#2488]
KSP 1.6.1
kOS 1.1.6.3

When executing `panels off` or `toggle panels` on a vessel equiped with an OX-STAT or an OX-STAT-XL solar panel, heavy log spam starts until the flight is reverted, or left otherwise.
This doesn't happen if vessel has only retractable and/or deploy-once solar panels attached.
If moveable solar panels and non-movable panels are combined on a vessel, the spam starts as well.
How to reproduce:

- Take a CX-4181 part,attach a probe core and an OX-STAT or OX-STAT-XL to it.
- Launch
- Mod-F12 to open KSP console
- open terminal and try `toggle panels.` 

expected result: nothing related
actual result: logspam starts

- revert to launch
- open terminal and try `panels off.`

expected result: nothing related
actual result: logspam starts

**Comment by Dunbaratu** [comment]
I think I might know the cause of this.  ``panels on`` tries to operate on all panels, rather than only on those panels for which an "extend" action exists.  When it *is* a solar panel but *is not* one that can be extended, kOS tries to call its extension action anyway.

**Comment by plonk75** [comment]
Just for clarification: I couldn't trigger the log spamming by executing a `panels on.` command. No matter which combination of panels. Only `toggle panels.` and `panels off.` produce the NRE spamming.
Could it be related to #1469 ? 

I was wondering if it's something new, or went through unnoticed for me all the time, so I tried it in my older KSP versions, and the problem occures in all of them, too:
KSP 1.4.5 kOS 1.1.5.2
KSP 1.2.2 kOS 1.1.0
KSP 1.2.0 kOS 1.0.1

**Comment by Dunbaratu** [comment]
I got this to recur with testing.

Interestingly enough nothing in kOS itself is complaining.  The NullRef is coming from KSP's own code.  They probably didn't expect the solar panel toggle to be invokable on these panels because it's not on the GUI panel.  It's kOS being able to invoke it "under the hood" that makes it do something they couldn't test for or expect to happen.

This is the message:
```
NullReferenceException: Object reference not set to an instance of an object
  at ModuleDeployablePart.updateFSM () [0x00000] in <filename unknown>:0 
  at ModuleDeployablePart.FixedUpdate () [0x00000] in <filename unknown>:0 
  at ModuleDeployableSolarPanel.FixedUpdate () [0x00000] in <filename unknown>:0 

```

**Comment by Dunbaratu** [comment]
Preliminary experimentation indicates it might be this thing in the part config files that affects whether or not the panels are *really* retractable:
```
		animationName = altsolarpanelbase
```
It appears that when the action groups "Extend", "Retract", and "Toggle", are defined, they still don't *really* get enabled unless that ``animationName`` is defined.  If you delete ``animationName`` from the part cfg for extendable solar panels, the game removes them from the action groups available in the VAB.

So what we might need to do is test whether that field exists.  If it does not, then this panel doesn't count and should be skipped over.
