### ISSUE TITLE
kOS 1.1.7, KSP 1.6.1 or 1.7 : No longer being able to set the target to a BODY

### ISSUE THREAD

**Issue by TheGreatFez** [KSP-KOS/KOS#2495]
`set target to Minmus.`

This code snippet used to work before on a previous version, but is currently not working in the latest version as of this post (1.1.7). I have been able to replicate this issue with ONLY kOS installed and the same error occurs on KSP version 1.6.1 and 1.7.

The error is as follows and the same thing happens when trying to set the target to any **BODY** (except of course the body the ship is orbiting since you can't set that target to begin with)

![image](https://user-images.githubusercontent.com/4756569/56631330-720abd00-661a-11e9-8b33-169cdc04c68f.png)

**NOTE: you can still set the target to a _VESSEL_, at least all the vessels I tried to set.**

It looks like it is assuming that the target its trying to set is always a vessel.

**Comment by Dunbaratu** [comment]
Note to self: this used to work.  Check to see if something may have broken about this because of PR #2403 - which had to alter the input lock handling around how SET TARGET worked.

**Comment by Dunbaratu** [comment]
Looking at this, it seems that BodyTarget isn't of type ITargetable, but Parts and Vessels are.  That appears to be the core cause of the difference, but now the question is - why?
