### ISSUE TITLE
[documentation] Description of BODY rotation values talk about its day

### ISSUE THREAD

**Issue by TheGreatFez** [KSP-KOS/KOS#2500]
In the following structure values in the `BODY` structure, the rotation of the body around its axis is incorrectly described as its day. The length of a day and how long it takes to make one revolution around its axis are not the same, since the rotation around Kerbol needs to be taken into account. 

As a suggestion, this can be described as it is in the KSP wiki (taken from the entry on Kerbin):

![image](https://user-images.githubusercontent.com/4756569/56857500-fd928f80-6933-11e9-88ef-00cdb99bbfde.png)

The Sidereal rotation period is the time it takes to go around its body axis. The solar day is the length of one day on Kerbin. `BODY:ROTATIONPERIOD` gives the sidereal rotation period not the solar day as it suggests.

`BODY:ANGULARVEL` and `BODY:ROTATIONANGLE` both also have this error in distinction between solar day and rotation around its axis.

Although not a big deal on Kerbin since it is a small difference, on different planets such as Moho the difference is quite pronounced.

**Comment by Dunbaratu** [comment]
Although I have to wonder why the heck the Wiki says "5h 59m 60s" when that "60 seconds" bit on the end should mean it's just written as "6h 0m 0s".
