### ISSUE TITLE
kOS can't access second engine of some multi-engine parts (i.e. RealEngines RD-108).

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#2508]
I don't know any stock engines with this problem, but mods can create engines with this problem.
One such mod is RealEngines, and one of its engines with the problem is the RD-108.

That problem is this: kOS assumes all engine parts fall into one of these two cases:
- Singleton engine: one part with one engine module in it.
- Multi-mode engine: one part with two engine modules that can only be active one at a time, with a mode switch toggling them.

The problem is that the following is also a valid configuration, and that RD-108 engine is an example of it:
- Multiple active engine:  one part with two (or more) engine modules that can be ALL active at the same time.  While there is only one part, the two engine modules in it are both independent, separately available and invokable. Both can be on at the same time.

Example of how it's used:  The RD-108 engine has multiple engine bells.  The big engine bells are fixed in place and provide most of the thrust.  They are surrounded by other smaller engine bells that can be gimballed.  This is modeled by using two engine modules active at once - one that has a lot of thrust, but no gimbal, and the other that has less thrust, but can gimbal.

Manifestations of the bug: 

- When you perform a LIST ENGINES IN FOO, and then examine the list, the list *does* indeed contain two engine modules for the part, BUT when you examine their properties, instead of two *different* engines, one being the stronger fixed engine and the other being the weaker gimbal engine, you just see the stronger fixed engine listed twice, and the gimbal engine isn't mentioned at all.

**Comment by RCrockford** [comment]
This is correct as I'm seeing it.

I'm not sure having multiple entries in LIST ENGINES IN FOO is correct though (my PR removes it). The issue there being that there is only one part (and hence one GUID), so there isn't an easy way to work out which of the two engine modules you are referring to at any given time.

**Comment by Dunbaratu** [comment]
I'm in the middle of regression testing and noticed there may be a second bug that predates your PR.

Older versions of kOS would report a multi-mode engine as 1 engine in LIST ENGINES.

Newer versions of kOS (even without your PR merged) report a multi-mode engine as 3 engines in LIST ENGINES - they appear to be 3 references to the same engine and all 3 work identically though (they are not the different modes of the engine, all 3 of them will report the new ":mode" when you toggle just one of them, so they are the same engine just referenced 3 times.  This is clearly wrong. 

I'm trying to trace down exactly when that happened.  It wasn't noticed at the time but we may have broken something in the last few months.

Therefore "try to make it match the previous behavior" might not be the right thing to do because the previous behavior seems to also have been a bug.

**Comment by Dunbaratu** [comment]
Should have gotten closed when PR #2498 got merged.
