### ISSUE TITLE
Backport for RO users. 

### ISSUE THREAD

**Issue by RCrockford** [KSP-KOS/KOS#2509]
There's currently not a recent backport for people running old versions of ksp for RO and similar mods.

**Comment by RCrockford** [comment]
I have a backport for 1.3.1 at https://github.com/RCrockford/KOS/tree/backport_for_1.3.1

I've not created a pull request as this isn't something that should go into the main develop branch.

**Comment by Dunbaratu** [comment]
This is a good idea.  I'll be looking at what you have in the coming days.  Right now I'm getting out a KSP 1.7 release of what we have and then I'll put kOS down for a day or two, but I'll come back to this and consider making a backport of what I'm releasing today.

**Comment by RCrockford** [comment]
RO has moved to 1.6.1 so I don't think this is required any more.
