### ISSUE TITLE
Part module fields sometimes appear with no name

### ISSUE THREAD

**Issue by RCrockford** [KSP-KOS/KOS#2518]
In certain cases part module fields can appear with no name if BaseField.guiName has zero length.
In this case it would be better to fall back to BaseField.name; the PAW in KSP appears to do this.

Repro: Latest RO in KSP 1.6.1, engines show a field at the top of the PAW "pressureFed". In kOS this is shown as an unnamed field.

**Comment by Dunbaratu** [comment]
Can you define "PAW"?  I've never heard the term.  From the context of your sentences I'm guessing it might be the menu you get when you right-click a part.

**Comment by RCrockford** [comment]
Sorry yes. Part Action Window, i.e. the right click context menu for a part.

**Comment by RCrockford** [comment]
I've attached a screenshot showing the issue.

![image](https://user-images.githubusercontent.com/40358880/58074303-dcbd0300-7b9c-11e9-81c6-4b395e6d8679.png)
