### ISSUE TITLE
Tutorials page has broken link.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#2528]
On this page: http://ksp-kos.github.io/KOS_DOC/tutorials.html

The link that says: "Basic Explanation Tutorial" is a broken link.

**Comment by Dunbaratu** [comment]
Duplicate of #2515

**Comment by DominikJaniec** [comment]
Note: If you, a very fresh rookie (like me today), and if you are looking for this document, you might find it under: https://github.com/KSP-KOS/KOS/blob/develop/doc/source/tutorials/basictutorial.rst
