### ISSUE TITLE
can't use string values that start with the "$" character.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#253]
```
PRINT "$some string".
Variable some string is not defined.
```

The problem has to do with how the kRISC system flags the difference between "this string on the stack is a literal" from "this string on the stack is a variable's name".  It does it by prepending a dollarsign to the string.

The fix would be to do one of two things:
1 - Use an "impossible" character instead of '$' as the flag - use something that a user probably cannot use as a character in a string - like a null char or a control char.  Be careful to use something
from 1-byte ascii and not an extension from Unicode because these strings do get saved in packed UTF-8 in some cases.
or 
2 - Provide a VarName object that is just a normal string, but wrapped in another class.  Push that on the stack instead of $name and then when popping it off the stack, the system can read its class type to know it's a variable's name.  This may make the ML file packing/unpacking a bit messy (because the ML file can only store primitives, not OOP class info) but there should be a way to do it.

**Comment by abenkovskii** [comment]
@Dunbaratu this feature can be used for "formatting":
```
set x to 42.
set var_name to "x".
print var_name + " is " + ("$" + var_name). // prints: x is 42
```

**Comment by Dunbaratu** [comment]
I've used that trick in debugging when I wanted to see what a lock function pointer was:
```
print "$throttle*".
```
But I'd rather that didn't work, and we had another alternative way to debug print that sort of thing.

**Comment by abenkovskii** [comment]
abuse (probably)
```
lock x to 0.
lock y to "I found a way to do 'callbacks' ".
set "$x*" to "$y*".
print x.
```

**Comment by Dunbaratu** [comment]
Clever.

Yeah it's definitely got to get fixed.  I figure we make the fix part of the upcoming "string manipulation" update, whenever that happens.

**Comment by abenkovskii** [comment]
I guess it's the same problem:
`print abc.blarg.` prints "abc.blarg"
![screenshot2](https://cloud.githubusercontent.com/assets/11031560/7512702/68c86c98-f4b7-11e4-9e77-9814bdde263f.png)
https://www.dropbox.com/s/rwngwqzxup8es5s/abc_blarg.txt?dl=0

**Comment by Dunbaratu** [comment]
I'm not 100% convinced that's the same as the original issue.
Instead it's parsing ``abc.blarg`` as a bareword filename instead of as an identifier, probably.

**Comment by abenkovskii** [comment]
I'm moving it to the new issue.

**Comment by abarbe-** [comment]
Looks like this is solved with the recent strings update.  Either that, or I'm failing to replicate it somehow.

**Comment by hvacengi** [comment]
This was indeed fixed.  At absolute minimum, the enforcing of encapsulation classes prevents the string value from being confused with an identifier.  I'll reference #1294
