### ISSUE TITLE
Add the ability to construct arbitrary orbit objects

### ISSUE THREAD

**Issue by pand5461** [KSP-KOS/KOS#2530]
I've noticed that orbit objects are not attached to existing orbits or maneuver nodes. One can create a maneuver node, save `nextnode:orbit` into a variable and delete the node. The variable still holds the orbit, although it's nowhere in the flight plan.

So, it could be useful to create orbital patches with user-defined parameters without maneuver node trickery. One example is the PEG algorithm where an auxiliary orbit is used to estimate gravity losses during a burn.

**Comment by ThunderousEcho** [comment]
Working on this

**Comment by ThunderousEcho** [comment]
Done on my branch.
