### ISSUE TITLE
Configurable default terminal size

### ISSUE THREAD

**Issue by mdpkh** [KSP-KOS/KOS#2548]
Unless it exists and I haven't found it, there doesn't seem to be a way to change the default terminal size in character cells. 36×50 is a rather awkward portrait orientation and doesn't fit a lot on a line. My preference is 64×20, which (given a font with a 5:12 ratio character cell) makes a 4:3 landscape screen and has about the ideal number of characters per line for reading text. Setting the font and font size are easy-to-find settings; why can't there be a default number of rows and columns right next to those settings?

I know I can change the terminal size programmatically using a boot script, but then I'd have to set every kOS module to run that boot script in every ship I design, and include the same code in any other boot script I might need, and if I want a ship's specific boot script to disable itself after its first run then it will also have to make sure the plain terminal-size boot script exists on the local volume and set it as the new boot script… sure it's all possible but it's a lot to have to consider to replicate the functionality that could very reasonably be a simple user preference alongside existing similar user preferences.

**Comment by Dunbaratu** [comment]
It's a good idea in general - to handle it the same way the default font height is handled on the kOS Toolbar Window.
