### ISSUE TITLE
Find centre of mass

### ISSUE THREAD

**Issue by meltingSnowdrift** [KSP-KOS/KOS#2555]
It would be considerably helpful to certain applications if some information about the position of the centre of mass of a vessel were accessible to scripts. For example, a vessel can be kept automatically balanced using resource transfers as resources deplete or staging changes.

There may be various ways in which this information may be presented. If there exists a coordinate system local to the vessel in which the centre of mass can be represented, it can be provided as a vector in that coordinate system. It may be possible to construct such a coordinate system if it is not provided, considering the position of the vessel is known and forward, top, and starboard vectors are already available.

If it is infeasible for some reason to find the centre of mass directly, it might be obtainable through something related to the camera, considering it is used by default as a reference point for camera placement.

**Comment by Dunbaratu** [comment]
The zero point of the XYZ coordinate system kOS presents to scripts (vector V(0,0,0)) IS ship center of mass.

**Comment by meltingSnowdrift** [comment]
Sorry for my lack of understanding of that fact.

How would it be possible, then, to find the position of this point relative to the vessel in some way? Can it be found relative to some part using the position vector of that part, which if the coordinate system is centred at the centre of mass is always the vector from the centre of mass to that part? What point on the part is used as the location of the part when getting part:position?

**Comment by Dunbaratu** [comment]
Yes you can pick a part and its position is relative to the ship's center of mass.  Which point on the part is the location is, unfortunately, depedent on how the graphic designer at SQUAD decided to design that part.  The part transform is centered depending on how they designed the mesh for the part.  Every part is different.

**Comment by Dunbaratu** [comment]
The closest label tag we have for "feature already exists" was "invalid" meaning "bug isn't a bug".
