### ISSUE TITLE
a way to get the waypoint selected for navagation [enhancement]

### ISSUE THREAD

**Issue by nuggreat** [KSP-KOS/KOS#2565]
When you set a waypoint as your navigation target in the map view it would be nice if there was some way for kOS to get this waypoint similar to how you can get the target.

A skim I did through the KSP API documentation and the mod [waypoint manager](https://github.com/jrossignol/WaypointManager/tree/2.7.5/source/WaypointManager) and it looks like there is a class [NavWaypoint class](https://kerbalspaceprogram.com/api/class_nav_waypoint.html#a93312424c2b7703bb828e52d1a5fda92) that may contain the needed info also might be something attached to the vessel for getting the waypoint called `navigationWaypoint` as well.

I would personally expect the use this to set or get the given way point would be similar to the use of the `target` bound variable using some var name like `waypointtarget`

**Comment by Dunbaratu** [comment]
The frustration I have with that is that the relationship points backward to what you're talking about.

You're talking about a way to ask "give me the active waypoint".

But what this is is "given a waypoint, tell me whether or not it's the active one".

Which means I can't see a way to implement it other than the unnecessarily expensive check: "for each waypoint that exists, test to see if its the active one."

**Comment by ThunderousEcho** [comment]
Working on this
