### ISSUE TITLE
Getting position vector from geographic coordinates

### ISSUE THREAD

**Issue by meltingSnowdrift** [KSP-KOS/KOS#2566]
There currently exists a function `Body:GEOPOSITIONOF(vectorPos)` which determines geographic coordinates from a position vector. However, there exists no function that I could find to do the opposite conversion. Such a function would be very useful to certain applications. For example, I intend to create a reentry guidance program which numerically solves some differential equations in the SOI-RAW reference frame. It would be very helpful if there existed an easy way to express the target coordinates in that reference frame.

Considering the conversion in the other direction already exists, there should not be too much difficulty here. For example, a computer algebra system can be used to reverse the vector-to-coordinates conversion.

Such a function could be of the form `Body:VECTORFROMGEOPOSITION(coordinates, altitude)`.

**Comment by nuggreat** [comment]
There do exist two calls that can convert a geoposition to a position vector they are both suffixes on a geoposition.

The first is the suffix `:POSITION` that returns the position vector of that geoposition at the terrain height.

The second suffix is `:ALTITUDEPOSITION(x)` where x specifies the altitude above/below the geoposition you want the position vector of.

Documentation on geopositions is [HERE](http://ksp-kos.github.io/KOS_DOC/math/geocoordinates.html#structure:GEOCOORDINATES).

On an unrelated note the issue tracker in github is not the best place to seek help on features within kOS you would do better to use ether the [subreddit](https://www.reddit.com/r/Kos/) or the [discord server](https://discord.gg/ZVVPEct) as that is where a fair number of kOS users hangout and as such a place where you are likely to get resonances fairly fast to what questions you might have.

**Comment by meltingSnowdrift** [comment]
Sorry about this. Sometimes I fail to find the right spots in the documentation, partly due to the way searches work there. I will try harder before posting this kind of thing again.

**Comment by Dunbaratu** [comment]
> On an unrelated note the issue tracker in github is not the best place to seek help on features within kOS 

To be fair, @nuggreat, @meltingSnowdrift wasn't coming here seeking help.  meltingSnowdrift was instead thinking "I want to make a feature request for something that is missing", which *IS* one of the things the github issues system is definitely for.  It was just that @meltingSnowdrift was mistaken about it being missing,  due to some searching fails.
