### ISSUE TITLE
KOS build breaks: 'Texture2D' does not contain a definition for 'LoadImage'

### ISSUE THREAD

**Issue by MaraRinn** [KSP-KOS/KOS#2569]
> …/KOS/src/kOS/Suffixed/Widget/Widget.cs(23,23): Error CS1061: 'Texture2D' does not contain a definition for 'LoadImage' and no accessible extension method 'LoadImage' accepting a first argument of type 'Texture2D' could be found (are you missing a using directive or an assembly reference?) (CS1061) (kOS)

I'm trying to get my development environment up to speed, and I've had to add a bunch of new assemblies that aren't documented in CONTRIBUTING.md.

My current list of assemblies is:

- Assembly-CSharp
- Assembly-CSharp-firstpass
- UnityEngine
- UnityEngine.AnimationModule
- UnityEngine.AudioModule
- UnityEngine.CoreModule
- UnityEngine.IMGUIModule
- UnityEngine.PhysicsModule
- UnityEngine.TextRenderingModule
- UnityEngine.UI
- UnityEngine.UnityWebRequestWWWModule

Development environment is Visual Studio for Mac Community edition, 8.2 (build 1105)

**Comment by Dunbaratu** [comment]
Okay, I'll keep this in mind.  I'm in the middle of getting a release ready.  Can you make a PR to that CONTRIBUTING.md file showing the extra things it needs to mention but doesn't right now?

**Comment by MaraRinn** [comment]
Assembly list update will happen on #2570

**Comment by MaraRinn** [comment]
Possible hint here: https://www.reddit.com/r/Kos/comments/9luwex/macos_development_bootstrapping/e7dyftc/

Checking that now.

**Comment by MaraRinn** [comment]
Builds without errors. Now to check that the built KOS actually works.
