### ISSUE TITLE
Means to detect if body exists

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#2587]
For people writing scripts meant to be played in multiple different modded solar systems (i.e. RSS versus Stock versus JNSQ versus GPP), it would be nice if a script could safely query (without crashing) whether or not a body exists.  Right now I don't see a means to do that.

i.e. if you do ``BODY("Mun")`` and there is no such body as Mun, the script crashes, but the script has no way to test with ``if BODYEXISTS("Mun")`` first, since no such test exists.

**Comment by plonk75** [comment]
You can easyly make the test exist using kOS alone. Is this too inconvenient? In V1.1.8.0 the following works.
```
declare function bodyexists {
    declare parameter bName.
    list bodies in bList.
    for b in bList {
        if b:name = bName {
            return true.
        }
    }
    return false.
}
print  "does mun exist? " + bodyexists("mun").
print  "does meep exist? " + bodyexists("meep").
```
If speed's an issue, one can transform the list to a lexicon having the names as keys, and initialise it once in an appropriate scope. Should work fine.

**Comment by ThunderousEcho** [comment]
Working on this.

**Comment by ThunderousEcho** [comment]
Added BODYEXISTS in my branch.
