### ISSUE TITLE
Small typo in pidloops tutorial documentation

### ISSUE THREAD

**Issue by lucaelin** [KSP-KOS/KOS#2604]
The pidloops tutorial page has a tiny typo in the example code. Instead of supplying Kp, Ki and Kd it supplies Kp twice to the constructor (missing the Ki term). This causes a lot of headache when people like me blindly copy and paste the example code :D

**Comment by ThunderousEcho** [comment]
Appears to already be resolved.

**Comment by lucaelin** [comment]
Hmm.. doesn't seem to be fixed in the develop branch, as my PR #2605 fixing it seems to be valid still...
