### ISSUE TITLE
Get rid of startup message about terminal fonts

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#2606]
There's something wrong with the startup dialog box that describes the terminal font, but it's hard to trace why it's happening because it might be an interaction with other mods.  The description is here:

https://forum.kerbalspaceprogram.com/index.php?/topic/165628-173-kos-v1190-kos-scriptable-autopilot-system/&do=findComment&comment=3661594

But in reality it doesn't matter how to fix it, because that dialog box doesn't need to exist anymore.  The proper solution should be to just get rid of it entirely.  The warning that says to go open the panel and pick a font should be replaced with just silently accepting the default and setting it as if it was the "user's choice".  If the player doesn't see that message, that's not the end of the world.  They just play with the default font kOS picked and don't know they could go change it on the toolbar dialog box, but not knowing that won't ruin any gameplay.

The original reason for the dialog was to inform people of the transition from the built-in bitmap letter images kOS shipped with to a system font (mostly so Unicode glyphs could be supported without me having to draw the bitmap images of hundreds of different multinational alphabets by hand).  But that change was years ago.  The box doesn't need to exist anymore.

**Comment by ThunderousEcho** [comment]
I fixed this on my branch.
