### ISSUE TITLE
Make HEADING() accept optional 3rd arg for ROLL

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#2609]
It would be handy if HEADING allowed you to say HEADING(compass,pitch,roll).
Note that with the default steeringmanager settings, roll won't do anything until you get close to the desired direction, so this would have to be documented with a note that you should also increase ``steeringmanager:ROLLCONTROLANGLERANGE`` to 180 make it have any effect.

**Comment by ThunderousEcho** [comment]
I am currently working on this.
