### ISSUE TITLE
A quick means to release all raw controls in an emergency.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#2624]
**The problem situation:**  You have a program that was using raw control (i.e. not ``lock steering``, but ``set ship:control:pitch to -0.2.``).  The program died unexpectedly because of an error.  The steeringmanager still leaves the raw controls stuck like that.  The airplane is now heading down to the ground and the player CANNOT override the setting with the manual controls.  The player now must hurry up and type ``set ship:control:neutralize to true.`` as fast as possible, hoping to get it all typed in fast enough to get control back before the plane nose dives into the ground.

There should be a FAST way to tell kOS "dangit LET GO NOW" and get control back for cases like this.  Either a hotkey, or a thing on the PAW - something like that.

Another possibility is for there to be a setting that says "let go on manual input" that will notice when the player is moving the axis in question, and have that override the raw controls for the axis. (i.e. while the player presses W or S, the pitch raw control is disabled until they let go of W or S.)

**Comment by Dunbaratu** [comment]
Addendum: Rebooting the CPU will release the control.  Maybe this is sufficient?

**Comment by poisonbl** [comment]
Just to actually record the notes from my added experimentation on this one so it's not lost to time, steeringmanager releases the controls when _all_ kOS cores are shut down (which just so happens in the case of a lone cpu during reboot). I vaguely recall that being related the fact that there's only one steeringmanager for the whole ship, and it quite reasonably doesn't try to track which cpu set what value.

**Comment by boiler1** [comment]
When this happens to me, I press Alt +F12 go to the "Locks" menu and press "release all Locks" until all zeros are displayed in the menu.  It would be nice if there was a hotkey to release locks.

**Comment by eusouaverdade** [comment]
What about a switch that prevent all cpus parts from receiving electricity.
The analogue to unplug the computer.

**Comment by mdpkh** [comment]
I imagine this should probably be a button in the kOS app window that lists the cores currently in the simulation. Of course, its effect should probably be limited to the cores on the active vessel, right?

And i think i like the idea of the button actually rebooting all the cores on the vessel, not just releasing the control locks, because that's a common troubleshooting procedure and could be useful for correcting other situations with misbehaving computers.
