### ISSUE TITLE
KSP 1.8 broke kOS.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#2632]
The KSP 1.8 update that just appeared by surprise today broke kOS.  Because it updates Unity and the version of .net, it may take a few changes in kOS source code to support it.

This issue will be the generic placeholder for getting it to work again.

**Comment by Dunbaratu** [comment]
My work on this is temporarily stalled by this question, which I just posted in the KSP forums:
https://forum.kerbalspaceprogram.com/index.php?/topic/188954-ksp-18-plugin-update-modder-questions-thread/&do=findComment&comment=3688459

**Comment by mlheur** [comment]
Build:
- had to change .net target version in my project file, not sure how come git didn't take your updated one
- had to link in more unity DLLs, more than just TriggerAu's list
- EventType.mouse* changed to EventType.Mouse*
- built with ~18 warnings.
- updated version to 1191 just so I could confirm I'm using the latest compiled version and not some stale kOS dll.

Gameplay:
- game starts, new sandbox career, make SPH, add KAL-9000.  All good.
- set boot to "/boot/kos.ks"
- launch: {blrup}, telnet 

`kOS Operating System
KerboScript v1.1.9.1
(manual at http://ksp-kos.github.io/KOS_DOC/)

Proceed.
Undefined Variable Name 'core'.
__________________________________________
           VERBOSE DESCRIPTION
Undefined Variable Name 'core'.
__________________________________________
__________________________________________
At 1:/boot/kos.ks, line 1
print "kos running as ["+core:bootfilename+"]".
                         ^
Called from [Boot sequence], line 1
run "/boot/kos.ks".`

**Comment by xot1643** [comment]
Does this explains why (for instance) the SHIP object is not recognized anymore by kOS in 1.8.1?
Looks like throttle is broken as well.

**Comment by nuggreat** [comment]
Yes, the fact that kOS is broken in KSP 1.8 does in fact explain why things in kOS are broken when you use the current release version in KSP 1.8.  The reason why they are broken is because KSP 1.8.x updated unity and .NET versions means that methods kOS previously used to do various things no longer work.  Hence why the issue is titled "KSP 1.8 broke kOS"

**Comment by xot1643** [comment]
Thanks for the explanation.
