### ISSUE TITLE
Documentation fails to mention OBT:nextpatch requires tracking station upgrade

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#2634]
It turns out that kOS will not let you see OBT:nextpatch and OBT:hasnextpatch if your tracking station isn't upgraded to where it can see the next patches.  If the user can't see the patches, then kOS won't show them either.  (HASNEXTPATCH will return false even when a transition is coming, and NEXTPATCH will fail just like it normally does when you have no patch coming.)

This isn't wrong -in fact it makes sense - but I don't see anything in the docs that mention it, and they should.

**Comment by nuggreat** [comment]
The career limitation on patches (and other things) is mentioned in the documentation [HERE](http://ksp-kos.github.io/KOS_DOC/general/career_limits.html).

For clarity it might not be a bad idea to have the the [orbit structure](http://ksp-kos.github.io/KOS_DOC/structures/orbits/orbit.html) page link to the career limits page.  The same can also be said about the [partModule structure](http://ksp-kos.github.io/KOS_DOC/structures/vessels/partmodule.html) page as that is also subject to restrictions but said restrictions are not mentioned on said page
