### ISSUE TITLE
(Dunbaratu's KSP 1.8 Branch) Telnet will not let you type anything.

### ISSUE THREAD

**Issue by ThunderousEcho** [KSP-KOS/KOS#2636]
After connecting to telnet, characters will not appear on screen regardless of the keys pressed by the user.

**Comment by Dunbaratu** [comment]
I cannot reproduce this problem.  I just tried with KSP 1.8 and my new branch, and PUTTY.  I got it to work on both 127.0.0.1 and on 192.168.1.4 (local real IP).
Can you find anything in your Player.log file from kOS about telnet failing?

**Comment by ThunderousEcho** [comment]
I just tested it again with PUTTY, and it worked fine. But windows built-in telnet does this:
`Connected to the kOS Terminal Server.                                                                                    Ç Terminal: type = INITIAL_UNSET, size = 80x24                                                                         ________________________________________________________________________________                                                      Menu GUI   Other                                                                                                        Pick Open Telnets  Vessel Name (CPU tagname)                                                                            ---- ---- -------  --------------------------------                                                                      [1]   no    0     orbiter? (CompoMax())                                                                  --------------------------------------------------------------------------------                                        Choose a CPU to attach to by typing a selection number and pressing                                                     return/enter. Or enter [Q] to quit terminal server.                                                                                                                                                                                             (After attaching, you can (D)etach and return to this menu by pressing Control-D                                        as the first character on a new command line.)                                                                          --------------------------------------------------------------------------------                                        > {Please resize to 120x30} Ç Terminal: type = ANSI, size = 120x30                                                     ________________________________________________________________________________________________________________________                                  Menu GUI   Other                                                                                                        Pick Open Telnets  Vessel Name (CPU tagname)                                                                            ---- ---- -------  --------------------------------                                                                      [1]   no    0     orbiter? (CompoMax())                                              ------------------------------------------------------------------------------------------------------------------------Choose a CPU to attach to by typing a selection number and pressing return/enter. Or enter [Q] to quit terminal server.                                                                                                                         (After attaching, you can (D)etach and return to this menu by pressing Control-D as the first character on a new commandline.)                                                                                                                  ------------------------------------------------------------------------------------------------------------------------>`
and does not let me type anything.

**Comment by Dunbaratu** [comment]
Important question:  Did you try Windows built-in telnet *before* KSP 1.8 and did it work then?  I'm not sure this is a thing that broke with KSP 1.8.  I remember Windows telnet never quite working right because it's not a proper full fledged telnet client.  It doesn't obey all of the client/server negotiation handshaking about which end of the connection should do what.  When kOS's telnet server tries to tell it, "no, you should be operating in one-char-at-a-time mode, without local echo, and let me echo chars back to you as I see you type them", Windows Telnet always just ignored those handshaking parts of the protocol and stayed in line-at-a-time mode.

**Comment by ThunderousEcho** [comment]
Windows telnet does not work on 1.7.3 either.
