### ISSUE TITLE
Version updating for KSP 1.8.1 release

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#2641]
(A placeholder issue for the release, just to hold true to the idea that edits need to be PR's and PR's need to have issues.)

**Comment by quade-ksp** [comment]
Loads, but when I try to open a terminal, it gives me an error related to the new .dds files. I checked the GFX folder and they appear to be there, but still fails.

I should probably mention I'm running KSP 1.8.1 on a Mac running 10.15.1.

[kOS_Errors.zip](https://github.com/KSP-KOS/KOS/files/3800573/kOS_Errors.zip)

**Comment by marcusdb** [comment]
Same here on Mac 10.14.6

**Comment by Dunbaratu** [comment]
v1.2.1.0 should fix the problems with texture loading on UNIX platforms.
