### ISSUE TITLE
Improved RCS module interface

### ISSUE THREAD

**Issue by RCrockford** [KSP-KOS/KOS#2657]
I'd like to propose a new part type for RCS thrusters which works similarly to the Engine type.

The proposed interface is to allow toggling of the thruster on and off, toggling the various advanced tweakable axis controls (yaw, pitch, roll, x, y, z), thrust and Isp readings (sea level and vacuum).

This would allow for better control of individual RCS thrusters and allow for performance calcs for making RCS manoeuvres.

I have some code written for this, I'll put together a PR when it is tested and documented.

**Comment by nuggreat** [comment]
It would also be nice if as part of the RCS type there was a way to get the a list of the thrust vectors that a given rcs engine can generate for use as that is useful when trying to balance RCS thrust using the thrust limiters to eliminate rotation.

**Comment by RCrockford** [comment]
That is certainly possible, though maybe goes against the ethos of kOS a little as that's not easily available to the user.

**Comment by nuggreat** [comment]
The thrust vectors are easily accessible to the player you just need to look at the part all this does is add them in such a way as it is easy to work with them in kOS with out requiring the player to build a data base of parts and there associated thrust vectors.

**Comment by RCrockford** [comment]
I have some code working wwhich adds the following suffixes: 
- `ENABLED` get/set toggle of the engine
- `YAWENABLED` `PITCHENABLED` `ROLLENABLED` `STARBOARDENABLED` `TOPENABLED` `FOREENABLED` `FOREBYTHROTTLE` `FULLTHRUST` these have the same effect as the advanced tweakable toggles. `FULLTHRUST` might better be named `FULLACTION` as that mirrors the GUI toggle more closely.
- `THRUSTLIMIT` `AVAILABLETHRUST` `AVAILABLETHRUSTAT` `MAXTHRUST` `MAXTHRUSTAT` these are similar the the engine suffixes of the same name. Note that there's no way to get the current thrust of an RCS port that I can find.
- `MAXFUELFLOW` `MAXMASSFLOW` `ISP` `VACUUMISP` `SEALEVELISP` `FLAMEOUT` `ISPAT` these are also similar to the engine suffixes. 
- `THRUSTVECTORS` gives a list of unit vectors that the thruster can thrust along.
- `CONSUMEDRESOURCES` is similar to the resource list for engines, except that many of the suffixes don't work, as fuel flow calcuations require an engine. 

This seems to me like a reasonable API, but I'm not that happy about the consumed resources information, given so many of the suffixes are broken.
