### ISSUE TITLE
Engine suffix to report consumed fuels

### ISSUE THREAD

**Issue by RCrockford** [KSP-KOS/KOS#2658]
A new suffix to return a list of fuels this engine consumes. Mainly useful for RO where there are a large number of fuels, but could be useful for stock fuelling calcs to determine if an engine is monoprop or liquid fuelled.

My current proposed solution for this just returns a list of strings. I noticed in #2075 that a lexicon with proportions was proposed; I haven't found a way to get this information yet.

**Comment by RCrockford** [comment]
Updated solution:
Lexicon of fuel names and flow rates.
These seem easy to get and work for rockets, though I'm not exactly sure what you get for variable flow engines (like jets).

**Comment by nuggreat** [comment]
Assuming the fuel flow you are getting is always the same regardless of the engine/craft state then that is likley to be the flow for some nominal thrust where the pressure is assumed to be 1 atm and the mach number is at 0 would be my guess.  The real question is this flow thing you have worked out true if one changes the thrust limiter or is it like `MAXTHRUST` and ignores the thrust limiter, because ether way that needs to be noted.  As well as noting (if true) that the flow rates given are for the current 100% thrust.  Said notes would also include the disclaimer for jets as the values given (again if true) are only accurate at the nominal state of 1atm pressure and with a mach number of 0.

**Comment by RCrockford** [comment]
I have done a little testing.

The flow numbers I have are in litres per second (the same number as in the fuel gauge UI) and ignore all settings (they are the maximum for the engine).

As a comparison I also checked what `FUELFLOW` gives by comparison at full thrust. `FUELFLOW` seems to be giving results in kg/s, so would more appropriately be called `MASSFLOW`. There's also data available for a `MAXFUELFLOW` suffix, which gives maximum mass flow for the engine [essentially maxthrustat(0) / (g0 * vacIsp)]. kg/s is a bit inconsistent with other measurements as almost everything else uses tonnes.

Jets seem to give some nominal figure, I'm not exactly wure what it is, it wasn't the same as a statically fired jet on the ground (but I have AJE installed which might be affecting that).

Thoughts:
- Do we want an additional suffix for volumetric fuel flow? This would be more useful for estimating fuel consumption or range as tanks report capacity volumetrically.
- Should `FUELFLOW` be changed to `MASSFLOW`? This would break existing scripts so seems less than ideal. Maybe add `MASSFLOW` as an alias.
- Should per resource fuel consumption be returned volumetrically or by mass? Or maybe both by returning a new structure?

**Comment by nuggreat** [comment]
The units in the UI will not always have liters as the the "volume" (how do you have liters of electric charge?) as the exact meaning of one unit depends on how the resource gets defined.  Keep in mind stock liquid fuel is equivalent to RP-1 but 1 unit of liquid fuel is 5kg where as RP-1 is 0.82 kg/l so unless KSP RP-1 is 6x denser than the IRL stuff the units are arbitrary.  Keep in mind a mod you have might be changing the definition of one unit of stuff so I would recommend some pure stock/kOS testing as well.

If the current fuel flow is indeed giving kg/s then getting a unit(volume) equivalent would be nice.  and if it is indeed giving kg/s then like all other things in kOS it should be converted to be in Mg.  As for changing the name If the `FUELFLOW` is indeed giving kg/s (and if it is this should be added to the documentation) not just the units and you really want a `MASSFLOW` just alias it as one should avoid breaking changes.  

As for the per resource consumption it would be nice to get both mass and units ("volumetric") would be nice.  But having said that if it must be one or the other then try for the units as engines like the ion engine that require a mass-less resource should get proper support so one should get the rate for all resources not just the ones that have mass.

**Comment by RCrockford** [comment]
Agreed on no breaking changes.

By litres I do mean "units" - it's essentially whatever the resource is measured in on the UI. The conversion to mass is just multiplying that by density, so for electric charge should give zero mass. I will investigate what an ion engine gives as flow and mass. I'd assume it's mass flow would just be whatever consumption of xenon it has.

I am running RealFuels, so my fuels are measured in litres and kg for the most part, but the principles should hold for stock fuels as well, just with different density. I will test stock before submitting the PR in any event.

On the subject of `FUELFLOW` returning kg rather than Mg, this should really be changed, but then that introduces a breaking change, so I'm a little wary of just adjusting it. That said, I'm not sure it's much used at present as it's poorly documented.

**Comment by nuggreat** [comment]
Just did some testing in stock and the suffix `FUELFLOW` on engines is still in the total "units" per second the engine uses not in kg/s likely the only reason why you are seeing that is that you are using real fuels.

**Comment by RCrockford** [comment]
Yes this seems to be an inconsistency between RealFuels and stock. I shall leave `FUELFLOW` as it is (reporting in units) and add a new suffix `MASSFLOW` for reporting mass flow rates (in Mg/s).
