### ISSUE TITLE
PartModule SetField is ignoring symmetry

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#2668]
Effect when the user plays manually: If something is in a symmetry group, like say two elevator fins on either side of the fuselage placed with mirror symmetry, and you use the PAW to adjust a slider on the left one of them, that same adjustment gets copied over to the one on the right.  (i.e. change the "authority limiter" on one, it does both.)

Effect when the user does that same thing through a script:  The SetField() suffix of PartModuleFields seems to be bypassing whatever the game does to copy the effect symmetrically.  Even though the parts are in a symmetry group, setting the value of one part does not change the value of the other parts.

Not sure if this is a "bug" or a "feature".  Fixing it might break a script that has come to expect this (use kOS to adjust things separately that can't be adjusted separately in the UI.)

**Comment by nuggreat** [comment]
If the parts structure in kOS could be expanded to include a way to query for the parts in symmetry with the current part.  That would allow for an easy way to work with the parts that are in symmetry as a group without changing how kOS has worked in the past.

The only problem is that like with some of the `STAGE` related stuff we could end up with bug reports that are not kOS's fault and are instead a result of stock messing something up.  As sometimes staging, docking, undocking messes with symmetry.
