### ISSUE TITLE
The CreateOrbit function takes Mean Anomaly At Epoch As Radians

### ISSUE THREAD

**Issue by JCSkyKnight** [KSP-KOS/KOS#2681]
I think this is unintentional as I have checked the other angles and they all seem to be taken in degrees. Can test with a simple script.

set orb to createOrbit(20, 0, 270000, 20, 20, 290, 0, Mun).
print(orb:meanAnomalyAtEpoch).

set orb to createOrbit(20, 0, 270000, 20, 20, 290*constant:degToRad, 0, Mun).
print(orb:meanAnomalyAtEpoch).

**Comment by Dunbaratu** [comment]
For some reason this didn't close when the PR for it got merged, so I'm closing it manually now.
