### ISSUE TITLE
(structure)KACAlarm:ACTION not working.

### ISSUE THREAD

**Issue by kjl2875** [KSP-KOS/KOS#2686]
// KSP 1.9.1.2788
// Kerbal Alarm Clock 1.8.9
print version. // 1.2.1.0

print ADDONS:KAC:AVAILABLE. // True
GLOBAL na IS ADDALARM("Raw",time:seconds+600,"kOS TimeWarp", "Script activated warp throttle.").
PRINT na:ACTION. // "PauseGame" (actual action is KillWrapOnly)
SET na:ACTION TO "KillWarpOnly".
PRINT na:ACTION. // "KillWrapOnly" (actual action is KillWrapOnly)
SET na:ACTION TO "Pause Game".
PRINT na:ACTION. // "KillWrapOnly" (actual action is KillWrapOnly)
SET na:ACTION TO "PauseGame".
PRINT na:ACTION. // "PauseGame" (actual action is KillWrapOnly)

Note. I guess not supported this version.

**Comment by Dunbaratu** [comment]
Sadly, KAC changed their wrapper in a way that means kOS has to fail to support older KAC in order to support newer KAC.  That means when fixing this it will render kOS into a version that can't be made backward compatible with older KSP instances without breaking KAC support.

**Comment by kjl2875** [comment]
Oops. I just see at now after long ago....
If I can, find and using another options. thank you.
