### ISSUE TITLE
Make time to periapsis / apoapsis obtainable for future (or planned) orbits

### ISSUE THREAD

**Issue by vyznev** [KSP-KOS/KOS#2687]
Situation: I'm trying to write a script that would plan a circularization maneuver at the periapsis of a future encounter.  However, kOS seems to provide no way of determining the time at which the periapsis will occur until I've actually entered the SOI of the body around which I want to circularize (at which point I can use `ETA:PERIAPSIS`).

I believe this information is in fact available from KSP, as it's clearly displayed in the map UI.  It would be very useful if kOS could provide some way to expose it to scripts too.  One way to do that could be to add a new `:ETA` suffix to `Orbit` and make it return a structure similar to the current global `ETA` structure, but for that particular orbit segment.  (The existing `:NEXTPATCHETA` suffix could then be deprecated in favor of `:ETA:TRANSITION`.)

Note: This is basically a duplicate of issue #550 from 2015.  However, that issue was closed four years ago without a full fix ever having been implemented.

**Comment by pand5461** [comment]
The ETA to periapsis can be derived from the `orbit` object, specifically, from the mean anomaly at epoch and semi-major axis. For predicted orbits after transition, the epoch is at the SOI transition, so that MNA almost directly translates into the time from transition to periapsis.

**Comment by nuggreat** [comment]
the ETA to your periapsis will always be 1/2 way between entering the SOI and leaving it so something like this `LOCAL etaPE IS (preOrbit:NEXTPATCHETA + preOrbit:NEXTPATCH:NEXTPATCHETA) / 2.` or you can calculate it from the orbital elements

**Comment by vyznev** [comment]
@nuggreat That'll work for simple fly-by orbits, but not if the orbit patch begins or ends with a satellite encounter. So it won't work e.g. if you're trying to plan a circularization maneuver around Duna and your fly-by orbit happens to pass near Ike.

For closed orbits, it's possible to determine the periapsis time from `:EPOCH`, `:MEANANOMALYATEPOCH` and `:PERIOD`, which is actually what I tried first. But that fails for open fly-by orbits, since those have an infinite period (and thus even trying to access `:PERIOD` will crash the kOS script).

@pand5461 In fact, looking at the KSP API documentation, it seems that [the Orbit class](https://github.com/Anatid/XML-Documentation-for-the-KSP-API/blob/master/src/Orbit.cs) directly provides `timeToAp` and `timeToPe` members. I'm not 100% sure if those will have meaningful values for non-current orbits, but if not, `orbit.epoch - orbit.ObTAtEpoch` at least should hopefully give the UT at periapsis.

**Comment by luxgladius** [comment]
> @nuggreat That'll work for simple fly-by orbits, but not if the orbit patch begins or ends with a satellite encounter (or a maneuver). So it won't work e.g. if you're trying to plan a circularization maneuver around Duna and your fly-by orbit happens to pass near Ike.
> 
> For closed orbits, it's possible to determine the periapsis time from `:EPOCH`, `:MEANANOMALYATEPOCH` and `:PERIOD`, which is actually what I tried first. But that fails for open fly-by orbits, since those have an infinite period (and thus even trying to access `:PERIOD` will crash the kOS script).

Actually, you can do it for hyperbolic orbits as well. In that case, your mean anomaly at epoch is negative, and mean anomaly is zero at periapsis. Then all you need is the rate of change of your mean anomaly, which is sqrt(-mu/a^3) radians per second. A little unit conversion and you're done.

**Comment by Dunbaratu** [comment]
Should have been closed by #2689

**Comment by Dunbaratu** [comment]
gaah.  Dangit no it wasn't.  that PR mentioned this issue, but only in passing while fixing a different issue.

**Comment by Dunbaratu** [comment]
Man I am so confused by the mix of PR's.  Yes.  This is closed.  Because the OrbitInfo ETA suffix was added by #2690.
