### ISSUE TITLE
TermWindow.cs should cache bitmap screen image and not redraw unless dirty.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#269]
Currently, TermWindow does this snippet of code in each and every OnGUI() call, whether it needs it or not (this is inside TerminalGui, called by OnGui():  It cycles through the entire framebuffer of the terminal and performs a bitmap image paint of each individual character in its location onscreen.  This is how it ensures that whenever the character cell framebuffer is changed in any way, it gets repainted nicely.  It's effective but crude because it spends time repainting all the characters even on the OnGUI calls where nothing has changed about the terminal screen, which will be the majority of them.  The code in question looks like this:

``` 
            IScreenBuffer screen = shared.Screen;
            List<char[]> buffer = screen.GetBuffer();

            for (int row = 0; row < screen.RowCount; row++)
            {
                char[] lineBuffer = buffer[row];
                for (int column = 0; column < screen.ColumnCount; column++)
                {
                    char c = lineBuffer[column];
                    if (c != 0 && c != 9 && c != 32) ShowCharacterByAscii(c, column, row, currentTextColor);
                }
            }
```

What might reduce wasted painting time is to just save the entire combined bitmap image as one object (rather than a mosaic tile of characters), and point to that during OnGUI rather than rebuilding it each time.  Then we implement a dirty flag that tells OnGUI that a print or character keypress or clearscreen has happened.  It only rebuilds the image when its been told its dirty.

You can't *entirely* avoid having to repaint the screen each time because of the ridiculous way GUIs work in Unity, where the entire GUI widget needs to be redrawn from scratch "every" time, multiple times per second, but we can do that redraw from a cached image of the screen rather than rebuilding the image piecemeal every time.

I've been noticing it getting slower and slower to type in the terminal with each passing revision of kOS and it's starting to get annoying.  I don't know if this is the cause of it but it just looks like an expensive wasteful operation.

**Comment by erendrake** [comment]
@Dunbaratu do you have any more thoughts about this after you finished your terminal EPIC?

**Comment by Dunbaratu** [comment]
Hmm.  Well I suppose I could implement the exact same differ algorithm, but for the terminal window, and have it tile character pictures from the fontimage into the terminal image only where there was a diff.

It's possible.  But I wonder if it's worth it.  It may be one of those cases of pointless premature optimization.  Let's close this and not bring it up unless it becomes a problem later.
