### ISSUE TITLE
Please add Vessel:MomentOfInertia

### ISSUE THREAD

**Issue by Lookerksy** [KSP-KOS/KOS#2696]
There has no way to get moment of inertia of a vessel in current kOS.
But **there has "MOMENT_OF_INERTIA" in kRPC Documentation**. (unit: kg*m^2)
 (http://krpc.github.io/krpc/python/api/space-center/vessel.html)
It means **KSP's API including it**. Maybe kOS can get it without difficulty.

**Its value is important** for physical calculation.
Please add it into Vessel structure. Thanks.

**Comment by nuggreat** [comment]
There are two ways you can get your moment of inertia in kOS right now should you so choose.

1) You can get your moment of inertia by calculating it from your angular momentum and angular velocity both of which can be obtained off of the vessel structure.

2) You have access to the position and mass of all parts relative to the center of mass of the craft it would not be hard to calculate the inertia your self.

**Comment by Lookerksy** [comment]
> There are two ways you can get your moment of inertia in kOS right now should you so choose.
> 
> 1. You can get your moment of inertia by calculating it from your angular momentum and angular velocity both of which can be obtained off of the vessel structure.
> 2. You have access to the position and mass of all parts relative to the center of mass of the craft it would not be hard to calculate the inertia your self.

---------------------------------------------------------------------

Thanks for your quick reply. My reply see below:

2. I have different opinions. I don't think this method works:
    Parts shouldn't be regard as particle. They has their moment of inertia, but I can't get the value by current kOS.
        So I can't calculate the moment of inertia of the whole vessel by Parallel Axis Theorem.
    As a counter-example about non-particle system:
        Imagine a two-parts rocket,  according to particles system, its moment of inertia on Z axis(Roll) will be zero.
        Obviously, it's an untrue result.

3. In addition, the details of Vessel:ANGULARMOMENTUM and Vessel:ANGULARVEL in kOS Documentation:
    (https://ksp-kos.github.io/KOS_DOC/structures/vessels/vessel.html#attribute:VESSEL:ANGULARMOMENTUM)
    The page shows Vessel:ANGULARMOMENTUM is Type: Direction not Vector. <- It's wrong.
    The page doesn't show the Type of Vessel:ANGULARVEL. <- It's lacked.

1. I used to try this ways. I calculate (angular-momentum)/(angular-velocity) but I got a constantly changing result.
    Today I tried again. I found a point:
    Vector-AngularMomentum and Vector-AngularVelocity, these two vectors are not in the same direction.
    See image below. I press "E" to roll the vessel twice. ( after the vessel being stable in different directions, "RADIALOUT" and "NORMAL" )
    The Vector-AngularMomentum work well, but the Vector-AngularVelocity changed completely.
    I guess that the axis of Vector-AngularVelocity:y is north pole not facing direction .
    Maybe it's a vector in SOI-RAW reference frame, not in SHIP-RAW reference frame.

1.1 Calculating division will cause some problems. Like infinity (1/0) and error propagation.
    It's not a safe way to get moment of inertia.

Thanks.

![rrrrrr](https://user-images.githubusercontent.com/21987795/80864013-65e81f80-8cb2-11ea-9c98-6aebb077e318.jpg)

**Comment by Lookerksy** [comment]
> There are two ways you can get your moment of inertia in kOS right now should you so choose.
> 
> 1. You can get your moment of inertia by calculating it from your angular momentum and angular velocity both of which can be obtained off of the vessel structure.
> 2. You have access to the position and mass of all parts relative to the center of mass of the craft it would not be hard to calculate the inertia your self.

-----------------------------------------

I think I has corrected it :

Set vx to Ship:Facing:RightVector.
Set vy to Ship:Facing:Vector.
Set vz to -Ship:Facing:TopVector.
Set vv to Ship:AngularVel.
Set TrueAngularVel to V(vx*vv,vy*vv,vz*vv).

**Comment by nuggreat** [comment]
Right having also gone and tested the relevant vectors I have come to some slightly different conclusions.

First `SHIP:ANGULARMOMENTUM` is very strange in kOS for a few reasons.  As far as I can tell it is a right handed vector when all other vectors in kOS are left handed.  Also its unit vectors are the roll, pitch, and yaw axis of the `SHIP` they do not match any other vector in kOS.

Second you are indeed right you indeed can't go from positions and mass to MoI.  But using `:BOUNDS` you should be able to approximate the shape of parts and thus even for 2 parts in line approximate the MoI.

Third when you resolve the oddities between `SHIP:ANGULARMOMENTUM` and `SHIP:ANGULARVEL` you can indeed get the moments for the various axis of your craft as I originally put forth.  Yes there would need to be additional logic to avoid division my 0 errors but that should be simple enough to implement.  The code to get the relevant moments looks something like this:
```
UNTIL FALSE {
	LOCAL am IS SHIP:ANGULARMOMENTUM.
	LOCAL av TO SHIP:ANGULARVEL * -SHIP:FACING.//x = pitch(w = pos, d = neg), y = yaw(d = pos, a = neg), z  = roll(q = pos, e = neg)
	
	PRINT "pitch inertia: " +  (am:X / av:X).
	PRINT "yaw   inertia: " + (-am:Z / av:Y).
	PRINT "roll  inertia: " +  (am:Y / av:Z).
}
```

**Comment by Lookerksy** [comment]
> Right having also gone and tested the relevant vectors I have come to some slightly different conclusions.
> 
> First `SHIP:ANGULARMOMENTUM` is very strange in kOS for a few reasons. As far as I can tell it is a right handed vector when all other vectors in kOS are left handed. Also its unit vectors are the roll, pitch, and yaw axis of the `SHIP` they do not match any other vector in kOS.
> 
> Second you are indeed right you indeed can't go from positions and mass to MoI. But using `:BOUNDS` you should be able to approximate the shape of parts and thus even for 2 parts in line approximate the MoI.
> 
> Third when you resolve the oddities between `SHIP:ANGULARMOMENTUM` and `SHIP:ANGULARVEL` you can indeed get the moments for the various axis of your craft as I originally put forth. Yes there would need to be additional logic to avoid division my 0 errors but that should be simple enough to implement. The code to get the relevant moments looks something like this:
> 
> ```
> UNTIL FALSE {
> 	LOCAL am IS SHIP:ANGULARMOMENTUM.
> 	LOCAL av TO SHIP:ANGULARVEL * -SHIP:FACING.//x = pitch(w = pos, s = neg), y = yaw(d = pos, a = neg), z  = roll(q = pos, e = neg)
> 	
> 	PRINT "pitch inertia: " +  (am:X / av:X).
> 	PRINT "yaw   inertia: " + (-am:Z / av:Y).
> 	PRINT "roll  inertia: " +  (am:Y / av:Z).
> }
> ```

I tested and it works. This value looks better than I wrote.
And the it has at least 4 significant digits. It's enough to use.
Thank you~
