### ISSUE TITLE
New maxTemp for parts .cfg

### ISSUE THREAD

**Issue by robopitek** [KSP-KOS/KOS#2698]
So I don't know how it looks in old kerbals but I sure about one.
**Today you can use these  Scriptable Control Systems as heatshields** because their `maxTemp = 3400` (except KOSCherryLight it `maxTemp = 2400`) for comparision maximum temperature for random stock heatshield is 3300 and that brokes game balance!
So I think that maximum temperature for these computers should be 1200 because stock electronics (eg science parts, probe cores) `maxTemp` is also 1200. (except KOSCherryLight it `maxTemp` should be 2000 because stock illuminators `maxTemp` is also 2000)

I think you understand and sorry for my english.

**Comment by Dunbaratu** [comment]
This should have been closed back when  #2699 was merged.
