### ISSUE TITLE
Apoapsis/Periapsis keep moving?

### ISSUE THREAD

**Issue by hany** [KSP-KOS/KOS#2703]
I'm running into a strange issue where in a stable orbit, the numbers returned from kOS for `apoapsis` and `periapsis` keep shifting slightly. Here's a sample:

```
t:1250.45999999915 ap:86607.8660840464 eta_ap:1266.36340520438 pe:84995.4921298741 eta_pe:2745.72900012829
t:1251.43999999915 ap:86607.8694689768 eta_ap:1265.38468002298 pe:84995.4866109786 eta_pe:2744.7502691123
t:1252.21999999915 ap:86607.8696639046 eta_ap:1264.6047475228 pe:84995.4863014554 eta_pe:2743.9703362988
t:1252.83999999915 ap:86607.8696636958 eta_ap:1263.98474708935 pe:84995.4863010198 eta_pe:2743.35033586358
t:1253.35999999915 ap:86607.8707882622 eta_ap:1263.46517656778 pe:84995.4844651456 eta_pe:2742.83076339718
t:1253.81999999915 ap:86607.8730375176 eta_ap:1263.00603530687 pe:84995.4807932561 eta_pe:2742.37161824658
t:1254.27999999915 ap:86607.8752841308 eta_ap:1262.54689760436 pe:84995.4771245153 eta_pe:2741.91247665575
t:1254.71999999915 ap:86607.8773441765 eta_ap:1262.10768674736 pe:84995.473760298 eta_pe:2741.47326223295
t:1255.13999999915 ap:86607.8784657551 eta_ap:1261.68811869297 pe:84995.4719264569 eta_pe:2741.05369223112
t:1255.41999999915 ap:86607.8790296851 eta_ap:1261.40833281977 pe:84995.4710078108 eta_pe:2740.77390538807
```

Then when closer to the Ap:

```
t:2301.27249223684 ap:86607.8824857838 eta_ap:215.561976459077 pe:84995.4576647562 eta_pe:1694.92752199492
t:2301.99249223684 ap:86607.8794368264 eta_ap:214.842670932002 pe:84995.4594888088 eta_pe:1694.20821311877
t:2302.39249223684 ap:86607.8776045606 eta_ap:214.443084658561 pe:84995.460578428 eta_pe:1693.80862481482
t:2302.81249223684 ap:86607.8748577069 eta_ap:214.023706616764 pe:84995.4622225065 eta_pe:1693.38924375786
t:2303.21249223684 ap:86607.8727200032 eta_ap:213.624189540812 pe:84995.4635069166 eta_pe:1692.98972434888
t:2303.59249223684 ap:86607.8727208216 eta_ap:213.244189892228 pe:84995.4634997003 eta_pe:1692.6097246828
t:2303.93249223684 ap:86607.8727213728 eta_ap:212.904190435515 pe:84995.4634977538 eta_pe:1692.26972522227
t:2304.25249223684 ap:86607.8727212808 eta_ap:212.584190199328 pe:84995.4634961311 eta_pe:1691.9497249814
```

While the variance is relatively small (~0.03m at the most in this sample for Pe), it's enough to throw some precise calculations off.

Is this expected? Any way to compensate for it?

**Comment by luxgladius** [comment]
Is this in warp or in physics mode? While in physics mode, it models everything in real-time and round-off errors lead to minor variances in the orbital parameters. I find that if warp on rails, physics are not simulated and the parameters are constant.

**Comment by hany** [comment]
This is in physics mode, yes. Is there any workaround for this? It’s strange if they are inconsistent, yet it returns values with 10 decimal places (which you would think implies accuracy). Warping to get consistent results may not work for my purposes.

**Comment by luxgladius** [comment]
IMO, this is a KSP issue, not a KOS issue as KOS is just reporting the values that the game engine is using internally. I am personally not familiar with any mods or workarounds that address it aside from just putting it into warp.

**Comment by hany** [comment]
Strange enough, I also use Mechjeb to display stats on screen. It displays Ap/Pe up to 3 decimal places, and it is always consistent regardless. Notice in my output above, even the first 3 decimal places show quite a lot of variance. I assume Mechjeb is getting the same data from the APIs?

**Comment by luxgladius** [comment]
I'm not super familiar with MechJeb's code base, but it looks like they actually use a moving average to track the orbital parameters, probably so they don't appear to have the jumpiness with them that you are noting: https://github.com/MuMech/MechJeb2/blob/4882c3d2db3e69cb9e82dce979611cc8a5ae6014/MechJeb2/VesselState.cs#L94

**Comment by hany** [comment]
I just noticed that too. Very interesting. I may have to do the same on my end.

Thanks for your help.

**Comment by Dunbaratu** [comment]
The digits don't imply it's really that accurate.  They just imply no effort was made to *remove* digits.

The *default* when you ask a programming language to print a float value is for it to print out the whole thing.  If kOS rounded it then you'd be annoyed if you wanted to see the rest and it refused to show it.

**Comment by Dunbaratu** [comment]
Gave "wontfix" label, as this is coming directly from KSP's own numbers.  The reason you don't usually see this in KSP is that KSP rounds the display values quite a bit, to the point where the wiggly digits aren't shown.
