### ISSUE TITLE
Ship acceleration relative to itselft.

### ISSUE THREAD

**Issue by Lordakos** [KSP-KOS/KOS#2704]
Is there any way to get the acceleration of the ship compared to its own frame of reference, so that for example positive x acceleration always points outwards from the back of plane, like in a real fighter jet?
I have only just started so sorry for the inconvenience.

**Comment by nuggreat** [comment]
To get your acceleration vector you run measure the change in your velocity vector.  And once you have your acceleration vector you can ether use VDOT to compare against the various facing vectors of your craft or you rotate the acceleration vector into the aircraft's frame of reference by multiplying the acceleration vector by `-SHIP:FACING` which will rotate the acceleration vector so that the x/y/z aling with the 3 facing vectors of the ship.

**Comment by Lordakos** [comment]
Ooooof. I think I have bitten off more than I can chew. I have literally just started I have no idea how to do this. Do you have any tutorials or examples that may help me?

**Comment by nuggreat** [comment]
I don't have a tutorial at hand as it is mostly considered basic physics to calculate acceleration from speed.  As by definition a change in speed divided by the change in time is your acceleration.  In kOS that looks something like this: 

```
LOCAL oldVel IS SHIP:VELOCITY:ORBIT.
LOCAL oldTime IS TIME:SECONDS.
WAIT 0.
UNTIL FALSE {
	LOCAL newTime IS TIME:SECONDS.
	LOCAL newVel IS SHIP:VELOCITY:ORBIT.
	
	LOCAL deltaTime IS newTime - oldTime.
	LOCAL deltaVel IS (newVel - oldVel) / deltaTime.
	
	SET oldTime TO newTime.
	SET oldVel TO newVel.
	
	LOCAL shipRelDeltaVel IS deltaVel * -SHIP:FACING.//x = lateral, y = vertical, z = forward
	PRINT shipRelDeltaVel.
	WAIT 0.1.
}
```

There are many more methods to get your acceleration than this one but it should serve as a general demo for how to do it.

**Comment by Lordakos** [comment]
Thank you. Physics is not what I don't understand but the in-game coordinate system and the syntax that kos uses, as I'm a beginner in no programming and kos itself. But I do think I know what's happening here now. Thanks again.

**Comment by nuggreat** [comment]
For future problems you might have a better place to ask for help is the [kOS subreddit](https://www.reddit.com/r/Kos/new/) or the [kOS discord](https://discord.gg/ZVVPEct) as there are more people there who can help.

**Comment by Lordakos** [comment]
Good to know, thanks once again.
