### ISSUE TITLE
vector to euler

### ISSUE THREAD

**Issue by erentar** [KSP-KOS/KOS#2706]
Need to convert from `V(x,y,z)` to `R(pitch,yaw,roll)` without setting it to `steering`

apologies for lazy issue, could not find any better way to get help

**Comment by nuggreat** [comment]
A vector does not cleanly convert to a direction as a vector only contains two of the three elements of a direction, thus a second vector is needed to get the third element.  While setting steering to a vector will convert the vector to a direction you can't access the resulting direction as that only exists internally and is not accessible in kerboscript, also NEVER SET STEERING.  If you do need a direction than the function [LOOKDIRUP()](http://ksp-kos.github.io/KOS_DOC/math/direction.html#function:LOOKDIRUP) is the method to convert a pair of vectors to a direction.  Also for something like this the [kOS subreddit](https://www.reddit.com/r/Kos/new/) or the [kOS discord](https://discord.gg/ZVVPEct) would be better places to ask for help of this type.

**Comment by erentar** [comment]
Thanks for the fast response! LOOKDIRUP() is exactly what i needed.

**Comment by erentar** [comment]
#2707

**Comment by Dunbaratu** [comment]
Should have closed but it didn't because I had to type PR 2707 by hand to recreate it from develop instead of from master
