### ISSUE TITLE
Massive log spam on the tracking station

### ISSUE THREAD

**Issue by Tonas1997** [KSP-KOS/KOS#2718]
Title. The game slows down to a crawl on the tracking station due to the log being spammed with the following message:

`[ERR 16:28:06.057] kOS: kOSVesselModule.CacheControllable called with null parentVessel, contact kOS developers`

This error appears to ocurr exclusively on the TS scene.

KSP version: 1.8.1.2694
kOS version: 1:1.2.1.0

**Comment by ThunderousEcho** [comment]
Can you provide a save file? I'm not getting this error with mine.

**Comment by Tonas1997** [comment]
Fortunately the issue seems to have disappeared from my current save; if it ever comes up again, I'll reopen and post the savefile.
