### ISSUE TITLE
Can't drag program window.

### ISSUE THREAD

**Issue by MoonstreamJustNotInSpace** [KSP-KOS/KOS#2720]
I can't seem to drag the program editor. It seems just glued to the bottom of the CPU window, which I can drag around. Where do I click to drag it?

**Comment by nuggreat** [comment]
You don't, the edit window is glued to the bottom of the terminal by design.  Most of the people who use kOS a lot never touch the in editor and instead edit using an external text editor of some kind and access there scripts through the archive feature in kOS's file system.

**Comment by MoonstreamJustNotInSpace** [comment]
Oh. Thanks!
