### ISSUE TITLE
Command prompt does not work. (Error Line: 1, Error Column: 0)

### ISSUE THREAD

**Issue by TigerCatMichael** [KSP-KOS/KOS#2728]
Typing anything in the command prompt does not work, and any time I try to use it, i get this error message:

Syntax: Unexpected  token 'EOF' found. Expected EOI at line 1
[command i typed]
                         ^
_______________________________________________
Verbose Description
The parser used by kOS is complaining about a part of the script it can't understand. kOS uses a parser-generator tool known as TinyPG, and the text description you see from this error comes mostly from TinyPG, not from kOS itself.
Error Line: 1
Error Column: 0
Message: Unexpected  token 'EOF' found. Expected EOI
__________________________
[command i typed]
_______________
_____________
At interpereter
<<--EOF
^

It happens with anything i put there, not just commands or anything specific. 
I am using kOS in combination with other mods, and the ones that integrate with it are these:
Raster Prop Monitor
Buffalo
kOSPropMonitor

how do i fix it? it looks like i may be missing an addon or file related to "TinyPG"
![Capture](https://user-images.githubusercontent.com/57407154/89199725-fae20980-d57c-11ea-95d7-8dff37c4b888.PNG)

**Comment by luxgladius** [comment]
You need a period (.) to terminate commands, similar to how C/Java/etc use a semicolon (;).
