### ISSUE TITLE
VECDRAW labels gone in flight view (still there on map view) as of KSP v1.10.

### ISSUE THREAD

**Issue by ElWanderer** [KSP-KOS/KOS#2741]
kOS version: v1.2.1.0

Disclaimer: I'm not at my computer (I'm away on holiday) so cannot draw up a simple demonstration case for this.

Traitor on the kOS discord reported that they weren't seeing any `VECDRAW` labels in KSP v1.10.1, at least in flight mode. Switching to map mode apparently made them visible.

I'm still on v1.10.0 and I have screenshots of docking that should be showing `VECDRAW` labels, but aren't. For example, the below should have a "Waypoint X" for each blue arrow:
![screenshot25 (1)](https://user-images.githubusercontent.com/16566715/90176262-973bb580-dda0-11ea-8699-e6de0340856d.png)
That definitely worked in the past, though I don't have screenshots for any other recent versions.

**Comment by Dunbaratu** [comment]
I can confirm.  I only see labels on map view now.  dang.  Okay, this is promoted to a real bug.
