### ISSUE TITLE
[bug] module:GetField("Authority Limiter") crashing despite "Authority Limiter" in the module:AllFields list

### ISSUE THREAD

**Issue by nuggreat** [KSP-KOS/KOS#2744]
The field "Authority Limiter" in the stock module "moduleControlSurface" found on aerodynamic control parts shows up in the `module:ALLFIELDS` list but if one tries `module:GETFIELD("Authority Limiter")` kOS crashes with the error

```
an attempt was made to retrieve a FIELD called:
	Authority Limiter
from an object of type
	PartModuleFields
but it isn't available at the moment.
```

But as the Authority Limiter is viable in the open PAW at time of execution and shows up in the something is going wrong.

The part I used in testing was the "Big-S Elevon 1" and testing code was
```
local par is ship:partstagged("t")[0].
local module is par:getmodule("moduleControlSurface").
print module:getfield("Authority Limiter").
```

I have only tested this on KSP 1.8.1, kOS 1.2.1.0, with all DLC installed so I do not know if this issue exists in more recent versions of KSP as I do not have them on my computer at this time to test with.

**Comment by Dunbaratu** [comment]
Is this a duplication of #2666 ?

**Comment by nuggreat** [comment]
So it is didn't turn up when I was searched for other instances of the same problem but then I didn't check the closed issues.
