### ISSUE TITLE
Bug: The mEp (meananomalyatepoch) parameter of CREATEORBIT() is in radian.

### ISSUE THREAD

**Issue by janismac** [KSP-KOS/KOS#2750]
Making a copy of an `Orbit` object requires the following:

    set obt_copy to createorbit(obt:inclination, obt:eccentricity, obt:semimajoraxis, obt:lan, 
        obt:argumentofperiapsis, constant:DegToRad * obt:meananomalyatepoch, obt:epoch, obt:body).

**Comment by JonnyOThan** [comment]
This has already been fixed in https://github.com/KSP-KOS/KOS/commit/2b6640ede83f3eb61698a84c7d60aa168b146f86 just not in any official release yet.
