### ISSUE TITLE
:apoapsis and :periapsis are NaN for unloaded landed vessels.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#2803]
Assume "other vessel" is some distant vessel that is either LANDED or SPLASHED, but is well outside your local loading distance so the vessel is unloaded.

This will cause a NaN error on the stack:
```
print Vessel("other vessel"):periapsis.  // NaN Error
print Vessel("other vessel"):apoapsis.  // also NaN Error.
```

It works fine for vessels in orbit, but not for landed ones.

**Comment by nuggreat** [comment]
looks like a duplicate of issue #2523

**Comment by Dunbaratu** [comment]
yup - duplicate.
