### ISSUE TITLE
Parts which are both engines and rcs may be missing suffixes

### ISSUE THREAD

**Issue by RCrockford** [KSP-KOS/KOS#2808]
I have a part which is both an engine and RCS, it currently gets the RCS suffixes rather than the engine suffixes, but shows up in `list engines` which makes for some rather awkward or crashy scripts.

Due to the way the PartValue classes are set up, it seems we can't have both, so I think prioritising engines over RCS will generally cause fewer issues.

**Comment by mgalyean** [comment]
Does kOS echo the multiple inheritance of C#?  Could these parts inherit both the engine and rcs suffixes in theory?

**Comment by Dunbaratu** [comment]
@mgalyean C# doesn't have multiple inheritance. The way KSP achieves something similar to multiple inheritance (if, say, a part is two kinds of part at once) is to say that a Part *contains* two kinds of PartModule rather than saying it *is* two kinds of Part.

**Comment by mgalyean** [comment]
Oh yeah, I was thinking of how interfaces are used to fake it.  nevermind
