### ISSUE TITLE
SteeringManager is confused about RCS because API call GetPotentialTorque() is wonky

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#2814]
The SteeringManager tries to tune things based on what it knows of the torque of the vessel, from information it gets from the API call ITorqueProvider.GetPotentialTorque().
(Search the code for "GetPotentialTorque" to see where it's using it).

The problem is that KSP returns inconsistent results for this call depending on what kind of torque providing part it actually is, and this is messing with the SteeringManager in cases where the majority of the torque comes from RCS rather than other sources.

Through experimental testing, this seems to be what it does:

- If the ITorqueProvider is a reaction wheel
    - Position of part from Center of Mass doesn't matter.  Torque provided is magically constant regardless of distance from center of mass.  This might actually be "correct" in the game universe if reaction wheels really do work this way in game.
    - Because position doesn't matter, returns a constant amount in all X, Y, Z axes.  i.e. the vector returned is V(10,10,10) for a reaction wheel that provides a torque of 10.
- If the ITorqueProvider is an engine with gimbal
    - Position of part from Center of Mass matters.
    - Vector returned is in the reference frame of the ship itself, with the usual swapping of Y and Z axes that controls seem to have.
    - Magnitude changes depending on engine thrust, which seems correct.
- If the ITorqueProvider is an areodynamic control surface
    - Position of part from Center of Mass matters.
    - Vector returned is in the reference frame of the ship itself, with the usual swapping of Y and Z axes that controls seem to have.
    - Magnitude changes depending on speed and air density, which seems correct.
- If the ITorqueProvider is an RCS part
    - Position of part from Center of Mass matters.
    - **Vector returned is NOT IN the reference frame of the ship itself**.  It appears to be in the reference frame of Unity's global **world coords**.  As the ship rotates in space around the world coords' x, y, z axes, it keeps providing a different answer.  Pointing the ship directly along the world X, world Y, and world Z axes returns values that appear to swap the 3 numbers around in the tuple exactly as one would expect if it was in the reference frame of world.

That last one is the problem.  The code in SteeringManager seems to presume that GetPotentialTorque() always returns values in the reference frame of the ship.  And that's true ... in all cases *except* for ModuleRCS for some weird reason.

Possible fixes.  Pick one:

1. Continue using the stock call, but check for the case where the ITorqueProvider happens to be a ModuleRCS, and if it is perform a reference frame transform to fix this problem and make it give the answer in ship relative coordinates.  Pro: least code change to kOS.  Con: It's designing it so two wrongs make a right, which isn't very future proof if KSP ever fixes this.

2. Throw away the use of ITorqueProvider and just make our own.  Pro: future-proof against KSP ever fixing the problem. Con: Duplicating KSP's code and thus not future proofed against a new type of ITorqueProvider coming out later that our homemade call doesn't know about.

**Comment by marianoapp** [comment]
I'd go for option 1. It's a simple fix and if KSP ever fixes the underlying issue it's also easy to rollback.

The problem with rolling our own torque calculation is that the results may differ from KSP internal calculations (either now or in the future), leading to errors that may be too small to notice on their own but that add up to some hard to troubleshoot issue.
That's another of the reasons why I prefer option 1, if KSP fixes the underlying issue it's going to be pretty easy to notice (now that we know where to look).

There also the possibility of a hybrid approach: the first time the SteeringManager is instantiated we find a RCS thruster part, we calculate the torque manually and then compare the result with the value provided by KSP. If the values are close enough that means KSP fixed the issue (assuming the craft facing rotation is not zero).
On the other hand, if the values don't agree it means the issue still exists so we set a flag so the torque calculations can apply the required reference frame transformation.

**Comment by Dunbaratu** [comment]
Unfortunately further examination shows that ModuleRCS.GetPotentialTorque() is even more broken than I thought.  It's not even correct in world coords.

Other modders have resorted to having to do option 2 because of this.  I've been asking them in discord about it. the good news is that means I have some other projects' code I can crib, and one example in particular is GPL3 so there's no license issue.
