### ISSUE TITLE
Radiobuttons and Checkboxes don't inherit from window:skin:button

### ISSUE THREAD

**Issue by Kamikaetzchen** [KSP-KOS/KOS#2815]
`set window:skin:button:fontSize to 12.` doesn't work for radiobuttons and checkboxes and there is no extra skin for them either, so `set window:skin:radiobutton:fontSize to 12.` isn't possible.

**Comment by Dunbaratu** [comment]
Does this skin suffix work and give you what you need?

http://ksp-kos.github.io/KOS_DOC/structures/gui_widgets/skin.html?highlight=toggle#attribute:SKIN:TOGGLE

**Comment by Kamikaetzchen** [comment]
yes it does, totally missed it. thanks :)
