### ISSUE TITLE
KerbalScript Compiled KSM File Assumes ArgIndexBytes Incorrectly

### ISSUE THREAD

**Issue by newcomb-luke** [KSP-KOS/KOS#2825]
The following KerbalScript program seems to have the perfect length to trigger this event:

`LOCK STEERING TO UP + R(20, 0, 0).

LOCK STEERING TO UP + R(25, 0, 0).

SET X TO 30.

LOCK STEERING TO UP + R(X, 0, 0).`

This has an argument section that has a size of 258 bytes including the %A and the ArgIndexBytes in the argument section header. Although in CompiledObject.cs when packing the arguments, it does not take into account the argument section header when finding FewestBytesToHold(). Therefore in this extremely specific case, it incorrectly found the length to be 255 bytes, which is the maximum size that a byte can index.

Therefore it set the numArgIndexBytes to 1 byte instead of 2 like it should have.

So when running this KS file on its own it runs, but after compilation, there is an instruction that tries to access the last argument which fails due to it not being valid. So running after compiling to KSM crashes.

**Comment by newcomb-luke** [comment]
I suggest changing in CompiledObject.cs:
`            // Now that we've seen every argument, we know how many bytes are needed
            // to store the argumentPack, and thus the largest possible index into it.
            // This will be how many bytes our indeces will be in this packed ML file.
            int numArgIndexBytes = FewestBytesToHold(argumentPackLogicalLength);`
to 
`            // Now that we've seen every argument, we know how many bytes are needed
            // to store the argumentPack, and thus the largest possible index into it.
            // This will be how many bytes our indeces will be in this packed ML file.
            int numArgIndexBytes = FewestBytesToHold(argumentPackLogicalLength + 3);`
To take it into account when finding the NumArgIndexBytes

**Comment by Dunbaratu** [comment]
This is a good catch.
