### ISSUE TITLE
CKAN support?

### ISSUE THREAD

**Issue by pjf** [KSP-KOS/KOS#284]
kOS has long been one of our test mods for [the CKAN](https://github.com/KSP-CKAN/CKAN), and I'd love for it to be one of the first modules supported on our release.

Since I know you're working on 0.15, can I provide a `META.ckan` file that ensures our bots will be able to correctly index kOS and install it whenever you release via KerbalStuff? Unless you change install methods, there'll be no need to change the CKAN file each release; we'll be able to pick up that information automatically from KS.

Many thanks!

~ Paul

**Comment by erendrake** [comment]
@pjf Do you guys have a newer spec for the *.ckan files? Is there anything else we can do to be more supported :)

**Comment by pjf** [comment]
As far as I know kOS support in the CKAN is *excellent*, however I took a break at the start of this year and I'm still coming back up to speed with all things CKAN, so if you know of any reasons why it might not be excellent, I'd be more than happy to help!

**Comment by pjf** [comment]
As for the spec, it's at https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md , but I don't believe you'd have any reason to need any of the new features (and we should continue to handle documents using the old spec just fine).

**Comment by erendrake** [comment]
I have been thinking about building a separate build for ckan that doesnt include the MM dll. this way i can list it and a few other mods in the Recommends section.

**Comment by pjf** [comment]
CKAN won't install ModuleManager from kOS unless it's explicitly listed in the install stanzas. However kOS does *recommend* ModuleManager, so CKAN will download and use the most recent MM release available for the user's system. These rich relationships are core to how the CKAN work, and just as importantly means that mod authors can continue to bundle MM and other mods to remain compatible with non-CKAN users.

I've got an older version of kOS installed on my machine, and you can see the only files that it installs are unique to kOS itself.

I'd advise against a separate build for the CKAN, simply because that runs the risk of the CKAN and non-CKAN builds getting out-of-sync somehow, and making future problems harder to debug.

```
$ ckan.exe show kOS
kOS: Scriptable Autopilot System: kOS is a scriptable autopilot Mod for Kerbal Space Program. It allows you write small programs that automate specific tasks.

Module info:
- version:	0.15.3.0
- authors:	erendrake
- status:	stable
- license:	GPL-3.0

Recommends:
- ModuleManager, min: 

Suggests:
- RemoteTech, min: 

Provides:
- kOS

Resources:
- homepage: http://ksp-kos.github.io/KOS_DOC/
- kerbalstuff: https://kerbalstuff.com/mod/86/kOS: Scriptable Autopilot System

Showing 31 installed files:
- GameData/kOS
- GameData/kOS/Flags
- GameData/kOS/Flags/kOS-Logo.png
- GameData/kOS/GFX
- GameData/kOS/GFX/FontFinder.png
- GameData/kOS/GFX/font_sml.png
- GameData/kOS/GFX/launcher-button.png
- GameData/kOS/GFX/monitor_launch.png
- GameData/kOS/GFX/monitor_minimal.png
- GameData/kOS/GFX/resize-button.png
- GameData/kOS/GFX/terminal-icon-closed.png
- GameData/kOS/GFX/terminal-icon-open.png
- GameData/kOS/kOS-module-manager.cfg
- GameData/kOS/kOS.version
- GameData/kOS/Parts
- GameData/kOS/Parts/kOSMachine0m
- GameData/kOS/Parts/kOSMachine0m/KR-2042_uv_layout_1_d_NRM.mbm
- GameData/kOS/Parts/kOSMachine0m/KR-2042_uv_layout_1_EMIS.mbm
- GameData/kOS/Parts/kOSMachine0m/KR-2042_uv_layout_d.mbm
- GameData/kOS/Parts/kOSMachine0m/model.mu
- GameData/kOS/Parts/kOSMachine0m/part.cfg
- GameData/kOS/Parts/kOSMachine1m
- GameData/kOS/Parts/kOSMachine1m/model.mu
- GameData/kOS/Parts/kOSMachine1m/model000.mbm
- GameData/kOS/Parts/kOSMachine1m/model001.mbm
- GameData/kOS/Parts/kOSMachine1m/part.cfg
- GameData/kOS/Plugins
- GameData/kOS/Plugins/ICSharpCode.SharpZipLib.dll
- GameData/kOS/Plugins/kOS.dll
- GameData/kOS/Plugins/kOS.Safe.dll
- GameData/kOS/Readme
```
