### ISSUE TITLE
problem in orbitETA documentation

### ISSUE THREAD

**Issue by nuggreat** [KSP-KOS/KOS#2885]
It looks like the suffix table for the [orbitETA](http://ksp-kos.github.io/KOS_DOC/structures/orbits/eta.html) structure was not formatted correctly for the documentation generator and thus it was not generated correctly.

EDIT: the `orbitETA` documentation also notes the returned types as scalars I do not know if this is still true or if they are actually `timespans` ether way this to should also be corrected.

**Comment by Dunbaratu** [comment]
They actually are scalars in seconds.  They were left that way for backward compatibility.
