### ISSUE TITLE
Make triggers able to span multiple updates doing away with all the annoying behaviors.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#289]
The fact that triggers must continue to the end and thus must fit inside one update is rather annoying to me and to lots of users who find out about the problem the hard way.  We've made stopgap solutions like throwing the exception on long triggers but there's a much better solution - just make triggers able to span multiple updates, like so:

Current Cpu.Update() behavior is this:

Step 1 - Run flybywire-based lock expressions to completion (not all the locks - just the ones used by LOCK STEERING or LOCK THROTTLE.  Most locks just happen on the fly when they're referenced in an expression and the rest of the time when not being referenced they don't do anything.)

Step 2 - For each trigger:
  If the trigger condition is true
    Run the trigger to the end and (maybe) delete it.

Step 3 - Mainline code:  Until number of instructions executed > CONFING:IPU, run another instruction.  When CONFIG:IPU is reached, then remember the instruction pointer to pick up from there next time, and quit the update.

My proposed change is to do this instead:

Use the same logic as step 3 in Step 2 as well.

Maintain a queue of "what needs to run yet" which is a list of triggers or mainline code contexts.  When a trigger becomes true, add the trigger to the end of the queue UNLESS it's already in the queue then don't.  

Execute items in the queue round-robin, as follows:

When executing a "thing" (trigger or mainline), it will either end on is own before CONFIG:IPU or it will end because it hit CONFIG:IPU limits and there's still more code in the body to go.  When the execution of a "thing" is done, do one of the following:

If it completed and isn't being PRESERVEd,  then remove it from the queue.

If it completed and IS being PRESERVEd, then reset it's execution state (current Instruction pointer) and move it to the back end of the queue.

If it did not complete because it hit CONFIG:IPU first, then remember its execution state (current instruction pointer) in part of the queue's data structure for that item in the queue, and move it to the back of the queue.

In either case where it completed (being PRESERVEd or not) then that means there are still some instructions left in CONFIG:IPU.  Keep going, using them on the next item in the queue.  (i.e. the count of instructions so far this update is global to the CPU across all items in the queue.

What this does is turns triggers into "equal" citizens with mainline code, being swapped in and out of execution along with the mainline code.  In fact, it turns mainline code into essentially a trigger that's always true, in a sense.

I think this would make things a LOT clearer.  Perhaps it can be added to the 0.16 list.

**Comment by hvacengi** [comment]
Closed via #1542
