### ISSUE TITLE
Should rename "kerbin" bound variable for planet packs

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-KOS/KOS#2895]
Many planet packs (at least Galileo and Beyond Home) have different fictional names for the home world, but they are still internally named "kerbin" in the config files.  I'm not exactly sure of all the details, but I'm guessing it's because other mods or the game itself might be looking for this name as a hardcoded string.

In TPKSP in particular, it's pretty weird to have to use `kerbin` to refer to the home world in KOS.  It might be cool (though hacky) to try to detect this case and supply a different name as the bound var for this body.

**Comment by nuggreat** [comment]
restatement of a point in issue #2419

**Comment by JonnyOThan** [comment]
Yeah, sort of...but I would lean against having KOS use localized names, since it means a script would be tied to a specific language and that seems wrong.  There are lots of possible solutions for this, with different tradeoffs.  There could even be a special config file or config node that the mod author includes to tell KOS what the name should be.
