### ISSUE TITLE
Geoposition terrainheight is wrong for LATLNG's that are very close to a rover scanner arm

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#2899]
I swear I thought this bug was already reported, but as I look through the issues, I can't seem to find it, so I'm reporting it anew.

**To reproduce the problem:**

1. Place a rover scanner arm on a vessel and launch it to the scene, by which I mean one of these three parts from the Breaking Ground DLC: https://wiki.kerbalspaceprogram.com/wiki/CRSY_Light_Scanning_Arm, https://wiki.kerbalspaceprogram.com/wiki/SPRT_Medium_Scanning_Arm, https://wiki.kerbalspaceprogram.com/wiki/OP-E_Large_Scanning_Arm
2. Ask kOS to tell you what the ``ship:geoposition:position`` vector is.  Use a vecdraw to visualize it.
3. Notice the position is NOT the terrain under the vessel like it should be.  It's weirdly a few meters up in the sky above the vessel.  If your vessel did NOT have a scanner arm on it, then the vector would be correct, pointing at the ground just under the rover.

**The cause, I think:**

The reason for this happening is something I consider KSP's fault more than kOS's fault, but we may be able to find a means to work around it in the kOS code.

The rover scanner arm parts appear to contain an invisible large spherical collider around them for some reason, and for some reason this collider is on layer 15, which is normally used by KSP for terrain. This sphere appears to be the exact same size and shape as the green "preview range" sphere you can see in the VAB for these scanner arm parts when you rightclick them.  

``GeoCoordinate.GetTerrainAltitude()`` uses a raycast to "find" the real terrain hit for LATLNG's near the active vessel where terrain is loaded, and because this weird phantom sphere is on the same layer as the terrain, it's getting seen as a "hit" for the raycast hitting what it thinks is terrain.

Since it seems likely the stock game won't fix this bizzare feature of a phantom collider on the terrain layer that emphatically is Not terrain, we may have to find a way to work around it.  (Note, this bug affects stock too, as the phantom collider also blocks solar panels from the sun, but again I don't think it likely that this is getting fixed any time soon.)

**Comment by scimas** [comment]
Without knowing how the underlying kOS code works: you might be able to workaround by doing another raycast starting from the position of the hit of the first raycast. If there was no phantom terrain collider in the way of the first cast, the second cast shouldn't give any hit (at least no reasonable hit).

**Comment by Dunbaratu** [comment]
**Proposed solution ideas**

By necessity, all of these are hacky and kludgy:

1. Just before performing the raycast, forcibly disable the spherical colliders on the vessel, then re-enable them after the raycast is done.  Pro: probably the fastest to execute.  Con: This is really taking advantage of the lack of threading in Unity more so than I'm comfortable with (basically, we know nothing else in the whole game is going to be running for the brief moment while the collider is disabled, so we don't mess up anything else this way, but it still feels *icky* to me.)
2. Similar to idea 1 above, except instead of disabling the collider temporarily, kOS moves it to a different layer temporarily.  Pros and Cons are the same as for 1.
3. Use RaycastAll, which finds ALL hits along the ray instead of just the first hit, then skip over any hits that are for the scanner arm.  Pro: simple code.  Con: RayCastAll can be more expensive than RayCast, as it doesn't abort as early, and we'd be paying that expense every time, for a workaround to a problem that only happens with some specific vessel designs.
4. Use the exact same code it uses now, BUT put it in a loop, where if the hit was the scanner arm, then ignore that hit, move the origin point along the ray to just after that hit, and raycast again from there.  The majority of the time this "loop" only iterates once, except on the rare occasions where a scanner arm is hit, then it likely only iterates twice.  Pro: fairly fast-ish but maybe not as fast as 1 or 2 above. Con: a bit more code to write.

I'm going to try idea 4 first, and not try the others unless I can't get idea 4 to work.

**Comment by mgalyean** [comment]
One wonders if there are other colliders on other objects mistakenly (presumably) in the layer 15 also.  I'd bet that Squad probably doesn't want that in layer 15 and might want to know about it, if that turns out to be the situation.  I wonder if it would be a good idea for (4) above to not just check if the hit is the scanner arm, but more generally check if it isn't actual terrain.  This would deal with other objects having this same bentwardness

**Comment by Dunbaratu** [comment]
I did mention it in an issue on SQUAD's bug tracker.  But I have no hope of such an issue getting fixed.
I don't know the gameobject structure KSP uses for sure, so I'm going to have to experimentally find out what is a reliable way to test.  Keep in mind, the hits we *do* want to return currently includes not just the ground but also the base structures like runways and buildings which I *do* want to count as hits, so it's not just one simple parent object to look for, as in "is this ground?".  It's more like"is this ground, or VAB, or SPH, or launchpad, or ...." and at that point using a whitelist is just as prone to future error as using a blacklist is.

**Comment by mgalyean** [comment]
The plot thickens. is there a way to diffentiate objects "anchored" to ground?  I'm not sure what I mean by that, but anchored in the sense that landed vessels are not and that buildings and launch clamps are.  A more "meta" check like that could bypass a fragile white or black list.  And it would make it simple to document also:  "If the object is anchored, its top will be detected.  If you want to detect distance above landed vessel you should get distance to that vessel via vessel position or the position of its parts"

**Comment by mgalyean** [comment]
Now I'm recalling that for the scanning arm to work one must not be in motion.  What if the scanning arm is "anchored" when the vehicle isn't moving and the layer 15 thing is a side effect of that?  That would be really weird.

**Comment by Dunbaratu** [comment]
To form the best compromise I can that avoids writing code for just a one-off weird part, I'm using this logic:
When a raycast hit is found, check if that hit is a KSP Part object.  If it's a Part object, then it can't be terrain.  That way it's at least a generic catch-all for any such weird parts that may exist later.

**Comment by mgalyean** [comment]
Solid and simple solution

**Comment by Dunbaratu** [comment]
I think I may have a solution coded, but first I should have a repeatable test case that shows the problem before applying the fix.

This is that repeatable test case.  Run this script to show an array of vecdraws around the vessel for where it *thinks* the terrain is:
```
local spots is list().
local draws is list().
local face is ship:facing.
for y in range(-8,9) {
  local yCoord is y/2.
  for x in range(-13, 14) {
    local xCoord is x/2.
    local spot is body:geopositionof(
        xCoord*face:starvector + yCoord*face:forevector).
    spots:add(spot).
    draws:add(
      vecdraw(spot:position+1*up:vector, -1*up:vector,green,"",1,true)).
  }
}

print "press any key to make vectors go away.".
local ch is terminal:input:getchar().

for i in range(0,draws:length) {
  set draws[i]:show to false.
}
```

For reference, here is a picture of running that with a craft that has two scanner arms attached to pylons on the wings:

![screenshot25](https://user-images.githubusercontent.com/5216848/111290538-3fa24880-8614-11eb-916b-21ea8ba014ce.png)
