### ISSUE TITLE
ALT:RADAR some times returns incorect values

### ISSUE THREAD

**Issue by nuggreat** [KSP-KOS/KOS#2902]
It looks like the `ALT:RADAR` call will not return the radar altitude if to high above a body.  In my testing when descending to the mun `ALT:RADAR` would return more or less the same value as `SHIP:ALTITUDE` until within about 10km altitude or so of the surface, this will likely very as I think the change to actually reporting the radar altitude is because of the terrain fully loading in.  I also observed `ALT:RADAR` not reporting the radar altitude once the craft went above around 30km altitude though this required descending low enough it actually starting reporting the correct radar altitude.

I suspect this is a result of us trusting the KSP API for this data as in my testing calls such as `SHIP:ALTITUDE - SHIP:GEOPOSITION:TERRAINHEIGHT` and the `:BOTTOMALTRADAR` suffix never stopped reporting what looked like the true radar altitude.

First noted by user gmaster0o0 on the kOS discord.

**Comment by Dunbaratu** [comment]
Yeah, I think the same "fallback to PQS" logic that's in ``GeoCoordinates`` should be borrowed by ``ALT;RADAR`` (Meaning the routine would be pulled out of ``GeoCoordinates`` and made into a static utility method so both could call it).

**Comment by RCrockford** [comment]
This is particularly bad on Mars with RSS as the `alt:radar` height is in some cases below the surface, resulting in some fairly severe errors.

**Comment by nuggreat** [comment]
Due to a discussion on the Twitch Plays KSP discord I ended up going and testing this and no fix for this issue was in PR #3043 nor any other part of the 1.4.0.0 release.
