### ISSUE TITLE
Sample vessel with overshooting steering problem - steeringmanager torque calc wrong?

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#2912]
This may be the same bug as #2880 but it might not be.

A user in the KSP forum reported a problem and gave an example save file that showed it.

(Link to thread: https://forum.kerbalspaceprogram.com/index.php?/topic/165628-ksp-1101-and-111-kos-v1310-kos-scriptable-autopilot-system/&do=findComment&comment=3948357)

With this design of vessel, the steeringmanager claimed the torque the vessel is capable of is about ``2.5 kN*m`` when a back of the envelope calculation seems to show it should be more like about ``1 kN*m``.  Being this far off in how much torque it *thinks* it has causes oversteering past the target direction and wavering back and forth.

I think something may be wrong inside ``SteeringManger.UpdateTorque()`` making it give a bogus value.  Note: this is a vessel that only had RCS thrusters for torque and no reaction wheels, so that means it is using kOS"s homebrewed ModuleRCS torque calculations, so there may be a flaw inside that logic.

**Comment by thexa4** [comment]
It could potentially be counting torque twice when the RCS is very unbalanced due to the way the steeringmanager handles negative torque values.

**Comment by thexa4** [comment]
Just checked and the KSP estimation does not return negative values.
