### ISSUE TITLE
part:STAGE value too large by one for liquid fuel engines

### ISSUE THREAD

**Issue by quetschke** [KSP-KOS/KOS#2917]
I was looping over the parts of a vessel using "LIST PARTS IN plist." and I found that my mass per stage was different than Kerbal Engineer. See ship and KER picture below. I wrote a small kOS script [stbug.ks.txt](https://github.com/KSP-KOS/KOS/files/6288724/stbug.ks.txt) to list the stage, engine parts and mass (output below),

```
p:STAGE,p:TITLE,p:MASS
-1,Probodobodyne OKTO,0.105000004172325
-1,OX-STAT Photovoltaic Panels,0
-1,CX-4181 Scriptable Control System,0.11999998986721
-1,FL-T800 Fuel Tank,4.5
-1,AV-R8 Winglet,0.100000001490116
-1,AV-R8 Winglet,0.100000001490116
0,LV-T45 "Swivel" Liquid Fuel Engine,1.5
0,TT-38K Radial Decoupler,0.025000000372529
0,FL-T400 Fuel Tank,2.25
0,Aerodynamic Nose Cone,0.0299999974668026
0,TT-38K Radial Decoupler,0.025000000372529
0,FL-T400 Fuel Tank,2.25
0,Aerodynamic Nose Cone,0.0299999974668026
1,LV-T30 "Reliant" Liquid Fuel Engine,1.25
1,LV-T30 "Reliant" Liquid Fuel Engine,1.25
```

Looking at the parts it becomes clear that the "Swivel" should belong to stage "-1" and that the two "Reliant" should belong to stage 0. This would fix the mass calculation and bring it inline with KER.  I also run a test where I replaced the Reliant engines, plus tanks with "Hammer" SRBs. Those are added to the right stage number. It appears that the stage numbers of liquid fuel engines are listed as to big by 1.

![lf](https://user-images.githubusercontent.com/5354403/114246022-37110980-9957-11eb-9655-85e1fc4819a5.jpg)

P.S.: It is possible that all parts are wrong, and only liquid fuel engines have the right staging value returned. Looking at the picture and KER, there should only be stages 0 and 1 for this example.

**Comment by nuggreat** [comment]
kOS does no stage parsing the numbers you get for that are entirely based on the direct values from the KSP API if there is an issue with them then it is a bug in KSP not kOS.  Also KER uses a custom stage parser that does not completely match with the internal values KSP uses thus is not a good tool to use to assess accuracy of staging information.

Having said that the general rules KSP follows as far as I know are that a if a part is activated by a given stage number (see lower right staging list) then it gets given that number, if a part never gets actived directly by a staging event then assign that part the sate number of the decupler/seperator/dockingport that is closer to the root part and that is activated by staging list,  For all other parts that do not have decupler/seperator/dockingport between then and the root part assign then the same staging number as the root part, and lastly assign the root part the staging number of `-1`

**Comment by quetschke** [comment]
Hm, below is the output where I replaced the reliant and tank with Hammer SRBs. And I was wrong, Thant is also not correct, The small nose cones amd the decouplers should be in the same stage as the SRBs. Looks like the p:STAGE is not very useful.

```
p:STAGE,p:TITLE,p:MASS
-1,Probodobodyne OKTO,0.105000004172325
-1,OX-STAT Photovoltaic Panels,0
-1,CX-4181 Scriptable Control System,0.11999998986721
-1,FL-T800 Fuel Tank,4.5
-1,AV-R8 Winglet,0.100000001490116
-1,AV-R8 Winglet,0.100000001490116
0,LV-T45 "Swivel" Liquid Fuel Engine,1.5
0,TT-38K Radial Decoupler,0.025000000372529
0,TT-38K Radial Decoupler,0.025000000372529
1,RT-10 "Hammer" Solid Fuel Booster,3.5625
1,Aerodynamic Nose Cone,0.0299999974668026
1,RT-10 "Hammer" Solid Fuel Booster,3.5625
1,Aerodynamic Nose Cone,0.0299999974668026
```

**Comment by JonnyOThan** [comment]
You might be interested in the `decoupledin` suffix...

**Comment by nuggreat** [comment]
Right did some digging into the parts and I think I have the rules that KSP uses to set the stage number.

1. root part is always `-1`
2. if a part is in the staging list then it's stage number is equal to the stage number it has in the list
3. if a part is not in the staging list then it's stage number is equal to it's parent part

A simple enough rule set if not necessarily built in the direction one might want for easy use when working on stage parsing.

**Comment by quetschke** [comment]
Thanks for the hint with `DECOUPLEDIN`, I had missed it.  That is good enough to work out the masses and fuel/thrust for future stages. Well, unless asparagus staging or cross feeds are used, then things get complicated.

Not a bug. Closing the issue.
