### ISSUE TITLE
D term in PIDLoop should be calculated based on error

### ISSUE THREAD

**Issue by ayzenquwe** [KSP-KOS/KOS#2920]
Currently D term calculation is based on Input, but Error should be used instead.

**Comment by nuggreat** [comment]
There are advantages to the way kOS currently calculates the D term see issues #1693 and as noted in the [documentation](https://ksp-kos.github.io/KOS_DOC/structures/misc/pidloop.html#using-setpoint-is-better-than-using-zero).

If you want the classical PID behavior for the D term them just subtract out your setpoint as part of the `:UPDATE()` call as apposed to setting the suffix `:SETPOINT`.

**Comment by ayzenquwe** [comment]
I completely missed this in the documentation. :( I'm closing this issue, since PIDLoop works as intended.
