### ISSUE TITLE
IsWaitingForCommand() errors on scene loading (possible race condition)

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#2925]
I've had several reports of the same error, but haven't seen it myself, where upon loading the scene, this starts spamming the log:

```
[EXC 10:55:51.196] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
	System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <ad04dee02e7e4a85a1299c7ee81c79f6>:0)
	System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <ad04dee02e7e4a85a1299c7ee81c79f6>:0)
	kOS.Screen.Interpreter.IsWaitingForCommand () (at <3ccb18ebae2a49929054690a1a176760>:0)
	kOS.Screen.TermWindow.ProcessUnconsumedInput () (at <3ccb18ebae2a49929054690a1a176760>:0)
	kOS.Screen.TermWindow.Update () (at <3ccb18ebae2a49929054690a1a176760>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[EXC 10:55:51.349] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
	System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <ad04dee02e7e4a85a1299c7ee81c79f6>:0)
	System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <ad04dee02e7e4a85a1299c7ee81c79f6>:0)
	kOS.Screen.Interpreter.IsWaitingForCommand () (at <3ccb18ebae2a49929054690a1a176760>:0)
	kOS.Screen.TermWindow.ProcessUnconsumedInput () (at <3ccb18ebae2a49929054690a1a176760>:0)
	kOS.Screen.TermWindow.Update () (at <3ccb18ebae2a49929054690a1a176760>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[EXC 10:55:51.500] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
	System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <ad04dee02e7e4a85a1299c7ee81c79f6>:0)
	System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <ad04dee02e7e4a85a1299c7ee81c79f6>:0)
	kOS.Screen.Interpreter.IsWaitingForCommand () (at <3ccb18ebae2a49929054690a1a176760>:0)
	kOS.Screen.TermWindow.ProcessUnconsumedInput () (at <3ccb18ebae2a49929054690a1a176760>:0)
	kOS.Screen.TermWindow.Update () (at <3ccb18ebae2a49929054690a1a176760>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
```

It might be possible to trigger it using a boot file that tries to read terminal input keys right away.

Looking at the code, I believe the cause of this is a race condition between the work done by kOS during the Unity ``Update`` versus the work done by kOS during the Unity ``FixedUpdate``.  In order for the problem to happen, kOS has to run its ``Update`` before it runs its first ``FixedUpdate`` for the newly loaded scene.

The ``FixedUpdate`` runs the ``Cpu.Boot()`` method on the first ``FixedUpdate`` pass.   This initializes the Interpreter's ``context.Program`` with its starting dummy program of one ``OpcodeEOF``.

But the ``Update`` (not ``FixedUpdate``) runs ``ProcessUnconsumedInput()`` for the terminal, which in turn calls ``Interpreter.IsWaitingForCommand()``, which tries to access ``context.Program``'s first opcode, that hasn't been initialized yet if the ``FixedUpdate`` hasn't happened and thus the Boot() hasn't happened.

I think the fix should involve making sure that ``ProcessUnconsumedInput()`` doesn't do anything until after the boot has finished.

**Comment by mgalyean** [comment]
I was wondering if it might help this issue, and maybe some others, have an implied, C# level, equivalent to "wait until ship:loaded and ship:unpacked" upon scene load?  I really don't know, but I'm trying to launch a small fleet of tugs in a fairing and so about 10 cores.  Five minutes to get to the point of launching is a really long time on a craft that loads in under a minute without cores installed.  I'm almost ready to put the cores in KIS inventory and have an engineer install them after launch sometime.  The log is just full of the same message as above during this loading period.  Again, I'm just shotgunning here, but I can't see any reason to ever boot a core prior to the ship being loaded and unpacked and would find the situations where it would make sense very educational

**Comment by nuggreat** [comment]
Adding a C# level `WAIT UNTIL SHIP:UNPACKED` to all cores would cause issues with some existing scripts as the presumption of ability to execute when the craft gets loaded but before the craft is unpacked is a requisite for some of my scripts.  As an option that is off by default I could be more on board with it but forcing across the board for everything would cause me issues.

**Comment by mgalyean** [comment]
Fair enough.  I'm just brainstorming something that would keep the cores from trying to do stuff before KSP and the craft are ready.  All the errors above happen during startup and apparently prior to any processing of bootfiles so there is no way to prevent them from boot script.  I did put in a feature request for a new core PAW toggle accessible in the editor for the power state of the core on launch.  It would be nice to just have them dormant until I get to Duna right from the VAB.  But another thing is that maybe just having a C# version of "wait until ship:loaded", and not addres the packed/unpacked would help without impinging on your existing code. Is it safe to say that no one is doing anything in a script prior to craft load?  I can't imagine that being a popular thing to attempt.  I really don't know obviously other than the cores while booting are clearly racing way ahead of other aspects so am trying to think of a hold point they could wait on to perhaps reduce or eliminate the apparent race condition

**Comment by mgalyean** [comment]
I was focusing on ships on the launch pad for which both loaded and unpacked would mostly like be safe, but yes, I see the issue.  Thanks for looking into a solution.
