### ISSUE TITLE
Telnet hangs at "Trying [IP address]..."

### ISSUE THREAD

**Issue by KrazyKerbalnaut** [KSP-KOS/KOS#2937]
I'm not sure if this is what caused it, but Telnet was working last night before the 20H2 update. My machine finally received the update from windows (in the past, something was broken with their code for my configuration but I was finally notified it was ready and it installed).

Now I can't telnet into the console in kOS. It shows that its ready and listening for a client to connect, but when trying to telnet in on 3 different devices, it hangs indefinitely. I'm not sure if the library for the kOS side is no longer compatible with Windows' telnet service and has broken telnet, and is thus an issue with windows and kOS compatability, or if I'm doing something wrong now that I wasn't doing before. I've checked my settings and I'm not getting a connection refused, or even a connection timeout. The clients all just say that they're "Trying [ip address]...".

**Comment by KrazyKerbalnaut** [comment]
New info. When connecting to the telnet on the machine running KSP, it opens at the IP and specified port. This is something with Windows security and firewall settings. I'm not using a loopback so I know that the port is not being opened to the local firewall for some reason... Windows updates suck :(

**Comment by mgalyean** [comment]
This is almost definitely windows firewall related.  You probably want to allow on the telnet port for localhost or equivalent.  Telnet on kOS is very stable. I can't remember where it is on windows but you want to go into security and port management

**Comment by KrazyKerbalnaut** [comment]
Oh, yes, I had already done that. I reverted back and all is good.
