### ISSUE TITLE
http link in terminal should be https

### ISSUE THREAD

**Issue by nuggreat** [KSP-KOS/KOS#2966]
On boot the kOS terminal displays a message telling the user where to find the documentation
![image](https://user-images.githubusercontent.com/26613510/121823659-9216f380-cc5b-11eb-8f88-3daf802af0dc.png)
as this link is currently a http link and we have been moving the documentation links over to https this to should be updated.

We should also take a look through the kOS exception messages and see if any of them also have links that are http as apposed to https.

**Comment by kna27** [comment]
I'm working on changing all occurences right now, and I'm noticing that many links are also broken and don't lead anywhere. Might as well fix those too as well as I can.

**Comment by kna27** [comment]
Here is a list of all the broken links, in case anyone wants to help find out where they are supposed to point:

- https://ksp-kos.github.io/KOS_DOC/command/flowControl/index.html#RETURN
- https://ksp-kos.github.io/KOS_DOC/command/flowControl/index.html#PRESERVE
- https://ksp-kos.github.io/KOS_DOC/summary_topics/CPU_hardware/index.html#WAIT
- https://ksp-kos.github.io/KOS_DOC/summary_topics/CPU_hardware/index.html#TRIGGERS
- https://ksp-kos.github.io/KOS_DOC/language/variables/index.html#DECLARE_PARAMETER
- https://ksp-kos.github.io/KOS_DOC/command/flowControl/index.html#BREAK
- https://ksp-kos.github.io/KOS_DOC/summary_topics/coordframe/raw/
