### ISSUE TITLE
Another RP-1 issue: RP-1 suppresses ship:control:fore when manual RCS fore works.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#2970]
Arrrgh.  When you don't have sufficient avionics, RP-1 allows pilot-input manual RCS fore and aft axis to still work (so you can fire an ullage-needing engine on a spin-stabalized probe), but RP-1 is suppressing kOS's set ship:control:fore to xxx. - only allowing actual manual keyboard or joystick input to fire RCS fore and aft.  Mechjeb's annoying "RCS responds to throttle when main engines not active" is the supposed way around it but that's not right for using some other scripting system.

Thus I can't ullage my engine for ignition in my spin-stabalized first lunar orbit probe.

``ship:control:fore`` is a get-only field that can't be set, and there is no ``ship:control:foretrim``, and there is no ``ship:control:pilotfore`` to set.

**Comment by RCrockford** [comment]
I'm thinking we need a better approach to this whereby kOS reads the control locks and only excludes those that are locked.

**Comment by Dunbaratu** [comment]
Is kOS the one causing the lockout here though?

**Comment by RCrockford** [comment]
It is, yes. In the top of `kOSVesselModule.UpdateAutoilot`.
