### ISSUE TITLE
xor operator

### ISSUE THREAD

**Issue by FalcoGer** [KSP-KOS/KOS#2990]
I'd like a logical XOR operator to be included in the instruction set.

**Comment by marianoapp** [comment]
There's already an issue open #2988 to add bitwise operators.

**Comment by mgalyean** [comment]
<> works as XOR generally

**Comment by FalcoGer** [comment]
> There's already an issue open #2988 to add bitwise operators.

which is why i opened a new issue. because I want a logic operation, not a bitwise operation.

**Comment by marianoapp** [comment]
I guess we can leave this open until we decide what to do with #2988, my intention was to have a single operator for both logic and bitwise XOR and change it's behavior depending on the data type.
In any case, you can use `a xor b = (a or b) and not (a and b)` in the meantime.

**Comment by mgalyean** [comment]
In the interest of keeping with the kOS philosophy of keeping things from being confusing I'm thinking that logical and bitwise operators should be separate.  And really, the bitwise could just be built-in functions with parameters to keep them even more separate from logical.  Given the scarcity of symbols to use for operators it might make it easier to implement also.

And as previously mentioned, while a xor b = (a or b) and not (a and b) is true, a xor b = a <> b, so for xor, there is already an op

**Comment by nuggreat** [comment]
We have combined operators for other things such as vector, scalars, and rotations so having combined logical and bitwise operators wouldn't be that confusing.  As a logical `OR` and a bitwise `OR` are comparable to vector vs scalar operations in a lot of ways.

**Comment by mgalyean** [comment]
It is the lack of strong typing mixed with logical and boolean operators that makes me think it will end up being confusing.  If there were a strict boolean type I'd change my mind.  Or if the boolean operation would only parse if both args truly held actual TRUE/FALSE values I suppse

**Comment by nuggreat** [comment]
I see no issues with crashing on a mixed type call like what happens if you try to add a scalar to a vector as we already do have a boolean type so differentiating the based on type wouldn't be that different from what already is done.

**Comment by mgalyean** [comment]
Not crashing, user and debugging confusion.  As functions they would stand out more as advanced usage items.  Very few of the ppl who show up to learn kOS are going to be diving for bit operations right away.  It isn't a big deal to me, just throwing it out there.
