### ISSUE TITLE
Filenames cant be numbers?

### ISSUE THREAD

**Issue by TedThompson** [KSP-KOS/KOS#3017]
`Local CH is 12. `
`Local pNum is CH:tostring. `
`runpath("pgms/" + pNum).`

There is a folder named `pgms`
There is a program file within named `12.ks`

KOS keeps throwing an error saying it can't open the path. However if I change all the relavent 12s to NoNumbersAllowed it works. 

If I change them to NoNumbersAllowed12 it does NOT work. 

Injecting a line to print the type states pNum is type String.

**Comment by mgalyean** [comment]
Try **RUNPATH("pgms/" + pNum + ".ks").**  Runpath want the ".ks" I think.  The related RUN command implies it, but not runpath

**Comment by TedThompson** [comment]
I'll explicitly try that, but ive been trying all manner of combinations and so far if there are any numbers in the *variable* for the path it fails. 

If I enter the same string directly between "s it works fine.

**Comment by mgalyean** [comment]
Looks like a bug to me.  Not my call but your testing seems to have it surrounded

**Comment by Dunbaratu** [comment]
I literally cannot make this happen, doing exactly what you showed.

- filename is "pgms/12.ks".
- I make a file called 12.ks there that just contains "clearscreen.".
- I make this program: testexample.ks, like so:
```
Local CH is 12.
Local pNum is CH:tostring.
runpath("pgms/" + pNum).
```
it runs just fine.

I believe you, but I can't diagnose it because it does not happen when I'm trying to make it occur.  There has to be something different about how you're doing it from how I'm doing it.

**Comment by nuggreat** [comment]
What OS are you running and what version of KSP and kOS do you have because I was also unable to reproduce the issue in KSP 1.10.1/1.11.1, kOS 1.3.2 on windows 10.

**Comment by TedThompson** [comment]
All latest versions. I don't have the numbers in front of me right now, but Steam updates KSP. And I just got KOS a week or two ago. 

I will recheck myself and report back.

**Comment by TedThompson** [comment]
> There has to be something different about how you're doing it from how I'm doing it.

Now I wonder if there's an unprintable character. My use of set CH to 12 was to simplify my example, CH is actually taken from a terminal input routine. (in case you rememebr me, I'm not using the Apple II, I'm using the in game terminal, but since I had that problem and you can't reproduce it, I'm thinking the ^m is part of the string... I shall investigate.)

**Comment by mgalyean** [comment]
You can iterate through the string and use UNCHAR() on each character and see what code it returns.

**Comment by TedThompson** [comment]
KOS is 1.3.2.0, KSP is 1.12.2.3167

And I'm an idiot. Some of my testing was done in direct entry, while other's were in my script. I am unsure why direct entry would produce the same error, but it doesn't matter (an error on my part I'm sure).

Despite my attempts to be sure and not send up a flare over nothing, here I am. A check of the LENGTH of my returned input, which had be working fine for checking an array, showed that it wasn't 2 characters long, but 3. The return at the end was part of it, and when I tried to use THAT to directly call another script it rightly didn't match.

Just for the record, this is my input code, else where this is called with `set ch to cmdInput().` - adding "substring(0.2)" fixed the issue.

```
declare function cmdInput {
	set kb to "".
	until(false) {
		set inkey to terminal:input:getchar().
		set kb to kb + inkey.
		if inkey <> terminal:input:enter {
			if kb:length > 2 {
				set kb to kb[1] + kb[2].
			}
		} 
		else {
			print "    " AT (20,8).
			return kb:substring(0,2).
		}
		print kb AT (20,8).
		wait 0.
	}
}
```
