### ISSUE TITLE
Lexicon keys set as numbers can not be used as suffix.

### ISSUE THREAD

**Issue by TedThompson** [KSP-KOS/KOS#3019]
```
local pgmList is lexicon().

set pgmList["99"] to "CONFIRM BURN".
set pgmList["foo"] to "bar".

print pgmlist:foo.
print pgmlist:99.
```
results in:
```
[
  ["value"] = "99"] =
  ["value"] = "CONFIRM BURN"
[
  ["value"] = "foo"] =
  ["value"] = "bar"
An attempt was made to get a suffix called:

from an object of type:
    Lexicon
when that object does not have that
suffix usable in that way.
Possible causes are:
  - No Lexicon ever has a  suffix.
  - There is such a suffix, but it can't be used
      with a get operation.
  - There is such a suffix on some instances
      of Lexicon, but not this particular one.
__________________________________________
__________________________________________
At Archive:/lex, line 7
print pgmlist:99.
      ^
```
If I remove `print pgmlist:99.` I get:
```
run lex.
bar
Program ended.
```

**Comment by mgalyean** [comment]
You can't use the suffix syntax unless the key could be used as a valid identifier.  A bare number cannot be used as a valid identifier.  But you can use the "asdf[99]" access method of course
http://localhost/KOS_DOC-gh-pages/structures/collections/lexicon.html?highlight=lexicon#lexicons-can-use-suffix-syntax

**Comment by TedThompson** [comment]
"http://localhost" is no bueno.

**Comment by TedThompson** [comment]
Also, as I have them in quotes, they are (or should be) a string, no different that "foo", which worked.

**Comment by nuggreat** [comment]
A "valid identifier" in kOS means anything you can use as a var and as you can't `SET 99 to 101` using the key `"99"`won't work with the suffix syntax.  But it would quite happily work if you went with say `"p99"`

**Comment by TedThompson** [comment]
I see. I've dabbled in many languages, but my strong suit goes back to BASIC, so when I see "99" I think "that's a string". It makes me struggle with how (kOS at least, and maybe other modern languages) numbers alone can sometimes not be.

Apologies.

**Comment by nuggreat** [comment]
kOS also thinks that `"99"` is a string and it can be used as such in a lexicon context calling the value would indeed require `someLex["99"]`.  The difference is that just because you can use it as a lexicon's key doesn't mean you can use it as a suffix on a lexicon.

**Comment by mgalyean** [comment]
I think you got it now, but just to be complete, "http://localhost" works fine as a lex key, just not in suffix form for same reason in that it couldn't be a valid identifier, or variable name (or function name).  So `SET loc_host TO myLex["http://localhost"]` would work fine

**Comment by TedThompson** [comment]
Localhost was referring to the link provided in the message I was replying to. Which, of course, goes nowhere for me. 

Case insensitivity can be toggled on and off. 

I realize my stupid mistakes may give a different impression, but I do read the manual. A lot.

**Comment by nuggreat** [comment]
A number of us have downloaded the kOS documentation for offline use or to avoid eating into data caps in this case the online equivalent would be:  https://ksp-kos.github.io/KOS_DOC/structures/collections/lexicon.html?highlight=lexicon#lexicons-can-use-suffix-syntax

Should you also want an offline copy of the docs the repository where the generated html pages live can be found [here](https://github.com/KSP-KOS/KOS_DOC) you would also need to remember to update your copy when kOS updates.

Also you don't give off the impression you don't read the manual you instead give off the impression of some one happily charging off into edge cases that while they might be documented are only covered by short description.  Which in this case was not very clear and only provided one example of an invalid identifier.

**Comment by mgalyean** [comment]
Excellent, I hadn't realized the case-sensitivity issue had been addressed, so we go that going for us.  I agree with nuggreat, you hit a corner case with brief documentation.  No worries
