### ISSUE TITLE
Allow kOS to read Trajectories add-on data

### ISSUE THREAD

**Issue by najaB76** [KSP-KOS/KOS#3033]
Could you make pre-calculated data in Trajectories available to kOS?  For example being able to get the impact velocity vector would help a lot with landing.  I've tried calculating it myself but the values I get are always out a bit, I suspect because I've been assuming constant gravitational acceleration rather than integrating it as the vessel gets closer to the surface.

**Comment by nuggreat** [comment]
If you are in a vacuum then just the built in [VELOCITYAT()](https://ksp-kos.github.io/KOS_DOC/commands/prediction.html#function:VELOCITYAT) function to get the velocity at time of impact.
If you are in an atmosphere then the impact velocity is of minimal use as drag is way to variable for the velocity vector to supply meaningful data.

**Comment by najaB76** [comment]
Ah, okay. I never thought to compare it to the VELOCITYAT() function, just assumed that Trajectories was doing something different.
