### ISSUE TITLE
Add Ability to Determine if File is Open

### ISSUE THREAD

**Issue by bigmcr** [KSP-KOS/KOS#3034]
When debugging my launch scripts, I often write a bunch of data to a CSV file on the archive and then open the file later in Excel. If I then modify my script, revert the launch and try again, I get an error saying "Sharing violation on path <filepath here>" Is it possible to determine if a named file is open for writing?

**Comment by nuggreat** [comment]
Sadly no we have not managed to figure out how to let other programs access files at the same time as kOS which includes not having been able to work out a method to detect when something is blocked.
Also it is less a file being open and more some other program has reserved exclusive access to that file for a period of time.

If you want to try to avoid having collisions like this you could change

**Comment by bigmcr** [comment]
I suppose I could have a logging core on the rocket that solely logs information to the archive. If it dies, the "main" core could monitor it and restart it as needed. I would prefer a function that basically returns "yes, the specified file is writeable", but it looks like that isn't really possible. Ah well. Thanks.

**Comment by mgalyean** [comment]
There may be a way to open the file in read only mode in Excel, check the command line options maybe.  It would be hard for kOS to get a sharing violation on a file with no write lock held
