### ISSUE TITLE
FILEPATH in CraftTemplate

### ISSUE THREAD

**Issue by Assan75** [KSP-KOS/KOS#3038]
The KoS documentation says that the CraftTemplate structure has the FILEPATH suffix, however, if I apply the suffix :suffixnames to a variable of the CraftTemplate type, then FILEPATH is missing from the list of valid suffixes. What am I doing wrong, or is it a bug?

**Comment by nuggreat** [comment]
The suffix is in the documentation but not the code so you haven't done anything wrong and this isn't a bug just a documentation mistake.
