### ISSUE TITLE
Maneuver node time suffix not updated when time changed manually

### ISSUE THREAD

**Issue by johnwhall** [KSP-KOS/KOS#3040]
If you change a node's time outside of kOS, that change is not visible in your script.

```
print (nextNode:time - time:seconds) + " " + nextNode:eta.
3636.70990401506 3636.70990401506
// manually drag node along orbit, then
print (nextNode:time - time:seconds) + " " + nextNode:eta.
3626.90991336107 6676.74107664824
```

If you read another suffix first, the time suffix starts returning the correct value.

**Comment by plonk75** [comment]
There is a workaround that might help until the fixed code makes its way into a release. It seems that converting `allnodes` to a string performs the required update. So you might want to add something like

`local workaroundIssue3040 is allnodes:toString(). // Somehow refreshes maneuver nodes. See https://github.com/KSP-KOS/KOS/issues/3040`

before accessing `nextnode:time`.
