### ISSUE TITLE
Questions about basic-tutorial if statements

### ISSUE THREAD

**Issue by Makarov-Ivan** [KSP-KOS/KOS#3053]
# Questions about basic-tutorial if statements
## Context
[There are examples with if statements](https://github.com/KSP-KOS/KOS/blob/develop/doc/source/tutorials/basictutorial.rst#example-2-only-using-if)

And *complex way* of solving two **if** statements seems to be a bit useless. 
Here it is:
```kos
set Done to false.

if Done = false {
  if distance <= 1 {
    print "Distance is within a meter.".
    set NotDone to false.
  }
}

if Done = false {
  if distance <= 100 {
    print "Distance is within 100 meters.".
    set NotDone to false.
  }
}

if Done = false {
  if distance > 1000 {
    print "Distance is farther than 1 kilometer.".
    set NotDone to false.
  }
}
```
## Questions
1. So, what for we need variable called **NotDone**?
2. In first run, when **distance** is 0, both two **if**s are satisfied , so both messages should be shown in output, so how can it be resolved?

**Comment by nuggreat** [comment]
There is a typo in the code it should read
```
set NotDone to true.

if NotDone {
  if distance <= 1 {
    print "Distance is within a meter.".
    set NotDone to false.
  }
}

if NotDone {
  if distance <= 100 {
    print "Distance is within 100 meters.".
    set NotDone to false.
  }
}

if NotDone {
  if distance > 1000 {
    print "Distance is farther than 1 kilometer.".
    set NotDone to false.
  }
}```

**Comment by Makarov-Ivan** [comment]
Yeah, think so too.
I'm on creating PR for this changes
