### ISSUE TITLE
Update docs "Creating GUIs", examples use gui as a variable

### ISSUE THREAD

**Issue by sneumyer** [KSP-KOS/KOS#3079]
Code examples for creating GUIs use gui as a variable, which conflicts with recent change "Prevent clobbering built-ins. #3016"
One example where documentation provides example code that clobbers GUI is found at  
https://ksp-kos.github.io/KOS/structures/gui.html#function:GUI

![Screenshot 2023-02-18 144041](https://user-images.githubusercontent.com/8310098/219885005-1c076d0a-409b-47f8-b356-d5fd195bb409.jpg)

**Comment by Dunbaratu** [comment]
Good catch.  I will probably update this one right away without waiting for a full release (since gh-pages is sort of a separate branch I can do that).
