### ISSUE TITLE
(RP-1 only) probe core is 6x heavier in flight scene than in VAB (disk space mass calculated wrong).

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#3081]
This bug only happens in RP-1.  But the code that causes the problem is definitely in kOS (It's in a section that is only triggered when RP-1 is installed.)  It's a pretty bad bug because it unfairly makes small probes have a lot more mass than they are supposed to have, thus greatly reducing their deltaV making them almost unusable when you have this bug.

To reproduce the problem:

1- Make sure you have the Avionics tech tree nodes researched to the point where you start having probe cores that start with 5000 bytes storage.  (The first few nodes only give you nodes that start with 500 bytes storage, and at that point you won't experience the bug yet.)

2 - In the VAB create an Avionics probe core at the tech level where it starts with 5000 bytes storage (or more).  "Deep Space, Interplanetary science" is the first node where I saw it happen, but it will also happen at higher tech nodes (but not lower ones).

3 - Use the slider that adds extra disk space to the Avionics part.  Move it from the default starting value of 5000 bytes up to the max value of 20000 bytes.

4 - Note how much the VAB believes the mass of this one-part vessel is.

5 - Put this one-part vessel on the launchpad via KCT's "simulate" button.

6 - Look at the mass again, now on the launchpad.  (Use either kOS's `print mass.` or use Mechjeb's Vessel Info panel.)  It's *waaaay* heavier than it was in the VAB.  By a LOT.  1.5 tonnes more.  This difference is enough to ruin attempts to make a small efficient probe.

What is happening:

At low tech levels, extra disk space is very punitive as it should be, costing 100 Kg per KB of space.

But at the 5000 default storage tech level, it's meant to be much less punitive, costing only 2.5 Kg per KB of space.

In the VAB kOS uses the higher tech 2.5 Kg per KB ratio like it should.  But in flight it still uses the 100 Kg per KB value of the default starting tech level, utterly ignoring the improvements that tech level is meant to bring.

**Comment by Dunbaratu** [comment]
I believe the bug is caused by this:

There is a method in ``KOSProcessor.cs`` called ``UpdateRP1TechLevel()``.  It seems to apply the tech level upgrades to the part's stats.

In all the scenes, that method gets called in ``OnStart()``, here:
https://github.com/KSP-KOS/KOS/blob/43f6f629e0178d85cca9bb4b207061ee8d4061a8/src/kOS/Module/kOSProcessor.cs#L402

But only in the EDITOR scene does that method also get called in ``Update()``, here: 
https://github.com/KSP-KOS/KOS/blob/43f6f629e0178d85cca9bb4b207061ee8d4061a8/src/kOS/Module/kOSProcessor.cs#L807

At first this might make sense, as during the EDITOR the part can be changed but in flight it is fixed at however it got manufactured.  So it might have made sense to only continually recalc the values every Update() if you're in the editor where they could change, and in other scenes just update it once up front in OnStart() and that's it.

But clearly something didn't work about that assumption.  Perhaps it's a race condition, where not all the stuff about the part's tech upgrades have been properly applied yet during OnStart() so kOS isn't seeing the proper tech level of the part until a few moments later during an Update().  If that's the problem, it may be possible to fix the race condition by calling it in all scene's Update()'s, but with some logic that stops calling it in Update() in non-editor Scenes when the values have settled in to their final value (don't know how you'd detect that..)

**Comment by Dunbaratu** [comment]
I looked at this for a couple of hours tonight and I think it might be a race condition as follows:

In RP-0's code on Github I see that the ``ModuleProceduralAvionics`` has an ``OnStart()`` that populates some of its fields based on the selected tech level.

In kOS's code, ``KOSProcessor`` has an ``OnStart()`` that looks for the ``ModuleProceduralAvionics`` that's inside the same part, and if it finds one it overrides the diskSpaceMassFactor with what it finds there.

I suspect this is only correct when kOS's OnStart() happens to occur *after* RP-0's procedural avionics' OnStart() has configured *it* properly.  If kOS's OnStart() happens to occur *first*, then it is pulling the values for diskSpaceMassFactor *before* RP-0 has properly populated it.

**Comment by darthgently** [comment]
Does RP-1 leave enough of a fingerprint to tell it has been there already?
