### ISSUE TITLE
how does one get meaningful directions?

### ISSUE THREAD

**Issue by Schnobs** [KSP-KOS/KOS#315]
I've got a plane that tends to veer slightly off-course. I need to check up on where it's actually going and apply corrections accordingly: if it's off by one degree, roll slightly; if it's off by three degrees, roll more, and so on.

So I started with putting a simple vessel into orbit, running the following code:
---snip---
set wantdir to up + r(0,90,90).
lock deltaX to (wantdir:pitch - facing:pitch).
lock deltaY to (wantdir:yaw - facing:yaw).

until 0>1 {
print round(deltaX,1) + " " + round(deltaY,1).
wait 0.1.}
---snap---

And started to turn it around so I see how kOS' idea of deltaX/Y changes as I point the vessel in different directions. I expect you won't be surprised if I tell you that the outcome was nothing I could use:

If I'm off to the left, I get readings of -1, -3, -5 -- that's great.
If I'm off to the right, I get -359, -357, -355 and so on. That's not cool.

Now, that vessel should never be off by more than a few degrees, so I can fake it by adding 360 to any number that's smaller than (say) -50 or so. But that's not a "proper" solution; it also makes me lose the utility of locking deltaX to something.

Is it possible that kOS could give me a useful answer straight away? If so, how? If not, could you please make it possible?

**Comment by ctbram** [comment]
okay I just want to f----ing!  Roll like roll in a real f---ink airplane 90 degrees!!!!  How the bloody hell do I accomplish this!!!  As you can probably tell I am ready to take a mother-f--ing brick and beat sh#t out of my computer.  $ god damn hoiurs try to just institute a god damn roll program is f---ing rediculous!!!!!

**Comment by gisikw** [comment]
Hi ctbram, I've removed your angry and violent comment on my video about this topic as well. A few points:

1. The process of learning and playing with kOS does have a bit of a learning curve. I can assure you that most of us spend far longer than a few hours to get up-to-speed, and if this is causing you this much anxiety, it might not be something worth investing your time in.

2. It's generally frowned upon to resurrect very old GitHub Issues - comments like these notify all the original participants of the conversation (including the original asker) - and falsely imply that the issue wasn't addressed.

3. You can find all of the information regarding raw steering control on [the documentation page](https://ksp-kos.github.io/KOS/commands/flight/raw.html).

**Comment by erendrake** [comment]
@ctbram i am not sure what you were hoping to achieve with your comment but for now i am simply going to delete it. I agree with everything @gisikw is saying. you get far more bees with honey than vinegar.
