### ISSUE TITLE
To make KOS scripts type-aware, wrap all types in an Encapsulated

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#334]
It occurs to me that in order for scripts to be able to do stuff like this:
```
print obj:type.
```
and get results like this:
```
String
```
or this:
```
Number
```
as well as this:
```
Vessel
```
We need to derive all KOS objects from a common base object that implements the suffix :TYPE (and maybe also therefore can implement other similar object-generic stuff like "IsAKindOf" for derived types).

While simple in concept, it does mean a LOT of search/replace through the code to find cases where raw C# objects exist as values a user sees (i.e. can be put on the stack) and are being used for things like math, and wrapping them up.

IMO: If this is done it also lets us say, for example, that the runtime stack only gets to store things derived from this KOSBase type, and it lets us make a KOSString that does all the string stuff we want to do, and it lets us make identifiers on the stack look different from user strings on the stack, solving a few other issues.

It's a sort of big refactor that I think is worth it some day, so I made this issue.

**Comment by hvacengi** [comment]
Implemented via #1249 and #1414
