### ISSUE TITLE
BODY needs a sphere of influence radius suffix

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#342]
Something like BODY:SOIRADIUS.

Returns: the radius of the body's sphere of influence.  If your orbit goes higher than that number you will escape the body EVEN IF your math still shows an elliptical rather than hyperbolic orbit.  This is a place where you have to break from roleplaying the reality a bit and look at the simulation artifact to get the autopilot to do the correct thing because doing what should work in the real world will NOT work in the simulated world of KSP.

Alternatively: BODY:SOIALTITUDE.  (The difference being whether it's measured from the body center or the body surface.  Periapsis and apoapsis numbers are reported in terms of altitude not radius so this might be the better way to show it to the user.)

Either number will be sufficient, because you can add or subtract BODY:RADIUS to get the other one.  It's just a matter of which we want to show.

**Comment by ndevenish** [comment]
This would be very useful. I'm writing a periapsis kicker and need to enter this information manually at the moment.

**Comment by abenkovskii** [comment]
Looks easy enough. Can I do it?

**Comment by erendrake** [comment]
@abenkovskii go for it!
