### ISSUE TITLE
allow List building with literal "{" ... "}" syntax.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#346]
Instead of making users type this:
```
set mylist to List().
mylist:add( list() ).
mylist[0].add( "A" ). mylist[0].add( "B" ). mylist[0].add( "C" ).
mylist:add( list() ).
mylist[1].add( "0" ). mylist[1].add( "1" ). mylist[1].add( "2" ).
```
It would be slick if they could type this:
```
set mylist to {  { "A", "B", "C" } , { "0", "1", "2" } }.
```
This would involve editing the kRISC.tpg file so that it allows an expression to contain:
CURLYBRACE arglist? CURLYBRACE

And then altering the compiler such that when it sees one of these it makes a new ListValue and adds the expressions of the arglist to it.

**An alternate solution**

Make a constructor for LIST that takes any arbitrary multiple arguments, like so:
```
set mylist to LIST( LIST("A","B","C), LIST("0","1","2") ).
```
The problem this gives us is that it makes it so we'd have to implement functions that take varying arguments.  We're almost entirely there already because delegates use the "argstart" stack marker to show where the arguments begin, so we could change the LIST constructor into a delegate rather than a built-in hardcoded value, and then use the argstart idea so it can read multiple args off the stack.

**Comment by Dunbaratu** [comment]
I've decided to do this a different way, using what's in PR #848

**Comment by abenkovskii** [comment]
@Dunbaratu PR is merged. New list(args) is working. Is there any reason to keep this issue open?

**Comment by abenkovskii** [comment]
close?
