### ISSUE TITLE
Inter-CPU communication can be made possible now

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#353]
The big hurdle to inter-CPU communication had always been the inability to NAME which CPU you meant.

Now you can do it with kOSNameTags.  We could send messages between CPU's now because you can name the SCS parts in the editor and then say "send this message to 'MyCPU1'.".

**Comment by Tabris83** [comment]
this would also enable detecting decoupling. (ie. when a probe becomes a separate vessel then run program.)
