### ISSUE TITLE
Allow users to highlight parts from scripts

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#367]
I've just worked out how the part highlighting system in KSP works, and it's really easy.

So I think users would like to have this, as it can make understanding the parts list easier:

```
PRINT "Part number " + i + " will light up for 3 seconds now:".
SET SHIP:PARTS[i]:HIGHLIGHT TO true.
wait 3.
SET SHIP:PARTS[i]:HIGHLIGHT TO false.
```

### Implementation:

If all you want to do is highlight a part you already have a reference to, the API is basically just this:
```
// Assume we have this somewhere accessible:
// Color saveOldColor = for storing what KSP had previously set it to.

public void StartHighlight(Part p, Color c)
{
    saveOldColor = p.highlightColor;
    p.SetHighlightColor(c);
    p.SetHighlight(true);
}
public void StopHighlight(Part p, Color c)
{
    p.SetHighlightColor(saveOldColor);
    p.SetHighlight(false);
}
```
(Not shown: dealing with the case where multiple parts get highlighted at once, for which this example doesn't quite work because it only stores the most recently highlighted part's old color, rather than remembering a separate instance of old color per highlighted part just in case they differ.  That's easy enough to handle, but it would have made the example too verbose for a quick example.).

**Comment by ZiwKerman** [comment]
@erendrake  Isn't this closed?
