### ISSUE TITLE
WAIT FOR PHYSICS

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#374]
Institute a new magic command: WAIT FOR PHYSICS, or just WAIT PHYSICS, or just PHYSICSWAIT.

(It's important that it NOT follow the syntax pattern WAIT UNTIL PHYSICS, for implementation reasons).

The effect of this command would be to pause execution until we have left the current physics frame and started a new physics frame.

Note, that's **physics** frame and NOT **update** frame.  That's important.  i.e. it's waiting for a new fixedUpdate(), not a new Update().

The reason for not making PHYSICS a special bound variable and just using the WAIT UNTIL syntax on it is that it has to check the previous versus the current value of the timestamp and that's just not doable using the existing system.  The "what was the value originally" has to be secretly stored behind the scenes when the wait trigger is first activated, and while that's easy, it's slightly different logic from how a WAIT UNTIL normally works.

The same magic word "PHYSICS" could be used as a when trigger condition as well:

WHEN PHYSICS THEN { …. }.

To make the when clause run only during those Update()'s that have occurred immediately after a fixedUpdate(), like so:

example:

Update() happened <-- WHEN PHYSICS does not trigger
fixedUpdate() happened
Update() happened <-- triggers WHEN PHYSICS
Update() happened <-- WHEN PHYSICS does not trigger
fixedUpdate() happened
Update() happened <-- triggers WHEN PHYSICS
Update() happened <-- WHEN PHYSICS does not trigger
Update() happened <-- WHEN PHYSICS does not trigger
Update() happened <-- WHEN PHYSICS does not trigger
fixedUpdate() happened // lag in animation - no updates happen for a bit
fixedUpdate() happened
fixedUpdate() happened
Update() happened <-- triggers WHEN PHYSICS
Update() happened <-- WHEN PHYSICS does not trigger

This is to solve this problem elegantly:

http://forum.kerbalspaceprogram.com/threads/68089-0-25-kOS-Scriptable-Autopilot-System-v0-14-2-2014-10-08?p=1535426&viewfull=1#post1535426

**Comment by ZiwKerman** [comment]
@erendrake Has this become redundant after moving execution to Fixed Update?

**Comment by erendrake** [comment]
Not really but i am starting to wonder if we still need it.

**Comment by Dunbaratu** [comment]
It is unneeded now.  WAIT FOR PHYSICS was meant to mean "unlike the normal Wait, which only waits for Update(), I'd like to wait until some actual in-game movement has happened".

FixedUpdate does indeed make that moot.  Now a "wait 0.0001" will do that.
