### ISSUE TITLE
Only allow partmodules to be altered for CURRENT ship

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#391]
It is currently possible to use the new partmodule system to fiddle with the controls of parts your CPU isn't actually connected to because they're on a different ship.

For example:
```
// open the shroud on a docking port of the target vessel:
target:partsdubbed("that dockingport")[0]:doevent("open").
```

That should only be done by the SCS that is ON that target ship.  A check should be put in place that for a DOEVENT, GETFIELD, SETFIED, or DOACTION to be legal, the part must be a member of the same vessel as the vessel running the code (the shared.vessel).

**Comment by abenkovskii** [comment]
1. Than part tags and name of another vessel should probably not be settable too.
2. We will need another way of communication between vessels that are not docked.

**Comment by Dunbaratu** [comment]
There's basically a lot of these we should probably look over.  We might need to implement a sort of "vessel of action is myself" check to be sprinkled all throughout.  There's a lot of things that a kOS processor can do to OTHER vessels right now that it really shouldn't.

Once upon a time I was thinking of making a "robot wars" sort of contest for kOS until I realized one kOS program could win by just hijacking the other robot's controls.  This would need to be fixed first before such a thing would be fair.
