### ISSUE TITLE
doing "control from here" spins LOCK STEERING out of control

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#397]
LOCK STEERING's algorithm doesn't comprehend the concept of a "control from here" that is offcenter of the main axis of the vessel - like when you control from a docking port 3/4 of the way up the side.
It spins about wildly because it can't understand how to align itself with the weird contextual reference frame.

**Comment by parastie** [comment]
This appears to be the same issue I've gotten. I have not actually docket at all. Just when I set "control from here" on the docking port that's off-center it just spins around. Is there a way to officially make a bug report? I can send my craft data.

**Comment by Dunbaratu** [comment]
This issue *IS* the official bug report, but it was missing exact steps to recreate it.  if you can just paste your information to this page that would be great.  (i.e. get your saved game into a state just before making the bug appear, save the game, copy the persistence.sfs file from your saved folder to some pastebin-like site, and then post a link to that here, and a description of the steps to take starting from that saved game to get to the point where the problem happens.

**Comment by parastie** [comment]
Okay!
Here's the pastebin just prior: http://pastebin.com/bgsVXFRb

1.Right click on target (ie, target ship docking port in my case). 
2.Set docking port as target.
3.Right click on CPU ship's in-line docking port and choose Control From Here
4. In KOS Terminal type, " lock steering to target:position.

CPU ship will continue to roll while trying to lock steering.

**Comment by Dunbaratu** [comment]
There's more than one vessel in your saved file.  You should probably tell us which vessel we should be clicking on from the tracking center after loading the game - which vessel is the one we are supposed to be flying.

**Comment by Dunbaratu** [comment]
To be honest I already believe the problem exists because I've seen it before.  I'm just hoping that getting an exact re-creatable set of steep to trigger it will help it get fixed when someone (erendrake maybe?) takes a look at it.

**Comment by parastie** [comment]
Oh right, sorry.

KOS Test Probe2 is the ship you should be flying. KOS Test Probe1 is the target ship. They should be flying next to each other.

**Comment by Wercho** [comment]
I can replicate this anytime I "control from" a part that is oriented differently from the root part, even if I'm controlling from the original command part. No docking necessary. My game is modded like crazy so I don't want to give you a save you can't open, but it is easy to reproduce. Using the "control from here" button isn't even necessary to reproduce this.

1. Make a craft with a command part not oriented in the direction of the root part. Eg. Root part is fuel tank. Mk1 command pod upside down on fuel tank.
2. Lock steering to prograde (or whatever).
3. Watch it spin.

**Comment by Dunbaratu** [comment]
Wercho, thank you for the report.  It's useful to know that it's ALSO triggered by command part being a different orientation from the root part.  That *really* helps a lot.  It immediately suggests where the problem is.  The code gets the ship's current rotation from ```vessel.ReferenceTransform``` in VesselUitls.GetFacing().  The poor documentation makes it hard to know what that really means, but from your description it sounds like it means the root part's transform?

Although, as a point of counter-evidence to that suspicion, I've found that when making a rover, If I use a command core oriented vertically at the sky, as in a stack arrangement, it can't get headings correctly for driving, but when I then click on the second command-core that's mounted sideways from the stack, facing the front of the wheeled vehicle, and do a "control from here", then it DOES change the direction returned by GetFacing and starts working.... so GetFacing *IS* paying attention to the orientation of the commanding part and *DOES* change when you "control from here".... so .... I don't understand.

**Comment by Wercho** [comment]
Further testing:

The ship:facing direction is correctly determined by kOS, based on the "control from" part. I tested this by drawing ship:facing:forevector. The vector drawn changes appropriately with different command parts. LOCK steering still didn't work though when the command part was different from root part. So, kOS can clearly get the proper orientation in any situation, but for some reason "lock steering" doesn't always work. I realize "ship:facing" within kOS is different than the KSP (or Unity?) function.

Also, lock steering seems to get things partially right. The closer the ship is oriented to the desired facing when lock steering is used, the less error there is. If you manually point in the right direction then lock steering, it will wobble a little, gradually increasing to wild swinging about. That makes me think different parts of lock steering code are looking at different facings. Its as if the different terms of the PID controller are seeing different things.

**Comment by dcrockwell** [comment]
I am also experiencing this issue. It seems as though there is no error correction in the PID controller. It corrects, but doesn't lessen it's corrections as it goes on. I've tried many combinations of various torques and that doesn't seem to be the issue.

**Comment by dcrockwell** [comment]
Here is a video clip that shows what I'm experiencing. http://www.twitch.tv/automateallthethings/c/6311593

Perhaps this is related to another bug, but @Wercho 's comment seemed right on with what I'm seeing:

**Comment by erendrake** [comment]
Locck steering does not use pid controllers. It uses a pretty crappy algorithm that we are in the process of replacing. You can use the raw controls. As they are working fine.

**Comment by dcrockwell** [comment]
@erendrake Thanks very much for the reply. Is there a guide of some sort to the source code? I would like to contribute but am not sure where to start in respect to the repo's directory structure.

**Comment by hvacengi** [comment]
Closed via #1118

**Comment by 8110740497** [comment]
> LOCK STEERING's algorithm doesn't comprehend the concept of a "control from here" that is offcenter of the main axis of the vessel - like when you control from a docking port 3/4 of the way up the side. It spins about wildly because it can't understand how to align itself with the weird contextual reference frame.

Pantalla de Bloqueo
