### ISSUE TITLE
CPU.OnLoad code to reload complex structure variables is utterly broken.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#430]
CPU.OnLoad() attempts to do the following:

For each variable in the persistence save node, build the following kOS script code in memory:
SET *thing* TO *value*.

Where *value* is whatever is in the persistence file.

So if your persistence file has this in its variables section:
```
                variables
                {
                        foo = 1
                        bar = hello
                        baz = LIST&#32;OF&#32;2&#32;ITEMS:
                }
```
It attempts to create and run this script:
```
SET foo to 1.
SET bar to "hello".
SET baz to LIST OF 2 ITEMS:
```
Which of course fails utterly.  

The Problem is that what is being saved in the variable context doesn't allow for re-creation of the value again properly if it's anything other than a dumb simple scalar.

This is throwing exceptions during OnLoad, interrupting it's work.

We have to either:
(1) Not bother trying to reload variable context.
or
(2) If we do it, do it right, with a fully correct streamed object dump and reload that rebuilds references and everything.

A half-way between solution doesn't work at all and throws exceptions.

**Comment by erendrake** [comment]
im calling this an enhancement because it has never worked and no one is depending on it right now

**Comment by hvacengi** [comment]
We didn't really fix this, but I'm going to close it as variable loading has been abandoned for the time being.  I'm going to close this issue refering to PR #1111.  For reference, a related issue is #245
