### ISSUE TITLE
LOCK THROTTLE is disabled at phys warp 2x, 3x, or 4x.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#433]
In previous versions of kOS, you could up your physics warp to 2x, 3x, or 4x and kOS could still fly the ship (although with a bit less precision because as far as the physics simulation of the universe can tell, the kOS CPU is slower in these modes - i.e. the CPU still executes just as fast, but the universe moves faster than normal, so from the universe's point of view, the computer is running fewer instructions per second).

But, despite the "slower" computer, it still could fly the ship and control it.

But now I notice that whenever I phys warp to 2x, 3x, or 4x speeds, kOS loses the capacity to use the throttle.  If I hit ALT-> to set phys warp to 2x, and then in the kOS terminal do LOCK THROTTLE TO 1.0. then nothing happens until I hit ALT-< to set phys warp back to 1x, and then all of a sudden the ship starts thrusting.

It makes perfect sense that kOS can't control the ship while the ship is on rails under normal (not physics) time warps like 5x, 10x, etc.  But under physics warp, it's not on rails and the controls should work.

**Comment by erendrake** [comment]
I cannot reproduce this, i used the following script 


    clearscreen.

    PRINT "START".
    LOCK THROTTLE TO 1.
    SET WARPMODE TO "PHYSICS".
    SET WARP TO 2.
    PRINT WARPMODE.
    WAIT 2.
    SET WARP TO 2.
    PRINT WARPMODE.
    WAIT 2.
    LOCK THROTTLE TO 0.
    SET WARP TO 0.


It behaved as you would expect. it also worked with keyboard shortcuts.
