### ISSUE TITLE
LOG <expr> TO <file> is really slow

### ISSUE THREAD

**Issue by goblin** [KSP-KOS/KOS#458]
When writing a PID or other controller it's useful to gather debug information - like ship's height, velocity, etc. Having 1 set of such values per physics tick is really useful.

So I logged them with LOG.

Result: at IPU = 2000 my script with logging makes the game stutter awfully. At default IPU = 150, it can only process 3 or 4 physics ticks per second. And when commenting out the LOG statements: script runs very well on IPU = 2000 and processes 20-30 physics frames per second with no fuss.

So I tried to look into the root cause for this.

Looks like kOS is keeping the whole contents of the log file in a string, then copying that string over every time a new line gets added, and then reopening the logfile from scratch and REWRITING all of its contents from that string every single time a log statement is issued... no wonder it's inefficient :-)

Appending to the file would really be a lot nicer for everyone.

Perhaps that's also the reason why `tail`ing the logfile in another process while the kOS script is running kills the script...

**Comment by Dunbaratu** [comment]
With the PR above, you can perform this test:
```
switch to 0.
until false {
  wait 1.
  log "time is now "+time:seconds+" seconds" to logfile.
}.
```
and then do a ```tail -f logfile.ks``` at the shell prompt to watch the log progress.

**Comment by goblin** [comment]
thank you! :-)
