### ISSUE TITLE
object equality fails on wrapper objects.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#459]
```
set aaa to body("Duna").
set bbb to body("Duna").
if bob <> aaa { print "they are unequal". } else { print "they are equal". }.
```
These tests seem broken.  I think the problem is that when we construct a wrapper around a KSP object, we're not implementing an equals checker method, so two wrappers around the same native object still report as unequal.  We should *mandate* that all kOS objects implement an equals method, and then go back and populate them properly:

i.e. two PartValue's wrapped around the same inner Part object should be reported as equal.  Two VesselTarget's wrapped around the same inner vessel object should be reported as equal, etc.

**Comment by Dunbaratu** [comment]
Well the way I figure it is if we just say that Structure implements IEquatable, then that would force us to find all the structures that exist and we'd have to THINK about each one and implement what equality should mean for it.  The point is that doing that prevents us from forgetting one.  In the cases where it IS actually appropriate for one to behave exactly as it would have had we given it no Equals() method, then we can easily implement that with a dumb one-line Equals() method for it that just does the reference comparison.

**Comment by erendrake** [comment]
This is fixed for now. We will revisit this topic later when we tackle reference equality
