### ISSUE TITLE
RemoteTech Integration Documentation 

### ISSUE THREAD

**Issue by erendrake** [KSP-KOS/KOS#486]
Now that we have an awesome new documentation page and we are integrated with two other mods. I think we should have some documentation for that integration. 

This should cover:

* a clear statement about why we integrated
* the current features with some screenshots/video
* compatibility info
* future plans for the integration

**Comment by Gaiiden** [comment]
yes please. I'm wondering if we can get signal delay

**Comment by ZiwKerman** [comment]
It is solved now, I've put up some basic documentation in Addons/addons.rst and below.
