### ISSUE TITLE
Ship won't turn or overcompensates whilst steering. (Latest kOS 0.90)

### ISSUE THREAD

**Issue by Brattan** [KSP-KOS/KOS#490]
No matter what craft, no matter what script my rockets just wobble around when asked to move by kOS, and then when I manually move them they seem to try and rotate back to dead upright, well I say try, they actually start to act like a giant spinning top. I've removed all mods but kOS but still no change.

The most recent script I have been testing with is here: http://www.reddit.com/r/Kos/comments/1qbkgt/tutorial_introduction_to_orbit_steering_variables/

**Comment by Brattan** [comment]
I've tested it a bit more today and it seems (looking at the pitch and roll readings) that kOS is using full pitch and yaw constantly, and holding it for too long, then over compensating too much the other direction. This is whilst using simple_autolaunch.

**Comment by erendrake** [comment]
@Brattan im sorry we didnt get back to you on this. Would you mind trying again with 0.16.0 that we just released? I have a feeling it might have some fixes for your trouble.

**Comment by Brattan** [comment]
Okay, thanks for the reply I'll try it out this weekend.

**Comment by Brattan** [comment]
Well simple_autolaunch now works, but the command 'SAS off' is not working for me and comes up with the error: object reference not set to an instance of a object..."

**Comment by Brattan** [comment]
thanks for getting back to me as well!

**Comment by hvacengi** [comment]
Closed via #1118
