### ISSUE TITLE
addons front page needs links to subsections (doc)

### ISSUE THREAD

**Issue by theodoregoetz** [KSP-KOS/KOS#495]
Addons has no links to the to be completed RT and AGX pages.

**Comment by Dunbaratu** [comment]
Is there a completed RT page?  I know there's an AGX one but I didn't find the RT one to link to.

**Comment by theodoregoetz** [comment]
no docs on RT wrt KOS, its just a stub file. I'm not sure what should be said. Maybe just a list of limitations or common gotchya's?

**Comment by erendrake** [comment]
https://github.com/KSP-KOS/KOS/issues/486
