### ISSUE TITLE
documentation on communication range could be removed.

### ISSUE THREAD

**Issue by theodoregoetz** [KSP-KOS/KOS#496]
outdated since 0.12.2

**Comment by erendrake** [comment]
yes, the only time we have a range is when we are using remote tech and that documentation lies with them. It should be mentioned in the remoteTech integration docs that are forthcoming.

**Comment by ZiwKerman** [comment]
This is fixed too.

**Comment by Dunbaratu** [comment]
I'll check these out later tonight and probably close several of them.
