### ISSUE TITLE
Ship:Facing changes with navball mode

### ISSUE THREAD

**Issue by ZahlGraf** [KSP-KOS/KOS#503]
Hello

First of all, sorry for writing my question as issue, but I did no find a forum where I can ask such questions. I'm sure it is not an issue of kOS more an issue of my understanding.

I control my ship dependent on a ENU vector calculated out of the Ship:Facing direction. 
Unfortunately the ENU vector inverts the east part when the navball is switching from surface mode to orbit mode. Since this happens automatically, it completely confuses my controlling script. 

So my question is:
- can I lock the navball mode with kOS to have always the same east orientation?
- or can I get the facing for surface and orbit mode directly (like Ship:Velocity:Surface)
- or can I read out the current navball mode with kOS to calculate a correction when the mode changes automatically?

Hopefully someone can help me :)

Best regars
ZahlGraf

**Comment by Dunbaratu** [comment]
Ship:facing doesn't switch modes between surface and orbit because there is no such switch to be made.  Facing isn't actually a vector - it describes your orientation but has no magnitude.   When you get a vector out of it, such as Ship:Facing:Vector or Ship:Facing:TopVector or Ship:Facing:StarVector, those are always returned as unit vectors because there's no magnitude for them to even have so it just arbitrarily picks a magnitude of 1.

Your velocity differs between surface and orbital, but your facing doesn't.  I don't understand what you're trying to do.

**Comment by ZahlGraf** [comment]
Hi

I'm really sorry, I cannot understand it: Yesterday I could reproduce it with a very small code example (just printing the facing vector), but today I cannot reproduce it anymore :/
I did a test in the sandbox mode with exactly the same script, but now the Facing vector does not change when I switch the navball modes.

Maybe there is something in addition, that influences the facing values?
However thanks you so much for your fast answer, I will check it again within the next days and when the "issue" comes back, I will reopen this thread.

Best regards,
ZahlGraf

P.S.:  You are right, I meant the vector from facing (Ship:Facing:Vector).

**Comment by Dunbaratu** [comment]
Even though this is closed I wanted to comment one more time for @ZahlGraf  - I still think you're misunderstanding something fairly major if you expect Ship:Facing:Vector to change depending on surface mode or orbit mode.  It isn't supposed to change.   What changes is your velocity, NOT which way your nose is pointed.

**Comment by ZahlGraf** [comment]
Hi, thanks for the explanation. 

I also cannot explain it, I saw the switch from positive to negative values in my test example some days ago, when switching the navball mode. But as I already told: I cannot reproduce it. So either I did a mistake in my first test or the positive/negative switch for the East direction came from something else (of course the direction of my ship did not changed). 

Maybe it came from the translation from XYZ vector to ENU vector, but since I cannot reproduce it so far, I cannot investigate further. I'm really sorry for bothering you with my issue... I guess the fault was very likely myself ;-)

Thanks for that really cool mod, I like it very much!

**Comment by Dunbaratu** [comment]
If anything changed when th navball mode switched that would be purely by coincidence.
kOS ignores the state of the navball and doesn't even provide a way to query it.  That's why you have to explicitly say whether you want surface or orbital velocity.

**Comment by Dunbaratu** [comment]
If anything changed when th navball mode switched that would be purely by coincidence.
kOS ignores the state of the navball and doesn't even provide a way to query it.  That's why you have to explicitly say whether you want surface or orbital velocity.

**Comment by Dunbaratu** [comment]
If anything changed when th navball mode switched that would be purely by coincidence.
kOS ignores the state of the navball and doesn't even provide a way to query it.  That's why you have to explicitly say whether you want surface or orbital velocity.

**Comment by ZahlGraf** [comment]
Yes I understand, thanks again.
