### ISSUE TITLE
part:UID returns a unsigned int that the rest of kOS doesn't support

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#504]
Most of kOS deals with the assumption that script numbers will be either int32's or doubles.  There's not a lot of support for the other kinds of numbers, even though there's a few places that try to support them, that support is not universally spread throughout.

This means that because Part:UID returns a Uint32 (unsigned) instead of an Int32, that people can't really use it properly in the rest of kos, as was found out in issue #501 when a user was trying to diagnose another problem, you can't even do a =, or a &lt; or &gt; on it.

Because KSP's part UIDs often really DO use the high-order bit of that unsigned number, you can't just fix it by casting it to the signed int32 the rest of kOS uses.  They either throw runtime exceptions when casted, or if you insert the right keywords in the source code to allow dangerous casting then they become negative when casted to int32.

Fixing that problem would involve having to mess about with other parts of kOS to add the ability to support more numeric types.

Two possible fixes:

1: string: Return UID as the string of digits for the number rather than an actual numeric type.  At least it can be compared for equality, which is really all a UID is really good for anyway - its numeric value isn't meaningful.

2: accept negatives: Go ahead and cast to an int32 anyway, inserting the right syntax to tell C# not to complain about the dangerous operation, and accept that we'll be handing out negative part UIDs.  If the only point of a UID is equality comparison with other UID's anyway who cares?

**Comment by SirDiazo** [comment]
Wait a second. Part.uid was removed in KSP 0.90 as it was a useless number.
Part.uid was being generated randomly, it was neither unique, persistent, or an ID.
Part.FlightID is what saves to the .sfs file as the UID value.
Part.FlightID is unique across all parts in the game, persistent, and works as a unique ID for a part.
(Part.UID does not even show in object browser in Visual Studio for me now.)

**Comment by erendrake** [comment]
@SirDiazo Part.uid and part.ConstructId are indeed gone as of 0.90. I recreated them as extension methods so we could get a version that worked at all with 0.90. 

They are decent for determining uniqueness at runtime. You are right that they aren't persistent

**Comment by SirDiazo** [comment]
Ah, k.

So the kOS part.uid is an object kOS creates, it has nothing to do with the KSP part.uid that was removed.

I jumped all over it because part.uid messed me up back in 0.25, took us 3 pages of discussion on the forums before we figured out what is going on.

**Comment by erendrake** [comment]
i looked at the old binaries for ksp ans copied their internal implementations into this extension method class 

https://github.com/KSP-KOS/KOS/blob/develop/src/kOS/Utilities/BetaShim.cs

then all of the part.uid had to become part.uid() and we were back in business :)

i will likely remove them someday when we have more time to reevaluate
