### ISSUE TITLE
Can't access more than one PartModule of the same name

### ISSUE THREAD

**Issue by jwvanderbeck** [KSP-KOS/KOS#510]
On parts that have multiple PartModule entries with the same name, there appears to be no way to access a specific one.

Two solutions. 
1. Provide a LIST of actual PARTMODULEs rather than just STRINGs
2. Allow an index to be passed with the name in GETMODULE.

The former is better , the latter probably the easiest and more backwards compatible.

**Comment by Dunbaratu** [comment]
Ugh .  It's ridiculous that you're allowed to have two partmodules with the same name in the first place.

Between the two solutions I think I'd prefer 2.  Given how stuff works behind the scenes, #1 is a bit of an expensive operation , which is why it wasn't done that way in the first place.

**Comment by jwvanderbeck** [comment]
The PR I submitted does just that.  I added a GETMODULEINDEX method.  It is actually quite nice to use, especially when used interactively as you can print a list, which nicely shows all the indices.

**Comment by erendrake** [comment]
Thank you @jwvanderbeck for the PR :)
