### ISSUE TITLE
Error when trying to get a single part that doesn't exist

### ISSUE THREAD

**Issue by Gaiiden** [KSP-KOS/KOS#540]
the [documentataion](http://ksp-kos.github.io/KOS_DOC/general/parts_and_partmodules.html#parts) states that one way to get a single part if that's all you expect to be there is to use

    SET onePart TO somevessel:PARTSDUBBED("my favorite engine")[0].

however doing this actually kicks out an error rather than returning an empty value for you to then check for

![ksp exe_dx9_20150204_012211](https://cloud.githubusercontent.com/assets/7699577/6033441/aaf1cf50-abe3-11e4-9933-afccc37d25c2.png)

**Comment by Dunbaratu** [comment]
Not a bug.  The documentation explicitly says, "If you expect to get just one single hit", rather than,"if you expect to get one or zero hits".

If you expect that you might get zero hits, and aren't certain you'll get one hit,  then check the count of the list returned.

```
SET hits to somevessel:PARTSDUBBED("my favorite engine").
if hits:LENGTH == 0 {
    .. presumably you want to do some error message here? ...
} else {
   set onePart to hits[0].
}.
```
