### ISSUE TITLE
cannot view any node after NEXTNODE

### ISSUE THREAD

**Issue by Schnobs** [KSP-KOS/KOS#549]
I can select NEXTNODE, inspect and modify it.
However, there seems to be no straightforward way of doing the same with a second, third, n-th node on the flight plan.

**Comment by abenkovskii** [comment]
Idea: we can make `list nodes.` (and `list nodes in node_list.`)

**Comment by abenkovskii** [comment]
Alternatively we can make `ship:nodes`, `ship:nextnode` and probably `nodes` as an alias to `ship:nodes`.

**Comment by abarbe-** [comment]
With the newest release, you can kludge up something akin to:

```
LOCAL NEVER is NODE(2147483647,0,0,0).//A node that is way far out in the future, very low likelihood of being sooner than the true next node; prevents the crash when querying a nonexistant nextnode.
ADD NEVER.
set NodeInspector to queue().//or stack
UNTIL NEXTNODE = NEVER{
  NodeInspector:PUSH(NEXTNODE).
  REMOVE NEXTNODE.
}
REMOVE NEVER
```

Then, just pop each node from the stack/queue back onto the flightplan, inspecting/modifying/tweaking as you go.
```
LOCAL SubjectNode is NEVER.//I never declare inside a loop if I can help it, regardless of whether the language is smart enough to optimize that away
UNTIL NodeInspector:EMPTY{
  SubjectNode is NodeInspector:POP().
  //Do whatever modification/editing
  ADD SubjectNode.
}
```
