### ISSUE TITLE
possible feature: Should we have an intro popup on first-time run?

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#554]
Some mods have a popup window that appears to the user the very first time the mod is run.  It gives an intro message just in case the user hasn't seen all the important stuff in the thread's first post.  (Remember some people will be installing by just browsing Curse and not by visiting the forums, so they won't see the "this is how you use this mod" first post in the thread.)

Should we have such a thing?  I'm thinking it could contain:

* Version Number.
* One or two sentence description of the mod (I shouldn't compose this.  I suck at being terse.)
* URL to the docs page. (dunno if it can be clickable or not)
* It's a potential place to put the mandatory opt-in message about telnet server.  (The other option would be to pop up the message whenever the radio button is turned on in the config options, and that could be annoying).
* (really cool idea, but probably messy to implement) Even if the mod had been played before, still pop-up the window if the version number is higher than existing previous install, then instead fill the window with the changelogs text between prev version and this version, or just a URL to the changelog if that's too hard.

The reason I was thinking of the version update triggering the window too is that for people who already installed the older versions, they still have to see the telnet server opt-in message for the new version.

**Comment by akrasuski1** [comment]
About the telnet server: you can make it so that the popup appears when the radio button is turned on, but with the checkbox "Never show this popup again", similar to the stock KSP's warning about physic warp instability. This is not too annoying, and reduces the amount of windows popping up on the new game, while still maintaining security.

**Comment by Dunbaratu** [comment]
It's currently set to be part of the telnet main server class, and it triggers on the attempt to start the server, regardless of when it attempts to start (that way it is ensured to pop up regardless of the techique you use - the button or the CONFIG:TELNET option.)

The dialog box has 3 choices:
No, Yes and don't show this message again, Yes just this once.

**Comment by Dunbaratu** [comment]
this ended up being done differently so I'll close it.
