### ISSUE TITLE
left/right inverted on pilot translational controls?

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#563]
as per this post:
http://forum.kerbalspaceprogram.com/threads/68089-0-90-kOS-Scriptable-Autopilot-System-v0-15-5-2015-1-3?p=1735112&viewfull=1#post1735112

**Comment by erendrake** [comment]
We have been accounting for this in the other flight controls, this is confirmed to be incorrect in the code.

**Comment by erendrake** [comment]
it looks like all of the trim variables would be incorrect too then, pilot and raw.
