### ISSUE TITLE
Complex and/or chained scripts produce errors

### ISSUE THREAD

**Issue by hvacengi** [KSP-KOS/KOS#569]
I primarily use boot scripts to launch my ships, for instance my boot script will open the terminal and then launch one of my mission scripts so that I can watch it launch without having to do too much interaction.  Some times I run into an issue where my script will error out, usually referring to an argument exception for the index parameter when I'm not using a list/array object.  I've traced this down to kOS throwing an exception when trying to pop off of the stack with a stack pointer of -1.

In the past, I have diverted the problem by either increasing the IPU, or by adding a reboot command in the middle of the script.  While I've been working on a script to automatically rendezvouses with my space station in orbit, I ran into the issue again and neither of these options helped.  I've also tried both manually starting the scrip and starting the rdv operation from an existing holding orbit to see if it is related to the boot or launch script, and the script throws an error at the same point. 

Looking at how the stack works, I don't really see a way for the stack pointer to get set incorrectly.  That makes me think that either this is an issue either with the opcodes themselves, with a function popping a value that shouldn't be popped, or with the outright execution of the opcode.  I have also had issues in the past where the script will try to run the previous line a 2nd time (so it may try to run my node execution script twice in a row) but that hasn't happened since I increased the IPU.  This is why I mention the 3rd option of the opcode execution being incorrect.  If the pop is being added because it is trying to loop back through previous code, that might also explain the issue.

I know that this doesn't seem to give a whole lot of information on it's own, so I've created a zip file with all of my scripts (some of which are adaptations from the old mission tool kit on the old wiki) and a stock testing vehicle called "!test rdv.craft".  You should either edit the runrdv.ks code to set the target to be an existing craft in orbit, or name one of your crafts "Babylon 1" in order for the "set target" portion of the script to work.  You can also run the script by executing "run runrdv." on the launch pad.  Not all of the scripts are used for the rdv operation, and the script itself is not yet complete.  You can download the pack here: https://dl.dropboxusercontent.com/u/19195825/AllScripts.zip  Using the stock vessel I had a little less control over the deltav at launch, so you will end up in an orbit higher than the intended 100km (you could also force a stage before leaving the atmosphere, i usually have about 30 to 40 dv left in stage 1 at this point).

**Comment by teleksterling** [comment]
(Note I don't have a dev environment set up, but read just reading through your scripts on the plane)

You mention that the script always errors at the same point - do you remember what point that is? 
Also, I notice that in exenode.ks there are a set of nested ``when`` blocks at line 16. I can't remember if this was discussed as a problem once before during development.

**Comment by hvacengi** [comment]
I should have been more clear on the point where I fail.  It fails at the same point for each way that I run the code, but when I change how the code is executed it throws the error at a different point.  This screenshot shows the error if triggered from the pad (either through the boot script or manually, that appears to be the same):
![runrdv run at launch pad](https://dl.dropboxusercontent.com/u/19195825/kOS/screenshot0.png)

And this screenshot shows the error if run from an existing circular orbit.
![runrdv run in orbit](https://dl.dropboxusercontent.com/u/19195825/kOS/screenshot1.png)

If you read through the printed messages in the first screenshot, you'll see that it claims to have thrown the error when executing the run warpfor script.  However, warpfor is only called from within the exenode script, and you can clearly see the close of the previous exenode script block (T+780) and no start to the next script block.  In the second screenshot, it seems to think that the multiplication symbol was the offending entry, and again the line cited should have already been executed (you can see the transfer orbit node execution has already happened).

If desired, I can provide the log file that includes both of the launches from these screenshots.

If it turns out that the when's are the problem, I can create a new set that reduces their usage.  I think that I read some where that nesting them was better because the mod only had to evaluate the applicable triggers, and it prevented overloading the pre-execution logic.  Cutting the when blocks would make my scripts longer, but I can manage that.

**Comment by Dunbaratu** [comment]
I may just be an instance of problem #427 - can you show the log?  It's important to see where the exception was thrown from in the kOS code.

Although I should warn you, I have nothing to do with the boot code, and have *NEVER ONCE* managed to get it to run *AT ALL*.  Neither with nor without any bugs - it just never triggers the script in the first place - so I just shrugged and called it a feature I'll just never bother trying to use.  I have no clue how to recreate your problem when I can't even run boot code in the first place.

**Comment by hvacengi** [comment]
Sure thing, you can get the log here: https://dl.dropboxusercontent.com/u/19195825/kOS/KSP%202015-02-17.log
I did not use the boot script portion with the first instance in the log, but I did for the 2nd one (since it just booted right to continuing the operation).  If you type `run runrdv.` on the archive at launch, or on the local mid flight you should see the same errors (I have when I've tried it, boot script didn't seem to matter).

I'm not sure if #427 is the same thing.  It would explain why things don't appear to line up with the correct point in execution.  But there shouldn't be an existing exception on the stack at that point.  After the first exception, I went back to the space center and then flew the ship from the tracking station just to make sure I didn't have variables hanging in limbo.

I did also modify the stack to log every time the stack pointer moved (talk about game lag).  I couldn't make anything out of it, except that it wanted to pop with a stack pointer of -1.

**Comment by Dunbaratu** [comment]
I know this issue is very old, but after looking at it again today I *very* strongly suspect that it's actually the same problem as was just solved here:
https://github.com/KSP-KOS/KOS/issues/707

The suite of scripts used by @hvacengi do contain a lot of cases where different scripts all execute the same ```wait until ......``` clauses, which is what triggers the bug.

**Comment by hvacengi** [comment]
Thanks for keeping the issue in the back of your mind @Dunbaratu , I haven't had a lot of time to mess around with KOS in the last month so I hadn't worked on tracking down the issue at all.

My first reaction is that you're brilliant!  That sounds like it could be a very plausible answer to the issues I'd experienced.  I'm going to download the latest source and see how the game behaves on the exact same script.  Will report here and close if appropriate.

**Comment by hvacengi** [comment]
I can report that the exceptions that were being reported in my scripts previously have not appeared in multiple attempts to run the program.  I have of course found other issues with the script, but I think that most of them are in my script and were just hidden by the previous issue.  I'm going to close this issue, because it appears that #707 did resolve my issues as well.

Thanks!
