### ISSUE TITLE
Vessel:ANGULARVEL is broken

### ISSUE THREAD

**Issue by geoffromer** [KSP-KOS/KOS#570]
[As reported in the [forum](http://forum.kerbalspaceprogram.com/threads/68089-0-90-kOS-Scriptable-Autopilot-System-v0-15-5-2015-1-3?p=1723279#post1723279).]

When I use it, it seems to be defined in terms of the ship's FACING direction, rather than the SHIP-RAW coordinate system: regardless of how I orient my ship, if I put it in a pure counterclockwise roll, ANGULARVEL is parallel with SHIP-RAW +Y (rather than being parallel with the ship's FACING). Similarly, yaw left corresponds to +Z, and pitch down corresponds to +X. Notice also that the sign of the Z component is backwards: in a left-handed coordinate system a positive yaw should correspond to a right turn, not a left. Notice also how Y and Z are reversed: the Y component represents rotation about the Z axis, and vice-versa.

Here's a demo script that makes it obvious:

    SET angular TO VECDRAWARGS(V(0,0,0), SHIP:ANGULARVEL, RGB(1,0,0), "Reported Angular Velocity", 1, TRUE).
    LOCK corrected_angvec TO SHIP:FACING * V(SHIP:ANGULARVEL:X, -(SHIP:ANGULARVEL:Z), SHIP:ANGULARVEL:Y).
    SET corrected TO VECDRAWARGS(V(0,0,0), corrected_angvec, RGB(0,1,0), "Corrected Angular Velocity", 1, TRUE).
    UNTIL FALSE {
      SET corrected:VEC TO corrected_angvec.
      SET angular:VEC TO SHIP:ANGULARVEL.
    }

When I run this script, I can put my ship through any crazy mix of rotations, and the "corrected" angular velocity vector seems to stay parallel to the axis of rotation, whereas the "reported" vector can be arbitrarily wrong.

**Comment by erendrake** [comment]
@Dunbaratu is this related to #529?
