### ISSUE TITLE
Let's make a bug fix list for the release.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#577]
@erendrake wanted to get a few bug fixes into the release along with the telnet server.  I'd like to see a concrete idea of which bugs they should be, and then spend my mod time on addressing JUST them and nothing else, so we can get the release out.

**Comment by erendrake** [comment]
Made a new milestone 

https://github.com/KSP-KOS/KOS/milestones/0.16%20punchlist

right now this is most of the current "bug" issues we have, lets triage the list asap. Some of them we can close very quickly and others are going to take some serious work. I think that everything in there has value for the 0.16 release.

**Comment by Dunbaratu** [comment]
Oh man that list is way too long  I was thinking of just stuff that would be done quickly in a day or two, as we currently have this cool telnet thing being held back from release by the bug list.  Yeah lets trim it down to a reasonable set of targets.

I was thinking it may be reasonable to, after this release, have a feature freezed release where all we do is tackle the bug list.

**Comment by erendrake** [comment]
thats fine, thats why i wanted to triage the list and find the ones we can get done quick.

**Comment by erendrake** [comment]
Some of these are already done i just wanted to bring them up and talk about them.
