### ISSUE TITLE
RT "signal lost. waiting to re-aquire signal" check disallows manned terminal use.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#580]
With CONFIG:RT2 enabled, there is a check that causes the following message to appear on the bottom of the terminal screen:
```



-----------------------------------------------------
Signal lost. Waiting to re-acquire signal.
```
When this message appears, use of the kOS display is frozen and you can't see anything change on the terminal screen.

This message has 2 problems:
(1) It ignores whether the craft has any Kerbal crew or not.  It should only lock out the terminal if the craft is unmanned and therefore you can assume the terminal must be back at KSC.  If the craft is manned, then the terminal might be a pilot-assistance tool running some autopilot stuff for the manual astronaut to look at in the cockpit.
(2) With the new update to allow telnet clients, nothing appears on the telnet terminal at all indicating the problem.  The message seems to be appearing only on the GUI terminal alone.  On the telnet window It does not mention the loss of signal and it just looks like the mod is frozen or buggy.

Number (2) is how I was using it when I discovered this feature and it utterly baffled me why it kept freezing things and breaking them, since the telnet terminal didn't show the message at all and this was the first time I was using RT with kOS so I wasn't familiar with the behavior.

It seems to me that to fix this requires a bit of thought as to detecting whether a terminal is "in" the ship or "in" the KSC before deciding to enable this check.  And we can't just use the idea that it's a telnet as the decision, since there's two reasons to use a telnet terminal:
1 - to have it in another window.
2 - to use it remotely.
The out-of-character consideration "is the terminal window local or remote" and the in-game consideration "is the terminal window local or remote" should be two different orthogonal things, with all cross-combinations of them being valid possibilities  (i.e. you can use the GUI terminal as either a remote KSC terminal or as a local in-ship terminal, and you should also be able to use the telnet terminal as either a remote KSC terminal or a local in-ship terminal.)

I guess what I'm saying is that before you have a remotetech "needs signal to use remote terminal" we first need a means of deciding what counts as a remote terminal.  I suppose we could just go with "if it's a manned craft then the terminal is local, else its at KSC" for now.  I have a few interesting ideas for in-game networking and choosing "where" a terminal is, and checking connectivity from THERE to craft instead of from KSC to the craft (i.e. the terminal controlling a probe on the moon's surface might be located not at KSC but closer, being operated by a kerbal in the command module orbiting the mun, for example.)

An unrelated problem:

Also, if the craft is intended to continue working on autopilot but the script just won't show on-screen then there's a second problem - when the message appeared my ascent script just broke completely, starting to display wrong numbers, misread the speed, etc.  It reported the speed from velocity:orbit about 4 times larger than it really was, which caused the script pid controller to shut the throttle off completely.

**Comment by erendrake** [comment]
I saw this a few weeks ago and added https://github.com/RemoteTechnologiesGroup/RemoteTech/pull/349 to let us query RT on the current control state. This doesnt solve the remote terminal question. I like the theme around the telnet terminal being a the KSC but that means that some missions wont be able to utilize telnet at all. 

I do like that as a bit of theme, esp when the terminal is actually remote rather than just a loopback connection.

**Comment by Dunbaratu** [comment]
I don't like that theme.  Just because I'm using a remote telnet doesn't mean I'm not on the ship.  .When two people are roleplaying crew members together, one has to be remoted in on telnet because the game is only running on one of their computers.

**Comment by erendrake** [comment]
so then the only thing that is really limited when you are in "local control" is access to the archive? that works just fine for me.

**Comment by erendrake** [comment]
we could also limit it based on the number of kerbals on the craft, where you must have > 2 kerbals in order to have an additional terminal? Maybe that is just silly

**Comment by Dunbaratu** [comment]
Perhaps, but they're all future ideas.  I think for the immediate release I'd rather you just go for something simple like "only perform the connectivity check when the craft has no crew."

**Comment by erendrake** [comment]
The archive limitation is already in so its not a future idea, its just undocumented like everything in the RT integration. but the kerbal limit will take a lot more work so i would say lets not even if that is the direction we want to go.
