### ISSUE TITLE
Repeated random error message when the game autosaves.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#597]
I kept getting this on the console every 5 minutes after running my ascend script, which finished normally, and it was weird because I wasn't doing anything at the time and no error message was appearing - just this message about why it can't show me the location of the error (which it hadn't printed).

```
kOS: (Cannot Show kOS Error Location - error might really be internal. See kOS devs.)
```

It corresponds to this in the log:
```
(Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)

System.NullReferenceException: 
  at (wrapper managed-to-native) UnityEngine.Object:get_name ()
  at kOS.Suffixed.Part.PartValue.ToString () [0x00000] in <filename unknown>:0 
  at kOS.Execution.CPU.OnSave (.ConfigNode node) [0x00000] in <filename unknown>:0 
```

Given the OnSave in the stack trace, and the fact that it was once every 5 minutes or so, I'm assuming it was triggered by the autosave.

I have no idea yet what causes it but I'm logging it in the hope I can reproduce it more reliably later.

**Comment by Dunbaratu** [comment]
I have a suspicion about the cause of this:

I think it happens when a script sets a variable to a value type of VesselTarget or PartValue, (which contains a reference to the KSP object type Vessel or Part inside it), and that vessel or part gets removed from the game (blown, up falls into atmosphere and gets deleted, etc).  For example, when you've been iterating over lists of engines, and some engines detach in a spent stage and fall away out of scope and get removed, but you've still got that list in a variable somewhere so you still have a C# reference to that now destroyed Part.)

Because that C# reference keeps the Part from being orphaned, it doesn't get destructed.  When the autosave tries to save the variable, it traverses the contents, and tries to use the dead part, most of the suffixes of which will now no longer function properly.

It occurs to me fixing this could be related to also fixing issue #575.

KSP has such a thing as objects that are dead and gone but you still have references to them.  There has to be some way to detect this and protect ourselves from accessing them when this happens.

**Comment by abenkovskii** [comment]
I get no error when autosaving while having a reference to a dead vessel and it's dead part. Could you try replicating this bug again?

**Comment by hvacengi** [comment]
Since we removed variable saving in PR #1111, I'm closing this issue.  There is no longer anything done in the exception throwing `OnSave` method.
