### ISSUE TITLE
After 0.12 is out - should there be a goal for 0.13 ahead of time?

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#60]
Obviously bugs should be fixed as solutions present themselves, but what really draws people in are new things to do.

Would it be a good idea to have a sort of brainstorming session of wishlist feedback from people, to help drive what 0.13 should focus on?

At any given moment there's always going to be more new features that people want than is reasonable to actually plan for just one release, but getting a feel for which things are most important to the user community might be a good idea to help prioritize which things to work on first.

But then again, when development is entirely on voluntary time, asking developers to work on a thing that the developers don't think is important, or is uninteresting to them, is a sure way to stall the project.

So to find a good compromise between those two competing factors of "give the users what they want" and "let developers work on what they want", I was contemplating this:  First, potential developers here discuss what things they'd like to work on - ideas they have for future enhancements.  Then second, a list of those things is presented on the forum for discussion.  The intersection of "set of things developers want" and "set of things users want" becomes the basis for picking the next goals.

I'm just throwing a random idea out through bleary eyes too early in the morning.  I don't know if I explained it well, but we'll see.  What do people think of this?

**Comment by jberkman** [comment]
(i'm guessing this can probably be closed?)
