### ISSUE TITLE
minor volume naming issue

### ISSUE THREAD

**Issue by pgodd** [KSP-KOS/KOS#602]
if you name a volume using one of the system colour names the volume name displays RGB data.
![screen shot 2015-02-21 at 12 19 57 pm](https://cloud.githubusercontent.com/assets/7835223/6315091/ef590c8c-b9c4-11e4-9d8b-1670de4d6d00.png)

**Comment by Dunbaratu** [comment]
Volume name expects a string.
Try naming it to ```"red"``` instead of ```red```.  What happened is that because it expects a string, it turned the RGBA object ```red``` into its ToString() output (the same as what happens when you try to print its value).

**Comment by Dunbaratu** [comment]
I don't think this is "really" an issue.  The whole point of having ToString() **is** to allow any object to be automatically casted to a string in any place where the prototype is expecting a string object.  It's the reason you can concatenate strings with numbers using "+" for example - you're not *really* concatenating a string with a number.  You're concatenating two strings, one of which got implicitly built using integer.ToString().

So everything is functioning as expected, correctly here.  If you used any object as the name of the volume, not just a color but any object, you'd get the volume named using that object's ToString() output.

You could, for example, ```rename volume 3 to SHIP.``` and end up with the name of the volume being the string ```Vessel("my first rocket")```.
