### ISSUE TITLE
Elements arent working

### ISSUE THREAD

**Issue by erendrake** [KSP-KOS/KOS#615]
The element list you get from

    LIST ELEMENTS IN elist.

gives a collection of parts nothing like what the design goal was. which was to give you a view of your docked craft like this:

![image](https://cloud.githubusercontent.com/assets/486486/6335405/95bcd92a-bb58-11e4-95e8-5a3def27748b.png)

I never managed to get this working the way i wanted :P

**Comment by pgodd** [comment]
If you exposed the varName of the device in the Editor then you could collect a list of devices by hunt and peck. That would be really close to the way the chart works.
