### ISSUE TITLE
Need an ability from within a script to list cores and identify current active core.

### ISSUE THREAD

**Issue by ZiwKerman** [KSP-KOS/KOS#623]
Maybe something like "list cpu" command which behaves like "list parts" command, but returns the list of all cores in physics range with some indication of active cores - almost the same functionality you get on a welcome screen of a telnet terminal.

**Comment by abenkovskii** [comment]
1. We can get `modulesnamed` and then access their `:part`
2. To identify the current core we can use `core`: https://github.com/KSP-KOS/KOS/pull/930
