### ISSUE TITLE
kOS captures key presses when terminal is running script.

### ISSUE THREAD

**Issue by TDW89** [KSP-KOS/KOS#630]
kOS prevents (most) key presses getting through to ksp when the terminal is in focus, should it continue to do so when the terminal is running a script and isn't doing anything with them?
Eg. a script that uses
```
until ag1 {}.
```
requires that the terminal be out of focus to activate the action group manually. This is also an issue when using kOS for readout only scripts while flying manually as during the day the transparency makes the out of focus window hard to read and with it in focus the vessel can't be controlled.

**Comment by Dunbaratu** [comment]
Rather than change the behavior, which is vital, perhaps a different solution would be "stop making the terminal so hard to read when it's not got the keyboard focus."

**Comment by TDW89** [comment]
I added that one too #631 :-/ 
Did not realise that it was vital for kOS to capture key presses when it was running script (not accepting terminal inputs), TBH I had forgotten about Ctrl-C and hadn't considered whether it was possible or not to distinguish between the two states of [in focus & idle] and [in focus & busy].
