### ISSUE TITLE
Pilot control docs have some errors

### ISSUE THREAD

**Issue by erendrake** [KSP-KOS/KOS#633]
This is my bad, i just missed changing some of the names from the normal control page. 

(eg SHIP:CONTROL:MAINTHROTTLE should be SHIP:CONTROL:PILOTMAINTHROTTLE )

http://ksp-kos.github.io/KOS_DOC/commands/flight/pilot.html

**Comment by Dunbaratu** [comment]
This has tag "bug" - is that true or is it pure documentation only?

(I'm trying to look at bug issues first as higher priority than docs, and only hit the doc issues when there are no bugs left, or none of the bugs are things I can address)

**Comment by erendrake** [comment]
i cant think of why but i was sure it had a bug component :P but i cant seem to remember why
