### ISSUE TITLE
Suggestion: replace current control for boot file selection.

### ISSUE THREAD

**Issue by ZiwKerman** [KSP-KOS/KOS#635]
As discussed with erendrake, I am raising this issue and will follow it up with a PR later today.

Current boot.ks file selection UI is quite broken and unintuitive. By introducing the KSPAPIExtensions.dll dependancy I suggest bringing in UI_ChooseOption control for boot file selection.
Example:
![Example](http://i.imgur.com/05kp7Sy.jpg)

I will also bring in some bits of documentation of how boot scripts work in kOS right now.

**Comment by erendrake** [comment]
The boot feature today is pretty arcane. I welcome any effort to make it better.

**Comment by ZiwKerman** [comment]
Please advise where it would be better to put the documentation part of this feature - to `general/volumes.rst` or to `commands/files.rst`?

**Comment by gillonba** [comment]
Not to digress too much, but is there currently documentation anywhere on how to use the boot file feature?  I would really like to use this feature but cannot find anyone explaining how

**Comment by ZiwKerman** [comment]
I am planning on posting a pull request with some basic documentation in 1-2 hours from now, then it's up to devs to merge it into main release, but you'll be able to read a preview of it on my fork.

**Comment by ZiwKerman** [comment]
By the way, if we release a version of kOS with KSPAPIExtensions as a dependency we should let the creator/maintainers of the mod know by posting in mod's thread on forums.
