### ISSUE TITLE
Documentation is rendering with all the :math: numbers weirdly three times repeated.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#638]
Look at this page:

http://ksp-kos.github.io/KOS_DOC/commands/flight/raw.html#raw

Note the bit that says this partway down the page:

> This will start pushing the ship to rotate a bit faster to the right, like pushing the D key gently. All the following values are set between −1−1−1 and +1+1+1. Zero means the control is neutral. You can set to values smaller in magnitude than −1−1−1 and +1+1+1 for gentler control:

Note the "-1-1-1" and "+1+1+1".

If you look at the source .rst file that generated it, it looks like this, and contains no such tripling:

```
This will start pushing the ship to rotate a bit faster to the right, like pushing the ``D`` key
gently. All the following values are set between :math:`-1` and :math:`+1`. Zero means
the control is neutral. You can set to values smaller in magnitude than :math:`-1`
and :math:`+1` for gentler control::
```

Something is broken about how

    :math:`____`

is getting rendered by sphinx, for any given value in the ____ blank.  This same tripling is happening everywhere else it uses this in the docs.  (for example the vector's :X suffix is described as returning the vector's "Xxx" component.)

**Comment by Dunbaratu** [comment]
This may be browser dependent.  I noticed that after rebooting to OSX to work on some documentation, that on Safari and Firefox on OSX the problem didn't exist.  (But it did exist on Firefox on Windows .... weird).

**Comment by TDW89** [comment]
Don't know if this is useful or not but for android;
Stock browser is fine,
Chrome has the bug,
Firefox is fine.

**Comment by abenkovskii** [comment]
Windows 8, chrome 41.0.2272.118 m - fine

**Comment by Dunbaratu** [comment]
ancient issue - not our problem anyway because it was just a small rendering problem but not a serious one.  I'll close it.
