### ISSUE TITLE
Error when trying to run script for the first time without loading+saving using the kOS code editor

### ISSUE THREAD

**Issue by Zyt3x** [KSP-KOS/KOS#644]
Using test script "test.ks" saved in Ships/Scripts.
```
SAS off.
RCS on.

print "test".
```
In kOS terminal: "switch to 0. run test." with KSP running with administrator privileges returns error:
Syntax: Unexpected token ´ ´ found. Expected EOF at line 1 ^sas off.

I then have to bring up the code editor ("edit test."), copy the script from Notepad++, paste it into the code editor and click save. Just clicking save does not work.

Script now successfully executes and runs as expected.

**Comment by erendrake** [comment]
can you upload the bare file to us?

**Comment by erendrake** [comment]
email it to erendrake@gmail.com

**Comment by Zyt3x** [comment]
For the others: The code editor adds 3 bytes to the file (a header of some sorts, perhaps?) after copy+pasting the code

**Comment by Zyt3x** [comment]
Tried encoding as ANSI instead of UTF-8 and the problem is gone
