### ISSUE TITLE
Resource Transfer 

### ISSUE THREAD

**Issue by erendrake** [KSP-KOS/KOS#656]
There is no way right now to achieve a resource transfer in kOS. that sucks really bad and i want to fix it :). such a system needs to be able to 

* Let you start a transfer of a specified amount from one set of parts to another
* Let you start a transfer of a all possible resource from one set of parts to another
* Lets you pause/restart a transfer
* Lets you monitor a transfer's progress

constraints on a transfer include:

* all parts must be on the same craft. the first revision would not be compatible with KAS attachment 
* if you specified an amount, there must be enough available space to accept the resource among the destination parts
* if you specified an amount, there must be enough available resource to supply the resource among the source parts

Failing any of these will stop the transfer.

**Comment by ZiwKerman** [comment]
For clarity on constraints when amount is specified incorrectly: will the transfer stop after all available amount is transferred/all available space filled or immediately upon receiving incorrect instruction?

**Comment by erendrake** [comment]
My first thought is to have it stop immediately.

**Comment by erendrake** [comment]
one thing i would like to discuss is the current behavior which is to instantiate in an inactive state. So you must set :ACTIVE to true before the transfer would start. I am thinking about reversing this decision because if the user didnt want to transfer right away they could just defer creating the transfer in the first place.

**Comment by ZiwKerman** [comment]
Well, yes I agree. Why would you create a TRANSFER in advance?

**Comment by Dunbaratu** [comment]
I disagree.
You can control timing more accurately for multiple transfers if you set up all the transfers first without them moving yet, and then, so to speak, go "on the count of 3 ready.... one two three... GO."

**Comment by ZiwKerman** [comment]
But you can already set up multiple-part to multiple part transfer in one go, no? or you think it may be more complex than that?

**Comment by Dunbaratu** [comment]
Also, there's the issue of giving the user a choice.

If the transfer doesn't go until the user says so, then the user has the choice and the control whether or not to get it started or not.

If the transfer automatically goes until the user says to stop, then the user does NOT have the choice to set up a transfer that doesn't start going yet.

Starting with it stopped is the way that gives the user the most choice.

**Comment by ZiwKerman** [comment]
Maybe then add a parameter on creation of Transfer whether you want to start it immediately or not? IMO it would feel more intuitive
a lot of users will forget to set TRANSFER:ACTIVE, I would be the first

**Comment by Dunbaratu** [comment]
A choice in the constructor is fine by me.
I just don't like the mentality of "I could never see a reason I'd do it  therefore I'll deny it to a user of my API"  That's really not the right mentality to have when making an API.

**Comment by erendrake** [comment]
I am reticent to add a constructor parameter because we dont have optional parameters. Im going to leave it normally inactive for now and we can get feedback.

**Comment by TDW89** [comment]
Not sure if it's something worth considering but would you want a restriction to prevent fuel transfer being used for pwm control of an srb?

**Comment by erendrake** [comment]
I haven't tried it yet but im pretty sure that SRBs won't be able to be transferred around based on their resource definition. 

It should be a more explicit error when you try
