### ISSUE TITLE
Colon in the string "ALT:RADAR" gets mangled when stored in a string variable.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#662]
```
SET FOO TO "??? ALT:RADAR".
PRINT FOO.
??? ALT_RADAR

PRINT "Watch the colon in ALT:RADAR magically become an underscore".
Watch the colon in ALT_RADAR magically become an underscore
PRINT "Other colons Like:This are fine"
Other colons Like:This are fine.
```

There's some code in the mod that tries to make ```ALT:RADAR``` and ```ALT_RADAR`` aliases for the same variable.  More than likely that's getting activated when they are just dumb strings and not identifiers.

There are a few other similar variable bindings like I think ETA:apaopsis and ETA:periapsis that do the same thing.

This might get fixed automatically if we make two different kinds of strings - user  strings and identifier strings.
.

**Comment by abenkovskii** [comment]
#931
> Technically, ALT and ETA are now objects

Close?
