### ISSUE TITLE
Telnet server binds to "wrong" interface

### ISSUE THREAD

**Issue by Craquehead** [KSP-KOS/KOS#668]
I have more than one IPv4 interface on my PC, and the kOS telnet server insists on attaching to my storage network interface rather than the one shared with the rest of the PCs on my network, including the laptop that I'd like to telnet from.

Is there a way to either hardcode the correct IP in a config file, or have the telnet server attach to all interfaces?

**Comment by ZiwKerman** [comment]
Maybe information here might help
http://ksp-kos.github.io/KOS_DOC/general/telnet.html#id7

**Comment by Dunbaratu** [comment]
You are correct that this is a problem.  It's one I foresaw when I was designing it but we didn't really have a means of making selection lists in the CONFIG object, so I couldn't implement it the way I wanted.  (Which was to get all IP addresses that are legal on the host, and let you pick one).

So I just went with whatever the "official" IP for the hostname is.

It may be possible to let you have a write-in blank for it, but I'm reluctant to make too many config args for the telnet server.  there;s 3 already.

**Comment by Craquehead** [comment]
> So I just went with whatever the "official" IP for the hostname is.

How is determining "official" ip? at least on my machine, when I ping the value returned by "hostname", I get an IPv6 address.

How about instead of an additional argument for the telnet server, you make it more intelligent about how it parses the existing arg? I.e, if the value is a straight up int, it's the port. If it contains a colon, it's an IP:port pair.

**Comment by Dunbaratu** [comment]
IPAddress[] localIPs = Dns.GetHostAddresses(Dns.GetHostName());
The docs claim the first (zeroth) address returned is the canonical one for that hostname.
