### ISSUE TITLE
List type not supported

### ISSUE THREAD

**Issue by dcrockwell** [KSP-KOS/KOS#669]
Am I doing something wrong with list? The following log shows how I've tried to list the contents of a non-empty list.

```
SET partLIst TO SHIP:PARTSDUBBED("Any Part Name Here").
PRINT partList.
LIST of 2 items
LIST partList.
List type not supported
At interpreter history, line 27
LIST mods.
         ^
```

**Comment by ZiwKerman** [comment]
to traverse your LIST you need to use something like this
```javascript
FOR part IN partLIst 
{
    IF part:name = "desiredName"
    {
         //do some stuff
    } 
        
}

**Comment by dcrockwell** [comment]
I am not trying to traverse the list. I'm only wanting to print out what the list is. 

**This Works:**
```
LIST SHIP:PARTS.
```

**This Does Not Work:**
```
LIST SHIP:PARTSDUBBED("SomePartHere").
```

I'm just trying to list which modules are on a part without having to iterate a PRINT command.

**Comment by Dunbaratu** [comment]
Have you tried:
```
    PRINT ship:partsdubbed("SomePartHere").
```
Frankly, I'm rather surprised that LIST SHIP:PARTS works.  The LIST command is for making lists using an alternate syntax, not for being passed a thing that already is a list to begin with (like SHIP:PARTS).

**Comment by dcrockwell** [comment]
Yes, it will print "list of 2 items" or however many there are.

**Comment by dcrockwell** [comment]
@Dunbaratu How do you print a list of modules on a part? All of the methods above except doing a direct iteration on the list seems to fail. I'm just trying to know what the modules are on a part, and which actions are available on the module easily.

**Comment by ZiwKerman** [comment]
I use `print part:allmodules` and `print module:allactions`
