### ISSUE TITLE
All flight control functions shoul respect InputLockManager settings

### ISSUE THREAD

**Issue by jwvanderbeck** [KSP-KOS/KOS#670]
If `InputLockManager.IsLocked(ControlTypes.PITCH | ControlTypes.ROLL | ControlTypes.YAW | ControlTypes.THROTTLE)` is set to lock out control of the spacecraft attitude and throttle, then kOS should respect that and not allow control.

If someone more familiar with the nuts and bolts of kOS AP implementations could add this that would be great, otherwise I will submit a PR once I've had a chance to familiarize myself with the setup.

**Comment by jwvanderbeck** [comment]
Ignore this.  Will update later.

**Comment by erendrake** [comment]
I don't think this is a bad idea. Is there a mod incompatibility issue we are dealing with here?

**Comment by jwvanderbeck** [comment]
Actually ignore it.  It isn't the best way to go about things and I jumped the gun.  Standby :)
