### ISSUE TITLE
print option to echo to log

### ISSUE THREAD

**Issue by Gaiiden** [KSP-KOS/KOS#681]
seeing the implementation of the echo option for HUD messages to be displayed also in the console window, it would be nice to have print do something similar to avoid needing to write the same string with two commands.

    print "some text" echo mylog.
    print "some text" at(0,0) echo mylog.

It has been pointed out to me that the new telnet functionality does provide you with a scrollable window, although that does rely on setting up the telnet functionality. (which I plan to do eventually but maybe not all users would want to)

**Comment by Dunbaratu** [comment]
Since functions are getting released, I'd rather see this relegated to user-land, like so:
```
    declare function printAndLog {
        declare parameter str.
        print str.
        log str.
    }.
```

**Comment by erendrake** [comment]
i agree with @Dunbaratu,

@Gaiiden does that work for you?

**Comment by Gaiiden** [comment]
yup that's perfectly fine
