### ISSUE TITLE
Trajectories API integration

### ISSUE THREAD

**Issue by erendrake** [KSP-KOS/KOS#687]
I have seen a few people using trajectories with their missions and for some it means they end up manually piloting parts of it.

eg https://www.reddit.com/r/Kos/comments/2zxw12/gfy_partiallyautomated_first_stage_rtls_xpost/

The trajectories mod has an API we could expose?
https://github.com/fat-lobyte/KSPTrajectories/tree/master/TrajectoriesAPI

**Comment by hvacengi** [comment]
Close via #1603, final review was 85df4bb5b7202b4c6cad5b0b06d73759d5e9298b
