### ISSUE TITLE
WAIT 0. freezes script/terminal

### ISSUE THREAD

**Issue by TDW89** [KSP-KOS/KOS#688]
The command `WAIT 0.` if typed directly to the terminal locks you out until you cycle power (never completes and you can't Ctrl+C out.)
When in a script it freezes the script until you abort it. 
This also happens if the value is negative.

**Comment by Dunbaratu** [comment]
hmm.  That's... weird.

I'll have a look after I get functions checked in.

```wait 0.``` should pretty much return on the very next update tick.  It means wait N seconds, where N is zero ,so it should immediately become expired the next time it checks.

**Comment by Dunbaratu** [comment]
self-assigned just to ensure nobody else accidentally tries to work on it at the same time (even though I was bad and did the PR first).
