### ISSUE TITLE
LIST ELEMENTS, DOCKINGPORTS (printed to screen, not IN VARNAME) doesn't work.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#693]
You can LIST ELEMENTS IN FOO, but you can't just LIST ELEMENTS to print them to the screen.

This can easily be fixed, but please hold off on doing so until after user functions are merged in, as all the 77 built-in functions had to be edited for that, and this is one of them.  It would make a merge conflict to have edited it before that merge.

**Comment by Dunbaratu** [comment]
I was debating whether to call this "bug" or "enhancement", but I think it's going to look like a bug to most users because they don't realize that LISTing to screen and LISTing to variable are in fact entirely separate things.

**Comment by erendrake** [comment]
This is actually a pretty lame refactor job. i considered moving it out but i think i might as well bite the bullet.
