### ISSUE TITLE
PARTMODULE:DOACTION

### ISSUE THREAD

**Issue by JDTiger** [KSP-KOS/KOS#700]
Hey guys,
since kOS works now for me, I try to establish a remoteTech network around Kerbin.
But to make my script work entirely like I want it to work, i need the PARTMODULE:DOACTION phrase... but from the documentary i can't really find the completely right exclamation for it.
Would be nice if someone could give me an example for this phrase.

Greets JD_Tiger

**Comment by erendrake** [comment]
This is not an 'issue' with kOS. You could ask it on reddit 

http://www.reddit.com/r/kos

or on the forums 

http://forum.kerbalspaceprogram.com/threads/68089-0-23-5-kOS-Scriptable-Autopilot-System-v0-12-1-2014-5-18
