### ISSUE TITLE
KerbalAlarmClock crashes when installing kOS

### ISSUE THREAD

**Issue by CC007** [KSP-KOS/KOS#701]
My game only crashes after installing the kOS mod. 

OS: Windows 64 bit
Version: KSP 0.90 x86_64  (need it because of mem issues) 

Mods:
- Distant object 1.3.1
- Docking port Alignment unit 5.1 /  6.1 (doesn't change the problem)
- Env Visual Enhancements 7.4
- FAR 0.14.6
- FMRS 0.3.02
- KAC 3.2.3.0
- Kerbal engineer 1.0.14.1 / 1.015.0 (doesn't change the problem)
- Kerbal Flight Indicators R9
- KerbinSide 0.41
- kOS 0.16.2
- Infernal Robotics 0.19.3
- MechJeb2-2.4.2.0
- NavHud 1.1.4
- Proc Fairings 3.11
- RemoteTech 1.6.3
- TacLifeSupport 0.10.2.15
- Toolbar 1.7.8
- Transfer Window Planner

```
========== OUTPUTING STACK TRACE ==================

(0x0000000103950000) ((module-name not available)): (filename not available): (function-name not available) + 0x0
(0x0000000020F2FBD3) (Mono JIT code): (filename not available):  KerbalAlarmClock.KerbalAlarmClock:RepeatingWorker () + 0x43 (0000000020F2FB90 0000000020F2FCF4) [00000000038B4D48 - Unity Root Domain] + 0x0
(0x0000000020F2FAF2) (Mono JIT code): (filename not available):  KSPPluginFramework.MonoBehaviourExtended:RepeatingWorkerWrapper () + 0x72 (0000000020F2FA80 0000000020F2FB69) [00000000038B4D48 - Unity Root Domain] + 0x0
(0x00000000041D72DB) (Mono JIT code): (filename not available):  (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr) + 0x6b (00000000041D7270 00000000041D734A) [00000000038B4D48 - Unity Root Domain] + 0x0
(0x00007FFD65CD3A82) (mono): (filename not available): mono_set_defaults + 0x2b9e
(0x0000000008845C08) ((module-name not available)): (filename not available): (function-name not available) + 0x0
(0x00000000FFFFFFFF) ((module-name not available)): (filename not available): (function-name not available) + 0x0
(0x00000000038B4D48) ((module-name not available)): (filename not available): (function-name not available) + 0x0

========== END OF STACKTRACE ===========
```

This is the log of before the crash:

```
...
3/31/2015 9:57:56 PM,TransferWindowPlanner,Loading Textures
 
(Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)

3/31/2015 9:57:56 PM,TransferWindowPlanner,Configuring Styles
 
(Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)

MessageSystem: Cannot load messages - MESSAGESYSTEM node does not exist
 
(Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)

Tac.AddScenarioModules[FFF971A0][56.14]: Adding the scenario module.
 
(Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)

3/31/2015 9:57:56 PM,TransferWindowPlanner,AppLauncher: Creating Button-BEFORE
 
(Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)

3/31/2015 9:57:56 PM,TransferWindowPlanner,AppLauncher: Creating Button-AFTER
 
(Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)

3/31/2015 9:57:56 PM,KerbalAlarmClock,AppLauncher: Creating Button-BEFORE
 
(Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)

3/31/2015 9:57:56 PM,KerbalAlarmClock,AppLauncher: Creating Button-AFTER
 
(Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)
```

**Comment by ZiwKerman** [comment]
There are no dependencies yet from kOS to any other mod. So your issues are most likely from Windows 64bit which is not supported by at least half of the mods you're using.

Please use KSP in 32 bit mode with `-force-opengl` option

**Comment by Dunbaratu** [comment]
And, furthermore, it's utterly masking the usefulness of the stack trace:  We can't work out what's happening when the log is hiding the names of everything.  All those "module name not available" and "file name not available" messages in the trace are where we're *supposed* to be seeing the names of the methods its calling.  Without that there's no way to know what's going on.  I've never seen the stack trace look like that from the 32 bit version.

**Comment by CC007** [comment]
Ok, I'll just run the game without KAC, It seems to be stable (no crashes or unexpected behaviour without it). This bug will remain a mystery until 64 bit is properly supported.

Note, I do need 64 bits due to memory issues. I know of the active texture management mod, but... yeah.

**Comment by erendrake** [comment]
@CC007 just FYI the next version of KSP will likely not ship with a 64 bit client. and that version just entered experimental testing. You might consider trying to get the memory usage down if you want to move your save to 1.0
