### ISSUE TITLE
Sensors wrong in the docs.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#702]
After a post in reddit by a confused user I had a look at our docs and the SensorValue.cs file and see that our docs are wrong.

The docs claim that all sensors have a suffix called :READOUT, and that it returns a varying type depending on the kind of sensor.

It's wrong on two counts:
1 - The suffix is actually called :DISPLAY.  There is no :READOUT suffix.
2 - and it's always a string, never a number.  (this also renders it utterly useless by the way, for most script purposes).

**Comment by erendrake** [comment]
1 sounds like a doc issue. 
2. sounds like a bug, we could attempt to parse the value?

**Comment by Dunbaratu** [comment]
Feel free.  I just listed the issue and moved on, based on seeing the user's comment asking why :READOUT wasn't working.

Are you ONLY able to get string values from KSP's API for it?  If so, then that's really lame.  The parsing of that would have to be rather smart because it sometimes changes units, I think.

**Comment by erendrake** [comment]
I forgot, they have the units in that value :P

**Comment by erendrake** [comment]
for 0.17 we can just change the docs.

**Comment by griderd** [comment]
Somewhat related to this, there are several other issues with the sensor documentation on the doc site, in this case specifically related to VesselSensors.

1. On the page Catalog of Bound Variables, SENSOR is listed as an alias for SHIP:SENSOR. Not only is there no such alias, there is no :SENSOR suffix attached to Vessel; only :SENSORS.

2. On the VesselSensors page, it lists VesselSensors:ACC as returning both the gravitational pull and the engine thrust. This is not currently correct. Only engine thrust is returned, and gravitational pull is ignored.

3. On the VesselSensors page, for VesselSensors:GRAV, it says that magnitude is expressed in "multiples of 9.802 m/s^2". The only problem there is that standard gravity is 9.0665 m/s^2, not 9.802. The value returned is correct, however.

**Comment by TDW89** [comment]
@griderd about point 2. sat on the launch pad I have a reading of 9.81m/s^2 from the gravioli detector and 0.995g from the accelerometer. This gives 9.81*0.995 = 9.76m/s^2 although i suspect there is a bit of error in that it is much closer to the 9.802 than 9.067.
