### ISSUE TITLE
A list of problems I found while testing a pre-release

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#727]
**Warning: I stopped updating this list!**
1. `edit` window does not get focus when invoked.
2. [closed] radial kOS unit is OP: smallest, lightest, biggest disk space. Was it intended to be like this?
3. on my old save on previously existed vehicle `edit` always edited 0.ks. Disappeared after quiting to main menu and reopening save. I'll probably try to reproduce this later.
4. del and backspace in console not displaying correctly #730 
5. printing a volume prints "structure" #731
6. [bug] [documentation] `volume:renameable` returns name of the volume. #747
7. running programs from inside functions #732
8. [closed] [kerboscript] [Ready To Merge] operators are not applied to a function's return value #733
9. disabling verbose logging shows "contact devs" on some exception types #735
10. `return` inside a `for` loop causes stack misalignment #756

**Comment by abenkovskii** [comment]
2) radial kOS unit is OP: smallest, lightest, biggest dick space. Was it intended to be like this?

**Comment by ZiwKerman** [comment]
2) we'll be rebalancing disk space on all cores

**Comment by Dunbaratu** [comment]
The idea was to make the radial unit a pinnacle part that is "more modern".  Thus smaller computer, but more capable.  It would be high on the tech tree in a career mode game.

**Comment by Dunbaratu** [comment]
> biggest dick space
you do seem to have this Freudian tendency to say that typo a lot.

**Comment by abenkovskii** [comment]
@Dunbaratu Oops. That unintended.

**Comment by Dunbaratu** [comment]
Don't worry about it.  I just thought it was funny.  If it bothers you , you can go back and edit your own comments by clicking the "pencil" icon.

**Comment by abenkovskii** [comment]
@Dunbaratu I'v edited #724 and #727. Now you'll probably want to update your comments.

**Comment by abenkovskii** [comment]
It looks like nobody is reading this issue. So I stop updating it.

**Comment by Dunbaratu** [comment]
It's not being read because it's too many different things for one issue.  You've split up the issue into separate issues, which is where the actual work gets done one thing at a time.  The only thing still left not mentioned in another issue is the edit keyboard focus item, which I'm not sure is worth working on when it works but it's just not intuitive.
