### ISSUE TITLE
Some strange bug with functions

### ISSUE THREAD

**Issue by ZiwKerman** [KSP-KOS/KOS#728]
See attached zip file with output log and scripts.

https://drive.google.com/file/d/0B9f5PHcywXQIMWZlTDlLV0xIZGM/view?usp=sharing

**Comment by ZiwKerman** [comment]
IMO it has something to do with creating a NODE object with local variables

**Comment by Dunbaratu** [comment]
If I remember your screenshot correctly from Slack, I think the part of the error log you included in the ZIP file is actually from the *second* follow-up error, not the original one that started the problem.

In your terminal window it showed an earlier error, saying "Values of Type System.String cannot have suffixes".  I suspect that's where it first went wrong, and then the error you're showing in the log is actually a side-effect of the first error breaking the state of things.  Can you show the part of the error log from the earlier error - the "System.String" error - and what the program dump looked like from that one?

**Comment by Dunbaratu** [comment]
It might still require an ugly re-run on my part to *really* get the debug data.  There's a variable inside  KOS/src/kOS/Execution/CPU.cs

Here:

```
        private bool ExecuteInstruction(ProgramContext context)
        {
            bool DEBUG_EACH_OPCODE = false;
            
```
Setting that to true instead enables an extremely verbose trace of each opcode as it happens (useful to find out if it jumped to the wrong place randomly).  Is it possible to re-run with that turned on and then get a copy of that whole log file from that run?  It would be very verbose but that's okay.  

I am about to be away, so I won't get any further on this until tomorrow.

**Comment by ZiwKerman** [comment]
This was actually solved with latest updates, as I cannot reproduce it anymore.
