### ISSUE TITLE
runing programs from inside functions

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#732]
![exception](https://cloud.githubusercontent.com/assets/11031560/6994641/d39a3936-db29-11e4-9aea-afa64ca1f758.png)
log: http://pastebin.com/Yie6RS6n

**Comment by abenkovskii** [comment]
![screenshot4](https://cloud.githubusercontent.com/assets/11031560/6994670/3b6812da-db2b-11e4-8ef5-fe146639a0b4.png)
and from a program it just does not invoke at all.

**Comment by Dunbaratu** [comment]
Hmm.... can you try again, but this time put empty parentheses on the function call both from interpreter and from program?

```hello1().```

```run_hello().```

I think that may be related to the bug, but this test would help prove if it was.

**Comment by abenkovskii** [comment]
From console: no difference
![screenshot1](https://cloud.githubusercontent.com/assets/11031560/6996007/ac663fe4-db75-11e4-9d1f-18ea4e0472a6.png)
From program: all the same
![screenshot3](https://cloud.githubusercontent.com/assets/11031560/6996022/821c2cf2-db76-11e4-876c-1d9ef00177a4.png)

**Comment by abenkovskii** [comment]
@Dunbaratu Thank you a lot! Now I'm finally able to merge my exec.ks and run_by_name_.ks into utils.ks.
P.S. I even thought of manually making a file _utils__exec.ksm that creates a function exec(command) when you import (`run`) it.
