### ISSUE TITLE
Unset all prevents run.

### ISSUE THREAD

**Issue by TDW89** [KSP-KOS/KOS#745]
When used in a script before a `run` command `unset all` causes the run command gives the error "Undefined Variable Name 'program-my_prog*'.

test script:
```
UNSET ALL.
RUN my_prog.
```
ps. unfortunately you cant take advantage of this to do `set 'program-my_prog*' to my_prog2` due to unexpected tokens `'` :-( .

**Comment by abenkovskii** [comment]
In the next version (0.17) `unset all.` is disabled and replaced with nested scoping. I'd say: close this issue, it is already solved. Just be patient and wait for 0.17 to come.
