### ISSUE TITLE
`volume:renameable` returns name of the volume.

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#747]
May be it was intended. But based on it's name someone might think that it returns a bool: "can this volume be renamed?".

**Comment by erendrake** [comment]
straight up bug, there is also the problem that i dont think we have documentation for the Volume structure.

**Comment by abenkovskii** [comment]
Nor a representation of a volume for `print` #731

**Comment by erendrake** [comment]
It's a fairly new structure that I did. Hence the lack of rigor in definition
