### ISSUE TITLE
Better keywords for global/local control (for locks but also vars)

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#750]
Proposal: The syntax is getting clunky for differentiating scope, and as I wish to add scoping to LOCK as well, it's getting needlessly verbose.

I propose this instead:

TO and IS synonyms:
----------------------------

We allow "TO" and "IS" to be the same: i.e. *declare x is 10* is the same as *declare x to 10*  This is needed for some of the changes below to keep things making gramattical sense:

We keep using "declare" only in a backward-compatibility sense.  We make the grammar allow it as an alternative extra keyword but prefer the use of "local".

DECLARE, LOCAL, GLOBAL:
----------------------------------------

Saying *declare local* : means you are making a variable local to current scope.  It's the same exact thing as saying just "declare" now does.

Saying *declare global* : means you are explicitly asking for a variable that lives at global scope *instead* of the current local scope.

Saying *local* only : means the same as *declare local*.  The word *declare* is entirely optional when "local" or "global" is used.

Saying *global* only : means the same as *declare global*.  The word *declare* is entirely optional when "local" or "global" is used.

Saying *declare* only : means the same as *declare local*.  The "local" is presumed when left off.

*set* : same as before - it stores in the first variable it can find when starting from localmost and going outward to globalmost, and if it finds none, then and only then does it make a variable, and it's global.

@LAZYGLOBAL:
-----------------------

Using *@LAZYGLOBAL OFF* now has a new meaning:  It still disallows *set* from implicitly making lazy globals, but it also disallows the use of saying *declare* only and having the "local" be presumed.  It now requires the use of either "global" or "local".  You can, however, leave the word "declare" off and just say "local" or just say "global".

PARAMETER:
-------------------

The word "parameter" can be left as-is now, dropping the "declare" if you like, but then like the cases above, an optional "declare" won't break anything.  You can say "declare parameter", "declare local parameter", or "local parameter", or just "parameter" and they are all the same, but the compiler will call it an error to say "global parameter" - parameters cannot be anything but local to where they are declared and saying otherwise is confusing.

FUNCTION:
----------------

The word "function" can be left as-is now, dropping the "declare" if you like, but an optional 'declare' is still allowed and won't break anything. You can say:
```
declare function foo {stuff}
```
or just
```
function foo {stuff}
```
and it means the same thing.

FILE SCOPING:
----------------------

At the moment, file scope and global scope are identical to each other.  With the new GLOBAL keyword, we could make file scope be its own indent level, and thus when declared in file scope, *local x is 1.* would be different from *global x is 1*.

Examples of valid lines of script using the above rules:
----------------------------------------------------------------------

The following would be equivalent and all valid:
```
local x is 0. // this is the version we'd encourage and people would probably prefer anyway.
local x to 0.
declare x to 0.
declare x is 0.
declare local x to 0.
declare local x is 0.
```

The following would be equivalent and all valid:
```
global x is 0. // this is the preferred way and the one people are more likely to use anyway.
global x to 0.
declare global x is 0.
declare global x to 0.
```

The following would be equivalent and all valid:
```
global lock foo to some_expression_here.
declare global lock foo to some_expression_here.
lock foo to some_expression_here. // only equivalent if there is not already a foo lock at some local scope.  Like set, it only makes a global one if there isn't one it finds to override already.
```

The following would be equivalent and all valid:
```
local lock foo to some_expression_here.
declare local lock foo to some_expression_here.
declare lock foo to some_expression_here.
```

The following would be equivalent and all valid:
```
declare parameter foo.
parameter foo.
local parameter foo.
declare local parameter foo.
```

The following would be disallowed:
```
global parameter foo.
declare global parameter foo.
```

### Not as complex to implement as it looks.

Despite how long it takes to explain all the possibilities in every detail, to *implement* this is really just a matter of changing the grammar file to allow the keywords to be optional, and making the compiler set some flags for the statement based on which keywords were actually present.

Why?
------

Issue #741 dealt with giving locks closures but didn't deal with the fact that all locks are global.  The effect is that when you make a lock, it's a lock forever.  Since they now have closures, that means they keep around the entire set of stacked variables in memory somewhere forever.
Consider the following:
```
// make g_list a list of 100 empty vectors:
set g_list to list().
set i to 0. until i >= 100 { g_list:add(v(0,0,0)). set i to i +1}.

declare function foo {
  declare a to 10.

  // make foo_list a local list of 100 empty vectors:
  declare foo_list to list().
  set i to 0. until i >= 100 { foo_list:add(v(0,0,0)). set i to i +1}.

  declare function bar {
    declare b to 20.

    // create a lock indented to be used in bar:
    lock l_bar to a+b.

    // make bar_list a local list of 100 empty vectors:
    declare bar_list to list().
    set i to 0. until i >= 100 { bar_list:add(v(0,0,0)). set i to i +1}.

    // ...Assume there's other code here, that uses the lock bar, and the bar_list and the foo_list .....
  }.
}.

foo().

// assume more code here for the rest of the program...

```
The problem with the
```
    lock l_bar to a+b.
```
being global is that even though it only uses A and B, it still keeps the entire scope alive in memory for both function bar and its containing function, function foo, and because it's global, it keeps that scope alive forever even after the function call foo() is long done.  So the two big lists of vectors (and whatever other locals may exist in foo() and bar() never really go away.  You can't reach them anymore - only l_bar can, but they still take up room in memory that cannot go away.

That's correct behavior for when you *need* that, like when doing a LOCK STEERING and it has to keep being capable of seeing those closure variables indefinitely until you LOCK STEERING to something else.

But there will be cases where you don't need it, and for them we need to provide users with the ability to make their locks local if they like.  Thus the impetus for this issue.

**Comment by Dunbaratu** [comment]
I'd really like this to be in 0.17.  I'm adding it to the punchlist so we don't forget it. Because it changes some syntax terms I think it should be there when we first release or it will be annoying (annoying to users to tell them later on in 0.17.1 that the syntax they just started using in 0.17.0 is already passe and frowned upon and only supported for backward compatibility.)

**Comment by Dunbaratu** [comment]
Edit: Based on a comment in the slack discussions:

If declare is optional for everything else it should become optional for "function as well, which the above description fails to mention.  As in:

```declare function foo { stuff }.```
and 
```function foo {stuff}.```
being identical in meaning.

**Comment by Dunbaratu** [comment]
Of all the stuff above, the one most significant I think is this one:

> FILE SCOPING:
> 
> At the moment, file scope and global scope are identical to each other. With the new GLOBAL keyword, we could make file scope be its own indent level, and thus when declared in file scope, local x is 1. would be different from global x is 1.

That's the one that takes the most "buy in".  SET X TO 1. would still be global as always , but DECLARE X TO 1. would now be local to file.  Since we're breaking DECLARE anyway in 0.17.0 (the "To val" part was previously nonexistent) I don't feel too bad about changing what it means too.

Why I propose this change and feel it may be necessary if we do all the other things is that otherwise it will be *very* confusing to a user that if you are at file-scope, outside any functions, and say:
```global x is 1.```
or say
```local x is 1.```
You are essentially saying the same exact thing.  If we change file scope to be local to file, then those end up being different as one would expect.

Also, making file scope be local would mean that the way functions work (not visible from the interpreter if declared in a script) would end up making much more sense because it would no longer clash with how variables work, which would start behaving the same way.

**Comment by erendrake** [comment]
How about local/global function? Sorry still reading if you answered this.

**Comment by erendrake** [comment]
alright, so if this is the contents of _foo.ks_

    function bar { //do stuff}.
    function fizz { //do stuff}.

and then my main program _main.ks_

    run foo.ks.
    fizz().

would that be legal, does the file scope block you from getting to fizz()?

**Comment by erendrake** [comment]
I think this is a fine plan. I am leery of using a useful keyword like _is_ as a strict synonym. No big deal :) lets do it!

**Comment by Dunbaratu** [comment]
> would that be legal, does the file scope block you from getting to fizz()?
Half true.  You are indeed blocked from getting to fizz from the interpreter, but at the moment the main reason is how memory space works and not how scoping works (which is why I don't want to implement the local/global keywords for functions - at the moment the keywords would be a lie.  all functions are effectively local right now.  We can work on fixing that later but it's not trivial so I'd like it to be post-0.17.0.  (It's about how global vars are shared between scripts and the interpreter, but nothing else is.  (Which is why reading a LOCK from the interpreter never worked even before my changes) Fixing that oddity would mean having to change how files are loaded and unloaded when run, and that' a bit more involved.)

I'm re-opening this because I was planning on using it as the issue that I'd attach to the PR later.  Leaving the issue open is the reminder that 0.17.0 isn't done yet until this is implemented.

**Comment by erendrake** [comment]
sweet, this is going to be great :)

**Comment by Dunbaratu** [comment]
This is now the only thing I work on until I get it working.  Anyone who wants to pick up some of those smaller documentation edits please feel free, even if you don't have the rendering suite installed.  We already know we have to run a check that detects RST syntax errors anyway because we already did a few changes without checking - so at this point adding a few more doesn't matter.

**Comment by TDW89** [comment]
Probably more effort than it's worth but what would it take to add a network key word? So ` Declare network ` declares a variable that can be seen by all cores on a vessel / maybe in load range but that bringing up other issues.

**Comment by Dunbaratu** [comment]
@TDW89, I don't like it thematically and I don't like how it would have to be implemented.  Thematically I'd rather support networking by doing some form of simple message queue - one program sends a variable to another cpu, and a program on the other cpu says "get next pending message" and reads the object.  Implementation-wise I don't like it because currently variables live inside a PartModule, of which there is one per Part.  Having two different parts share the same variable space means doing some odd moving around of data from where it lives now,

**Comment by Dunbaratu** [comment]
I'm splitting off the docs for this into a separate issue (sort of violating my own rule I know) just so that I can fix up the bugs first, get them in for others to play with, and make the docs a separate issue I can work on after this is merged in.

**Comment by erendrake** [comment]
im fine with it, we are stacking up a ton of doc tickets that others might be able to help with!
