### ISSUE TITLE
BUG - Revert to hangar, then launch causes crash.

### ISSUE THREAD

**Issue by Tabris83** [KSP-KOS/KOS#751]
running:
KSP 32bit
Win 7 64 (ultimate)

when running a kOS script the n reverting to either the launchpad or VAB then re-launching i get "log-spammed" by NRE
[here are the logs](https://gist.github.com/Tabris83/2ad1794c3a437f45e20e)

**Comment by erendrake** [comment]
oh joy. Thank you for your report!

**Comment by Dunbaratu** [comment]
The log you linked to, here:
https://gist.githubusercontent.com/Tabris83/2ad1794c3a437f45e20e/raw/output_log
Says "Error: blob too big" when I try to click on it to look at it.

**Comment by Tabris83** [comment]
[dropbox link to output_log](https://www.dropbox.com/s/66b9j3lt0cnsrhy/output_log.txt?dl=0)

**Comment by hvacengi** [comment]
Thanks for the updated link.  I was actually going to look into this very problem cause I found it in my RemoteTech save.  As near as I can tell, it's an issue with remote tech itself, but I haven't dug into it yet.  I will look into the issue and see what I can turn up.

**Comment by hvacengi** [comment]
As this error was fixed in RemoteTechnologiesGroup/RemoteTech#375, I'm going to close the issue.
