### ISSUE TITLE
stock toolbar button disappeared

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#752]
![screenshot2](https://cloud.githubusercontent.com/assets/11031560/7041641/c0d43ee8-dde3-11e4-8090-15a6e8b52070.png)
output_log: https://www.dropbox.com/s/yd6yze1l7iixg7x/output_log_button_disappeared.txt?dl=0
KSP.log: https://www.dropbox.com/s/z2zu8rbpw4z6ebp/KSP_button_disappeared.log?dl=0

**Comment by erendrake** [comment]
i assume that this was an upgraded install that was missing the new config for the blizzy toolbar integration?


[LOG 11:33:34.333] kOS: KOSToolBarWindow: Now making instance number 5 of KOSToolBarWindow
[LOG 11:33:37.111] kOS: KOSToolBarWindow: PROOF: OnGUI() was called at least once on instance number 5
[LOG 11:33:37.126] kOS: KOSToolBarWindow: Instance number 5 is trying to ready the hooks
[LOG 11:33:37.129] kOS: KOSToolBarWindow: Instance number 5 will now actually make its hooks
[EXC 11:33:37.133] KeyNotFoundException: The given key was not present in the dictionary.
	System.Collections.Generic.Dictionary`2[kOS.Suffixed.Config+PropId,kOS.Suffixed.ConfigKey].get_Item (PropId key)
	kOS.Suffixed.Config.GetPropValue[Boolean] (PropId id)
	kOS.Suffixed.Config.get_UseBlizzyToolbarOnly ()
	kOS.Screen.KOSToolBarWindow.RunWhenReady ()
	EventVoid.Fire ()
	ApplicationLauncher.OnSceneLoaded (GameScenes scene)
	EventData`1[GameScenes].Fire (GameScenes data)
	HighLogic+.MoveNext ()

this is a pretty suspicious log entry

**Comment by Dunbaratu** [comment]
Did this get fixed by the KOSToolbarWindow re-work by @ZiwKerman ?

**Comment by erendrake** [comment]
This is merged now.

**Comment by abenkovskii** [comment]
@erendrake I'll try compiling it myself this time

**Comment by ZiwKerman** [comment]
Solved and merged, can be closed.
