### ISSUE TITLE
[proposal] a way to copy a file in the same volume

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#754]
```
make copy of "my_file" as "some_other_name".
```

**Comment by krisdestruction** [comment]
`copy blah as blah_copy.` works as well too

**Comment by krisdestruction** [comment]
That way you can use the same command with different parameters

**Comment by abenkovskii** [comment]
to: @krisdestruction 
@hvacengi already suggested `copy ... [to ...] [as ...]` in #760
