### ISSUE TITLE
List files in does not return a list of type fileinfo. (for Archive)

### ISSUE THREAD

**Issue by TDW89** [KSP-KOS/KOS#757]
`List files in` does not return a list of type fileinfo.
Either that or the suffixes are not working.
```
list files in filelist.
for files in filelist {
print file:name. //or any of the other file info suffixes.
}.
```
gives a suffix not found error.

Not sure if this is a separate issue as so will mention it here and create another one if necessary.
Found the above when trying to protect against running files that didn't exist. Something else I tried was this:
```
clearscreen.
log "" to my_prog.ks. //create a file with known name
list files in fileList.
print "fileList:contains(''my_prog.ks'')".
print fileList:contains("my_prog.ks").
print "".
set index to fileList:iterator.
index:next.
until index:atend {
 if index:value = "my_prog.ks" {
  print "Step through found file at item: " +index:index.
 }.
 index:next.
}.
```
this will tell you that the list doesn't contain a known file and then find it for you anyway. This only happens with files and I was unsure about creating another issue if it is a symptom of the above.

**Comment by abenkovskii** [comment]
@TDW89 
1. I didn't notice that the documentation says it should be a list of FileInfo. It is a bug than.
2. I also didn't know that there is a contains(item) suffix for lists.

**Comment by abenkovskii** [comment]
@TDW89 2. that's wierd. a list does not `:contains` an item it contains. It might be case-sensitive because kOS's `List:contains()` just calls `C#'s List.contains()`. Try it with lists of strings, add `print fileList.`.
Is `"string" = "StRiNg"` true in kOS?

**Comment by TDW89** [comment]
@abenkovskii From the [listinfo docs](http://ksp-kos.github.io/KOS_DOC/structures/misc/fileinfo.html#file-information) "You can obtain a list of values of type FileInfo using the LIST FILES command." Since you can't do anything (script wise) with the info printed strait to the terminal I took this to mean use `list files in`. Tried `list files:names in foo.` too, that also failed.

The reason `list:contains()` does not find it is because it is looking for a string an the list elements are not strings.
```
for item in fileList { foo:add(item).}. print foo:contains("my_prog.ks").       //False.
for item in fileList { foo:add(item+"").}. print foo:contains("my_prog.ks").  //True.
```

To the best of my knowledge kOS is mostly case insensitive. I say mostly because it actually just uses lower case for everything. This distinction is only relevant for files stored on the archive if your OS file system is case sensitive eg. on linux a file called TEST.ks is impossible to run and will give file not found errors whatever you put in the terminal.

**Comment by abenkovskii** [comment]
@TDW89 not strings and not FileInfo? That's really weird.

**Comment by erendrake** [comment]
@TDW89 do we have an issue for TEST.ks not working? i have to admit to not having a linux test box

**Comment by TDW89** [comment]
@erendrake there is now #762 I didn't really think of it as a bug when I found it as I assumed anyone that encountered it would be using linux and probably only take them a second or two to realise what was going on. + it is probably a bit much to expect kOS to try every variation of upper and lower case to find a file.

**Comment by beltorak** [comment]
It does return a list of FileInfo structs if not run from the archive. When run from the archive it seems to return a list of strings.

The return values of `:filetype` are not quite correct. For `z_run.ks` it returned `ks`.

**Comment by akrasuski1** [comment]
Not sure if it is connected issue, but the :modified and :created suffixes don't work for me even from local volume. They throw "GET Suffix "CREATED" not found on object test.ks". Other ones are okay (:size, :name, :filetype).

**Comment by abenkovskii** [comment]
@akrasuski1 I'll probably take a look at it after investigating this: https://github.com/KSP-KOS/KOS/issues/951

**Comment by abenkovskii** [comment]
0. I ended up doing both researchers parallelly
1. Yes. There are no such suffixes as `:CREATED` and `:MODIFIED` in fileinfo: https://github.com/KSP-KOS/KOS/blob/6b7d217b11dfed690da105d369083d1a1da1c220/src/kOS.Safe/Encapsulation/FileInfo.cs#L32
2. It's a different issue.

**Comment by akrasuski1** [comment]
I'll open a new issue then.

**Comment by abenkovskii** [comment]
`List files in bar.` actually returns FileInfo. But it doesn't generate suffixes for it. [This constructor](https://github.com/KSP-KOS/KOS/blob/develop/src/kOS.Safe/Encapsulation/FileInfo.cs#L39) should call `InitializeSuffixes()` too. I'll make a fix PR.
