### ISSUE TITLE
[proposal] boot options

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#758]
1. It would be nice to have an ability to change what boot file is used on an already launched vessel.
2. This would be especially useful if you implement an ability to change boot file from program (a command like `setboot to "new_boot_file_name".`).
3. It also looks like there is no way to change boot slider in the VAB back to unset after you set a boot file.
P.S. I know that the first two could be done now by creating a boot.ks that just runs another program and editing the boot file to change what program will run next time you load your craft.

**Comment by erendrake** [comment]
1. Not a bad idea. we could show the selector as soon as you have more than one 'boot' file on the local volume. Lets make a separate enchancement issue for it in the back log. 
2. we would also need the ability to list the available boot files as part of this. lets make this a separate enhancement issue.
3. I noticed this bug a few days ago, lets make a bug ticket for it.

**Comment by abenkovskii** [comment]
@erendrake I'll split this issue into 3 then.

**Comment by ZiwKerman** [comment]
@erendrake: re 2) this is buried quite deep into CPU.cs, I don't think it's worth spending time on.

But I agree that there should be an option to set boot file no "None" in VAB/SPH

**Comment by ZiwKerman** [comment]
re 1) the only way to change bootfile is to overwrite the file itself, unless we change the system completely (and I don't think it's worth doing it as very few people actually use that)

Most questions arise because this feature was not documented properly, but there are docs now in place (at least they were in the PR alongside with UI changes).
