### ISSUE TITLE
kOS Processors are separate "virtual processes"

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#764]
If I understand it right kOS does something like:
```
each "frame"
for each cpu in active_cpu
    process up to n instructions
```
But than each CPU is a virtual process (they are executed in one process, but influence each other like if they were a separate processes)
They have separate code segment, stack and dynamic memory, but share the vessel control and the file system access.
Imagine a situation where one core logs some commands into a file and the other executes this file. What will happen if the user expects several lines to be logged to this file before it gets executed and than the second CPU runs the file in the middle of a change (leaving unclosed function body for example)?

**Comment by TDW89** [comment]
You change the volume names temporally with the scrip to prevent it. eg:
```
Rename 1 to "writing".
log "stuff" to message.
log"more stuff" to message.
Rename 1 to "read message".
```
then the other core wait for a volume called "read message" to exist.
Action groups are also a possibility as they are shared. (if agX is true then file is in read state if false then it is being edited).

**Comment by erendrake** [comment]
i agree with @TDW89, i wrote a long post that was talking about file locking features, but that is going to be just as cumbersome as the solutions that TDW89 is talking about.

**Comment by TDW89** [comment]
I know this is closed but.
possibility 3:
2 files
core 1 does this:
```
log "everything you want" to file1.
log "delete file2." to file1.
log "" to file2. // no need for file 2 to actually contain anything its existence just being used as a cross core trigger.
```
then on the other core:
```
until success {
 list files in temp.
 set fileList to list().
 for item in temp {
  fileList:add(item+"").
 }.
 temp:clear.
 if fileList:contains("file2.ks") {
  set success to true.
  run file1. 
 }.
}.
```

**Comment by abenkovskii** [comment]
@TDW89 
You are already iterating over a list of all files using kOS's `for`. Why not just compare file to what you are looking for in this loop? This works for me:
```
declare parameter search_file.
list files in files.
set result to false.
for file in files {
  if file = search_file {
    set result to true.
  }
}
```

**Comment by abenkovskii** [comment]
@erendrake Is there any documentation and examples on the main documentation site about this feature?

**Comment by abenkovskii** [comment]
@TDW89
1. About the third solution: this will only help if the second core is desired to read (execute) the file only once after each change.
2. Solutions where the first core both sets and clears some "flag" are not safe:
```
// core 2:
do some important stuff
wait till flag is not set // ends immediately because core 1 didn't set it yet
// core 2 ipu limit reached
// core 1:
do even more important stuff
set flag
start editing the file
// core 1 ipu limit reached
// core 2:
run the file // and here it breaks
```
3. I'm trying to implement "get_current_volume_number"
It works by creating a dummy file and than searching for this file in each volume.
But then how to make running get_current_volume_number on multiple cores safe?

**Comment by TDW89** [comment]
@abenkovskii the doubling up of iterations was my bad, it was late and I had been working with / around the whole list:contains not working with files issue so that was the first thing that came to mind.

1. yep fair enough that script would only work if the file was intend to be run once, but it wouldn’t be to much to change it to do more.

2. um yep thought of that that's why core 1 doesn't both create and clear the flag. It logs the command to clear the flag to the file so that on running it the first thing core 2 does is delete the flag. I will admit though that there is nothing to prevent further edits to the file while the flag exists. But that could be protected against in the same way as core 2 is pretested against running it when the flag doesn’t exist.

Is your script is trying to standardise volume names for all cores on a vessel? If so we are working on the same problem. I'll let you know if i get anything working.

**Comment by abenkovskii** [comment]
@TDW89 No I'm trying to create a way of saving and restoring the volume selection. If a subprogram changes current volume by `switch to` it would be nice haw a way to switch back to the volume that was selected before invocation when leaving the subprogram. The only easy way is to always `switch to 1` but it potentially can cause a lot of problems if you forget about this side effect or if the subprogram is called from trigger, because the trigger can interrupt execution of the main program at any point (if I understand it correctly).

**Comment by abenkovskii** [comment]
@TDW89 What kind of name "standardization" you are truing to do? If I find it useful I might help you writing it.

**Comment by TDW89** [comment]
I am trying to leave a file in each volume called my_uid.ks as a way of linking volumes with parts. That way i can name volumes after tags and make create scripts that can identify which stage a volume is in when loading large amounts of script (eg. the script will know to put the landing programs in the volume for the cpu on the lander)

**Comment by erendrake** [comment]
@TDW89 would you mind sending me an email at erendrake@gmail.com? i would like to ask you some questions.

**Comment by TDW89** [comment]
@erendrake e-mail sent

**Comment by abenkovskii** [comment]
@TDW89 Why do you need multiprocessing for it? Just choose one core, and set it's boot file to something like this (pseudo code):
```
for each part
    if a part has a module kOSProcessor
        for each volume
            create a dummy file
               if the file is created in the current part (free space is reduced)
                   congratulations! you found a volume to part link!
```

**Comment by TDW89** [comment]
@abenkovskii because free space isn't reflected by the part information. It's not in the right click menu (that is total space) and it is not a resource so I have found no way of connecting them like that. That said I may have missed something.

note:
the small one can be linked by toggling its lights on and off to find it but that doesn’t work for the larger ones (or anything that has had it added via module manager)

**Comment by abenkovskii** [comment]
@TDW89 I thought there is a way of getting space left but it turns out I was wrong.
@erendrake Are parts in the parts and volumes except the volume 1 listed in the same order?

**Comment by abenkovskii** [comment]
@TDW89 try `run on` command: #775. It does not work (fails silently == without exception) if the part is unpowered. Caution: make sure not to unpower the part where your script is running.
