### ISSUE TITLE
Weird issue with generating random booleans.

### ISSUE THREAD

**Issue by clanehin** [KSP-KOS/KOS#766]
print random(0,1) < 0.5.

Correctly renders "true" or "false". However . . .

set x to random(0,1) < 0.5.

Yields: Cannot cast from source type to destination type.

May or may not be related to #765 if the issue is a weird value being left on the stack.

**Comment by Dunbaratu** [comment]
I'm going to call this a duplicate of issue #765 and close it.  (We're having a hard time managing the sudden influx of new reports coming in faster than we've had before.)
