### ISSUE TITLE
Integrated solar panel in the radial kOS unit is facing wrong direction

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#770]
I see a solar panel no the texture of radial kOS part but it works not how someone would expect it to work.
![screenshot6](https://cloud.githubusercontent.com/assets/11031560/7066251/6a3cd34c-dec9-11e4-895a-7223b1b81dc2.png)
The sun is in the zenith so the part on top should generate power and the panel on the side should not. However It is working in exactly opposite way to how it should.

**Comment by Dunbaratu** [comment]
Is this something we could fix quickly for 0.17 or would it require a complex model re-work? I think, based on guesswork, that it's this in the Part.cfg that defines which way the sun has to hit the panel for it to work:
```
  raycastTransformName = suncatcher
```
And changing that probably means changing the model itself.  I hope not but I could be wrong.

**Comment by erendrake** [comment]
@pgodd do you still have the files you used to build the part? it would be nice to be able to have them in the repo if you are willing.

**Comment by pgodd** [comment]
Working on it today. I think its an easy fix.

**Comment by pgodd** [comment]
Hmmmm. Not so easy. The coordinate system is screwing with me.
