### ISSUE TITLE
[documentation] run <file_name> on <volume_number> is not documented

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#775]
I while looking though your source code i found a [Function("run")] that takes two arguments: volume number and program. Also: normal `run` command compiles into "if first time call build and than call compiled program". So I tried `run hello on 2.` and it worked for all volumes except the archive. After some testing I figured out that it runs a script on the part associated with that volume.

**Comment by Dunbaratu** [comment]
It's not documented because marianoapp had never quite gotten it working fully before he left the project.
The problem with the archive is such a case.

**Comment by abenkovskii** [comment]
@TDW89 `run on` gives you the ability to run multiple programs on the same "core". They are other kind of "virtual processes" because they have separate stacks, code segments and dynamic memory.

**Comment by austinjames314** [comment]
If this actually works, it could be just what I'm looking for, but as it's undocumented, I'm a bit wary.

I want to have a rocket where the launcher has it's own CPU, controlling ascent and de-orbit of the final stage, and the payload has it's own CPU. I've been trying to figure out how to signal to the payload vessel that it's been released to it's own devices, and that it should start doing stuff.

Is running a boot script on the payload CPU going to work? On of the things I read made it seem like the script is actually run on the CPU of the part executing the run command. I'm going to have a quick look through the source now, but any help would be appreciated.

**Comment by austinjames314** [comment]
OK, _if_ I'm reading this right, it does in fact run the given script on the given CPU. Is that right?

https://github.com/KSP-KOS/KOS/blob/develop/src/kOS/InterProcessor/ProcessorManager.cs#L37-42

Apparently one potential pitfall is that if the target CPU is powered off then there will be no error. (it'd be nice if the run function returned something depending on whether it was successful.) I'm going to start using this tomorrow and see how it goes.

**Comment by abenkovskii** [comment]
@austinjames314 It looks like `run on` recomplies the file you run. I'm going to try reimplement my lib_exec using it and see if it works.

**Comment by abenkovskii** [comment]
@austinjames314 `run on` was never fully implemented. It sort of works but has a lot of special cases where it behaves  in a really strange way. I think it will work fine for what you need. Though I didn't tested it enough to be more than 61.5% sure about it. You may also try `wait until ship:name <> ...` in boot or wait for an action group or wait for a name tag change (`wait until ship:rootpart:tag <> ...`).

**Comment by tomekpiotrowski** [comment]
In recent discussions we have mentioned that this feature could be dropped. We can achieve a similar effect now by setting the other processor's boot file and then activating it. Could we close this then?

**Comment by hvacengi** [comment]
We should also remove the broken functionally from the load/run functions.
