### ISSUE TITLE
Malicious kOS scripts

### ISSUE THREAD

**Issue by TDW89** [KSP-KOS/KOS#778]
oooh this is fun i can `log "stuff that is not a script" to "/log/koslog.txt".` (log folder needs to exist first so can only be done on the archive). hadn't thought of doing that before.

**Comment by abenkovskii** [comment]
You can create, edit, copy, rename and delete any file as long as you are able to make a string expression that evaluates to your file's name. But `run` command is special. You can only run something that is a valid but unset identifier. And the first character of any identifier must be a letter (not a digit). It all is in the [documentation](http://ksp-kos.github.io/KOS_DOC/language/syntax.html). It's not a bug, it is how it is supposed to work. This limitations allow to optimize sequences of `run` calls for the same file by parsing this file only once.
P.S.
1. Although according to the doc identifier shouldn't start with an underscore, in my experience identifiers with leading underscore are working fine both for programs and for variables
2. I never tested identifiers with dot inside but for `run` dot is ok (`run hello.ksm`).
3. In almost every language identifiers starting with digit are forbidden to avoid collision with number literals.

**Comment by TDW89** [comment]
I was looking in the wrong place in the documentation for that. (was looking at the rules surrounding run not the syntax section).

oooh this is fun i can `log "stuff that is not a script" to "/log/koslog.txt".` (log folder needs to exist first so can only be done on the archive). hadn't thought of doing that before.

**Comment by Dunbaratu** [comment]
Does that actually allow you to escape from the KSP directory and go to root?  It's not supposed to allow that.  If it does there's a bug.

**Comment by TDW89** [comment]
um i think it only allows me to go down the file system not up will check though.

**Comment by TDW89** [comment]
nope at least `log "run for it" to "~/Desktop/escapee.ks".` doesn't work.

**Comment by NoPanShabuShabu** [comment]
Yes you can.  
  log "This is a test" to "/../../../../NVIDIA/koslog4.txt"
Handily made me a file in "C:/NVIDIA/".  The only thing stopping me from writing elsewhere were file permissions.

**Comment by TDW89** [comment]
confirmed on linux too. @NoPanShabuShabu does the `%UserProfile%` short cut work with this and windows? `$HOME` does not work for linux.
also I Imagen this could get interesting with:
```
log "something interesting" in "/../../../../ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\kOS.bat".
```
what are the permissions on the windows start-up folder?

**Comment by Dunbaratu** [comment]
Does anyone know if .NET has an equivalent to the UNIX chroot() ?
That would be the proper secure way to deal with this.  (the reason I care about the security is the potential for collaboration over telnet).

**Comment by TDW89** [comment]
ok anyone want to try `delete "/../../KSP.x86.exe".` (don't do it it works).

**Comment by abenkovskii** [comment]
@TDW89 I'd recommend renaming this issue to "malicious kOS scripts".
It is also a great idea not to discuss security breaches in public posts.

**Comment by abenkovskii** [comment]
@TDW89 It is very confusing that the first post in "malicious kOS scripts" is about something unrelated to the main discussion.
P.S, Removed my post about numbers and identifiers.

**Comment by Dunbaratu** [comment]
The simplest solution is to just deny all filenames containing any '\' or '/'.  But I sort of wanted to allow the ability to descend DOWN into a subdirectory - just not up into a parent directory.

So how about: 

  * Can't contain colon anywhere (to stop things like "C:\"
  * Can't contain two consecutive dots '..' anywhere.
  * Cannot begin with a '\', or '/', but is allowed to have one elsewhere (for subfolders).

Would that cover all the cases?

**Comment by abenkovskii** [comment]
In my view it's an awful idea to use string operations with file names unless you are implementing a module for path manipulation.
If I were you I'd used something like this:
```
// pseudo code:
bool is_safe (file_name):
  path = file_name.normalize()
  result = false
  while path.has_parent() and not result:
    path = path.parent()
    result = path.same_path(scripts_folder)
  return result
```
This will solve the problem for all the file systems without leaving any special cases behind.
P.S. I'm sure C# has it's own module for working with file names.

**Comment by Dunbaratu** [comment]
Hmm it should be possible to get the full-path equivalent name from an API call, and then walk it to see if it contains the intended 'chroot' or not.  But I would worry about legitimate cases where someone has installed KSP under a symbolic link path, which they should be allowed to do, but asking the OS for the "real" name causes it to tell you about the hard path instead of the soft path, and therefore it always claims to be an illegal folder.

**Comment by abenkovskii** [comment]
What if you normalize both file_name and scripts_folder?

**Comment by erendrake** [comment]
We can get the a  bunch of path definitions of any file before we write to it. Maybe at runtime we could find the absolute path of the script folder. Then when we are about to modify a file we check that that file has an absolute path that starts with the script path we found before. 

I don't know if this would work for people who have symlinked in a subfolder. That being said I don't want us to spend all week on this for something that might not be needed. We do need to address the "virus" potential

**Comment by abenkovskii** [comment]
I think that a proper fix will be to implement a virtual file system with root under scripts folder in the real file system. It will also abstract out the differences in the path parsing in different OS.
