### ISSUE TITLE
We need to be able to switch to a Volume represented by a volume structure

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#789]
When I have a volume structure I can do `switch to volume:name.` but it only works fine if all my volumes have unique names (@erendrake, it is the third "not implemented yet" feature I was talking about).

**Comment by abenkovskii** [comment]
Alternatively we can make this possible:
```
list volumes in v_list.
switch to v_list[3].
```

**Comment by hvacengi** [comment]
I'm actually planning some modifications to volumes already to make them more "part" friendly.  I'll see if I can add an index suffix or something like that.

**Comment by hvacengi** [comment]
I take it back... getting that index into the volume structure will be really tough on two fronts.  

First, the volume struct currently resides in the kOS.Safe namespace, and has no direct access to the KSP specific information.  This could possibly be moved, but it would need a lot of testing and care to make sure nothing got broken in the process.  It's fairly integral to the rest of the persistence logic, which is also under the kOS.Safe namespace.

Second, volume instances are shared across processor instances.  That means that the volume object that is index 0 for one processor may be the exact same object for another processor.  I was considering adding a field to the volume class which would hold that index number, but it would only be right for one processor (whichever processor last set the index field).

What we can do fairly easily though is add a field that contains the uid of the part attached to the volume.  Then we would just need make a method to get the volume based on uid (and maybe a volume count) to be able to work with that list however you wanted (for instance, a quasi dictionary).

**Comment by abenkovskii** [comment]
[VolumeManager.SwitchTo](https://github.com/KSP-KOS/KOS/blob/develop/src/kOS.Safe/Persistence/VolumeManager.cs#L125) actually takes a Volume as an argument so my second idea should be easy to implement.
