### ISSUE TITLE
PRINT RESOURCE

### ISSUE THREAD

**Issue by krisdestruction** [KSP-KOS/KOS#799]
According to the alias shortcuts chart, the command should print the amount of liquid fuel on the spacecraft.
        PRINT LIQUIDFUEL.

The expected output should be the same value as:
        PRINT SHIP:LIQUIDFUEL.

Either the documentation is wrong or the execution of the code is wrong.

Tutorial wiki link.
http://ksp-kos.github.io/KOS_DOC/bindings.html

**Comment by space-is-hard** [comment]
Can you clarify what's happening with each and how it deviates from the documentation?

**Comment by krisdestruction** [comment]
If I recall, it errors out when I use that line of code. I will post a screenshot when I get home.

**Comment by krisdestruction** [comment]
Error screenshot. First command is the unexpected output. The second command is the expected output.
http://i.imgur.com/7hMQvyq.jpg

The alias shortcuts for SHIP fields section states that "Any resource" is the same as "Same as SHIP:resourcename, eg. LIQUIDFUEL is the same as SHIP:LIQUIDFUEL". Thus "print liquidfuel." should have the same output as "print ship:liquidfuel.".

**Comment by Dunbaratu** [comment]
That line of the table needs to be removed.  it is incorrect.

**Comment by abenkovskii** [comment]
The PR is merged. Is there a reason to keep this issue open?

**Comment by Dunbaratu** [comment]
old merged issue - never got closed.
