### ISSUE TITLE
[Enhancement] String ASCII value comparison. 

### ISSUE THREAD

**Issue by TDW89** [KSP-KOS/KOS#803]
Mostly for use in creating/searching lists of stings.
ASCII as oposed to just alphabetical so that both of these work:
```
If "a" < "b" { print True.}.
If "a0" < "a1" { print True.}.
```

**Comment by abenkovskii** [comment]
BTW the [current implementation](https://github.com/KSP-KOS/KOS/blob/develop/src/kOS.Safe/Compilation/Calculator.cs#L371) of string comparison (except `=` and `<>` operators) just compares string's length. Is this behaviour intentional?

**Comment by abenkovskii** [comment]
Newer issue: #1006

**Comment by TDW89** [comment]
string comparison now exists
