### ISSUE TITLE
[bug] pause menu doesn't displays correctly while name tag editing window is opened

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#805]
1. open name tag window
2. unfocus it and press escape.
3. screenshot:
![screenshot1](https://cloud.githubusercontent.com/assets/11031560/7143151/79638462-e2e6-11e4-960f-d0c42c7d7621.png)

**Comment by Dunbaratu** [comment]
After I changed the window ID for fixing #718 I can no longer reproduce this problem.
After I make the PR and it's merged, can you try this again and see if it's fixed?

**Comment by Dunbaratu** [comment]
Associated with PR #826

**Comment by abenkovskii** [comment]
Solved in PR #826
