### ISSUE TITLE
Third bug with name tag window: it remains open when you leave a scene but looses all it's buttons

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#806]
This prevents me from altering name tags until I reload a game.
![screenshot2](https://cloud.githubusercontent.com/assets/11031560/7143282/38ef0342-e2e7-11e4-9190-c58ac1835763.png)
log: https://www.dropbox.com/s/5on5kqe0giu971k/output_log_tag_window_broken.txt?dl=0

**Comment by abenkovskii** [comment]
Also: a pause menu disappears completely when this appears.

**Comment by Dunbaratu** [comment]
I'm ging to look at these after all the problems with scoping are done.  I think they can be fixed by just catching a bunch of events and closing the nametag window when they happen.

**Comment by Dunbaratu** [comment]
Okay the fix is to listen for part destruction events (which also covers part unloading when scene changing) and remove the nametag window when the part it's meant for goes away.

**Comment by Dunbaratu** [comment]
Associated with PR #826
