### ISSUE TITLE
[can't be fixed][documentation] omitting parentheses in function call only works if a function is defined in the same file

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#811]
I know that it can't be fixed.
What we can do about it:
1. either document it
2. or don't tell our users that they can omit  parentheses
```
// library.ks
function foo
{
  return 42.
}
```
```
// main.ks
run library.
print foo. // error
```
```
// main.ks
run library.
print foo(). // fine
```
```
// main.ks
function foo
{
  return 42.
}
print foo. // fine
```

**Comment by Dunbaratu** [comment]
I preference is to label the lack of parentheses as a backward compatibility thing only, and encourage that they get used from now on (make sure we edit our example programs in the docs to reflect this).  Document the fact that they only work for locks and functions within the same file.

**Comment by abenkovskii** [comment]
@Dunbaratu Yes I also think think that is the right way to solve it. Could you add a "documentation" label than?

**Comment by Dunbaratu** [comment]
Given that locks between programs never worked before *at all*, I don't feel bad at all about saying that now they only work with parentheses.

**Comment by Dunbaratu** [comment]
Close when #821 is merged.
