### ISSUE TITLE
Developer Docs

### ISSUE THREAD

**Issue by ondono** [KSP-KOS/KOS#830]
I've been looking around, trying to figure out how all works. I was thinking that I'm probably not the only one, and that it would be very helpful to have some kind of technical/developer documentation, even if it's  not complete or partially out-dated.

I was planing on doing something on that front, but I wanted to ask first for ideas/tips/etc..

**Comment by ZiwKerman** [comment]
Do you want to contribute to mod's development?

**Comment by ondono** [comment]
I want to try at least :P

**Comment by ZiwKerman** [comment]
Is the email on your github profile operational?

**Comment by ondono** [comment]
yes

**Comment by alanrburns** [comment]
Hi It would be nice to have some compile instructions.
I have looked everywhere in this repo and I can't find anything.
I it suppose to be a secrete?

**Comment by erendrake** [comment]
It's not a secret. 

1. Install Visual Studio 
2. Download repo 
3. Open the kos.sln file
4. Build it

Each step is well documented on the World Wide Web. I didn't think to document them here

**Comment by ZiwKerman** [comment]
You beat me to it :)

**Comment by alanrburns** [comment]
Um so I need Windows?

**Comment by ZiwKerman** [comment]
You can use MonoDevelop too

**Comment by ZiwKerman** [comment]
I use both - Xamarin (monodevelop) on my mac and VS2013 on my PC

**Comment by ZiwKerman** [comment]
http://wiki.kerbalspaceprogram.com/wiki/Setting_up_MonoDevelop

**Comment by alanrburns** [comment]
@erendrake  I usually compile the software I use from source and they all have the process documented. Thanks for the details..

**Comment by alanrburns** [comment]
So I have monodevelop and referenced csharp and unity but it is asking for  NUnit.Framework
Do you guys seriously have no documentation for this process?
I honestly can not believe that you guys want to explane this every time someone wants to test your code

**Comment by ZiwKerman** [comment]
We usually don't have to explain. NUnit framework is not our dependency afaik

**Comment by alanrburns** [comment]
Okay so I got it to build without any errors.. then what?
I didn't notice any packages being created...

**Comment by ZiwKerman** [comment]
Building creates KOS.dll and KOS.Safe.dll in your default build directory (usually inside src/kOS/bin/)

What are you trying to achieve? Help develop kOS or just build a version of it for yourself? If it's the latter then you better download an existing release first, and see what is there apart from those 2 dlls.

**Comment by alanrburns** [comment]
I have played with 0.16 but I really want to try out the function in v0.17.
So all I want to do for now if get it running..

All I can find is src/kOS/bin/Debug/kOS.Safe.dll

**Comment by ZiwKerman** [comment]
Inside information: 0.17 will be released in less than 24 hours, you may as well just wait for it.

Try Build All option in Xamarin
![screen shot 2015-04-16 at 14 28 52](https://cloud.githubusercontent.com/assets/11242352/7181791/0d9ff9da-e445-11e4-9a47-fefd90d8f355.png)

**Comment by alanrburns** [comment]
When I build all I get 9 errors..

![kos safe test - clampsetsuffixtest cs - monodevelop_002](https://cloud.githubusercontent.com/assets/1893377/7181947/46d74bb0-e4a2-11e4-8e7e-23893b12e6b1.png)

**Comment by ZiwKerman** [comment]
Try building just kOS project, you should get the kOS.dll

**Comment by alanrburns** [comment]
These are the only dll files created 
./src/kOS/bin/Debug/kOS.Safe.dll
./src/kOS.Safe/bin/Debug/kOS.Safe.dll
./src/kOS.Safe.Test/bin/Debug/kOS.Safe.dll

**Comment by Dunbaratu** [comment]
If you say it's giving 9 *errors* but show the window scrolled so that only the *warnings* are showing in the screenshot, it's not very helpful.

**Comment by ZiwKerman** [comment]
![screen shot 2015-04-16 at 15 09 29](https://cloud.githubusercontent.com/assets/11242352/7182635/a0715966-e44a-11e4-812d-21ef63c8cf05.png)

Please Post what you see in you References for KOS, KOS Safe and KOS.Safe.Test - example above

**Comment by Dunbaratu** [comment]
Some of the undocumented stuff about how to build it is because they're steps that are presumed  obvious to the community of modders who have built a KSP mod before, but are not so obvious to anyone outside that community.

One thing that you can encounter in the UNIX world, that generally doesn't happen much in the Windows world, are people who prefer to build every software package they install, from the sources, even when they don't intend to actually edit the source code or be a developer.  (There are a variety of reasons for this, one of which is to make sure you get native executable machine language that's optimized to your exact setup, rather than a one-size-fits-all lowest common denominator executable you'd get with a binary-only release, but with how .NET DLL's work, that's largely a moot point.  They're not *really* native anyway.)

But the point is that for someone coming from that world, having no "how do you compile this" documentation seems weird.  They grow to expect that as a minimum.

**Comment by alanrburns** [comment]
@Dunbaratu  most of the software I use I compile from source in command line none are in mono.
And all the projects have the basics even if it is just 
./configure 
make 
make install

But if there is one thing I know it's devs are arrogant and will always make excuses not to document something.

**Comment by alanrburns** [comment]
Looks like KSPAPIExtensions is a dependency. 
https://github.com/Swamp-Ig/KSPAPIExtensions/releases

If this was documented nobodies time would have been wasted. 
But I guess the almighty devs know better..

**Comment by erendrake** [comment]
@alanrburns

**Comment by Dunbaratu** [comment]
You are correct that it needs to be documented better.

You are incorrect in your decision to lie about the motivations of why, and project your own arrogance onto others.

In other words, do I think it's a good idea to document the build instructions better? yes - for OTHER people who need it, not for you.  Will I do it to help YOU, specifically?  No, not after you kept on lying like that.  I was on your side until you chose to be a liar like that.

In this case the squeaky wheel does not get the grease.  The squeaky wheel gets ignored.

And if you continue to insist on lying and refuse to own up to it, remember the thread can just be deleted.

**Comment by Dunbaratu** [comment]
We've always known we needed better build instructions for new developers.  But not for this guy.  Don't let his arrogance cloud our judgement on that.  We should still add it soon - I'm just in no hurry to do it for HIM.  Maybe after 0.17 is out.

**Comment by erendrake** [comment]
I do agree, one of the reason i havent spent the time to document it was the fact that my particular preference in IDEs handles many of the issues that others might have. So i havent felt the pressing need for it. 

We should at least document what our external dependencies are and give a short description on where to get them.
