### ISSUE TITLE
[Enhancement] A state field in the core right click menu

### ISSUE THREAD

**Issue by TDW89** [KSP-KOS/KOS#831]
Since it's not possible to tell the current state of a core from within a script would it be possible to have a field in the right click menu for it?
so it could be discovered with `:getfield("State").`.
Useful states could include:
"off"  - the core is shut down.
"starved" - the core has no power.
"idle" - the power is on but no scripts are running.
"busy" - the power is on and the core is running script.

**Comment by hvacengi** [comment]
This information was added to the kOSProcessor type in PR #1195 (documentation here: http://ksp-kos.github.io/KOS_DOC/structures/vessels/kosprocessor.html ).  Does that fulfill your need, or do you still think that a field is necessary for the status?

**Comment by TDW89** [comment]
yep that works (sorry didn't notice your comment until now)

**Comment by hvacengi** [comment]
Don't worry, I forgot that we had this sitting out there.  Anything that closes issues is a good thing in my book.
