### ISSUE TITLE
POSITIONAT() only works on other vessels that have previously been selected as target.

### ISSUE THREAD

**Issue by kaufman-bryce** [KSP-KOS/KOS#834]
I have three vessels in orbit: kCom 1, kCom 2, and kCom 3.
Attempting to use `POSITIONAT` to get the location of any non-active vessel with any value for time returns a null reference exception.

However, if I first `SET TARGET TO vessel("kCom 1")`, I can suddenly read it's values for the rest of the flight scene even if I un-target it later. kCom 2 will continue to fail until it is targeted as well. Upon scene reload the problem returns until I perform the sacred target-dance again.

This is all being done from the interpreter. I get the same results from a script, other than that I need to make sure I wait a brief moment each time I set the target to make sure KSP actually registers the target change.

I have reproduced this on a clean install with only kOS. I have checked against vessels that are both inside and outside physics loading range, both exhibit the same behavior.

[KSP.log](http://pastebin.com/F5d2NJVr)

Steps to reproduce:
1. Have two or more vessels.
2. `print POSITIONAT(vessel("name"),time).` where the vessel chosen is not the active vessel.
3. `Object reference not set to an instance of an object` 
4. `set target to vessel("name").` then repeat step 2.
5. Receive an actual position vector.

**Comment by Dunbaratu** [comment]
Note to self - further bug report:  I get this even when the vessel IS the target.

The exception is this:
```
print positionat( vessel("Simple space launcher"), time:seconds+100).
                                                               ^

(Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)
System.NullReferenceException: Object reference not set to an instance of an object
  at kOS.Suffixed.VesselTarget.GetOrbitAtUT (Double desiredUT) [0x00000] in <filename unknown>:0 
  at kOS.Suffixed.VesselTarget.GetPositionAtUT (kOS.Suffixed.TimeSpan timeStamp) [0x00000] in <filename unknown>:0 
  at kOS.Function.FunctionPositionAt.Execute (kOS.SharedObjects shared) [0x00000] in <filename unknown>:0 
  at kOS.Function.FunctionManager.CallFunction (System.String functionName) [0x00000] in <filename unknown>:0 
  at kOS.Execution.CPU.CallBuiltinFunction (System.String functionName) [0x00000] in <filename unknown>:0 
  at kOS.Safe.Compilation.OpcodeCall.Execute (ICpu cpu) [0x00000] in <filename unknown>:0 
  at kOS.Execution.CPU.ExecuteInstruction (IProgramContext context) [0x00000] in <filename unknown>:0 
 ```

**Comment by Dunbaratu** [comment]
Ah crud.  It looks as if only Vessels that are loaded properly have a ``Vessel.patchedConicSolver`` on them.  Unloaded "distant' vessels have no patchedConicSolver, as far as I can see, and that's the problem.

**Comment by abenkovskii** [comment]
And how KSP displays all vessels in the map view without this information?

**Comment by Dunbaratu** [comment]
It doesn't use patchedConicSolver for on-rails vessels.  If it's on rails then it's just an orbit object.  The patchedConicSolver is for objects who's path is composed of more than one elliptical patch (i.e. objects undergoing encounters with other bodies, or with manuever nodes).  

But the code doesn't seem to have a catch for this - it doesn't protect itself against the case where patcedConicSolver returns null (until now I didn't realize that it did return null).  It only uses patchedConicSolver for manuever node predictions.  It should check for if it's null and if it is then just fall down into the same code it would normally run if it was present but reported no encounters or maneuvers.

It's fixable.  But not tonight.  I'm done for the evening.

BTW: 1.0 is expected in the next 24 hours.  That may delay things as I'll want to try playing it for a little bit.

**Comment by Dunbaratu** [comment]
Oops I closed it too soon.  I didn't see that the PR wasn't merged yet.
