### ISSUE TITLE
Update ckan with dependencies 

### ISSUE THREAD

**Issue by erendrake** [KSP-KOS/KOS#839]
https://github.com/KSP-KOS/KOS/blob/develop/Resources/GameData/kOS/kOS.ckan

we have a new external dependency in KSPAPIExtensions

And a new suggestion in AGX

**Comment by TDW89** [comment]
Can suggest alarm clock now too.

**Comment by ZiwKerman** [comment]
Not a dependency, but we can put them into recommended list

**Comment by Dunbaratu** [comment]
already done ages ago?  This must have been from an old release.
