### ISSUE TITLE
Add docs about tweakable disk space PR #654

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#840]
This PR doesn't seem to have anything about it in the docs pages that I could find.  
Let's push this out to 0.17.1.  UI features like this aren't as important to document because people can find them with trial-and-error.  But still, the effect it has on your mass and cost should be described.

**Comment by ZiwKerman** [comment]
Where in the docs you want me to put it?

**Comment by Dunbaratu** [comment]
It's a good question.  I don't really think there's a good area for things that exist entirely inside the user interface.  Maybe adjacent to where the KOSToolBarWindow is documented, with its screenshot.
