### ISSUE TITLE
[documentation] mod function from "math" module doesn't actually follow "mathematical" defenition of modulo

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#847]
In mathematics modulo is always positive. But in C#, kOS and a bunch of other languages the result of modulo operation has the same sign as dividend. It is normal but it should be documented properly. I'll make a PR about that soon.
P.S. In some other languages the result of modulo operation has the same sign as divisor.

**Comment by abenkovskii** [comment]
```
print mod(7, 2). // 1
print mod(-7, 2). // -1
```

**Comment by Dunbaratu** [comment]
closed with no followup?

**Comment by abenkovskii** [comment]
@Dunbaratu Am I missing something? I thought it is merged and there is no reason to keep it open. Am I wrong?

**Comment by Dunbaratu** [comment]
Sorry I'm sleepy - I didn't notice it was already merged.  We've been fighting with video editing software.

**Comment by Dunbaratu** [comment]
Yeah I did, but in a rather indirect way.
I went through and collected all the small one-liner doc fixes and pulled them into my branch so I could gen the docs, then pushed my branch back to get all the small fixes merged in.  I hadn't noticed that this was one of them.
