### ISSUE TITLE
running an empty file restarts the main program

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#858]
Only works when you run an empty file from inside another program:
```
// main.ks
print "program started".
log "" to empty_file.
delete empty_file.
log "" to empty_file.
print "next line will implicitly restart your program".
run empty_file.
```
The code above prints:
```
program started
next line will implicitly restart your program
program started
next line will implicitly restart your program
program started
next line will implicitly restart your program
program started
next line will implicitly restart your program
program started
next line will implicitly restart your program
...
```
Possible cause: load() returns 0 when parsing an empty file.

**Comment by Dunbaratu** [comment]
Hmm.  Yeah that's the problem.  The grammar produced by TinyPg technically considers nothingness to be a valid utterance, so no syntax error exceptions are raised.  (Something has to *exist* for it to be wrong).

I suppose we can alter the compiler to throw exception when the parse tree is empty.

**Comment by krisdestruction** [comment]
Well the expected behaviour should be that it doesn't run the file and continues on the main program. What if you're loading/running a data file or something....

**Comment by Dunbaratu** [comment]
I'd say the expected behavior should be that it *does* run the file, but the contents of the file are nothing more than to do nothing and return.

**Comment by erendrake** [comment]
I agree with dunbaratu.

**Comment by Dunbaratu** [comment]
I think the problem is that the compiler inserts the EOP instruction as the last step of visiting a START node.  When there are no statements, there isn't even a START node in the parse tree (I think) so the program ends up being a list of opcodes... containing zero opcodes.

**Comment by krisdestruction** [comment]
@Dunbaratu Sorry yes that's what I meant :)
