### ISSUE TITLE
Feature request: Manual telnet control

### ISSUE THREAD

**Issue by eschoenawa** [KSP-KOS/KOS#859]
I was working on an android app to control a vessel some time ago (I paused it since I am a bit stressed these days) and I was able to archieve some successes. However, it would be a lot more easier if we had some kind of manual telnet control. To be exact I was thinking of some way to turn off the automatic transmission of the terminal over the telnet server and some methods to send and recieve data from the telnet connection. Or maybe even the possibility to setup another, independent telnet server inside the program.

**Comment by krisdestruction** [comment]
What if you update the terminal's first N lines with data with a program and simply make your app read it?  There's a way to make it overwrite using positions in the terminal screen. Then simply apply commands to the ship using the terminal.

**Comment by eschoenawa** [comment]
I've done it that way until now but I also wanted to be able to continue to display user friendly information on the actual terminal. Since this is meant to become some kind of mission control using two operators, one in the craft and one "remote".

**Comment by Dunbaratu** [comment]
I'm not certain I understand this one.  Can you elaborate?

**Comment by eschoenawa** [comment]
Well, it is some kind of roleplaying thing. One Operator on the ground and one pilot actually in the craft. Both have to get different and userfriendly readouts from the craft (for example, the operator might be looking at the fuel (or something actually useful, I can't think of a better example atm because I'm a bit sleepy :D) while the pilot is docking, using the terminal as a docking UI). Now it would be easier for me to accomplish that if I could manually send telnet commands (or something the native java server-client system can use, I am not that good with telnet).

**Comment by erendrake** [comment]
@eschoenawa so you want to be able to completely control the contents of the terminal from an outside script? why not just do it with kerboscript?

**Comment by eschoenawa** [comment]
@erendrake as I mentioned: some sort of roleplay: two pilots. I want multiple pages of data to be displayed for each pilot seperatly. I know it doesn't make a lot of sense efficiency-wise but it would be interesting. Also the seperate telnet control would make remote controllers a tiny bit easier.

**Comment by TDW89** [comment]
@eschoenawa have you considered just using 2 cores? 1 for the pilot the other for the controller via telnet?

**Comment by eschoenawa** [comment]
@TDW89 Oh... I really should have thought about that :'D Thank you for that ;) However, I would like keep my suggestion for the native Java Client-Server Communication as that would make stuff easier for the android app. If you want I'll put that in a seperate issue.

**Comment by Dunbaratu** [comment]
I still don't understand what was being asked for here.

**Comment by Dunbaratu** [comment]
I wish I had a label that means "huh?"

**Comment by eschoenawa** [comment]
Okay, it has been some time since I've asked this and sadly my studying doesn't give me time to do a lot with kOS or KSP in general, but I see that I wasn't very clear about what I was looking for, which was another way other than telnet to send commands to kOS and data from kOS over a network. Like send and read methods.
