### ISSUE TITLE
In release version of kOS 0.17 list constructor with arguments doesn't work

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#867]
![screenshot0](https://cloud.githubusercontent.com/assets/11031560/7219274/b42df6a0-e6a0-11e4-9531-8b9853172f36.png)

**Comment by abenkovskii** [comment]
Same for kerbalstuff version

**Comment by abenkovskii** [comment]
It's true for CKAN, kerbalstuff and curse versions.

**Comment by abenkovskii** [comment]
Works fine in version I compiled myself from develop brunch.

**Comment by Dunbaratu** [comment]
Yeah the code is definitely there in develop.  I don' know what happened.

**Comment by erendrake** [comment]
It never made it to master apparently. I'll have to release again. It shouldn't take long

**Comment by Dunbaratu** [comment]
0.17.1 fixes this.
