### ISSUE TITLE
Documentation error: LOCK LOCAL instead of LOCAL LOCK

### ISSUE THREAD

**Issue by kaufman-bryce** [KSP-KOS/KOS#869]
On the [Variables and Statements](http://ksp-kos.github.io/KOS_DOC/language/variables.html#local-lock) page, the docs say the syntax for local locks is `LOCK LOCAL` identifier `TO` expression, when it should say `LOCAL LOCK`.

**Comment by Dunbaratu** [comment]
PR #870
