### ISSUE TITLE
No way to get string length, or not specified in documentation

### ISSUE THREAD

**Issue by Zyt3x** [KSP-KOS/KOS#872]
Couldn't find any information in /doc/source/language/features.html about getting length of a string?

I'm guessing this functionality doesn't exist? It'd also be nice to have some string manipulation functions like trim, replicate, etc :)

**Comment by erendrake** [comment]
@Zyt3x is it actually one of the features we want to tackle next. 

https://github.com/KSP-KOS/KOS/issues/270

**Comment by Zyt3x** [comment]
Thanks! I should have looked through the open issues first.. :+1:

**Comment by erendrake** [comment]
all good, we will count it as another 'vote' for the feature :)
