### ISSUE TITLE
CI Version checking

### ISSUE THREAD

**Issue by erendrake** [KSP-KOS/KOS#875]
Right now we have many places we have to touch in order to update the 'version' of the mod
- .net project assembly info
- KVC file https://github.com/KSP-KOS/KOS/blob/develop/Resources/GameData/kOS/kOS.version
- docs https://github.com/KSP-KOS/KOS/commit/bb5fea365670c11e17e0f3030dc2a19aee1b1a81

~~\* Core.cs https://github.com/KSP-KOS/KOS/blob/develop/src/kOS/Core.cs~~

we should either reduce the number of touches or fail the build if these are different

**Comment by JonnyOThan** [comment]
https://github.com/KSP-KOS/KOS/commit/1ea5b1faa37f4f1beb2b61412454f054cc5edf03 should handle the assemblyinfo and .version files.  Still need to work on docs...but maybe I'll file a separate issue for that.
