### ISSUE TITLE
[renamed title] Misleading error message trying to run a file that is not found.  Catch the case and make a better message.

### ISSUE THREAD

**Issue by zlsa** [KSP-KOS/KOS#876]
That error is thrown on the line of the "run" command with lib_pid and its example, both unmodified and in the root "Scripts" directory.

kOS version 0.17.0.0, KSP version 0.90.

**Comment by Dunbaratu** [comment]
Can you post a dump of the output log?

**Comment by zlsa** [comment]
[LOG 07:52:39.520] kOS: At example_pid on 1, line 25
    run lib_PID.
    ^
    
    [LOG 07:52:39.520] System.NullReferenceException: Object reference not set to an instance of an object
      at kOS.Function.FunctionLoad.Execute (kOS.SharedObjects shared) [0x00000] in <filename unknown>:0 
      at kOS.Function.FunctionManager.CallFunction (System.String functionName) [0x00000] in <filename unknown>:0 
      at kOS.Execution.CPU.CallBuiltinFunction (System.String functionName) [0x00000] in <filename unknown>:0 
      at kOS.Safe.Compilation.OpcodeCall.Execute (ICpu cpu) [0x00000] in <filename unknown>:0 
      at kOS.Execution.CPU.ExecuteInstruction (kOS.Execution.ProgramContext context) [0x00000] in <filename unknown>:0 
    [LOG 07:52:39.521] Code Fragment
    File                 Line:Col IP   opcode operand
    ----                 ----:--- ---- --------------------- 
    1/example_pid          30:49  0155 push $old-ag4 
    1/example_pid          30:49  0156 push $ag4 
    1/example_pid          30:49  0157 store 
    1/example_pid          30:49  0158 push $remove-on--642319354 
    1/example_pid          30:49  0159 br.false 3 
    1/example_pid          30:49  0160 push 137 
    1/example_pid          30:49  0161 removetrigger 
    1/example_pid          30:49  0162 EOF 
    1/example_pid          25:1   0163 push $program-lib_pid* 
    1/example_pid          25:1   0164 push 0 
    1/example_pid          25:1   0165 eq 
    1/example_pid          25:1   0166 br.false 8 
    1/example_pid          25:1   0167 push $program-lib_pid* 
    1/example_pid          25:1   0168 push $<argstart> 
    1/example_pid          25:1   0169 push lib_pid 
    1/example_pid          25:1   0170 push null 
    1/example_pid          25:1   0171 call load() <<--INSTRUCTION POINTER--
    1/example_pid          25:1   0172 pop 
    1/example_pid          25:1   0173 store 
    1/example_pid          25:1   0174 call $program-lib_pid* 
    1/example_pid          25:1   0175 pop 
    1/example_pid          25:1   0176 push 0 
    1/example_pid          25:1   0177 return 
    1/example_pid          54:1   0178 push $throttle* 
    1/example_pid          54:1   0179 push 52 
    1/example_pid          54:1   0180 store 
    1/example_pid          25:1   0181 push $program-lib_pid* 
    1/example_pid          25:1   0182 push 0 
    1/example_pid          25:1   0183 store 
    1/example_pid           2:1   0184 push $display_block* 
    1/example_pid           2:1   0185 push 1 
    1/example_pid           2:1   0186 store 
    1/example_pid           2:1   0187 push $<argstart> 

    [LOG 07:52:39.522] kOS: Stack dump: stackPointer = 3
    004      SubroutineContext: {CameFromInstPtr 271}
    003 SP-> $program-lib_pid*
    002      $<argstart>
    001      $<argstart>
    000      0
    
    [LOG 07:52:39.522] kOS: Popping context 2
    [LOG 07:52:39.523] kOS: Removed Context File                 Line:Col IP   opcode operand

![2015-04-20-07-54-27-am](https://cloud.githubusercontent.com/assets/6366062/7232842/a4d97a66-e732-11e4-92f2-ab237c966263.png)

**Comment by abenkovskii** [comment]
Trying to reproduce it now.

**Comment by abenkovskii** [comment]
Can't confirm. Flies fine.
KSP 0.90
kOS 0.17.0 (downloaded via CKAN)
For @Dunbaratu it is **not** a dev build.
![screenshot0](https://cloud.githubusercontent.com/assets/11031560/7236475/dd94f946-e79d-11e4-9215-a2aa2113760a.png)

**Comment by abenkovskii** [comment]
@zlsa 
Are you sure that happens in Stock + kOS, Without other mods?
It looks like you have a **lot** of mods. It might just be "not enough RAM" exception which in C# is indistinguishable from "null reference".
questions to find out if my guess is right:
0) Is it happening in "stock" to?
1) are you using 32-bit or 64-bit version of KSP?
2) how much RAM do you actually have?
3) install this: http://forum.kerbalspaceprogram.com/threads/92907 and tell us your memory usage
P.S.
After testing is done check out these mods to reduce memory usage:
1) http://forum.kerbalspaceprogram.com/threads/59005-0-90-Release-4-3-Dec-16-2014-Active-Texture-Management-Save-RAM!
2) http://forum.kerbalspaceprogram.com/threads/101309-Script-AutoPruner-v1-1-Prune-those-parts-that-suck-up-your-RAM!-(2015-018)

**Comment by zlsa** [comment]
I found out what the problem was (PEBKAC). Sorry for wasting everybody's time... it turns out you have to `copy lib_pid from 0.` I would have known that if I had ever tried to use multiple kOS files.

It does happen in Stock + kOS. I have more than enough memory + swap for KSP (4+8GB), and I'm using 64-bit KSP. I am using ATM, but I didn't have to.

Thanks to everybody...

**Comment by Dunbaratu** [comment]
Hang on a second... are you saying the *real* error was that the file "lib_pid.ks" was not found on the current volume?

Because if that's true then there's still a problem here, which is merely that that's a massively misleading error message.  We should be presenting some sort of "file not found" error in that case.

**Comment by erendrake** [comment]
I am going to reopen this issue because we should be able to give a much better exception for this

**Comment by zlsa** [comment]
Yes, I run from the ship volume and copy over the files I need, then run them. I assumed that the `run` command would also copy files over, but in hindsight it would have no idea where to copy them from.

**Comment by abenkovskii** [comment]
@Dunbaratu @erendrake Can confirm now: only happens when running a nonexistent script from another script (not from console).
