### ISSUE TITLE
Warping to a specific time is kind of a pain in the butt.

### ISSUE THREAD

**Issue by erendrake** [KSP-KOS/KOS#882]
right now whenever i warp it kinda turns into a bunch of code for ramping up to the warp speed i want and then ramping back down as the time gets near. It seems like we could make it just a little easier by adding something to the effect of.

    WarpTo(<Time>, *OnUpdateFunction).
    // *OnUpdateFunction would be mostly used for display updating.

This could be a simple core library function except for the fact that we do not have function pointers. I only used the * syntax to try and make it clear what i was getting at. I dont know that establishing * as a deref symbol is the design i would want.

**Comment by abenkovskii** [comment]
KAC integration works to.

**Comment by erendrake** [comment]
@abenkovskii you are right, that would be a pretty good way to do this. it might be a good example of how to use KAC

**Comment by erendrake** [comment]
Apparently there is work in the API to enable this so we should be able to leverage that rather than having it in the standard library
