### ISSUE TITLE
A few enhancement requests

### ISSUE THREAD

**Issue by mileshatem** [KSP-KOS/KOS#889]
I'll list them all here for now, but if you'd like I can submit separate issues for each. Also, apologies of some of these have been previously requested, I did a quick search and didn't find anything similar.

1. Add a REPLACE suffix for lists which would do as it sounds. Current workaround I know of is doing a list:REMOVE(i). list:insert(i, newdata). which isn't so bad, but the replace would be nice.

2. Add a suffix to engines that is a list of what fuels it requires (e.g. eng:FUELS ) 

3. Add a suffix to resources that returns the density

4. Capability to read in an external text file as a list where each line in the file is read in as a string in a list.

5. Ability to use negative values to index backwards from the end of a list.

**Comment by Dunbaratu** [comment]
1. REPLACE:  is there a reason that mylist[i] = newdata doesn't work for your needs?

**Comment by abenkovskii** [comment]
4. I'd like this to. But it has not much use until string operations are implemented.

**Comment by abenkovskii** [comment]
3) the average density of all the resources in the part can be calculated from it's mass, dry mass and the amount of resources. A nice idea for a standard library function. Though the ability to request a density of the specific resource can probably be useful to.
Can you give me an example when you need to know the resource density.

**Comment by mileshatem** [comment]
> 1. REPLACE: is there a reason that mylist[i] = newdata doesn't work for your needs?

Nope, that'll do. Brain fart on my part. Sorry.

> 4 I'd like this to. But it has not much use until string operations are implemented.

Agreed, the particular use case that had me submit the issue wouldn't require string ops (reading the last x lines of log file to print to a scrolling list on screen) but I have another way to do that and I can see how many other users wouldn't want file reading without string ops

> Can you give me an example when you need to know the resource density.

If it's not obvious by some of my other requests, I'm trying to write a generic deltaV calculator. Because I want it to work with all mods including realfuels/realism overhaul there's a chance that tanks containing fuel don't only contain fuel (e.g. service module parts). So if I just use mass - dry mass then I might be including food/water/electricity/leadballast/etc. as propellant mass. So I need the mass of each resource in the tank and asking for capability to list densities seemed like the easier option. If it's easier for you guys though, adding a :MASS suffix to a part's resources would be just as useful to me as  :DENSITY would be. 

Now that I'm thinking more about resources and fuels though, I think my request for eng:FUELS might not cover everything. There's the probability that I'd need to know the fuel flow rates for each resource as well (both maximum and current?). I know you can get the fuel flow rate from an engine, but this is just a single number of the total units/s of any fuel that the engine is consuming. The reason to know the individual fuel flow rates would be if the fuel tanks don't contain the exact mix ratio required by the engines (think spaceplanes where you carry some extra liquidfuel to cover atmospheric flight or realfuels/realism overhaul where engine mixes change all over the place)
