### ISSUE TITLE
Can't copy scripts from the terminal

### ISSUE THREAD

**Issue by austinjames314** [KSP-KOS/KOS#890]
Running on 0.17.1, I'm unable to copy files (except boot.ks):

![screenshot15](https://cloud.githubusercontent.com/assets/788349/7248854/327f4ca0-e86a-11e4-856a-5a81a46a6f43.png)

I found a bunch of exceptions being thrown in the log file. I've kept the whole file if needed, but here is what seems to be the relevant part: http://pastebin.com/R5CZZL6s

**Comment by Dunbaratu** [comment]
You are using a local volume that only has 2500 bytes on it, of which 202 is used up.  lib_pid won't quite fit in the tiny space left.  When there's not enough space to store the destination, you get the cryptic "File copy failed".  (That needs fixing - there needs to be more descriptive different messages there for the different reasons for failure).
