### ISSUE TITLE
[refactoring] What are `batch` and `deploy`  key words for?

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#893]
It looks like a program containing them can't be complied.
https://github.com/KSP-KOS/KOS/blob/7706d36fe8f563ea9c9cd7da9c775b4239c0ebd6/src/kOS.Safe/Compilation/KS/Compiler.cs#L2660
Why are we keeping them in kOS if they are unused?

**Comment by Dunbaratu** [comment]
No idea what they're for.  They were there all along before I joined the project.

**Comment by erendrake** [comment]
They were added with the RT integration, I have never tried them and they should be removed.

**Comment by Dunbaratu** [comment]
I'll assign myself, since it deals with compiler stuff which is where I'm usually sticking my hands in it.
