### ISSUE TITLE
Telenet - Can't remote edit a file.

### ISSUE THREAD

**Issue by Bear67** [KSP-KOS/KOS#899]
You can type in "Edit filename.", but nothing happens on the putty side. But the Filename is opened in KSP.
![screenshot_1](https://cloud.githubusercontent.com/assets/5138687/7339091/9c8dc714-ec27-11e4-84af-b9c935231705.jpg)

**Comment by abenkovskii** [comment]
Telenet clients probably have no interface to edit files. You'll have to use external text editor to edit files in the archive. I use atom https://atom.io/
P.S. In case you don't know: archive is located in <your_ksp_folder>\Ships\Script

**Comment by Dunbaratu** [comment]
I'd call this a sort of 'duplicate' of #698 - in the sense that the editor being unusable via telnet is one of the many reasons to revamp the text editor, and the fact that it doesn't work in telnet is one of the things that was brought up in the discussion of that issue.

I'm going to close as duplicate for that reason.
