### ISSUE TITLE
funny error message when trying to use ETA:

### ISSUE THREAD

**Issue by erendrake** [KSP-KOS/KOS#905]
https://youtu.be/4B2rEDrqw40?t=7m

    set someNode:ETA to ETA:periapsis.

sets the ETA then bails with an NRE

**Comment by Korvar** [comment]
I'm the guy who made the video: here is the code that I use:

```C#

// Circularise from Apoapsis using maths

// Calculate the desired orbital velocity at apoapsis for this body.

set desiredV to sqrt(ship:body:mu / (ship:obt:apoapsis + ship:body:radius)).

print desiredV.

set currentV to velocityat(ship, time + eta:apoapsis):orbit:mag.

print currentV.

set nodeDV to  desiredV - currentV.

print nodeDV.

SET newNode TO NODE(0,0,0,0).

set newNode:ETA TO ETA:apoapsis.

add newNode.
set newNode:prograde to nodeDV.

run calcISP.

run exNode(isp).

```
It also happens if I issue the command on the command line.

    set someNode:ETA to ETA:periapsis.

**Comment by Korvar** [comment]
Similarly:
    set somenode to node(0,0,0,0).
    set somenode:eta to 100.

This errors out, but still sets the ETA correctly.

**Comment by abenkovskii** [comment]
Confirmed: this throws NRE:
```
set somenode to node(0,0,0,0).
set somenode:eta to 100.
```
But this works fine:
```
set somenode to node(0,0,0,0).
add somenode.
set somenode:eta to 100.
```

**Comment by Dunbaratu** [comment]
Eyeballing the code, this looks like a common problem with all the node's suffixes, not just ETA.  Most of the ``node`` suffix setters unconditionally try to call:
```
 ToNodeRef();
```
after changing the value, which is a method that maps the kOS Node object's fields into their matched meaning in the associated KSP maneuver node that's been associated with it.

If no KSP manuever node has been associated with the kOS Node (if the ``add`` command hasn't happened), ``ToNodeRef()`` doesn't protect itself against this possibility and it just blindly tries to do it anyway.

**Comment by Dunbaratu** [comment]
AT least I think that's the problem.  This isn't code I've touched before but just from a quick glance that looks like it might be it.  I'd rather not be the one to fix it, so I can stay in the area of the underlying virtual machine, but I just thought I'd mention it for whomever picks this up and runs with it.

**Comment by abenkovskii** [comment]
I can try fixing it.
