### ISSUE TITLE
document new ETA and ALT objects???

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#932]
Pull request #931 contained new suffix structures ETA and ALT.  They were not documented because they were an under-the-hood refactor to simulate the old "fake" ETA and ALT objects.  Do we want to promote them to the level of user-documented objects or just leave them as they are as behind the scenes trickery for backward comaptibilty?

**Comment by abenkovskii** [comment]
What makes ETA and ALT different from other structures? All other structures are documented.

**Comment by erendrake** [comment]
I agree, we should document them.

**Comment by xeger** [comment]
Saying that ETA only remains for backward compatibility, seems to imply that it's deprecated and that there's a more palatable way to obtain these values. If that's true, then the docs should at least point people toward the right way to do things.
