### ISSUE TITLE
Broken link or missing documentation on Engine:ISP

### ISSUE THREAD

**Issue by aznoohwee** [KSP-KOS/KOS#945]
http://ksp-kos.github.io/KOS_DOC/structures/vessels/engine.html#structure:ENGINE

Under the description for ISP and VACUUMISP the link for the description is broken.

The description currently links to http://ksp-kos.github.io/KOS_DOC/structures/vessels/isp

**Comment by erendrake** [comment]
@aznoohwee thank you for finding that.
