### ISSUE TITLE
STAGE:SOLIDFUEL returns 360 not 0 once booster is empty in KSP 1.0.2

### ISSUE THREAD

**Issue by aznoohwee** [KSP-KOS/KOS#946]
KSP 1.0.2 update broke my booster staging logic.  STAGE:SOLIDFUEL now returns 360 once solid fuel is depleted.

**Comment by erendrake** [comment]
blarg :P thank you for the report

**Comment by aznoohwee** [comment]
I think I figured out what is going on.

This is my problematic code:

````
// Calculates the amount of fuel left in stage.  If we have boosters, use that value first.
FUNCTION fuelInStage
{
  local qty TO 0.0.
  local booster_present TO false.

  if STAGE:SOLIDFUEL > 0 { set qty TO qty + STAGE:SOLIDFUEL. set booster_present TO true. }
  if not booster_present { set qty TO qty + STAGE:LIQUIDFUEL. }
  
  print qty.
  
  //if booster_present and qty < 0.1 or qty = 360 { set qty to 0.0. }
  if booster_present and qty < 0.1 { set qty to 0.0. }
  
  return qty.
}
````
In versions previous to KSP 1.0.2 when a solid booster was empty the quantity was not actually 0 (more like .05).  KSP 1.0.2 fixes this and once solid fuel is depleted my booster_present flag is not set and therefore only the current fuel in the stage is returned.

I think the other part of the confusion is that the KOS "STAGE" variable does not match up directly with the staging setup in the game.  That is STAGE:LIQUIDFUEL returns a non-zero value, even if we are only powered by boosters in the current KSP stage.

The fix here is to use a global for booster_present and reset it after we stage().

**Comment by abenkovskii** [comment]
@aznoohwee  @erendrake 

> That is STAGE:LIQUIDFUEL returns a non-zero value, even if we are only powered by boosters in the current KSP stage.

Is it a desired behaviour?

**Comment by abenkovskii** [comment]
Probably the same problem: #513.

**Comment by erendrake** [comment]
#513 is annoying. And this is certainly related
