### ISSUE TITLE
[bug][able to reproduce] kOS toolbar window appearing in Space Center scene

### ISSUE THREAD

**Issue by space-is-hard** [KSP-KOS/KOS#951]
Steps to reproduce:
* Go to space center scene
* Open any one of the following: Astronaut Center, R&D Center, Mission Control, Admin Building
* Exit back to space center scene
* Open any one of the above buildings again (doesn't have to be same building)
* Exit back to space center scene again
* Toolbar window should now be open despite not having its icon in the toolbar

**Comment by space-is-hard** [comment]
I know we'll be adding the toolbar icon to the toolbar in the space center scene which will allow the player to close the incorrectly-displayed window, but have we figured out why it's displaying in the first place?

**Comment by abenkovskii** [comment]
I probably found the cause. I'll try fixing it.
