### ISSUE TITLE
[bug] Strange error message after "program aborted"

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#958]
![screenshot0](https://cloud.githubusercontent.com/assets/11031560/7450168/6dee3cd0-f24a-11e4-813f-c5127a4e7f06.png)

**Comment by liasdf** [comment]
i've seen similar on aborting with ctrl c. for me it was always a for loop variable. i tried to make something to reproduce it, maybe i did but i'm not sure.

set foo to list(1,2,3).
for f in foo{wait 60.}

run that and ctrl c, and it will give an argument out of range on parameter index. i don't know the code at all, but it wouldn't surprise me if the ctrl c stuff is....hairy.

i think it'd be fair to just leave it. if i ctrl c i don't care about doing anything cleanly -- just stop running now please, and it does that. if i want to do it cleanly, 'on abort' works nicely.

**Comment by abenkovskii** [comment]
1. Every bug is a bug.
2. Sometimes digging into one bug helps to find another.
3. I agree though that this bug is a "low priority" bug.

**Comment by abenkovskii** [comment]
It's probably the same bug: #735.

**Comment by Dunbaratu** [comment]
it is the same as #735.
