### ISSUE TITLE
KR-2042 b Scriptable Control System attachment bug

### ISSUE THREAD

**Issue by Skyla** [KSP-KOS/KOS#960]
The bottom attachment node (in default orientation) for the KR-2042 b Scriptable Control System appears to be non-functional. The top node attaches fine, however the bottom node will not attach even if the part is flipped, rotated, or any other change to orientation is made.

I suspect this problem is a result of the part not being able to handle the new directional nodes properly.

This issue is not present in the CX-4181 Scriptable Control System, which as far as I can tell is handling attachment logic properly.

**Comment by abenkovskii** [comment]
It is already fixed (in development version): https://github.com/erendrake/KOS/commit/6bb74671e0f5ef41d76b724032c64521b78be521. You may wait for the next kOS release or manually change your .cfg file.

**Comment by abenkovskii** [comment]
@erendrake Close it.

**Comment by erendrake** [comment]
@Skyla Thank you very much for your report. please let us know if you spot anything else!
