### ISSUE TITLE
Add An Associative Array! AAAAAAAA

### ISSUE THREAD

**Issue by erendrake** [KSP-KOS/KOS#963]
I have noticed that without user structures people are having a fun time passing lists around and having to worry about index. 

So i have decided to make a new associative array structure it should have the following features by the time i am done.

- [x] Be able to use any user object as a key
- [x] String keys are case preserving by default (for access, replace, removal)
- [x] case sensitivity can be enabled with the `:casesensitivity` or `:case` suffixes.
- [x] CRUD actions against each key
- [x] Replacement without error 
- [x] pretty print dumping like LIST currently has
- [x] dumping any collection type should be able to dump its inner collections.
- [ ] user documentation

because this gets to live in kOS.Safe there will be unit tests!

EDIT: i have been working on this for days and i just realized there was no issue :P
EDIT2: WIP can be found here https://github.com/erendrake/KOS/tree/assoc_array. WARNING i will be rewriting the history on this branch so dont get too attached to it :)

**Comment by abenkovskii** [comment]
> String keys are case insensitive

problem:
```
set s1 to "abc".
set s2 to "ABC".
print s1 = s2. // false
//but my_arr[s1] and my_arr[s2] are the same index
```
It might cause cold fusion.

**Comment by erendrake** [comment]
@abenkovskii when we make string a user object, i hope to change the string equality behavior. my hope being that everything in kOS is case insensitive.

**Comment by abenkovskii** [comment]
@erendrake What about one-line array creation like: `list("abc", 42, 3.1415, my_var)` but for associative arrays?

**Comment by Dunbaratu** [comment]
It is incorrect design to make it impossible for the user to pick case sensitivity vs insensitivity.
If you build insensitivity in at too low a level, you make it impossible for the programmer to choose.
The reason most languages don't do what you're talking about is that case insensitivity is a loss of information, which you don't want to enforce at too low of a level of the system.

Or to put it more clearly what the problem is:
You CAN implement case-insensitivity on top of case sensitivity.
You CANNOT implement case sensitivity on top of case-insensitivity.

Whether the kerboscript language is case sensitive is an entirely separate question from whether or not the values of its variables are.

**Comment by Dunbaratu** [comment]
The solution is to provide users with the option to do case insensitive vs sensitive checking, not to make it impossible to escape from it.

On another note, we never formalized what the meaning of kOS's case insensitivity is.  There are places were we use CurrentCulture and other places where we don't.  It would be a shame if a script that works when you run it in one country stops working when someone runs the same script in a different country.

**Comment by erendrake** [comment]
@Dunbaratu then we can add another case sensitive option later if we want it. it is frankly not interesting to me to have case sensitivity for equality checking.

    SET FOO TO LEXICON().
    FOO:ADD("bAr", 2).
    print FOO["BAR"]. // 2
    print FOO["bar"]. // 2
    print FOO:KEYS. // [0] "bAr"

**Comment by Dunbaratu** [comment]
> we can add another case sensitive option later

The fact that we can't is exactly the problem here.

**Comment by erendrake** [comment]
@Dunbaratu we do need to address the currentculture at some point. I am not sure how to form the requirements for it.

**Comment by erendrake** [comment]
The fact that we can't is exactly the problem here.

I dont see a problem.

**Comment by Dunbaratu** [comment]
You are designing the low layer on top of which everything else is implemented, and enforcing case-insensitivity in that low layer.  Once the case information gets lost it cannot be re-inserted at a higher level layered on top.

**Comment by abenkovskii** [comment]
I agree with @Dunbaratu. For me:
```
print "bAr" = "BAR". // true
```
is nonsense.
P.S. I think it's because in all other languages it's `false`.

**Comment by erendrake** [comment]
I am not loosing it. if you look at my example above the printout still has the original case. if we want one later on to replace the hash rules thats fine.

**Comment by Dunbaratu** [comment]
To make it clear, what raised my complaint is that you didn't want to merely make an option to make a case-insensitive key index for associative arrays, but then went on to say that you wanted to make ALL string comparisons, everywhere, insensitive.

Remember that user input and string manipulation is coming later.  Doing it at the low level of ALL string comparisons makes it impossible to let a script differentiate 'a' from 'shift a' on the input stream.

**Comment by abenkovskii** [comment]
@erendrake I still don't understand why do you think that case insensitive array is better.

**Comment by abenkovskii** [comment]
"Explicit is better than implicit" ()
I'm for the explicit approach: `print "My sTrInG":TOLOWER().`

**Comment by erendrake** [comment]
@abenkovskii because i dont there there is a use case for 

    SET FOO TO LEXICON().
    FOO:ADD("bAr", 2).
    FOO:ADD("BaR", 5).
    print FOO["BAR"]. // Error
    print FOO["bar"]. // Error

I think that writing case sensitive code in this way is less readable.

**Comment by Dunbaratu** [comment]
Also, I find it poor to say "this collection is keyed by any object you feel like.  Oh, but if that object is of type string, then it activates this special case behavior just for strings."  That sort of decision belongs outside the primitive, at a higher level.

**Comment by erendrake** [comment]
@Dunbaratu i dont agree. if anything strings are the oddball by having this special quality that nothing else does.

**Comment by Dunbaratu** [comment]
Why can't you just do this?
```
   set foo to mapper().
   set foo:sensitive to false. // or to true depending on what you want
```
And thereby make it a property of the associative array itself how it treats its keys, RATHER than making it a low level feature of the language that it is incapable of ever differentiating "A" from "a", anywhere in the whole script.

**Comment by Dunbaratu** [comment]
Strings are not an oddball.  You are making them BECOME an oddball with what you're proposing.  Default behavior for any object used as a key is precise exact equality for ALL types objects, strings included, UNTIL you insert case-insensitivity that mashes different values together into being the same.  The proper design for doing that is to layer that mashing on TOP of the low level system, not embed it inside the low level system where it cannot be escaped from.

**Comment by erendrake** [comment]
@Dunbaratu because i dont think there is a good reason to ever set it to true. I dont think case is a very useful tool. It is my opinion that sharing and maintaining code that depends on case sensitivity will be harder, so why have the option. 

Also your assertion that it would make it harder to detect custom key presses is incorrect. We will already need the concept of a modifier key for alt and ctrl. Shift would just be another modifier.

**Comment by Dunbaratu** [comment]
> Also your assertion that it would make it harder to detect custom key presses is incorrect. We will already need the concept of a modifier key for alt and ctrl. Shift would just be another modifier.

Strange, I thought you said you liked the telnet interface, but apparently you want to cripple it by making it only possible to read the difference between 'a' and 'A' when in the gui terminal.

**Comment by abenkovskii** [comment]
@erendrake 
How many case insensitive languages you know?
Are there many languages with case insensitive strings?

**Comment by Dunbaratu** [comment]
There are case-insensitive languages where the keywords are insensitive.  NONE of them embed presumptions of insensitivity into their low level string comparisons in a way that cannot be escaped from.

And for very good reason.

**Comment by erendrake** [comment]
@abenkovskii i know kerboscript already has a lot of case insensitivity and it is the language we are designing ( right now i guess :) )

@Dunbaratu why would it be impossible for the telnet server to turn `A` into `shift + a` when using it for keybindings. 

@Dunbaratu `And for very good reason.` what is it? what is the benefit of having it to a kerbal space program scripter?

**Comment by erendrake** [comment]
@abenkovskii i am also not talking about smashing user strings. preserving case while ignoring it in the context of equality checking is what i am talking about.

**Comment by Dunbaratu** [comment]
@erendrake, Your last two questions are the same.  You cannot communicate non-chars via telnet.  "shift" isn't a character until applied to another key.  You can't read that the shift is down, all by itself, over telnet.  You can only read that the letter sent was 'A' instead of 'a'.

For a use case:  "Here's my keymapper object.  It's an associative array that maps chars to activities that should happen when they're pressed.  It does a different thing depending on what character it reads.  If it reads 'A' it does foo, if it reads 'a' it does bar, and so on... oh crud kerboscript refuses to let me have them as two different entries in my associative array.  Okay fine I'll have to make up my own primitive then from scratch - oh crud I can't even differentiate 'a' and 'A' in a boolean check of any kind, well crap. I can't do it then."

As to your claim that you're not talking about smashing user strings, yes you are.  Read your own comment here: https://github.com/KSP-KOS/KOS/issues/963#issuecomment-99229581

**Comment by erendrake** [comment]
@Dunbaratu in that comment i am talking about equality for user strings. 

    SET FOO TO "fiZz".
    PRINT FOO. // fiZz

is fine by me.

**Comment by erendrake** [comment]
@dun

**Comment by erendrake** [comment]
@Dunbaratu when we receive an `A` over telnet. what would stop us from mapping it to a user mapping for `shift + a`? I dont see where we would be blocked in c# land from making that distinction for the user.

    SET KEYBINDING:AG1 TO 'shift + a'.

could surely be mapped, are you saying that we will not be able to use other modifiers in bindings? thats too bad.

**Comment by Dunbaratu** [comment]
You are talking about making it utterly impossible for any script to detect the case of a letter.  That effectively mashes strings.  They only print the original case, you can't actually USE that original case in any meaningful way in the code.  The user can see a difference that the code is completely blind to.

And that is purely wrong design.

**Comment by Dunbaratu** [comment]
I am in favor of having a case-insensitive string comparator.  I can even accept having it be the default you get when you say nothing.  I can't get behind making it the ONLY way a kerboscript is allowed to be written, thus forcing your opinion on everyone else.

**Comment by erendrake** [comment]
@Dunbaratu fair enough. how do you want to do this? on a collection by collection basis with a suffix? or with a config entry? I am open to either, it might be lame to specify it each time for string equality unless we add a new operator.

**Comment by erendrake** [comment]
@abenkovskii if we make it a config entry. do you see any reason that kslib would ever not work with one or the other?

**Comment by abenkovskii** [comment]
Will it be displayed in the kOS settings window if it's a config entry?

**Comment by Dunbaratu** [comment]
We can go with two string compare operators, perhaps '=' and '~"? (I'm a bit reluctant to use tilde because of its meaning for regex - it would be neat to support regex when we do string stuff later, and several languges use "~=" to mean regex replace-in-place.)  Or maybe '=' vs '=case=', if you want insensitivity to be the default '=' and '=case=' to be the case-sensitive one?

Then just have a suffix for the assoc array object ``:sensitive`` set to true/false, and default it to false if you like.

On another note- is it really called 'Lexicon"?  that seems sort of... string-centric.  But it's not a big deal - just a strange word for it.

**Comment by Dunbaratu** [comment]
I'd rather it not be a config operator.  Because the SAME script can encounter two different situations, one of which it's appropriate to be sensitive and the other it's not.

**Comment by erendrake** [comment]
@abenkovskii i assume so. that window is getting pretty cramped and we might end up pruning some of them here soon.

**Comment by erendrake** [comment]
@Dunbaratu yeah, i was thinking that a config would be lousy too. i am all on board for a suffix for the associative array and a new operator `=case=` is actually not too shabby

**Comment by Dunbaratu** [comment]
I changed my mind on the name ``:sensitive`` - it's too ambiguous what that is.  how about ``:case``.

**Comment by erendrake** [comment]
@Dunbaratu `:casesensitive` with a synonym of `:case`?

**Comment by erendrake** [comment]
alright, im going to change the OP.

**Comment by Dunbaratu** [comment]
casesensitive - sure.  I just am a bit mindful of the verbosity of our suffixes - with case-insensitive identifiers it can be a bit annoying to run together several words like that.

**Comment by erendrake** [comment]
@Dunbaratu I agree, i wouldnt want casesensitive to be the only choice because it is verbose

**Comment by Dunbaratu** [comment]
I'm in a position of not seeing your code yet.  Have you already made it so that "aaa" = "AAA" returns true, or does that 'rounding' only happen inside the keys?

**Comment by abenkovskii** [comment]
@Dunbaratu 
problem:
```
set case to 42.
print "ABC"=case="abc".
```
I propose: `==` or `===`.

**Comment by erendrake** [comment]
@Dunbaratu right now i havent touched other strings. only the keys of this collection that i have so far been calling `lexicon`. But the name is up for grabs too if people dont like it.

**Comment by Dunbaratu** [comment]
Looking at tinypg, I think ``=case=`` will probably work as an operator.  (I was worried it might parse as ``=``, ``case``(identifier name), ``=`` - as 3 tokens, but it looks like if it's faced with the chioce vs '=' and '=case=' at the same point, it will pick '=case=', provided you ran it together as all one word with no spaces.

**Comment by Dunbaratu** [comment]
The reason I asked about the = operator being in there yet or not is I was wondering about the feasibility of making it a separate PR to be done after this one - that looks feasible.

**Comment by abenkovskii** [comment]
I know that comparing booleans is a bad practice. But someone might do: `"abc"=case=false` where case is a string variable and expect it to be the same as `("abc" = case) = false`.

**Comment by erendrake** [comment]
that is good to know, i also agree with you that using the `~` would be a bummer. 

@abenkovskii `===` was my first thought too but i actually am pretty keen to see how some alternatives would look :)

**Comment by erendrake** [comment]
@abenkovskii and wouldnt `print "ABC"=case="abc".` be just as complicated as `print "ABC"="abc".` once you have tokenized it you should be good.

**Comment by erendrake** [comment]
@Dunbaratu and i agree that this PR is big enough without having all of that. I was not planning on having it in the scope of this issue or its PRs

btw if you want to take a look at my progress you can look at this branch on my fork.
https://github.com/erendrake/KOS/tree/assoc_array

**Comment by Dunbaratu** [comment]
@abenkovskii  - that problem might happen.  We can pick something else as the operator.  But I don't like '==' as having those sprinkled in the code at the same time as '=' will REALLY confuse anyone coming from C, C++, C#, or Java who looks at the code for the first time.

It can also be just a pure bareword operator.  ``"aaa" caseequal "AAA"``.

Other possibilities are ``@=``, or ``$=`` - we can wait to see what works for that later.  Now that I know that's not really part of this PR it isn't important to nail down the exact token yet.  We can just say:

"=" will be the case-insensitive check for strings, and something else to be determined will be the insensitive one.

for now.

**Comment by Dunbaratu** [comment]
I'm going AFK a while.  I'll just wait for the PR to look at the code.

**Comment by erendrake** [comment]
@Dunbaratu i agree. I very well might be totally off on this and i burn in effigy for it :) 

@abenkovskii @Dunbaratu I think this is the right path but we are a team so i am very glad i had both of you to talk about this today. it was a great conversation.

**Comment by abenkovskii** [comment]
Another idea use string's suffix:
```
print "ABC":equal("abc").  // true
print "ABC" = "abc".  // true
print "ABC":caseequal("abc").  // false

**Comment by abenkovskii** [comment]
@erendrake Can we have two different types of associative array? One case sensitive and other not. Problems it'll help to avoid:
1. Each time case sensitivity of array changes we'll have to recalculate hashes.
2. Changing a non empty array from case sensitive to case insensitive can even cause an exception if it contains two key that differ only by case and we have no way to catch it yet.
3. When we pass an array as a parameter to a function it can change it's case sensitivity without the user noticing it.

**Comment by TDW89** [comment]
Might be a bit late with this but would it work to do it in the same way a `lazyglobal` so you could stick at the top of the script `@CASEINSENSITIVITY off` if you didn't want it?

**Comment by Dunbaratu** [comment]
I dislike doing it that way either, for the same reason - it's something you decide on a case-by-case basis rather than something you leave as-is through the whole file.

Also, if you see a line of code like this:
``` local x is 0.```
That line of code means the same thing whether @lazyglobal is off or on.  @lazyglobal changes whether you're forced to use it or not, but doesn't change the meaning of that line of code once you type it.

using a directive for sensitivity would make it so that this line:
``` if x = "hello" ```
would change its meaning depending on the directive, making it more hidden and less clear how it behaves from a cursory glance.  That's why I favor making it explicit in the code.  So you can tell from reading THAT line of code what it does, without having to cast your eyes elsewhere to find out.

**Comment by abenkovskii** [comment]
@erendrake Github says that this line of code: https://github.com/KSP-KOS/KOS/blob/develop/src/kOS.Safe/Compilation/Calculator.cs#L393 is here scince initial @marianoapp's commit: https://github.com/KSP-KOS/KOS/commit/46910f76c948f0086de99d55a30f35b91dcc440d#diff-35e814f7fcfa228ea2b7bd147a4df769R241. So string comparison IS case insensitive since Feb 20, 2014. And no one even noticed. But I'm 100% sure string comparison was case sensitive when we was discussing this issue. Did anyone travel to the past to change the history of kOS?

**Comment by erendrake** [comment]
it was me, i have lots of super powers. timetravel is one of the more useful ones.

**Comment by Dunbaratu** [comment]
Well that sucks.
The duration of the wrongness of the decision still doesn't change how wrong it is.

**Comment by abenkovskii** [comment]
@Dunbaratu I thought that we came to an agreement that we make the default string comparison case insensitive and add a new operator (or suffix) for case sensitive comparison.

**Comment by Dunbaratu** [comment]
The inability of the script programmer to choose which comparison they want, regardless of which way around is the default, is what I was describing as the wrong decision.  The fact that this incorrect behavior has been in there a long time should not be taken to mean its correct just because nobody complained yet.

I suspect that the only reason nobody has complained or noticed is because strings in general are so hard to use in kOS at the moment that the string equality check probably hasn't been exercised much yet either way, sensitively or otherwise..

**Comment by abenkovskii** [comment]
BTW do you know that `"abc" < "def"` compares strings by their length.

**Comment by Dunbaratu** [comment]
well that's clearly broken too.

**Comment by erendrake** [comment]
@Dunbaratu im going to make a new issue where we can decide how each operator should work. the length only inequality is strange to say the least.

**Comment by Dunbaratu** [comment]
that should be part of the big strings refactor coming up.

**Comment by erendrake** [comment]
@Dunbaratu agreed, we dont need to actually change it now i just thought it would be nice to have that discussion in its own issue. I also created a milestone for the big block of string work we have coming up

**Comment by abenkovskii** [comment]
I don't think it's mentioned here: if we make the default string comparison case insensitive it will make implementing other languages on top of our opcode harder. Every comparison operator will have to check operand's type and if it's a string use a different operator. Based on [this comment](https://github.com/KSP-KOS/KOS/issues/966#issuecomment-99575231) I assume that we are not disregarding the possibliity of adding other languages to the kOS.

**Comment by abarbe-** [comment]
Think this was solved by the introduction of the Lexicon type, right?

**Comment by erendrake** [comment]
Thanks! yes it is
