### ISSUE TITLE
Why not Lua?

### ISSUE THREAD

**Issue by viluon** [KSP-KOS/KOS#966]
Hello, I'm not sure if it is a good idea to post this as an issue, but I found not FAQ in the thread nor anything similar in the documentation.

 My question is, why doesn't kOS switch to Lua? There are many many enhancements it would bring, listing a few:

+syntax actually similar to those of *modern* languages
+fast and flexible, easy to bind with C#
+much love amongst programmers
+easy to learn and understand! No confusing CAPS LOCK commands
+actually used in business (Love 2D, Corona SDK), players gain useful knowledge
+OOP is fully possible
+tables allow for simple understanding of structures and objects, no need to know any C languages
+way nicer syntax not only to newbies but also to the eye
+open source 
+and much, much more...

So yeah, Lua would be great. If not Lua then some other scripting language but seriously, why do you reinvent the wheel? A popular language = a popular mod.

**Comment by abenkovskii** [comment]
> easy to learn and understand! No confusing CAPS LOCK commands

**Comment by abenkovskii** [comment]
f

**Comment by viluon** [comment]
"Switching" might not be the best expression. Implementing Lua would be better, obviously. You could e.g. run .lua files with the Lua VM to prevent breaking backwards compatibility

**Comment by abenkovskii** [comment]
> No confusing CAPS LOCK commands

Kerboscript IS case insensitive.
`PRINT 42.` does the same as `print 42.` and even `PrInT 42.`
So you don't have to use CAPSLOCK.

**Comment by viluon** [comment]
I get it, yet most tutorials do use caps. Modern languages are case sensitive by the way

**Comment by Dunbaratu** [comment]
The language isn't the problem.
The VM is the problem.  It has to be custom made to deal with how the updating in Unity works.  It's not a native machine language set of opcodes.  You can't just take an off-the-shelf Lua interpreter or compiler and use that - you have to redesign it to map into the Opcodes used in KSM files.  If you want to do that, go right ahead.  But don't pretend it's as easy as just grabbing some off-the-shelf solution and slapping it on to the exising mod.  It is a large undertaking.  The infrastructure is there to be able to compile something else than kerboscript, BUT, it does mean you have to design the way it maps the language into the opcodes entirely from scratch.

**Comment by viluon** [comment]
So I guess it would be easier to make a whole new Lua based mod from scratch

**Comment by erendrake** [comment]
@viluon honestly there are a multitude of reasons why we havent implemented Lua in kOS. 

* we have been adding language features slowly over time. If we had decided to go down the Lua route we would have gotten so much flack for not supporting every part of it right away. 
* I at least have enjoyed designing our own language, it has been fun to say "what is my favorite way to do something?"
* None one who actually contributes to the code has ever said they wanted to implement Lua. 
* If I was building a new language into kOS it wouldnt be Lua.

**Comment by viluon** [comment]
So you couldn't use for example https://github.com/blacknecro/selene/ code because your opcode system relies on the language running atop it giving it custom crafted instructions right?

**Comment by Dunbaratu** [comment]
If you want to use an existing language, there is an entirely different approach used by another mod called kRPC that is more appropriate to that style, because it does not attempt to run the code INSIDE the KSP game itself at all - it just provides an api to *talk to* the KSP game from an outside process, and you run what you want as an outside program.  Making it so that you run code in an outside process means that process can be written from whatever language you feel like.  The downside is that kRPC doesn't seem to have been updated as much and is a bit sparser on what it supports from KSP.  But if you seriously want to 'start from scratch' it's probably easier to just start from kRPC and add more to it.

**Comment by viluon** [comment]
@erendrake
1) doesn't make sense to me
2) not practical for this kind of project
3) obviously
4) subjective error, arguments expected got opinion

**Comment by viluon** [comment]
@Dunbaratu 
Ah, I see, thanks for making that clear to me! Too bad Lua can't be implemented, it would really attract a lot of new users as it is very English like.

**Comment by erendrake** [comment]
@viluon want to have a bullet argument :) thats fine

1. ill chalk that up to lack of imagination?
2. I disagree, there are many DSLs out there for all kinds of applications. are you saying they are all wrong?
3 and 4. when there are a few people who spend their free time making a mod for a game for free. their interest in languages is very much germane to which one gets implemented.

**Comment by erendrake** [comment]
@viluon you are misunderstanding @Dunbaratu. any language could be implemented in kOS. it just takes work.

**Comment by erendrake** [comment]
@viluon if you would like to see Lua implemented in kOS. we would happily take a pull request from you and work with you to make it happen.

**Comment by viluon** [comment]
@erendrake
1. Reply
Ha, debate's forming up :D
1) adding language features slowly is *better* than to present a complete, solid, stable and fully functional language straight ahead? That doesn't make sense to me. If you'd implement Lua,keyboard interaction and print, users could already start creating ASCII games and the mod community would grow (who doesn't want to play ping pong with Job on the way to the Mun?)
2) I must say this was subjective opinion from my side, but I have arguments for that. A fully featured, functional language such as Lua with a good user base is more likely to get attention, help on internet forums and technical support than a handcrafted custom language (probably). That's my way of thinking. I agree that custom language=lots of fun for the programmers but not really for the user in my opinion. With Lua they'd use their knowledge somewhere else too.
3&4) I guess that is unavoidable, at least in this case.

2. Reply
Oh no I did understand, I meant it probably *won't* be implemented since it is too much work for too little profit, fighting with a system that already works and wasn't meant to change languages (or implement another one). So yeah, possible but not that fancy.

**Comment by viluon** [comment]
Oh damn I have got a hard time writing all of this on my smartphone.. so yeah that reply is kinda malformatted but you're programmers you know how you'd fix JSON right? Same with English.

Anyway @erendrake
That would be cool. Unfortunately, I have no skill for that, I cannot code in C#. While I do know the theory (I mean I know how OOP works or how a language is parsed compiled interpreted whatever) I'm only learning C++ right now. Maybe a year in the future, when I turn 18 and we'll get C# tutorials in the school, I'm not going to learn C# until then since.. well I think Unreal Engine 4 is just way cooler :P esp. cause its free now

**Comment by Dunbaratu** [comment]
People have tried before to make things like kOS that use other languages than kerboscript.  The reason such projects don't get far, I think, is that people enter into them with a total misunderstanding of what the hard parts of kOS are.  They think we spend all our time on the language.  Actually we spend most of our time on the runtime VM, and for lack of a better word, the API library, not the higher level language that makes use of them.  It was only just recently that the runtime VM became sophisticated enough to even consider thinking about other languages.

People think it's "kerboscript can't do a feature, therefore the kOS doesn't.  I can fix that with a different language", when that's backward.  The more accurate description is "kOS doesn't do a feature, therefore it can't be added to kerboscript yet."  We can't provide a language feature that the underlying system doesn't run.

The advantage of having a custom language is that if we used an existing one, but couldn't do most of it's features, people would be complaining that they're not there - and for good reason - because it would be a lie to say "we can do language foo" when not everything that foo does is really doable in the underlying system so half of language foo is disabled.

It is only just recently that the underlying VM has gotten good enough to consider being able to write a compiler into it from some other language.

To give an idea of what I mean - when I added local variables to the system for 0.17.0, I spent most of that effort on the VM and the opcodes to get them to stop assuming everything must be global, and to get them to support some runtime modified scoping.  The mapping of that into the higher level scripting language that gets compiled into it was probably really only about 10-20% of the work that went into it.

If you start from the presumption that it's the LANGUAGE that is causing a feature to be lacking, you're beginning from the wrong assumption.

**Comment by viluon** [comment]
@Dunbaratu
That is kinda what I expected, really. I dislike kerboscript from the syntactical point of view.

Anyway what I truly meant by "implementing Lua" was really implementing Lua. You don't have Lua if you don't have Lua bytecode,that's just not Lua. You would be turning the *same* source code into a very *different* bytecode, in the end actually implementing the language again but only for your specific system.

One question though, is my assumption correct?
Your backend can support multiple languages but.. no not really. It has its own bytecode (set of opcodes) and it supports multiple *compilers* but they have to end up creating the same bytecode format.

If its incorrect then I don't really know what you mean and it is kinda off topic :D you don't have to bother explaining if you don't have to

**Comment by erendrake** [comment]
@viluon almost every language you have ever used has to compile down to work on top of many systems. C for instance is able to compile down to the assembly language of almost every microprocessor on the planet. That is the job of most languages is to keep you from having to write the lower level code yourself :)

**Comment by Dunbaratu** [comment]
@viluon - yes, kOS is essentially a bytecode runner, with a language crafted on top of that bytecode called kerboscript.  Things the bytecode doesn't implement aren't in kerboscript, so as to avoid generating the illusion that they'd work.

For comparison, there exist compilers that turn other languages into Java bytecode to be run inside a JVM.  That would be the sort of thing you'd have to do to make Lua work in kOS.

Also, another very large part of what kOS does is provide an abstraction layer between the raw, fiddly, very messy API of Kerbal Space Program itself and the higher level abstraction of it that makes more sense to a user.  When you say LOCK STEERING TO V(40,31,0) there's a heck of a lot kOS is doing with that under the hood that is layered on top of the KSP API.   Most of the "run something in a scripting language" attempts to do something kOS-like have sort of skipped or greatly simplified that layer in their implementations such that to a certain extent all they're really doing is letting you write a brand new KSP mod from scratch in something other than C#.  If that's what you want, there's more direct ways to do that on your own.

**Comment by abenkovskii** [comment]
I guess it's to late to comment the OP but I somehow got disconnected from the github.
> OOP is fully possible

We are going to add OOP to the kerboscript soon.

> no need to know any C languages

Could you explain what you are talking about?

> way nicer syntax not only to newbies but also to the eye

For me syntax looks fine.

> open source 

kOS is open source. Am I missing something?

**Comment by viluon** [comment]
@erendrake
No no no not what I meant. I mean that Lua has its own bytecode but you couldn't use that in kOS because the underlying system doesn't understand it. You can turn Java bytecode into Lua bytecode for example, that is what my friends did https://github.com/Team-CC-Corp/JVML-JIT

**Comment by abenkovskii** [comment]
@viluon If I remember it correctly Python has it's own bytecode too.
But it can for example be compiled to .exe with Py2exe. Am I misunderstanding something?

**Comment by erendrake** [comment]
@viluon i am going to call this issue asked and answered. Thank you for the discussion.

**Comment by viluon** [comment]
@abenkovskii
That wasn't a list of what kerboscript doesn't do, it was a list of Lua features
@Dunbaratu
Yeah so I got it more or less right. I guess your way of doing it is kinda hard coded but very fast at the same time right?
Understood :)

**Comment by abenkovskii** [comment]
@viluon 
From the creator of kOS:
https://youtu.be/Vo8kRvuUDlA?t=1m14s

**Comment by viluon** [comment]
@erendrake
Thanks for your time and patience :)
@abenkovskii
No you probably aren't, why? Not sure why you're talking about python and *.exe's right now...?

**Comment by abenkovskii** [comment]
@viluon 
Sorry. Sometimes I read only the first part of a comment.

**Comment by viluon** [comment]
@abenkovskii
Ah, I see. Nice video there :D kOS backstory I'd call it

**Comment by viluon** [comment]
I know this is closed, but a major feature of having Lua instead of kerboscript is that it would prevent this https://github.com/KSP-KOS/KOS/issues/963 sort of debates..

**Comment by erendrake** [comment]
@viluon you are welcome to keep discussing in here as long as you like with whoever would like to join you :). Also, the debates like #963 are the reason I am still building this mod. Not a reason to stay away. designing languages is a pretty fun pursuit

**Comment by dail8859** [comment]
@viluon Had recently been wandering about Lua scripting in KSP. I've enjoyed KOS but its always seemed a bit too low level for me, and learning the syntax has always bugged me. I just think with a higher level language like Lua you could do alot more. It's times like this I wish I knew more about modding KSP. Although no time like the present...right?

Since this is in a KOS thread I should at least say I appreciate the tremendous effort that's been put into KOS. And I'm not bashing on KOS at all, its an amazing mod.

**Comment by abenkovskii** [comment]
@dail8859 
1. check out kRPC: http://forum.kerbalspaceprogram.com/threads/69313-WIP-1-0-2-kRPC-Remote-Procedure-Call-Server-v0-1-8-4th-May-2015
2. For me using kerboscript brings more fun into the process.

**Comment by dail8859** [comment]
@abenkovskii Thanks. Actually just looking into kRPC now and seems pretty cool. And yes I totally understand that part of the fun of KOS is learning it and building something cool from all the small pieces :)

**Comment by abenkovskii** [comment]
@dail8859 It's also fun to participate in kOS development. Learning kerboscript wasn't actually this hard for me.
Investigating strange things like this:
```
// test_1.ks
log "" to temporary_file.
delete temporary_file.
log "print 42." to temporary_file.
run temporary_file. // prints 42
delete temporary_file.
log "print 777." to temporary_file.
run temporary_file. // still prints 42
```
```
// mediator.ks
// this file is used in the examples below
run temporary_file.
```
```
// test_2.ks
log "" to temporary_file.
delete temporary_file.
log "print 42." to temporary_file.
run mediator. // prints 42
delete temporary_file.
log "print 777." to temporary_file.
run mediator. // prints 777 now
```
```
// exenode.ks
log "" to temporary_file.
delete temporary_file.
log "print 42." to temporary_file.
run mediator.
delete temporary_file.
log "print 777." to temporary_file.
run mediator.
// do some stuff to execute maneuver node
```
```
// test_3.ks
run exenode. // prints 42 and 777
run exenode. // prints 777 and 777
```
```
// test_4.ks
log "" to temporary_file.
delete temporary_file.
log "print 0." to temporary_file.
run mediator. // prints 0.
run exenode. // prints 42 and 777
run exenode. // prints 42 and 777 now
```
is fun too.

**Comment by zesterer** [comment]
@erendrake Apologies for necroing this thread, but do you have some reference for the internal bytecode that you mentioned?

**Comment by FranseFrikandel** [comment]
@zesterer A tad late, but I was looking into this myself. Opcodes are defined here:
https://github.com/KSP-KOS/KOS/blob/develop/src/kOS.Safe/Compilation/Opcode.cs

And the KSM format is described here:
https://github.com/KSP-KOS/KOS/blob/develop/src/kOS.Safe/Compilation/CompiledObject-doc.md

**Comment by Delta-official** [comment]
as far as i know, the included ksm documentation is outdated (i might be wrong tho). it's better to use this https://github.com/newcomb-luke/kerbalobjects.rs/blob/main/docs/KSM-file-format.md
