### ISSUE TITLE
[documentation] Arithmetic and logic operators are bad documented

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#968]
1. There is no information about the order of operations
2. `True` and `false` are listed as logic operators
3. `(` and `)` are listed as  arithmetic operators
4. Some operators (`^` and `e`) probably should be explained

P.S. I know what `^` does but I don't know what `e` is for.

**Comment by Dunbaratu** [comment]
`e` is for scientific notation.  1.432e32, for example.  But it's incorrect to call that an operator.  It's actually part of the parser's definition of what makes a number literal.

**Comment by Dunbaratu** [comment]
merged PR, but the issue didn't close - dunno why.
