### ISSUE TITLE
(regression) body comparison fails

### ISSUE THREAD

**Issue by baloan** [KSP-KOS/KOS#97]
KSP 0.23.5 with kOS 12.1p1
Comparing bodies fails. Comparing body:names works fine.

![body-cmp](https://cloud.githubusercontent.com/assets/651799/2949243/cf3bcce8-da0c-11e3-9f7e-ed49d8ea5030.PNG)

This code worked in 0.11:
```
declare parameter bodyobj.  // called with foo(Mun)
until time:seconds >= t1 or body = bodyobj:name {
...
```
No longer works. Now it has to be:
```
declare parameter bodyobj.  // called with foo(Mun)
until time:seconds >= t1 or body:name = bodyobj:name {
...
```

Btw: ```print version.``` has not yet been updated to "12.1p1".

**Comment by erendrake** [comment]
fixed
