### ISSUE TITLE
can't interact with certain file names

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#973]
![screenshot1](https://cloud.githubusercontent.com/assets/11031560/7512563/8f1d558a-f4b6-11e4-89e5-64b9f65b6ae7.png)
https://www.dropbox.com/s/ux383yzqjja8y11/aux_bug.txt?dl=0

**Comment by Dunbaratu** [comment]
This has nothing to do with kOS.  "AUX" is a special magic filename on Windows, dating back to its old DOS days, and the restriction against using it for a filename is still present.  (It's like calling a file LPT1 or COM1).

http://blog.onetechnical.com/2006/11/16/forbidden-file-and-folder-names-on-windows/

**Comment by abenkovskii** [comment]
Never heard about this. Thanks for clarifying.

**Comment by Dunbaratu** [comment]
There could be a secondary side issue added, though, about the fact that it nullrefs when it can't open the file.  For whatever reason if the OS is refusing to let it create a file it should trap that and give a better message.  Even a "can't open file xxxx" is still less cryptic than a null ref.
