### ISSUE TITLE
kOS processor sinks into the launchpad:

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#980]
I'm not sure if it's a kOS problem or a KSP bug but when I launch this:
![screenshot9](https://cloud.githubusercontent.com/assets/11031560/7540851/6e876334-f5b9-11e4-9a62-c0e983f30c89.png)
The kOS processor sinks into the launchpad:
![screenshot10](https://cloud.githubusercontent.com/assets/11031560/7540870/a25da6fa-f5b9-11e4-9518-4289cc1b1c3b.png)
It only happens with stack mounted parts, radial part doesn't sink.
@pgodd Is something wrong in the model or in the .cfg? Or is it supposed to work like this?

**Comment by pgodd** [comment]
Probably the collision mesh is not constructed properly.
I will take a look and see.

**Comment by Dunbaratu** [comment]
I can report I've had the exact same problem, may times.
