### ISSUE TITLE
stage:liquidfuel wrong when using radial decouplers

### ISSUE THREAD

**Issue by gregbean** [KSP-KOS/KOS#981]
stage:liquidfuel shows the correct value when using a stack decoupler, but includes the fuel for the next stage when using radial decouplers.  See the attached images for two very similar rockets.  The top rocket uses a stack decoupler and stage:liquidfuel is correct, the bottom has radial decouplers and is returning the wrong value.

![kos1](https://cloud.githubusercontent.com/assets/1521348/7547458/610e0882-f5a2-11e4-9ea1-3b749d40243d.png)
![kos2](https://cloud.githubusercontent.com/assets/1521348/7547457/610d2e08-f5a2-11e4-9893-e9a98c122b6b.png)

**Comment by Dunbaratu** [comment]
It looks as if we'll just have to resurrect our old parts walk code and get it working again.  The API from KSP for this that we switched to just doesn't work at all.

**Comment by Dunbaratu** [comment]
Although... hang on.... you are clearly using a mod to display those stage values in the toolbar - that's not the stock way it looks in KSP.  What is that mod?  It might have publicly visible code that we can look at and figure out how the heck you're supposed to call the KSP API for it.  The way it *looks* like you're supposed to doesn't work, as is clearly shown by these constant complaints about the stage values, and like everything in SQUAD's API, it's utterly undocumented how any of it is meant to be called.  Seeing an example of how to call it that another mod is using might help.

**Comment by gregbean** [comment]
It's TriggerAu's Alternate Resource Display.

**Comment by Dunbaratu** [comment]
Thanks.  Might give it a look.

**Comment by tristanklempka** [comment]
I have the same bug with stock KSP.

**Comment by Dunbaratu** [comment]
Stage values have been a constant problem for ages.  I'd like to see all the issues folded into one.

**Comment by hvacengi** [comment]
Fixed in #1082, #1233, and/or #1243
