### ISSUE TITLE
The compile command fails silently if there is not enough disk space

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#985]
In my view it should raise an exception.
[Errors should never pass silently. Unless explicitly silenced.](https://www.python.org/dev/peps/pep-0020/)

**Comment by Bear67** [comment]
Can compile be restricted to work only on the archive directory? That way you never have to worry about running out of space.

**Comment by abenkovskii** [comment]
0. Thanks for your suggestion
1. Everything reasonable is possible in a Turing complete language (I'm talking about C#)
2. But I prefer making it throw an exception if it runs out of space
