### ISSUE TITLE
[bug] Setting Warp in PHYSICS warpmode doesn't work.

### ISSUE THREAD

**Issue by Feinbube** [KSP-KOS/KOS#989]
SET WARP TO 2. Will result in "Timewarp x1" in game. Both, in the terminal (I'm using putty) and in scripts. Works fine in RAILS warp mode though..

**Comment by abenkovskii** [comment]
Confirmed. Strange. Suggest [bug] label.

**Comment by abenkovskii** [comment]
I can confirm: it's solved now.
