### ISSUE TITLE
Can we now have one Function("round")?

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#993]
0. Now functions can take variable number of arguments
1. Function("roundnearest") was never documented
2. I assume it will require some refactoring of complier too

**Comment by hvacengi** [comment]
Technically, don't we just some how alias `round(d).` to be `round(d, 0).`?  It looks like there is a functionsOverloads dictionary in Compiler.cs, which only holds the round function.  It looks like we can just remove the round functions from this dictionary and proceed as normal.

@Dunbaratu Is there any reason to leave this legacy overload capacity in place?  This is literally the only reference I could find to the overload dictionary.

**Comment by abenkovskii** [comment]
@hvacengi 
> Technically, don't we just some how alias round(d). to be round(d, 0).?

Currently they are separate functions.

> It looks like we can just remove the round functions from this dictionary and proceed as normal.

I already did this in my fork.

**Comment by hvacengi** [comment]
Sorry, I wrote that first part before reviewing the code.  We do use the two functions, but it is still a matter of aliasing (overloading).  I meant it more to mean that it is documented, it's just documented using the overload not the base function.  But I agree that it would be cleaned up to be in one function, if for no better reason than to have a single function to maintain if we need to make a change.

If you have it running in your fork, submit a pull request.  The refactor itself can follow after you've updated round.  You might add "TODO" comment tags at the spots you expect to need a refactor, just so it's easy to find when you/we/they get around to it :wink:

**Comment by Dunbaratu** [comment]
@hvacengi : 

> Is there any reason to leave this legacy overload capacity in place?

No.  It can be removed after changing round() as you suggest.

**Comment by abenkovskii** [comment]
It's merged. I'm closing the issue.
