### ISSUE TITLE
We probably don't want the player to be able to invoke some functions

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#995]
I'm talking about load: https://github.com/KSP-KOS/KOS/blob/develop/src/kOS/Function/Misc.cs#L222
and toggleflybywire: https://github.com/KSP-KOS/KOS/blob/develop/src/kOS/Function/Misc.cs#L86

**Comment by erendrake** [comment]
@abenkovskii because they are not part of the public API, im ok with people using them knowing that we can yank them out from under them at any time
